### ISSUE TITLE
Focus on the password field when using separate pages for username and password

### ISSUE THREAD

**Issue by tspearconquest** [keycloak/keycloak#10027]
### Describe the bug

Hi,

We have configured the login flow on our keycloak instance in all realms to use Webauthn.
The flow we use for this looks as so:

![image](https://user-images.githubusercontent.com/81998567/152711417-1acc1763-a637-4ddc-9054-d58c2aed1ae8.png)

When users go to login, after entering their username, and clicking the login button, they are taken to the password form.

On the password form, the page loads up without the password field in focus. Users have to click on it in order to enter their password.

We have a feature request from a user asking to make it automatically focus on the password field on this form.

### Version

16.1.1

### Expected behavior

The password field will be automatically selected

### Actual behavior

The password field must be clicked on in order to put focus on it so that the user can enter their password

### How to Reproduce?

Configure a flow as per the screenshot above (optionally without the webauthn authentication -- the important part is the username and password fields being on separate forms), and then login to the realm where the flow is configured.

**Comment by mabartos** [comment]
@tspearconquest Thanks for creating this issue. I think it's rather an enhancement than a bug. It'd be nice to have the password input focused, so feel free to create a PR for that.

**Comment by tspearconquest** [comment]
You're right, apologies. I agree.

**Comment by mabartos** [comment]
@tspearconquest Pretty good points! I'll try to investigate it a little bit more and I'll let you know. Thank you!

**Comment by Pfuenzle** [comment]
I edited my local instance to focus on the password field when using webauthn as it was really annoying to have to use the mouse again to click the field instead of just continuing to type.

Is this issue still relevant?
If so, I could add a pull request with my fix.

If the accessibility issues from 2011 still are relevant (not sure, as it 1. was a long time ago and 2. the password field is the only one present in the form), I could try to add a setting to the Keycloak admin UI where this could be toggled (Altough I dont know if this is easily possible).

**Comment by tspearconquest** [comment]
Hi @Pfuenzle yes it is still relevant.
