### ISSUE TITLE
Favicon missing in welcome page on chrome / macos

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#10031]
### Describe the bug

Our favicon is missing when opening the welcome page on chrome / macos (see additional details)

### Version

<=latest

### Expected behavior

Favicon is shown

### Actual behavior

Favicon is missing on the welcome page. It shows up when opening other pages like login / admin ui, though. 

### How to Reproduce?

e.g. 
`kc.sh start-dev` -> navigate to localhost:8080 -> see no favicon shows up on welcome page browser tab -> enter admin credentials and click 

### Anything else?

Chrome version: 98.0.4758.80 (Official Build) (x86_64)
MacOS version: 11.6.1

Works on Firefox 91.5.0esr (64-bit)

**Comment by brsolomon-deloitte** [comment]
Seeing this same issue on Chrome 98.0.4758.109 / MacOS 11.6.4.

![Screen Shot 2022-03-01 at 1 08 07 PM](https://user-images.githubusercontent.com/81818815/156224549-ceb71b9d-044d-4de8-afea-9c01a3d18bbb.png)

Is it possible this is because everything is jammed in to `<body>` rather than `<head>`?

![Screen Shot 2022-03-01 at 1 09 01 PM](https://user-images.githubusercontent.com/81818815/156224635-e97f3f39-8a6f-498d-8a07-71eb46e7a828.png)

Deployment: `bitnami/keycloak` Helm chart version 6.0.1 on AWS EKS.

**Comment by brsolomon-deloitte** [comment]
Edit: yeah, it looks like on all other pages besides Welcome, the `meta`/`link` tags are properly in `<head>` rather than `<body>`

**Comment by brsolomon-deloitte** [comment]
Seems strange since the [template itself seems to put things correctly in `<head>`](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/keycloak/welcome/index.ftl)

**Comment by marvinscham** [comment]
As of 17.0.0 line 23 contains an invisible `U+00A0` non-breaking space character (see the `&nbsp;` in the body element) which seems to cause this. Commit 9fd86ac removes this character so the next release should fix this.

**Comment by DGuhr** [comment]
just double-checked. This issue here is fixed by the PR from #10157 - thx @marvinscham for pointing it out. I think we should include #10157 / #10271 in 17.0.1 then :) 

closing here for it is fixed and will create a backport of #10271 for the 17.0.1 release.
