### ISSUE TITLE
Client Mapper should not wrap returned values in square brackets when Multivalued toggle switch is off

### ISSUE THREAD

**Issue by chrisnurse** [keycloak/keycloak#10079]
### Describe the bug

An original issue:
https://issues.redhat.com/browse/KEYCLOAK-17909?jql=text%20~%20%22user%20client%20role%20mapper%22

In the user interface for setting up a Client Mapper, the user has toggled the Multivalued option to 'OFF' and then, for example, maps the User Client Role, expecting to see a string value which is strictly the name of the first client role assigned to the user.  

The mapper sets the string value to [ the_client_role_name ], erroneously making the returned value appear as an array, when multivalue has clearly been specified as off.

### Version

16.1.1

### Expected behavior

When the user has specified Multivalued as off, the system should not wrap the result in square brackets.

### Actual behavior

When the Multivalued setting is set to off, the required first value should be returned without being wrapped as an array.

### How to Reproduce?

The following image depicts an example Mapper Configuration to enable the provision of a user's system role. The target system in this example is Hasura GraphQL engine, which expects a simple clean string denoting the name of the user's role.

Hasura fails to Authorise the user because the role is wrapped in [ ].

The output of the claims is shown after a call to token endpoint, clearly depicting where the system has wrapped the denoted value as an array.

![image](https://user-images.githubusercontent.com/45703746/153094483-4df223a6-bc14-4cd1-b029-e39cdc436fe6.png)

### Anything else?

If anybody can point me to the area of the source code I will attempt to contribute a PR. This is very urgent for myself and a few other user I note who have made a similar request over the years.

So if someone can say "look at this source file" I can fix, build and test this then issue a PR.

**Comment by ahus1** [comment]
Hi @chrisnurse - I suppose the problematic piece of code is in [AbstractUserRoleMappingMapper.java](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java)

```
        boolean multiValued = "true".equals(mappingModel.getConfig().get(ProtocolMapperUtils.MULTIVALUED));
        if (!multiValued) {
            claimValue = realmRoleNames.toString();
        }
``` 

When toString() is called on a Set, this results in a single value wrapped in brackets. When fixing this, please check if it would be possible for a set with two or more values to end up here.

When creating a PR, please comment how this could be tested to help reviewers. This usually speeds up the review process.

**Comment by chrisnurse** [comment]
@ahus1 thank you so much for the clear guidance. I hope the review and test process can complete soon to assist me in having this fix in my next product build.

**Comment by srose** [comment]
@chrisnurse @ahus1 I want to help with this feature, but after looking into the issue for some hours I am not sure how to actually implement the behaviour.
I have configured grafana to use the roles delivered by Keycloak with multivalue=true and Grafana settings:
`
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "resource_access.grafana.roles[0]"
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: "true"
`

I did not find any meaningful specification on how to handle this case. Neither JWT (RFC 7519) nor in OIDC or other OAuth2 related specs. If someone else has a link, please share it.

From implementation perspective:

A use can have 1 to n client and/or realm roles.
If the mapper is configured with _multivalue=false_, one could argue to still write that list of roles in the string value of a claim.
Maybe clients depend on the current _Set.toString_ logic? At least some Unit-Tests verify this behavior.

Options for a mapper configured with ### multivalue=false 

1. just take the e.g. lexical first element of roles in all cases (issue a warning if not all roles are considered might lead to a lot of warnings)
2. check if the roles-list has only one entry and remove the braces only then, keep the existing logic otherwise
3. put some extra configuration in a realm attribute to explicitly decide what should happen, old logic is kept when nothing is configured

Open for other suggestions...
Please let me know what you think.

**Comment by ahus1** [comment]
Hi @srose - thanks for looking into this. 

Good to see that Grafana (the original use case for the Jira issue) works with the multivalue=true option.

Still, I think there should be an option where a single-valued attribute without brackets is expected like for the in the Hasura case.

The "extra configuration" you suggest could be part of the mapper configuration near the "multivalue" option IMHO, this would keep it quite close and specific where it is actually used.

Maybe we could get a maintainer's opinion here? Pinging @mposolda as you've been commenting on the original Jira issue. Thanks!
