### ISSUE TITLE
Authz: Resource Server with affirmative decision strategy only grants access to resources without assigned authorization scopes when all permissions are permitted

### ISSUE THREAD

**Issue by pboehm** [keycloak/keycloak#10086]
### Describe the bug

I'm using the Keycloak Authorization Services for managing access to different resources and I have discovered an unexpected behaviour for resource servers with an `affirmative` decision strategy and resources with multiple defined permissions. Resource access is only granted when all applicable permissions are permitted but is denied when at least one of the permissions is denied. Based on the description of the decision strategy field I think this is a wrong behaviour:

```
The decision strategy dictates how permissions are evaluated and how a final decision is obtained.
'Affirmative' means that at least one permission must evaluate to a positive decision in order to grant access to a resource and its scopes.
'Unanimous' means that all permissions must evaluate to a positive decision in order for the final decision to be also positive.
```

**EDIT**

The wrong behaviour only occurs when no Authorization Scope is assigned to the resource. When you create some Authorization Scope and assign it to the resource the affirmative decision strategy with multiple permissions works as expected.

### Version

16.1.1

### Expected behavior

I would expect that resource access is granted when at least one of the applicable permissions is permitted and not all of them even when no authorization scope is assigned to the resource.

### Actual behavior

Access to resources without assigned authorization scopes is only granted when all applicable permissions are permitted.

### How to Reproduce?

* Create a realm `authz-test`
* Create a user `user-a`
* Create a group `test-group` and leave it empty
* Create a confidential client `authz-test` with `Authorization Enabled`
* Within the `Authorization` tab:
  * Set the decision strategy to `Affirmative` within the `Settings` tab 
  * Create a resource `authz-test-resource` with type `urn:authz-test:resources:test`
  * Create a policy `access-for-user` of type `user` and add `user-a` as user
  * Create a policy `access-via-group` of type `group` and add `test-group` as group
  * Create a permission `resource-access-for-user` for resource `authz-test-resource` and apply policy `access-for-user`
  * Create a permission `resource-access-via-group` for resource `authz-test-resource` and apply policy `access-via-group`

Evaluate from within the `Evaluate` tab:

![image](https://user-images.githubusercontent.com/665684/153189620-019b7536-7733-42f6-aa61-78fee56b7403.png)

The result is:

![image](https://user-images.githubusercontent.com/665684/153189775-809bf426-dca9-4e2e-a109-8f02ee758e4a.png)

When I add `user-a` to `test-group` resource access is granted because all permissions are permitted.

When I assign the `test` authorization scope to the resource, resource access is granted even when not all permissions are permitted (like when `user-a` is not a member of group `test-group`):

![image](https://user-images.githubusercontent.com/665684/153381070-a3d52b34-8dc0-47a7-94a2-f6038fdf0c5b.png)

### Anything else?

* Keycloak Discourse Thread https://keycloak.discourse.group/t/decision-strategy-affirmative-strategy-doesnt-behave-as-expected/12010

**Debugging Results**
* From some remote debugging I can limit the problem to to the `DecisionPermissionCollector` https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DecisionPermissionCollector.java
* It defines two variables `resourceGranted` and `anyDeny` https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DecisionPermissionCollector.java#L71-L72
* In our scenario both of the variables will be `true` after examining the permission results
* Because no scopes are involved in this scenario, this https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/authorization/policy/evaluation/DecisionPermissionCollector.java#L149-L151 if-Condition will be `true` and resource access is not granted because of early return.

**Comment by pedroigor** [comment]
That is an expected behavior where affirmative works only for scopes because resources permissions end up in conflict so DENY is the final outcome.

**Comment by bjoern-nowak** [comment]
Sorry for commenting on an quite old issue, but since I just faced the same problem I could not let it unsaid for others searching about the same.

**A workaround** would be to assign a single "dummy" scope to all resources and ignore the scope in the permission check result.

-----

@pedroigor I do disagree that this should be expected, the decision strategy should be applied regardless on what the permissions are based on, its task is (or should be) to simply aggregate all permission results to a final result by applying the unanimous/affirmative rule:

**Baseline:**
Having one resource R1 and associated scopes S1 and S2.

**Scenario A: only scope-based permissions**
There could be two scope-based permissions present: 
P1 granting R1 with S1 with a single time-based policy only positive on 1 o'clock.
P2 granting R1 with S1 with a single time-based policy only positive on 3 o'clock.
So at either 1 and 3 o'clock the permissions for R1 with S1 ends up in a conflict (one permit, one deny).
Thats excatly for what the "decision strategy" is/should be meant for: to resolve this conflict to a final decision.

**Scenario B: only resource-based permissions**
The basic conflicht-resolve concept also applies here if you have only resource-based permissions. 
P1 granting R1 (with all associated scopes if any) with a single time-based policy only positive on 1 o'clock.
P2 granting R1 (with all associated scopes if any) with a single time-based policy only positive on 3 o'clock.
So at either 1 and 3 o'clock the permissions for R1 (with all associated scopes if any) ends up in a conflict (one permit, one deny).
Which again must be decided by the choosen strategy.
There is no reason to ignore the configured "decision strategy". If so this should be clearly documented and shown in the help text.

**Scenario C: resource-/scope-based permissions mixed up**
scope-based P1 granting R1 with S1 with a single time-based policy only positive on 1 o'clock.
resource-based P2 granting R1 (with all associated scopes) with a single time-based policy only positive on christmas day.
On a any day (but christmas) at 1 o'block there will be a conflict: R1 with S1 permitted (by P1) but R1 (with all associated scopes) denied (by P2).
The question here is "when should be a possible scope if present be permitted" 
A) in case of a unanimous decision strategy: R1 should be denied on all scopes due to P2.
B) in case affirmativ decision strategy: R1 with S1 should be permitted due to P1
