### ISSUE TITLE
Investigate possible support for Java Keystore

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10117]
* Operator will support PEM only keystore at the beginning.
* Investigate if there's any benefit in adding support for Java Keystore.

**Comment by BadgerOps** [comment]
I'll weigh in with one good reason - configuring [ldaps](https://www.keycloak.org/docs/latest/server_admin/#connecting-to-ldap-over-ssl) for User federation - unless there is another method for importing Active Directory SSL certificates into the Keycloak Operator.

**Comment by shawkins** [comment]
@BadgerOps Please see https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/24_0_0.adoc#keycloak-cr-truststores - the expectation is that you'll provide the certs as pem or in a pkcs12 keystore in a Secret. If you need specific support for jks, then we'll update this issue and leave it open for now. Otherwise we'll close this issue.

**Comment by BadgerOps** [comment]
Hi @shawkins  I forgot to come back and update my comment after stumbling across [this documentation for KC_SPI_TRUSTSTORE_* ](https://www.keycloak.org/server/all-provider-config#_truststore) . I was able to successfully test using a volume with a `truststore.jks` mounted from a secret, using `KC_SPI_TRUSTSTORE_FILE_FILE` and `KC_SPI_TRUSTSTORE_FILE_PASSWORD` 

I will re-try with the docs you just linked - I appreciate the direction!

**Comment by shawkins** [comment]
Resolving as there have been no new plans around supporting JKS.
