### ISSUE TITLE
Support for post_logout_redirect_uris in OIDC client registration

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#10135]
### Description

The motivation is here: https://github.com/keycloak/keycloak/discussions/9950

This is not strictly a blocker for the frontchannel logout support, but will be good (partly due the fact that it helps with OIDC logout certifications for all logout profiles including frontchannel logout certification). See details as issue 8 in here: https://docs.google.com/document/d/1yKg_F-pG0NPz3pxLtDc7g288d7jAC8f0leABh50BZn0

We will probably address this by adding "Post Logout Redirect URI" as new attribute on the client (Note that it will be attribute to not require more changes in the model / DB schema).

When it is filled with '+', it will just inherit "Redirect URI" configured for the client (Something similar is done for web origins).

For backwards compatibility, we may need to add '+' to existing clients, which has at least on redirect URI. It should be possible to do it with SQL query similar to this:
```
insert into CLIENT_ATTRIBUTES (CLIENT_ID, NAME, VALUE) select distinct CLIENT_ID, 'post.logout.redirect.uris' as NAME, '+' as VALUE from REDIRECT_URIS;
```

Something can be hopefully for JSON import (When importing from previous versions).

### Discussion

#9950

**Comment by infohash** [comment]
Good catch. This issue is currently affecting dynamic client registration. When the client is dynamically registered with Keycloak, Keycloak registers list of `redirect_uris` that are sent in the registration request but doesn't add `post_logout_redirect_uris` in Valid Redirect URIs.

So the user has to either mix post_logout_redirect_uris with redirect_uris before passing to the registration request or register post logout redirect URIs manually.

**Comment by Westie** [comment]
Just a note for anyone scouring the internet wondering why you get an error saying `invalid_redirect_uri` - or, "Sorry, invalid redirect uri" errors from the frontend

Upgrade to latest UI. This field is not visible from old depreciated Keycloak UI.

**Comment by dsaju** [comment]
On a k8s setup for keycloak (20.0.5) configured with edge reverse proxy setting I am seeing a problem logout from the client (account) . I GET request is  always sets the  post_logout_redirect_uri to http instead of https even though the KC_HOSTNAME_URL is set with https schema. On enabling the debug option on keycloak I see some entries from Quarkus that looks something like below - 

_2023-07-27 11:14:54,255 DEBUG [io.quarkus.vertx.http.runtime.ForwardedParser] (executor-thread-1) Recalculated absoluteURI to http://<KC_HOSTNAME_URL>


In the above log entry , I see absoluteURI  https://<KC_HOSTNAME_URL>. Does anyone has an idea on what configuration might be causing this ?

Thanks a lot for the help .
