### ISSUE TITLE
Ensure that Liquibase is only called once per area

### ISSUE THREAD

**Issue by hmlnarik** [keycloak/keycloak#10132]
## Description

Liquibase check whether update to database is necessary is costly. Ensure that the Liquibase update check is executed only once per area (clients, realms, ...) within a component lifecycle, and is always skipped when it has been executed.

## Further information

The stacktrace in https://github.com/keycloak/keycloak/pull/10124#issuecomment-1035449547 looks suspicious and may indicate that the check is run every time the storage instance is requested.

**Comment by ahus1** [comment]
:+1: for this, had a similar suspicion, and put it on the list of optimizations to make.

**Comment by pedroigor** [comment]
@hmlnarik In Dist.X we are avoiding unnecessary calls to Liquibase already but we might have room for more improvements. Is this issue considering both Wildfly and Quarkus?

Asking because we have some duplications for some key providers like jpa and liquibase connection providers. Perhaps we should start aligning and refactoring the default implementations to better support both dists?

**Comment by pedroigor** [comment]
Sorry, it is a different topic than what I was thinking.
