### ISSUE TITLE
[tech-debt] Use the new Junit extension in JOSDK

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#10148]
Quarkus Operator Extension >= 3.0.3 includes(most of) the functionalities to run the operator locally and remotely.
We should align with upstream and remove our custom code for the testing infrastructure.

**Comment by vmuzikar** [comment]
Related task: #10128

**Comment by andreaTP** [comment]
Result of the initial investigation:
https://github.com/quarkiverse/quarkus-operator-sdk/issues/328

**Comment by DGuhr** [comment]
To elaborate a bit more here before putting it on hold (and so I don't forget later):

This ticket will be put on hold for the time being, as the josdk JUnit extension does not play well with quarkus atm, for more details see the referenced ticket. My best guess is it is caused by these issues: https://github.com/quarkusio/quarkus/issues/12511 / https://github.com/quarkusio/quarkus/issues/10623 and the way the extension is created and initialized, but going down that rabbit hole would most likely result in a complete rewrite of the sdk junit extension, and as we have a funtional workaround, for now we created the reproducer. 

Putting it on hold now.

**Comment by andreaTP** [comment]
Related upstream initiative:
https://github.com/fabric8io/kubernetes-client/pull/4117

**Comment by vmuzikar** [comment]
This is no longer considered.
