### ISSUE TITLE
Admin API create group path not applied to group hierarchy

### ISSUE THREAD

**Issue by BigBallard** [keycloak/keycloak#10211]
### Describe the bug

I have been attempting to to use the Admin API to produce new groups with a path so to ensure they are in a sub group. The result of which is that the path structure is ignored all together and the new group is always placed in the root of the groups.

These are the representation combinations I have tried as I am unsure of the path structure being inclusive of the name:
```json
{
    "name": "group-b",
    "path": "sub"
}

{
    "name": "group-b",
    "path": "/sub"
}

{
    "name": "group-b",
    "path": "/sub/group-b"
}

{
    "name": "group-b",
    "path": "sub/group-b"
}
```

The expected result is that `group-b` would be created as a sub-group of `sub`.

### Version

15.0.2

### Expected behavior

A new group be created underneath the `sub` root group.

### Actual behavior

New group is created at the root.

### How to Reproduce?

- Create a group name `sub`
- Make a `curl` or equivalent request with the minimum body of
```json
{
    "name": "group-b",
    "path": "sub"
}
```

### Anything else?

This has been producible with both CURL commands and the `@keycloak/keycloak-admin-client` library.

**Comment by DallasP9124** [comment]
I decided to observe the API calls produced by the admin console. Turns out that the group creation on a parent is done with `groups/{id}/children`. 

The confusions comes from the fact that the API `POST /groups` says to pass a GroupRepresentation that which itself includes a path. This gives a false understanding of what values are intended to be passed and considered in the call. The API docs do a poor job of documenting behavior and specifics like this.

Are there any plans, active items, or considerations for updating the API docs for more brevity and explicitness?

**Comment by DallasP9124** [comment]
I want bump this. The admin API documentation sucks. Is there any plan to update it to a more descriptive and explicit?

**Comment by sschu** [comment]
I guess the fastest way to get an improvement is to provide a PR at https://github.com/keycloak/keycloak-documentation.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team don't have time to look at this in the near future. Community contribution is welcome to further investigate and eventually fix this.
