### ISSUE TITLE
Password policy 'Not email' not enforced 

### ISSUE THREAD

**Issue by aidachami-qc** [keycloak/keycloak#10234]
### Describe the bug

We noticed that even if we activate the password policy 'Not Email' we are able to create a new user using his email as a password, which does not comply with the password policy 'Not Email'. The same policy, is applied correctly in the update password's case.

When we debugged, we found that this policy receives in the email's value parameter the value of the username instead of the email's value, also. we noticed that the test fo this policy worked as expected because you tested the use case of registering a user using the email as username: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/forms/RegisterTest.java#L530

### Version

15

### Expected behavior

Have an error message informed the user that he can not create a new user using his email address as password.

### Actual behavior

We are able to create a new account with his email as password.

### How to Reproduce?

Activate the policy 'Not Email'.
Create a new account.

**Comment by rmartinc** [comment]
Hi @aidachami-qc !

Any `PasswordPolicyProvider` implements two methods:

```java
    PolicyError validate(RealmModel realm, UserModel user, String password);
    PolicyError validate(String user, String password);
```

The email policy in the case of the second one cannot check the email (because it's not there, only the username and password is passed). For that reason in the registration flow the task `Password Validation` perform the validation in two steps:

1. First it's just compares [using username and password](https://github.com/keycloak/keycloak/blob/21.0.0/services/src/main/java/org/keycloak/authentication/forms/RegistrationPassword.java#LL74C9-L74C9) (it passes as you say).
2. After creation (when the full user is in place) performs [a second validation with the first variant](https://github.com/keycloak/keycloak/blob/21.0.0/services/src/main/java/org/keycloak/authentication/forms/RegistrationPassword.java#L96). In your case it fails and the user is redirected to change the password immediately after registration. So the user is created with a wrong password but UPDATE_PASSWORD is added.

I know this is a bit weird but it's like this because of historical reasons. The email validator cannot implement the username/password variant correctly. In all the other places the first variant is used and it works OK (at least in the account auto-change password and in the admin set password by admin that I have tested).

I'm going to close this as it's explained.
