### ISSUE TITLE
Kill sessions after a password reset or MFA modification

### ISSUE THREAD

**Issue by PragmaChris** [keycloak/keycloak#10232]
### Description

Hey !

I noticed that after a "password reset" process or after adding MFA, all current sessions remain active.

To reproduce, sign in from one browser and do a password reset from another one.
After set a new password, you are always logged within the first browser.

### Motivation

It's a security good practice to kill all sessions (at least all, except the one used to make the change).

See OWASP site : https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#renew-the-session-id-after-any-privilege-level-change

Moreover, if I manually changed my password, currently all other sessions are well killed.

### Details

Use the same code as password change post actions.

Thanks.

**Comment by alex5513** [comment]
Same problem for me

**Comment by rnarayana** [comment]
Same problem. It would be nice if this didn't require a custom eventlistener, but is a default config, same behavior as Change password.

**Comment by fkhachatrian** [comment]
Hi, could anyone recommend a decent temporary solution to this issue?

**Comment by mposolda** [comment]
- When user changes his password in account console, there is AIA triggered. It has checkbox `Sign out from other devices`, which is ON by default. When user keeps it to ON, the existing sessions in other browsers are killed (not the particular session, which user just uses, but IMO this is completely fine as user has control under current browser session).

- When user changes his password by Reset-Password flow (Clicking on "Forget Password" link on the username/password screen displayed during login), then the existing sessions are not restarted and the checkbox `Sign out from other devices` is not displayed

### Possible solution

Can we just display link  `Sign out from other devices`  always on the page for updating password? This will display it also in cases when password reset is enforced by admin (EG. administrator manually adds `Update Password` required action to the user), which is completely fine IMO.

I personally don't think that we need to kill existing sessions when user adds new 2-factor authenticator to his account. If user has suspicion that his account is compromised, he will likely update his password instead of just adding new 2-factor authentication

**Comment by mposolda** [comment]
Scheduled to 22 for now, but we can possibly postpone to 23 or 22.0.1. This is not a blocker for 22 release IMO

**Comment by pedroigor** [comment]
It also makes sense for me to add the option to sign out from other devices when running the flow.

I'm not sure about destroying sessions when managing 2FA credentials. IMO, we can do it as a follow-up.

**Comment by mposolda** [comment]
Update:
- There was other PR https://github.com/keycloak/keycloak/pull/20658, which partially fixed this for the "update password" part in Keycloak 22.0.0. So when user updates his password (either by account console/AIA, required-action, forget password flow etc), there is always option "SignOut existing sessions".

- The PR did not cover multifactor authentication. So the remaining work is, that there should be displayed "Sign out from other devices" also during any add/update of any credential (OTP, WebAuthn, Recovery Codes) either by AIA or by required-action added by admin or during authentication flow

- Maybe something is also needed when user changes email. Need to figure it...
