### ISSUE TITLE
Due to "updatedAt" User Attribute, /account endpoint returns unauthorised 401

### ISSUE THREAD

**Issue by ddezoysa** [keycloak/keycloak#10263]
### Describe the bug

When updatedAt exists with a timestamp value, /account endpoint fails with 401 Unauthorised.

### Version

16.1.1

### Expected behavior

- Based on "updatedAt" User Attribute, /account endpoint should not return unauthorised 401.
- If "updatedAt" User Attribute cannot be supported in user attributes, add necessary validations to the user APIs to restrict "updatedAt" user attribute.

### Actual behavior

- When "updatedAt" User Attribute exists with a timestamp, /account endpoint returns unauthorised 401.
Ex: updatedAt: 2021-10-29T12:30:29.638Z

### How to Reproduce?

Create a user with following attribute.
updatedAt: 2021-10-29T12:30:29.638Z

Then login to https://[keycloak-domain]/auth/realms/[realm]/account/ with the user credentials and try to access "Personal Info". Account Console keeps refreshing again and again while GET https://[keycloak-domain]/auth/realms/[realm]/account/ returns 401 Unauthorized.

**Comment by stianst** [comment]
This sounds rather odd, and unexpected. You sure this is the reason? Anything in server logs?

**Comment by antek-drzewiecki** [comment]
I can confirm. updatedAt on attribute on user profile will result in a 401. Keycloak doesnt give any server logs.

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. One note here is, that `updatedAt` is considered standard attribute by OIDC specification and it is supposed to contain number (timestamp) as mentioned by @thomasdarimont. Updating attribute that way should help to avoid the issue here.

Community contribution is welcome to possibly improve exception handling in case that `updatedAt` contains some incorrect (non-properly formated) value.

**Comment by pedroigor** [comment]
See https://github.com/keycloak/keycloak/issues/26744.
