### ISSUE TITLE
Remove SPI Configuration not possible in Keycloak.X

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#10327]
### Describe the bug

Configuring a custom SPI implementation works for Keycloak.X via keycloak.conf, env variables or CLI arguments in combination with a configuration rebuild.

For instance one can set a custom login-forms provider via:
```
spi-login-provider=acme-custom-login-forms (keycloak.conf)
KC_SPI_LOGIN_PROVIDER=acme-custom-login-forms (env variable)
--spi-login-provider=acme-custom-login-forms (CLI argument)
```

However once the server updated the server configuration after `build` or `--auto-build` one cannot revert the
login-provider to the default implementation anymore.

I think support for something like `--spi-login-provider=default` would be helpful here, to revert the override.

### Version

17.0.0

### Expected behavior

It should be possible to revert the a SPI implementation override to the default implementation.

### Actual behavior

An exception is printed that the default provider cannot be found.

### How to Reproduce?

- Configure an SPI with a default implementation
- Run a config rebuild
- Start the server
- Reset the configuration again
- Run a config rebuild
- Server fails

### Anything else?

See https://github.com/keycloak/keycloak/discussions/10311#discussioncomment-2203472

**Comment by DGuhr** [comment]
@thomasdarimont is this still valid? I try to understand right now:

1) you are creating your-custom-provider.jar
1.1) you add `spi-login-provider=acme-custom-login-forms` in e.g. keycloak.conf
2) you're building it `kc.sh build`, effectively making it part of the new closed world assumption of the dist (I like to think of "build" as creating a new, closed reality). 
3) you start the server, your acme-custom-login-forms are available
4) you remove `spi-login-provider=acme-custom-login-forms` from keycloak.conf
5) you re-run `kc.sh build` 
6) server fails bc. no provider is set up.

Is that right? Asking because I first thought "not an issue, but lacking documentation", bc. we're switching providers e.g. here: https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/main/java/org/keycloak/testsuite/util/SpiProvidersSwitchingUtils.java#L95-L98 

But I am not sure what happens when you only remove the previously built-in custom provider without setting it back to "default" again manually. When this fails (so: when I understand you correctly), we need to provide some logic in the build processor to check that at least one provider is available for every factory, and if not, use "default", so effectively a fallback to default. cc @pedroigor wdyt?

**Comment by pedroigor** [comment]
Perhaps it might be related to https://github.com/keycloak/keycloak/issues/10818.
