### ISSUE TITLE
SAML/ECP: HTML Response page on error instead of SOAP Fault

### ISSUE THREAD

**Issue by MaxFichtelmann** [keycloak/keycloak#10352]
### Describe the bug

When using Keycloak with the SAML ECP protocol, the exception/error handling does not seem to follow the spec.

see https://docs.oasis-open.org/security/saml/Post2.0/saml-ecp/v2.0/cs01/saml-ecp-v2.0-cs01.html#_Toc366664732

> Regardless of the success or failure of authentication of the principal and of processing the <samlp:AuthnRequest> message, the identity provider MUST return a <samlp:Response> message or SOAP fault.

Currently, keycloak responds with a html page describing the problem either when the AuthnRequest does not fulfill requirements or the authentication fails.

It would be extra nice if the Service Provider could differentiate credential mismatch from operational errors.

### Version

16.1.1

### Expected behavior

A SamlResponse with status `urn:oasis:names:tc:SAML:2.0:status:AuthnFailed` on authentication failure.
A SoapFault on expected error cases.

### Actual behavior

A html page describing the problem

### How to Reproduce?

send a ECP request with incorrect user credentials or misconfigured client configuration to the saml endpoint.

### Anything else?

I would like to submit a PR that remediates the issue.

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by rmartinc** [comment]
Doing a little test with the [SOAPBindingTest](https://github.com/keycloak/keycloak/blob/23.0.6/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/saml/SOAPBindingTest.java) class that tests the SOAP/ECP profile, I checked the two cases you commented about:

1. Login with invalid credentials in the basic authorization header. I receive a saml response with status code `urn:oasis:names:tc:SAML:2.0:status:Responder`.
2. Login with invalid signature for the authn requests. I receive a SoapFault: `<SOAP-ENV:Fault xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><faultcode xmlns="">error</faultcode><faultstring>invalidRequesterMessage</faultstring></SOAP-ENV:Fault>`.

Maybe there are cases that are returning plain HTML instead of SOAP, if you detect those you send a PR. But the two cases I have tested retrun proper response or fault.
