### ISSUE TITLE
ConditionnalAuthenticatorFactory configuration not instanced 

### ISSUE THREAD

**Issue by please-openit** [keycloak/keycloak#10457]
### Describe the bug

On a custom ConditionalAuthenticatorFactory : 
- isConfigurable : true
- getConfigProperties : Arraylist with 2 elements (ProviderConfigProperty), each one has a default value.

In the ConditionalAuthenticator : 
context.getAuthenticatorConfig().getConfig() returns null.
Unable to access default values if the conditional authenticator has not been set. 

Works normally with AuthenticatorFactory.

### Version

16.1.0

### How to Reproduce?

Write your own ConditionalAuthenticatorFactory, configurable.

Access a configuration field in the authenticator.

Add it to your authentication flow, without any specific configuration.

Results on a "nullpointerexception"

**Comment by please-openit** [comment]
Hi @mabartos , thanks for looking at this.

We made a repo that reproduces the bug : https://github.com/please-openit/keycloak-conditional-authenticator-default-configuration
It is when we do not define a configuration for the conditional authenticator, out of the box our example does not works. We have to define by hand a configuration to the conditional authenticator.

Thanks.

**Comment by mabartos** [comment]
@please-openit Thanks! I'll check it soon.

**Comment by mabartos** [comment]
@please-openit I've been investigating the issue and I've decided to reject this issue. 

I tried to export the realm settings in Keycloak 17.0.0 and Keycloak 16.1.0 and in both cases I didn't reproduce the issue. No NPE is thrown in those situations. If the conditional authenticator is configurable and its configuration is not set up, the authenticator is disabled by default and its evaluation is not executed during the authentication flow. Besides that, the configuration should always be set up by the administrator and it's his/her responsibility to do that. 

The issue is reproducible with your custom `realm-json.xml` file[1], which seems slightly different than the one I exported. In this file, the requirement for the conditional provider is set up to `REQUIRED` instead of `DISABLED`, so the NPE is thrown when the configuration of the authenticator should be obtained. Did you modify the requirement on your own, or was it generated after exporting the realm? 

As I've mentioned, it's the administrator's responsibility to properly set up the proper configuration for the authenticators, and the configuration should always be checked despite the default values are set up or not. And I don't see any scenario/reason to keep the configuration of the authenticator not set up.

Thanks for understanding. Feel free to respond to this.

[1] https://github.com/please-openit/keycloak-conditional-authenticator-default-configuration/blob/main/realm-export.json

**Comment by please-openit** [comment]
ok @mabartos thanks for your review and precisions. We will use a configuration in our imports.

Regards,
