### ISSUE TITLE
Expired cache objects in infinispan cache are never garbage collected in standalone configuration

### ISSUE THREAD

**Issue by Skrethel** [keycloak/keycloak#10461]
### Describe the bug

Fix for https://issues.redhat.com/browse/KEYCLOAK-18518 solved session leak for standalone-ha configuration, however it seems that the same problem occurs for standalone configuration and it is not fixed. It is even mentioned in original issue that issue affects both standalone and standalone-ha modes however it seems that fix was applied only for standalone-ha.

Following screenshot shows leak analysis of memory dump taken after 2 days of heavy Keycloak usage (mostly tokens and userinfo endpoints).
Keycloak is configured to run in standalone mode with MySQL DS and 1GiB of memory assigned to JVM. Out of memory errors occurred in Keycloak log.
![image](https://user-images.githubusercontent.com/8984448/155543831-a23bc653-5138-42f5-9aff-062ca39ed097.png)
Session caches size in memory dump
![image](https://user-images.githubusercontent.com/8984448/155546550-49982c44-308b-4ba7-a3c9-38f9b5882946.png)

When workaround/fix from KEYCLOAK-18518 is applied to standalone configuration, leak is no longer occurring.
Applied configuration change
```  <subsystem xmlns="urn:jboss:domain:infinispan:12.0">
            <cache-container name="keycloak" modules="org.keycloak.keycloak-model-infinispan">
                <local-cache name="realms">
                    <heap-memory size="10000"/>
                </local-cache>
                <local-cache name="users">
                    <heap-memory size="10000"/>
                </local-cache>
                <local-cache name="sessions">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
                <local-cache name="authenticationSessions">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
                <local-cache name="offlineSessions">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
                <local-cache name="clientSessions">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
                <local-cache name="offlineClientSessions">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
                <local-cache name="loginFailures">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
                <local-cache name="work">
                    <expiration lifespan="900000000000000000"/>
                </local-cache>
```

### Version

15.1.1

### Expected behavior

No sessions in memory after keycloak is no longer used.

### Actual behavior

Sessions are kept in memory.

### How to Reproduce?

Observed during performance test for application that is using Keylock as authn/authz server.
Application is using Keycloak via REST API to authenticate users (token endpoint), validate users and their permissions (userinfo endpoint).

I've modified example from KEYCLOAK-18518 to use standalone configuration and Keycloak 15.1.1
 to showcase that issue.
[keycloak_cache_expiry_oom](https://github.com/Skrethel/keycloak_cache_expiry_oom)

**Comment by thomasdarimont** [comment]
This seems also to be missing in standalone-openshift.xml.

**Comment by ahus1** [comment]
I started a root cause analysis and traced this down to Infinispan's [ExpirationManagerImpl](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java) that will run the "reaper" only when it has been enabled via an the expiry configuration. 

In WildFly, this configuration is created indirectly via WildFly's [ExpirationServiceConfigurator.java](https://github.com/wildfly/wildfly/blob/main/clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ExpirationServiceConfigurator.java) and will enable it differently in different versions of Keycloak and Wildfly: 

| Keycloak Version | WildFly version | Activated by |
| --- | --- | --- |
| 15.1.1 | 23.0.2.Final | [`lifespan > 0 OR maxIdle > 0`](https://github.com/wildfly/wildfly/blob/23.0.1.Final/clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ExpirationServiceConfigurator.java) |
| 16.1.1 or later | 26.0.1.Final+ | [`interval > 0`](https://github.com/wildfly/wildfly/blob/26.0.1.Final/clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ExpirationServiceConfigurator.java) | 

At the same time [ExpirationResourceDefinition.java](https://github.com/wildfly/wildfly/blob/26.0.1.Final/clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ExpirationResourceDefinition.java) in WildFly 26.0.1.Final+ defines a default for `interval` of one minute.

This boils down to the following: 
* when using Keycloak 15.1.1 (and probably earlier versions as well), set either `lifespan` or `maxIdle` for all caches to enable the reaper as you suggested.
* when using Keycloak 16.1.1 or later (including the current main branch) no setting is necessary to enable the reaper as it is enabled by default via the default setting of `interval`.

This means that in the current main branch everything should work as expected. All settings of `lifespan` that were created for version 15.1.1 can be removed from the configuration. A debugging session showed me for 17.0.0 that all created caches have the reaper setting active when running the standalone configuration. 

Kudos go to @martin-kanis for pairing up with me to analyze this. Pointing me to the reaper configuration put me on the right track here. // @hmlnarik

**Comment by Skrethel** [comment]
@ahus1 Thank you for this investigating and finding root cause. If I understand correctly, this doesn't need fix for 16.1.1 or later. However in my opinion it would be useful to have (if it is possible) some kind of test that verifies that reaper is running for those sessions. If this kind of issue can sneak up once, it may occur again without being noticed. What do you think?

**Comment by hmlnarik** [comment]
@Skrethel You are right that such a test would be nice. There is such a test in model tests, however it does not target any distribution. Development and specifically maintenance of such a test in a distribution represents a nontrivial effort. Moreover, since Infinispan addressed this issue in recent version, we do not expect development of any additional testing beyond the model tests in Keycloak.

**Comment by Raufozdemir** [comment]
Hi,
I've been following you for a while. In the final result, does the default installation for the Keycloak version 16.1.1, without adding anything in the Standalone.xml or standalone-ha.xml files, solve this problem?

**Comment by Skrethel** [comment]
I've checked 16.1.1 using [keycloak_cache_expiry_oom](https://github.com/Skrethel/keycloak_cache_expiry_oom) and issue with sessions staying in memory didn't occur.

**Comment by ahus1** [comment]
Thank you @Skrethel for taking the time to confirm this!

**Comment by DikUl** [comment]
Despite what @ahus1 had been found, it still leaking in 17.0.0. Even with lifespan and maxIdle > 0. We tried it on 3 node configuration with xmx=4GB and 108 load threads. It took about ~12 hours to fill up all the heap, and then it never goes down. eviction thread working every minute, but the sessions and clientSessions caches still growing up and never cleans. I've wanted to figure out is there a way to set fixed cache size on legacy version, but no luck.

**Comment by ahus1** [comment]
@DikUl - please consider creating a new issue and provide link to a repository where one can reproduce your findings as [Skrethel](https://github.com/Skrethel) did. Analyzing your scenario is out-of-scope for this issue.

**Comment by bfyxzls** [comment]
I 've checked 14.0.0,using [keycloak_cache_expiry_oom](https://github.com/Skrethel/keycloak_cache_expiry_oom),issue with sessions staying in memory OOM,I generate dump file,then I find top 3 biggest objects

<img width="950" height="100" alt="Image" src="https://github.com/user-attachments/assets/c61525ba-352b-4852-95fa-4a004a6f65bf" />

**Comment by ahus1** [comment]
This issue has been closed long ago, and the version at hand is no longer supported. If you are affected in a recent version of Keycloak (26.5+), please open a new issue.
