### ISSUE TITLE
Keycloak 17 User Storage SPI failure

### ISSUE THREAD

**Issue by justin-stephenson** [keycloak/keycloak#10555]
### Describe the bug

My custom user storage SPI .jar works well on Keycloak 16 but fails after upgrading to Keycloak 17. I see the following errors when my plugin reaches code for JAX-RS resteasy client communication.
~~~
2022-02-28 15:31:59,010 ERROR [keycloak.scim_user_spi.Scim] (executor-thread-0) java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
2022-02-28 15:31:59,011 INFO [keycloak.scim_user_spi.SCIMUserStorageProviderFactory] (executor-thread-0) java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.client.JerseyClientBuilder
~~~

I am using the following RestEasy Client imports:
~~~
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation.Builder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Form;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.NewCookie;
import javax.ws.rs.core.Response;
~~~

My pom.xml looks like
~~~
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>keycloak</groupId>
  <artifactId>scim-user-spi</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>scim-user-spi</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-core</artifactId>
      <version>13.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-server-spi</artifactId>
      <version>13.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-jaxrs</artifactId>
      <version>3.15.0.Final</version>
    </dependency>
    <dependency>
    	<groupId>org.jboss.logging</groupId>
    	<artifactId>jboss-logging</artifactId>
    	<version>3.1.4.GA</version>
    </dependency>
  </dependencies>
</project>

~~~

### Version

Keycloak 17

### Actual behavior

Keycloak errors in previously working code. 

### How to Reproduce?

The SPI is being loaded properly, but fails when resteasy client code is reached.

The User Storage SPI code I am using is here:

https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/

### Anything else?

I tried bumping the version numbers in pom.xml and setting keycloak version to 17.0.0, but it did not help - maybe I did not get the correct versions set.

**Comment by stianst** [comment]
As Keycloak on Quarkus is not an application server this boils down to there is a lot less dependencies available out of the box. One such dependency is the RestEasy Client. 

Since Keycloak doesn't use the RestEasy Client itself it is not included in the runtime.

For outgoing request Keycloak uses Apache HTTP client, and we also have a relatively simple util that wraps around it to make it a bit simpler to use SimpleHttp.

How much effort would it be to use Apache HTTP client, or something like SimpleHttp, instead of RestEasy Client?

**Comment by justin-stephenson** [comment]
> As Keycloak on Quarkus is not an application server this boils down to there is a lot less dependencies available out of the box. One such dependency is the RestEasy Client.
> 
> Since Keycloak doesn't use the RestEasy Client itself it is not included in the runtime.
> 
> For outgoing request Keycloak uses Apache HTTP client, and we also have a relatively simple util that wraps around it to make it a bit simpler to use SimpleHttp.
> 
> How much effort would it be to use Apache HTTP client, or something like SimpleHttp, instead of RestEasy Client?

Thank you very much for the response. 

It will require re-writing a non-trivial amount of my plugin code. If it is the recommended option then of course it can be done, though I would prefer an alternative. Is there some instruction/docs on loading third party dependencies, or is this an approach that would not be recommended (or prone to breakage at some later point)? 

How would I add SimpleHTTP to my `pom.xml`? Apologies, i'm still becoming more familiar with the java ecosystem

**Comment by pedroigor** [comment]
@justin-stephenson As @stianst said, some dependencies are no longer available from the new distribution. Right now, you would need to change your provider to not use these dependencies or include them by yourself.

This is a general problem related to how we should be providing the capabilities so far available from Wildfly (e.g.: a REST/HTTP client API) without increasing the dependency graph of the server. 

The server is no longer running on top of an application server (from where you get a lot of runtime dependencies for free) and at the same time, we should not make life harder for people when they need to use 3rd party libraries when developing their providers.

For this particular case, you could change your provider to replace JAX-RS Client with our HTTP client APIs. As @stianst mentioned, you could be using the `HttpClientProvider`:

```
HttpClientProvider httpClientProvider = session.getProvider(HttpClientProvider.class);
```

And then use Apache HTTP Client API to call your endpoints.

However, that is not the best experience in terms of migration.

I was able to make your example work if we include an additional extension (`quarkus-rest-client`) into our distribution. But I'm not sure if we are going to be able to include additional extensions whenever a dependency is missing from Wildfly.

That said, we want to solve this general problem before the next release in order to unblock people from migrating. And there are still no consensus on how to do it properly.

I have a feeling that we could at least provide some key Jakarta/JEE dependencies OOTB. But not sure yet.

**Comment by justin-stephenson** [comment]
Thank you, I was able to use the keycloak `SimpleHTTP` util class and it worked well aside from a few issues I encountered.

https://github.com/justin-stephenson/scim-keycloak-user-storage-spi/commit/40e87f866dec6763c7e6123a7332f4e9e79e4249
