### ISSUE TITLE
User Session Count Limiter authenticator should return a non-generic error message when used in direct grant flow

### ISSUE THREAD

**Issue by 999eagle** [keycloak/keycloak#10563]
### Description

When limiting the maximum number of concurrent user sessions by denying new sessions using the User Session Count Limiter authenticator in a direct grant flow, Keycloak returns a HTTP 500 with the generic error message `{"error":"unknown_error"}`. Other errors in the direct grant usually generate a 400/401 and a more specific error message and this authenticator should do so as well.

### Details

According to the OAuth spec, only HTTP status codes 400 and 401 should be returned with an unsuccessful token response. For the User Session Count Limiter either one of these status codes should be returned instead of the current 500. Maybe even a 429, even though that is not specified in OAuth.  
An `error_description` should also be supplied in the response.

**Comment by mposolda** [comment]
duplicates #13368
so I am closing it. Please use that other issue for further questions/concerns/discussions around this.

I am pretty sure that it has same cause (stacktrace is not included in this issue, so I can just guess, but 99% sure that it is it). The reason is, that `context.form()` doesn't work when it is used in any authenticator inside the direct-grant flow.
