### ISSUE TITLE
Password blacklists folder

### ISSUE THREAD

**Issue by diego-cqen** [keycloak/keycloak#10608]
### Describe the bug

I'm trying to use the password-blacklists policy and the server is not recognizing my file.

Reading the documentation I see the default folder is: "${jboss.server.data.dir}/password-blacklists/". I know we don't have Jboss anymore and I did assume that the default folder would be "/opt/keycloak/data/password-blacklists/".

### Version

17

### Expected behavior

Should be able to find my blacklist file and let me add the policy.

### Actual behavior

Do not find my file and give me the error: 
ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-7) Password blacklist myfile.txt not found!: java.lang.IllegalArgumentException: Password blacklist myfile.txt not found!

### How to Reproduce?

Try to add a password blacklist policy to a realm.

### Anything else?

https://www.keycloak.org/docs/latest/server_admin/index.html#_password-policies

**Comment by ported-pw** [comment]
It's definitely broken, currently the default resolves to `/opt/keycloak/null/password-blacklists/`. If you place it in there, it works.

**Comment by rmartinc** [comment]
@diego-cqen It seems that the data dir is not found when using quarkus but you can set a specific path for the list files using the system property `keycloak.password.blacklists.path` (as in the documentation). So, for example, you can use `JAVA_OPTS_APPEND` to pass extra options to the JVM:

```
JAVA_OPTS_APPEND="-Dkeycloak.password.blacklists.path=/path/to/folder" ./kc.sh start ...
```
And place the files in that folder.

@thomasdarimont Maybe in quarkus the system prop `kc.home.dir` should be checked instead of data. WDYT? I can provide a little PR if you are OK.

**Comment by thomasdarimont** [comment]
@rmartinc Yes I think it would make sense to change the lookup. However I'm not sure whether we need to check both places `kc.home.dir` and `jboss.server.data.dir` for backward compatibility.

Btw. the current test-suite sets the path explicitly in the keycloak.conf.
https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/servers/auth-server/quarkus/src/main/content/conf/keycloak.conf#L36
```
#password-blacklists path
spi-password-policy-password-blacklist-blacklists-path=${kc.home.dir:}/dependency/password-blacklists
```

**Comment by rmartinc** [comment]
@thomasdarimont OK, understood, I'll prepare a PR during the week.

**Comment by DGuhr** [comment]
Instead of making the existing factory supporting both usecases, i'd love to see the pr provide a quarkus specific provider/factory. So provide another impl for quarkus instead? 

Example: remove the problematic jboss provider in https://github.com/keycloak/keycloak/blob/f77ce315bbbd6b7c9ffe185faf9c1d15ebae95c4/quarkus/deployment/src/main/java/org/keycloak/quarkus/deployment/KeycloakProcessor.java#L147 and add a specific new one to the runtime package. You can look at the other excluded classes to see how we did it for other providers, e.g. the new QuarkusFolderThemeProviderFactory provides a default dir as fallback, and thus removes the need to set the config in the shell script.

**Comment by rmartinc** [comment]
@DGuhr OK, no problem, I'll implement a special class for quarkus, but I'll extend the current wildfly one. All the code is the same except a little override to get the default folder. I think that tomorrow I can have the PR ready. Thanks!
