### ISSUE TITLE
Keycloak admin UI drops https port if --hostname is used

### ISSUE THREAD

**Issue by sberyozkin** [keycloak/keycloak#10627]
### Describe the bug

If I do
```
docker run --name keycloak -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -p 8543:8443 -v "$(pwd)"/target/classes/server-keystore.jks:/etc/server-keystore.jks quay.io/keycloak/keycloak:17.0.0 start  --hostname=localhost --https-key-store-file=/etc/server-keystore.jks
```
and then go to `https://localhost:8543` to the Admin UI which is displayed correctly and then click on an option to administer Keycloak, it fails with `404` the link has something like `https://localhost/somepath`, without `:8543`.

Replacing `--hostname=localhost` with `--hostname-strict=false` fixes it.

Perhaps it is a misconfiguration issue

### Version

17.0.0

**Comment by rmartinc** [comment]
Try with `--hostname=localhost:8543`.

**Comment by stianst** [comment]
Looks like same issue as mentioned in https://github.com/keycloak/keycloak/discussions/10331

**Comment by stianst** [comment]
You should not really include the port in `--hostname`, but seems for some reason that works now. 

`--hostname=localhost` should be all that you need and as long as proxy mode is not enabled it should use the ports from the request.

**Comment by DGuhr** [comment]
I think i finally found the problem.. 

we have 

```
noProxy = Configuration.getConfigValue("kc.proxy").getValue().equals("none");
```
in the quarkus [DefaultHostnameProvider](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L212) - this always leads to false, because the actual configvalue we get back when calling `Configuration.getConfigValue()` looks like this: 

```
value ConfigValue{name='quarkus.http.proxy.proxy-address-forwarding', value='false', rawValue='null', profile='null', configSourceName='null', configSourceOrdinal=0, configSourcePosition=0, lineNumber=-1}
```
so when getPort is called it assumes we're behind a proxy though we are not, and returns -1 [here](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/hostname/DefaultHostnameProvider.java#L99-L112)


changing the noProxy resolver to 

```
noProxy = Configuration.getConfigValue("kc.proxy").getValue().equals("false");
```

and starting up with 

```
kc.sh start --hostname=id.keycloak.test --https-certificate-file=../conf/id.keycloak.test.pem --https-certificate-key-file=../conf/id.keycloak.test-key.pem --https-port=8988
```

(having id.keycloak.test set up locally)

seems to work.

I'll check with other ports etc.. the resolvement of `Config.getConfigValue` is somehow unexpected for me though, as the defaultvalue of kc.proxy is set to "none" [here](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/ProxyPropertyMappers.java#L22). 

cc  @Pedro Igor Silva

I'll provide a PR to see how the CI behaves, we have at least some hostnametests and I am very irritated this does not fail.

**Comment by psytester** [comment]
Looks like I noticed this in my previous configuration playground as well ???

The behavior of the "Management Console" link in the UI differs to the setup.

bin/kc.sh start in production mode is forcing TLS and will build redirect urls with https schema. I have no TLS setup at this stage.

Thus I'm using bin/kc.sh start-dev for development to have full http access on port 8080

BTW: Is it forced now in production mode, to have TLS on admin interface, too??? With Wildfly we could use internal interface and without TLS.

Case 1)
hostname is not set!
hostname-strict=false

now some hostname-admin variants:
variant 1a) pure hostname
hostname-admin=keycloak-1.local --> UI Link to http://keycloak-1.local:8080/auth/admin/ click on it all redirects and resources are loaded as expected.

variant 1b) with port
hostname-admin=keycloak-1.local:8080 --> UI Link to http://keycloak-1.local:8080:8080/auth/admin/ which is invalid for sure
manual call of http://keycloak-1.local:8080/auth/admin/ redirects to --> http://keycloak-1.local:8080:8080/auth/admin/master/console/ which is invalid
manual call of http://keycloak-1.local:8080/auth/admin/master/console/ loads other resources, but gets an error in browser console:
``` 
		Uncaught ReferenceError: Keycloak is not defined
			<anonymous> http://keycloak-1.local:8080/auth/resources/5i94q/admin/keycloak/js/app.js:14
			jQuery 13
		app.js:14:24
``` 

variant 1c) not set
hostname-admin is not set! --> UI Link to http://keycloak-1.local:8080/auth/admin/ and all redirects and resources are loaded as expected.

Case 2)
hostname=my_domainname
hostname-strict=false

same hostname-admin variants again:
variant 2a) pure hostname
hostname-admin=keycloak-1.local --> UI Link to http://keycloak-1.local/auth/admin/
manual call of http://keycloak-1.local:8080/auth/admin/ redirects to --> http://keycloak-1.local/auth/admin/master/console/ and ends up in no connection
manual call of http://keycloak-1.local:8080/auth/admin/master/console/ works partly, but finally it tries to load this resource from wrong port: http://keycloak-1.local/auth/js/keycloak.js?version=5i94q

variant 2b) with port
hostname-admin=keycloak-1.local:8080 --> UI Link to https://keycloak-1.local:8080/auth/admin/, direct call is possible, it redirects to /auth/admin/ --> to /auth/admin/master/console/
but finally it tries to load this resource from hostname value and this domain name is not in local DNS http://my_domainname/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=5i94q

variant 1c) not set
hostname-admin is not set! --> UI Link to http://my_domainname/auth/admin/
But the admin part is not expected to be reachable over public domain name. This is not wanted for security reason.
