### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by emreisler** [keycloak/keycloak#10769]
### Describe the bug

When user registers with identity provider LinkedIn, name and surname appers like ��ahin (should be şahin)
This problem doesn' t occur while registering via Google and Facebook.
 

### Version

17.0.0

### Expected behavior

surname should be şahin

### Actual behavior

surname appears as ��ahin

**Comment by DGuhr** [comment]
Hey @emreisler  could you please try out a build from latest main and see if the issue is solved for you? I just tried to reproduce the error, but could not reproduce it (but also didn't change something on our side afaict). See screenshot:
![Screenshot 2022-03-21 at 17 38 31](https://user-images.githubusercontent.com/89905860/159312179-f5266990-3e3d-4929-8540-a869aef1d500.png)

so would be nice if you could re-check with latest main (e.g. check out the project, run `mvn clean install -DskipTests -Pdistribution` in root dir, then you'll find the zip/tar in `<root>/quarkus/dist/target`)

**Comment by emreisler** [comment]
Hey @DGuhr.
The issue is solved with using latest version jboss/keycloak - Docker Image, like you said.
Thank you for your interest.
