### ISSUE TITLE
RoleStorageProvider does not get picked up by Keycloak

### ISSUE THREAD

**Issue by CollinAlpert** [keycloak/keycloak#10768]
### Describe the bug

I have implemented a `RoleStorageProvider` and registered it in META.INF/services. I can see that it gets loaded when I start Keycloak. However after I log in and head to the "Roles" section, I can neither see nor search for the roles the Provider is supposed to import. I tried to set breakpoints in any of the Providers methods and none of them, including the Factory's `create` method get called.

What am I missing? Do I need to enable it, similarly to a `UserStorageProvider` in the "User Federation" section? I couldn't find a way to do this in the UI. Any help is greatly appreciated.

### Version

17.0.0

### Expected behavior

The roles show up in the Roles => Realm Roles tab and I can search for specific roles.

### Actual behavior

None of the roles are displayed in the tab.

### How to Reproduce?

1. Create a `RoleStorageProvider` which returns any number of custom roles
2. Create a JAR with a META.INF/services/org.keycloak.storage.role.RoleStorageProviderFactory file
3. Put it in Keycloak's `providers` directory
4. Start Keycloak
5. Search for your custom roles in Roles => Relam Roles

### Anything else?

I debugged the Keycloak source code a bit and found that my UserStorageProvider was being loaded in the `CachedRealm#componentsByParentAndType` field, however my RoleStorageProvider's implementation is missing. I don't know if that helps.

![IMAGE 2022-03-16 13:56:30](https://user-images.githubusercontent.com/14217185/158594748-744f1b79-674d-4c04-a2c1-754304377409.jpg)

**Comment by Strangeboylego** [comment]
Ok,  so here is my idea.
I would expect you are using next dependency.
 <dependency>
   <groupId>org.keycloak</groupId>
   <artifactId>keycloak-dependencies-server-all</artifactId>
  </dependency>
By default it contains:
 <dependency>
   <groupId>org.keycloak</groupId>
   <artifactId>keycloak-model-jpa</artifactId>
  </dependency>
 So  role provider is picked up from there.
 
 If you need custom role or client  provider:
 1) Implement RoleProviderFactory and not RoleStorageProviderFactory.
 2) Override getOrder() there , by default it is 0, in  jpa implementation it is 1.
    So you need to return there something bigger, for example 10.
    `@Override
    public int order() {
        return 10;
    }`
 3) It could be that concrete provider hardcoded in   json file.
 So check in json file (for me it is called **_keycloak-server.json_**), for something like this:
 `  "client": {
    "provider": "${keycloak.client.provider:jpa}"
  },`      for client provider 
    "role": {
    "provider": "${keycloak.client.provider:jpa}"
  },      for role provider.
  
  You will have to remove this records.
  
  No you should be fine.
  But as a tip,  from me.
  On application startup you will probably get an error, because your custom providers will be used for all realms.
  so I would do next:
  
`public class CustomClientProvider implements ClientProvider {

  private final RealmProvider defaultProvider;

  public CustomClientProvider(KeycloakSession session) {
    EntityManager em = session.getProvider(JpaConnectionProvider.class).getEntityManager();
    this.defaultProvider = new JpaRealmProvider(session, em, new HashSet<>());
  }

@Override
  public ClientModel getClientById(RealmModel realmModel, String s) {
    if(realmModel.getName().equals("yourRealm")) {
      return null;//your custom logic
    }
    return defaultProvider.getClientById(realmModel, s);
  }
`

**Comment by hmlnarik** [comment]
Sadly, `RoleStorageProvider` is not supported (contrary to `UserStorageProvider`).
You will be able to implement a role storage once the new storage (a.k.a. map storage) would be released. At this moment, map storage is in preview state and only has documentation available in JavaDoc.

**Comment by mhartkorn** [comment]
Since this was written, the Map Storage project has been canceled.

Is there any chance that Keycloak will gain this feature in the near to medium future?
