### ISSUE TITLE
User's properties not visible with UserStorageProvider's cache policy set to DEFAULT 

### ISSUE THREAD

**Issue by CollinAlpert** [keycloak/keycloak#10824]
### Describe the bug

When registering a custom UserStorageProvider in the User Federation section of Keycloak, unless its Cache Policy is set to "NO_CACHE", a user's properties are not displayed.

### Version

17.0.0

### Expected behavior

No matter what Cache Policy I choose, the user's properties are displayed.

### Actual behavior

When choosing anything other than "NO_CACHE", the user's properties are not visible.

### How to Reproduce?

Here is a repro: [KeycloakTest.zip](https://github.com/keycloak/keycloak/files/8305848/KeycloakTest.zip).
1. Run `docker build -t keycloak-test . && docker run -p 8080:8080 keycloak-test` to start up a Keycloak server with my UserStorageProvider bundled.
2. Log into localhost:8080 with admin/admin.
3. Register my UserStorageProvider in the "User Federation" section and set the Cache Policy to "DEFAULT".
4. Head over to the "Users" section and select the "LoremIpsum" user.

His first and last name are not displayed.

5. Change the UserStorageProvider's Cache Policy to "NO_CACHE"
6. View the same user again.

His first and last name are now displayed.

**Comment by vramik** [comment]
@CollinAlpert Thank you for reporting the issue. Although I was able to reproduce it previously in keycloak 17, now with current main I am not. Therefore I'm adding it back to triage state. 

I updated your example provider to latest sources and user's first and last name are properly displayed even with DEFAULT cache settings. It seems it might have been fixed already.

Could you please check and verify with latest release if the issue is still present?
