### ISSUE TITLE
After reset password auto logged in to the system

### ISSUE THREAD

**Issue by veerakishorekallam** [keycloak/keycloak#10878]
### Describe the bug

Hi Team,

After we reset the password user is redirected to home page without asking the login to the system.
Steps to reproduce the issue
1.Click on forgot password
2.Enter email and submit
3.Received the link 
4.Click on link
      -  ( If the keycloak opened in same browser user is auto logged in after set the password)
      -  ( If the keycloak opened in different browser getting the login form after set the password)
5.Set the new password

Thanks
Veera

### Version

16.1.0

### Expected behavior

Expected : After change password user should be redirect to login page and enter new password for login.

**Comment by stianst** [comment]
This is expected behaviour and it's pointless to ask the user to enter the password again after they've just reset it.

**Comment by eldarj** [comment]
Keycloak isn't an application on it's own - it doesn't make any sense to say that something is expected behavior when obviously use cases dictate that. 

Most applications on the web will request you to login with the newly created password, you can argue that actually this is the expected behavior.

In either case - this issue should be open really and investigated whether it's feasible to implement a mechanism to easily disable the automatic login if someone would want to do so.

**Comment by SergeyZubatkin** [comment]
@stianst
Completely agree with you, asking for the password after setting the password is pointless. Why does Keycloak ask to login if user  opens email link in new browser? (case 4.2 from original scenario) Is it somehow security related?

**Comment by dcbCIn** [comment]
IMHO it's a valid and very appreciated issue.
The main purpose for me is to enable users to reset their password even if they don't use any system. There is no point in redirecting the user to a page that he is not supposed to have access.

We use this feature to reset ldap password that provides access to many things, but not all users have access to anything outside ldap, and in this case is pointless to redirect the user to a system that he don't have access.

**Comment by battosai30** [comment]
If you have restriction by role for example, this "auto-login" feature is a safety issue : https://github.com/sventorben/keycloak-restrict-client-auth/issues/121

In my case, for example a user which is not allowed to access to a specific app can't when it uses the standard form. But if he reset its passwors, he can log to the app ... At least it would be great to have a step in flow to logout a user, so we could choose the behaviour.

When you work in a companies or equivalent structure, you have to limit accesses, and not all apps allows to "filter" users from roles. So for me it's a really strategic issue :s

**Comment by xgp** [comment]
Agreed that asking for the password after setting the password is not necessary. However, this problem also seems to circumvent things like OTP, or other parts of the login authentication flow.

**Comment by jordibuj** [comment]
My application doesn't allow multiple tabs open, for good reasons. That means, if the user loads the application in another tab, the first one will be kicked out.
Now we are introducing OIDC login with Keycloak, and the reset password flow doesn't play well with this requirement.

1. The user clicks on forgot password link in Keycloak login page
2. Then submits the form with the username
3. The browser goes back to the login page with the message saying the email has been sent, username field is prefilled with the value sent in the previous form, and password field is empty.
4. User receives the email, then clicks on the email link.
5. A second tab is open where the user changes the password.
6. Then, both tabs are allowed in, and one of them fails because of the single tab requirement.

Would it be possible to prevent this behaviour? Either by redefining the reset credentials flow, or by extending the existing one with some custom behaviour?
I'm thinking of preventing the background tab being allowed in, when the password field is empty, and the user is interacting in a different tab, but other solutions would be welcome as well

**Comment by prifulnath** [comment]
I am facing the same issue as well. I needed to redirect to login page after the password reset.
I think where to redirect after login should be configurable from keycloak realm settings itself.

**Comment by avpdiver** [comment]
Agreed. Same issue.

**Comment by gautierrog** [comment]
same issue, that's a surprising behavior.

**Comment by gautierrog** [comment]
One thing we did to circumvent the issue are to use the keycloak SPI in order to:

- implement an event listener on "UPDATE_PASSWORD" event which set a custom required action on the user
- the required action redirects to a page notifiying user he has to reconnect and make the authentication process fails through a call to `context.failure`

The kinematics works as is:
As soon user reset his password the required action is called through the following authentication process, since the required action make it fails, the user is not logged in and is redirected to login page.
It logs a CUSTOM_REQUIRED_ACTION error but it's the cleanest solution I found so far.

Hope this helps.

**Comment by edwardpress** [comment]
> One thing we did to circumvent the issue are to use the keycloak SPI in order to:
> 
> * implement an event listener on "UPDATE_PASSWORD" event which set a custom required action on the user
> * the required action redirects to a page notifiying user he has to reconnect and make the authentication process fails through a call to `context.failure`
> 
> The kinematics works as is: As soon user reset his password the required action is called through the following authentication process, since the required action make it fails, the user is not logged in and is redirected to login page. It logs a CUSTOM_REQUIRED_ACTION error but it's the cleanest solution I found so far.
> 
> Hope this helps.

Hi @gautierrog can you provide some links/resources on making the above implementation possible? I have some idea on how to implement custom listener for update password but I am not quite sure how u set a required_action to user from there
