### ISSUE TITLE
Use Quarkus JOSDK to generate CSV for OLM in the operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#10911]
This is a follow-up from #10908. We should be able to ged rid of most of the shell scripts.

**Comment by ASzc** [comment]
Copied from #20630:

The operator OLM YAML files are essential for a functional bundle. Currently they are generated by manually calling a custom script, `operator/scripts/create-olm-bundle.sh`, based on templates in `operator/olm-base/`. Since they are manually generated, they're not accessible to maven and any build process based around that.

Ideally these should be generated through maven, and subsequently deployed as a maven artifact of the keycloak-operator pom, probably a zip or tar archive of the files, perhaps with the classifier of `olm` to distinguish it from the archive of quarkus+operator jars already deployed.

At the same time, it probably makes sense to take advantage of the Java Operator SDK's ability to generate these files, since the SDK is already integrated into the maven build. Integrating the scripts themselves is possible, though far less portable, since CLI tools like `yq` need to be installed.

**Comment by ASzc** [comment]
I'm picking this up, I'd rather get this all done now than have to come back later and change the product automation
