### ISSUE TITLE
The base path of admin API is not correct in doc

### ISSUE THREAD

**Issue by Jeff-Tian** [keycloak/keycloak#11007]
### Describe the bug

The base path of admin API is not correct.

![image](https://user-images.githubusercontent.com/3367820/160811933-c05176db-3c0f-41aa-ba1b-380975c2faa1.png)

### Version

17.0

### Expected behavior

The base path for Admin API should be /auth/admin/realms.

Only change the base url to /auth/admin/realms you can get the correct result, for example:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/3367820/160813251-00b24c80-cab5-4364-a520-94b29fa4e366.png">

### Actual behavior

The docs shows the base path as /auth.

By composing the url you get endpoint 404 not found, for example:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/3367820/160812876-09c56c06-6e00-4054-9e56-064056ef26e7.png">

### How to Reproduce?

See https://www.keycloak.org/docs-api/17.0/rest-api/#_role_mapper_resource

### Anything else?

fix: https://github.com/keycloak/keycloak/pull/10933

**Comment by minusdavid** [comment]
Finding this issue was really helpful and vindicating.

All the old documentation is still wrong, which is super confusing. 

I think the new documentation for 19.0.3 is right at https://www.keycloak.org/docs-api/19.0.3/rest-api/index.html but it's still a little bit confusing. It would be nice if it said that "[/admin/realms](http://localhost:8080/admin/realms)" was the base URL for the API...
