### ISSUE TITLE
Multiple Vulnerabilities not being picked up in Quay

### ISSUE THREAD

**Issue by ice-safaali** [keycloak/keycloak#11051]
### Description

Hi,
We use a combination or Amazon Inspector and we will double check with trivy. There are a bunch of vulnerabilities not being shown in Quay. I will also send and email to the security team as this seems to to be something that has happened before.

Version 16.1.0, 16.1.1, 17.0.0 and 17.0.1 are coming back with these critical and high vulnerabilities.

**17.0.1:**
![image](https://user-images.githubusercontent.com/99017786/161226044-c76dd757-22f4-4ac6-86c8-3b40833896f9.png)

**17.0.0:**
![image](https://user-images.githubusercontent.com/99017786/161226220-33451365-9376-447b-9091-fbf580eb2b76.png)

**16.1.1**
![image](https://user-images.githubusercontent.com/99017786/161226365-124f5ab0-ae36-4eb2-a38a-027cc2c3ef21.png)

**16.1.0**
![image](https://user-images.githubusercontent.com/99017786/161226737-476b5070-a501-44fe-a14b-86a13d3b0b8e.png)

**Comment by abstractj** [comment]
@ice-safaali as mentioned on the mailing list for issues related with the Quay reports, please reach out to their team.

Trivy is part of the Keycloak main repository[1] and the scan runs on the [daily basis against our nightly builds](https://github.com/keycloak/keycloak/blob/main/.github/workflows/trivy-analysis.yml).  We do not maintain old releases of Keycloak.

The only tags that should remain up to date are `latest` and `17.0.1`. Please give nightly build a try and let us know.

**Comment by ice-safaali** [comment]
@abstractj 

This is what I am getting from the nightly build:

![image](https://user-images.githubusercontent.com/99017786/161281286-bf492486-fef6-4e49-a1a3-51b188d3a8f4.png)

**Comment by abstractj** [comment]
Following up on the issues reported on 17.0.1:

- openssl-libs: fixed in the nightly builds, but should be fixed also on the latest release.
- com.h2database:h2

Adding the quote from the CVE only to bring more context to the conversation: _"H2 Console doesn't accept remote connections by default. If remote access was enabled explicitly and some protection method (such as security constraint) wasn't set, an intruder can load own custom class and execute its code in a process with H2 Console (H2 Server process or a web server with H2 Console servlet)."_ - https://github.com/h2database/h2database/security/advisories/GHSA-h376-j262-vhq6

Keycloak does not enable it by default.

- com.fasterxml.jackson.core:jackson-databind: we have a fix in progress https://github.com/keycloak/keycloak/pull/10917

- com.thoughtworks.xstream:xstream: fixed by https://github.com/keycloak/keycloak/issues/11063

**Comment by abstractj** [comment]
Thanks for bringing this issue to our attention. Now we have an extra check with Trivy (https://github.com/keycloak/keycloak/blob/main/.github/workflows/trivy-analysis.yml), and our team has been proactively acting to improve it.

For now, I'm closing this issue because I believe it was clarified. But if you disagree, please reopen.
