### ISSUE TITLE
Blank admin/master/console/

### ISSUE THREAD

**Issue by AlexeiKlimenko** [keycloak/keycloak#11113]
### Describe the bug

Installed 17.0.1 on Debian 11. 
Config is listed below. Certificates have been issued by domain Windows CA.

Admin user has been successfully created with lynx.

Faced with issue - blank page via visiting https://%server_fqdn%:8443/admin/master/console/
%server_fqdn% is FQDN equals to config file (keycloak.conf):

https-certificate-file=/server/cert/cert.crt
https-certificate-key-file=/server/cert/key-decrypted.key
hostname=%server_fqdn%:8443

User/Pass for admin are not requested during opening admin console.
What's wrong?

### Version

17.0.1

**Comment by niceborn** [comment]
Please try to set environment variable KC_PROXY=edge, this helped me

**Comment by DGuhr** [comment]
Also, pls try to remove the port from the HOSTNAME config first. That was a bug in 17.0 leading to people using the port in the hostname. that bug was fixed in 17.0.1, there `8443` is set as default. Setting proxy to edge might not help here, as the https-port is not standard 443. That is another bug related to running keycloak with https without a proxy. I created this PR for that one: #11119

**Comment by DGuhr** [comment]
@AlexeiKlimenko Did it work out for you? I'll close here for now. feel free to re-open when there are still problems.

**Comment by maradanasai** [comment]
I'm getting the black page after the setup with 18.0.2 version

**Comment by tharukan** [comment]
> Also, pls try to remove the port from the HOSTNAME config first. That was a bug in 17.0 leading to people using the port in the hostname. that bug was fixed in 17.0.1, there `8443` is set as default. Setting proxy to edge might not help here, as the https-port is not standard 443. That is another bug related to running keycloak with https without a proxy. I created this PR for that one: #11119

This is worked for me. Thank you.
