### ISSUE TITLE
[Quarkus | CLI | Windows]  `-` abbreviations not recognized for start, build and start-dev

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#11185]
### Describe the bug

When invoking `-h` for all but the kc.bat command, keycloak starts up / builds instead of showing the CLI help

### Version

current (quarkus)

### Expected behavior

Help is shown

### Actual behavior

command is invoked instead of help is shown

### How to Reproduce?

1) download zip on windows
2) run e.g. `bin/kc.bat start-dev -h`
3) see build is triggered instead of help is shown.

### Anything else?

we're missing tests for invoking the short `-h` on subcommands of the script. we have one test that checks `kc.sh/bat -h` shows help, but as `kc.bat` without arguments also shows the help this test is ambiguous.

**Comment by DGuhr** [comment]
also true for e.g. `-pf`, shorthand for --profile. This leads to `StartCommandDistTest.failIfAutoBuildUsingDevProfile` failing. Running the test using 
```
@Test
    @Launch({ "--profile=dev", "start", "--auto-build", "--http-enabled=true", "--hostname-strict=false" })
    void failIfAutoBuildUsingDevProfile(LaunchResult result) {
        CLIResult cliResult = (CLIResult) result;
        assertThat(cliResult.getErrorOutput(), containsString("You can not 'start' the server in development mode. Please re-build the server first, using 'kc.sh build' for the default production mode."));
        assertEquals(4, cliResult.getErrorStream().size());
    }
```

works. changed title accordingly as it seems to be a more general error.

**Comment by Pepo48** [comment]
Hi, 
as per @DGuhr request I take a look at this issue. The problem is with the if clause in the `kc.bat` script[1].
When it comes to Windows CMD/DOS syntax the IF statement does not support logical operators AND and OR.
Cascading IF clauses like it can be seen on the line no. 59 translates to the implicit conjunction.
But in this particular the OR operator is needed, so we can always do something like:
```SET RES=False
if "%KEY:~0,2%"=="--" SET RES=True
if not "%KEY:~0,2%"=="-D" SET RES=True
if "%KEY:~0,1%"=="-" SET RES=True
if "%RES%"=="True" (...) 
```

I will provide the fix ASAP.

[1] https://github.com/keycloak/keycloak/blob/main/quarkus/dist/src/main/content/bin/kc.bat#L59
