### ISSUE TITLE
Sync user attributes on identity provider account linking

### ISSUE THREAD

**Issue by isla-nye** [keycloak/keycloak#11195]
### Describe the bug

Currently, user attributes do not seem to sync when using account linking from an identity provider, despite mappers being set up for the identity provider.

I can see a PR open that seems to address the issue (though no issue open on Github as far as I can see), could this be reviewed?

https://github.com/keycloak/keycloak/pull/8139

### Version

17.0.1

### Expected behavior

When a user has their account linked from an identity provider and attribute mappers are set up for the provider, the attributes are created for the Keycloak user using their identity provider account.

### Actual behavior

A user can successfully link to an identity provider account but no attributes are created for the user.

### How to Reproduce?

Enable account linking only for an identity provider and mappers for some attributes.

### Anything else?

PR seems to be open here:
https://github.com/keycloak/keycloak/pull/8139

**Comment by mposolda** [comment]
Adding label "help wanted" . The PR #8139 was closed due the missing automated test. Anyone is welcome to continue with that work and send new PR with the test for this.

**Comment by ch-lepp** [comment]
I asked the question already in the comments of the PR. But since the PR is closed, I don't know if you gonna see it.
So I am asking my question here again:

I was just looking for a suitable spot to add the requested automated tests, but couldn't find any automated tests for the IdentityBrokerService class at all...

As far as I can see, there are none in the [test section of the services project](https://github.com/keycloak/keycloak/tree/168734b817da2138548bacba973204e80f566b2c/services/src/test).
And I could not find any tests for the account linking usecase in the [test suite project](https://github.com/keycloak/keycloak/tree/main/testsuite) either.

Where are automated tests for this class supposed to be?
Are there any so far?

**Comment by toddkazakov** [comment]
Opened a new PR with integration tests included (#20248)
