### ISSUE TITLE
hostname-strict-backchannel=false does not work

### ISSUE THREAD

**Issue by phamlankt** [keycloak/keycloak#11315]
### Description

I setup a cluster of 3 Keycloak v17.0.1
There is an external Loadbalancer for external access via https://external.test.com
So I set the hostname=external.test.com
The access from external works well

I set up another internal Loadbalancer for internal acces via http://internal.local.com
So I set the parameter hostname-strict-backchannel=false
When I tried to access http://internal.local.com, I can see the "Welcome to Keycloak" page, once I clicked on Administration Console, it then redirects me to the external URL and give the error:
WE are sorry...
Invalid parameter: redirect_uri
Back to Application

I expect to get the login adminsitration Console works through the internal URL too. Or did I do something wrong?

**Comment by phamlankt** [comment]
Thanks.
After setting the valid redirect URI as you mentioned, I don't receive the error: Invalid parameter: redirect_uri anymore.
However the page still redirects me to the external URL which is https, after typing in the username/password to login, it change to http://external.test.com which is http and it does now work either. 
How to make this page dynamically, stay on internal or external depending on the access URL I use (like https://external.test.com or http://internal.test.cm) but not to redirect always to external link?

**Comment by pedroigor** [comment]
The login page is always served from the `hostname` you set. That means it will always go through the frontend URL (the public URL).

Recently, we did some changes to use a relative path when loading static admin resources but the server URL used for authentication (used by `keycloak.js`) is still based on the `hostname`.

I'm not sure if we are able to change this behavior. @stianst wdyt?

**Comment by phamlankt** [comment]
ah ok. But for the communication between the application and the Keycloak server, I can always use the internal link without being redirected to the frontend URL, right?

**Comment by pedroigor** [comment]
Communications between your application and the server through the backchannel (e.g.: token endpoint requests) should work fine if you use the internal URL.

The main impact of the `hostname-strict-backchannel` option is on the OpenID Connect Discovery Document. If set to `false` the backchannel endpoints (e.g.: token endpoint) are advertized based on the request URL. Otherwise, their URLs are based on the hostname/frontend URL.

**Comment by phamlankt** [comment]
ok thank you very much. I will ask our developers to try.
1 more thing which might be irrelevant here, could you please send me some links to monitor the Keycloak. What I want to see for example is, if one user is connected/authenticated, how can I know which cluster node is the owner, which cluster node has the replica of user authentication information? I tried to look in the debug log, but could not find what I wanted to see.

**Comment by phamlankt** [comment]
What do you mean by regular URLs for admin console? @stianst

**Comment by stianst** [comment]
> What do you mean by regular URLs for admin console? @stianst

If "login" is hosted on "mykeycloak.org", while the admin console on "kcadmin.internal" the admin console should redirect to "mykeycloak.org" for authentication.

**Comment by phamlankt** [comment]
Thanks @stianst  for the explaination. it means that we have to go externally to access admin account. Not sure if it is possible, but it would be nice  to be able to access admin console via internal link that can be set.

**Comment by stianst** [comment]
Not quite, you can still access (and limit expose) the admin console, and the underlying APIs, from the internal links. It's just that the admin console uses the external links for authentication, which it figures out based on the frontend URL.

**Comment by phamlankt** [comment]
Thanks everyone for helping me in this topic.

**Comment by edwint88** [comment]
I don't want to open a new ticket, because I think my problem is related somehow with what is discussed here.

Currently I’m running Keycloak 18 in a OKD Cluster and I have set a frontend URL to access a realm and one client. But then I have a spring boot micro service that I want to access Keycloak only in the cluster (internally). All works fine, up until one point when the Keycloak adapter somehow magically change form the Keycloak internal URL to the public URL.

Looking into the console in the client generated JSON for the adapters, the auth-server-url is generated with the public URL and I think that is in a way how Keycloak resolves the auth-server-url, although in the micro service the URL is set to the internal URL.

`2022-06-17 09:28:01.757 DEBUG 1 --- [nio-8445-exec-5] o.a.h.impl.conn.tsccm.ConnPoolByRoute    : Releasing connection [{}->http://internalURL:80][null]
2022-06-17 09:28:01.757 DEBUG 1 --- [nio-8445-exec-5] o.a.h.impl.conn.tsccm.ConnPoolByRoute    : Pooling connection [{}->http://internalURL:80][null]; keep alive indefinitely
2022-06-17 09:28:01.757 DEBUG 1 --- [nio-8445-exec-5] o.a.h.impl.conn.tsccm.ConnPoolByRoute    : Notifying no-one, there are no waiting threads
2022-06-17 09:28:01.758 DEBUG 1 --- [nio-8445-exec-5] o.a.h.i.c.t.ThreadSafeClientConnManager  : Get connection: {s}->https://publicURL:443, timeout = 0
2022-06-17 09:28:01.758 DEBUG 1 --- [nio-8445-exec-5] o.a.h.impl.conn.tsccm.ConnPoolByRoute    : [{s}->https://publicURL:443]`

How can I resolve this?

**Comment by pedroigor** [comment]
The adapter should be fetching the server endpoints from the discovery document (well-known endpoint). Even if you set the `auth-server-url` to use the internal address, it will still use the public URL when reaching out any frontend URL like authorization or logout endpoints.

**Comment by edwint88** [comment]
So what's the solution here? I have set `--hostname-strict-backchannel=false` too ...is there a way to prevent to use the frontend URL?
