### ISSUE TITLE
keycloak 17.0.1 unable to add user (Production mode)

### ISSUE THREAD

**Issue by missourian55** [keycloak/keycloak#11332]
### Describe the bug

When I tried this

```bash
./bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin
Logging into http://localhost:8080/auth as user admin of realm master
Enter password: ********
null [RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/master/protocol/openid-connect/token]
```

Then tried this, because */auth* was removed from 17.0.1

```bash
./bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin
Logging into http://localhost:8080 as user admin of realm master
Enter password: ********
Invalid user credentials [invalid_grant]
```

### Version

17.0.1

### Expected behavior

Able to add user/credentials

### Actual behavior

Error shown in discription

### How to Reproduce?

1. Download keyloack 17.0.1 zip and unzip it
2. Build `./bin/kc.sh build`
3. Start `./bin/kc.sh start`
4. Access http:localhost:8080 to see the error

**Comment by DGuhr** [comment]
Hi @missourian55 I've just re-checked with 17.01 and 18.0.2 and could not reproduce this error at all.

A few assumptions I've made:
1) You are not using `http-relative-path` to run keycloak
2) you've not invoked "start" as-is, but - because you want to run using http - e.g. like this: `kc.sh start --http-enabled=true --hostname-strict=false --hostname-strict-https=false`

I could correctly create a realm with kcadm.sh using the relative path and the according kcadm config, or not. 

I will close here for now, please feel free to re-open when the problem still persists. If so, I'd need more information about your configuration, because "out of the box" it works.
