### ISSUE TITLE
Quay image tags overwritten? SHAs purged?

### ISSUE THREAD

**Issue by ThijsBroersen** [keycloak/keycloak#11463]
### Describe the bug

It looks like public keycloak images get purged when a tag is overwritten. I am pinning my keycloak image refs with SHAs but the images are very soon not retrievable anymore. Main tag I am using: `17.0.1-legacy`

My questions:
- why are tags overwritten? Shouldn't a tag be stable?
- if a tag is overwritten, why is the old SHA not available any more?

### Version

17.0.1-legacy

### Expected behavior

Images to stay available at Quay.io

### Actual behavior

Images get deleted why tags are overwritten.

**Comment by diversit** [comment]
We're always using image SHA's instead of tags to prevent getting images with malware in case an image was hacked, so for us it is also an issue when images are being removed.
When there is a need to create a new image, for example when the base image has been update, should the new image not just have a new tag with incremented patch number? Then you leave the choice to update with the users.

**Comment by ThijsBroersen** [comment]
the same is happening for all v18 image it seems. This is pretty annoying...

**Comment by maapteh** [comment]
@stianst can you maybe help us a little more about this issue maybe? We have the same issue and use SHA from security perspective as well!

**Comment by stianst** [comment]
I fully appreciate the SHA pinning issue, and we should figure out some solution to this issue. The problem here is when we re-spin the images rather than release a new version of Keycloak we end up publishing the updated container with the same tags.

Not quite sure how we should handle the re-spins and automate the tags there. At the moment this is how we set tags:

https://github.com/keycloak/keycloak/blob/0efa4afd493de0cb62501301f8a6828e95ea4982/.github/workflows/release-container.yml#L23-L31

Typically a re-spin would have an incremental number (something like 18.0.1-1, 18.0.1-2, etc.), but that would require checking what the last number is to increment it. Another option may be possible to just add a date based tag (18.0.1-20220501 for example).

It's not something I can prioritize looking at right now, and we've done in this way for quite a long time, but if someone has a clean proposal I'd be more than welcome to review it. If not I'll take a look at it in a few weeks hopefully.

**Comment by maapteh** [comment]
Thanks Stian for looking at the release flow, this can be helpful for us to look at! Appreciated!

**Comment by diversit** [comment]
I assume when an image has the same tag, nothing has changed.
Does Quay.io not have a setting to not allow to overwrite an existing tag?
I believe at Dockerhub overwriting an existing tag is not allowed.
Or perhaps check if an image with the same tag already exists (e.g. by pulling image) to determine whether or not to push.

**Comment by stianst** [comment]
@diversit Both Quay and DockerHub allows overwriting tags, and for some tags that's expected (18.0.0 for instance is tagged as 18.0.0, 18.0 and latest). The problem here is when we re-spin the images (basically to do a update of packages in the base image) it doesn't result in a new KC version, which then results in overwriting all tags. The solution, which most folks use, is to have an additional tag (18.0.0-xx) or something that is not overwritten in this case.

**Comment by ThijsBroersen** [comment]
Overwriting tags is not per se an issue. But dropping the old digests is. Also, for specific tags (lets say full semantic versions) I do expect them to be final. A less specific tag like 18, 18.0 or latest is expected to be overwritten. 
It is confusing when images are suddenly not available anymore. One could think the image was taken down because of a serious issue.

**Comment by abstractj** [comment]
@ThijsBroersen @diversit @maapteh created a proposal here https://github.com/keycloak/keycloak/discussions/12082. You're welcome to join.

**Comment by stianst** [comment]
We've now fixed this issue and going forward there will be an additional tag with a rolling number added to the end when we respin containers.
