### ISSUE TITLE
`disableDefaultIngress` of the Keycloak CR doesn't work

### ISSUE THREAD

**Issue by andreaTP** [keycloak/keycloak#11577]
### Describe the bug

The operator crashes trying to deserialize the field `disableDefaultIngress` when set

### Version

18.0.0

**Comment by andreaTP** [comment]
Ref: https://github.com/java-operator-sdk/java-operator-sdk/issues/1170
as follow up.

**Comment by DGuhr** [comment]
@abstractj just to make sure: this issue isn't backported yet, because nothing has been backported yet, right? seems gh has set it automatically to "backport" in the project view for the patch release (perhaps bc its the last lane) when it was closed, so adding it to "backport pending" now. Feel free to change later.

**Comment by dejwsz** [comment]
would be good to have a minor release with that feature, currently only nightly works well and this is really a must-have option

**Comment by andreaTP** [comment]
@dejwsz we plan to include it, eventually, in 18.0.1 👍
