### ISSUE TITLE
Impossible to search on a user Full Name

### ISSUE THREAD

**Issue by briacp** [keycloak/keycloak#11802]
### Describe the bug

Since KeyCloak **17**, it is not possible to search a user by providing its Full Name (or a part of it).

For example, if we want to find a "John Wick" user :
* If we type "`John`", we get the list of all users named "`John`" in Keycloak (in either their First or Last name)
* If we type "`Wick`", we get the list of all users named "`Wick`" in Keycloak (in either their First or Last name)
* If we type "`John Wick`", nothing matches as the query is matched against either Tthe First or Last names fields.

We were able to pinpoint the relevant changes in PR #8346

### Version

17.0

### Expected behavior

In KeyCloak **16.1**, searching for "`John Wick`" or "`John W`" would return the expected user (the concatenation of First and Last name field).

### Actual behavior

Searching for "`John Wick`" or "`John W`" returns nothing.

### How to Reproduce?

* Search for any user with its full name

### Anything else?

We're willing to create a PR to fix this issue,

Thanks.

**Comment by Horsemouth** [comment]
To search full user names just add a % to the search.

example user name - person.dept.work
search term - dept - returns nothing unless the name starts with 'dept'
search term - %dept - returns all users with 'dept' any where in the user name.

**Comment by rosario-vandebron** [comment]
Looking at the PR what you actually need to do is to use `*` instead of `%`. 

https://github.com/keycloak/keycloak/pull/8346/files#diff-e5737e47c97cffabf466eab5aeb754e79ce19152a36cc8607e8a198aae75025bR812

**Comment by artur-baltabayev** [comment]
Hello,
i was not able to reproduce the bug @briacp on Keycloak 17.0 (both locally and on our production instance). If i create a user with `John` as first name and `Wick` as last name the search `John Wick` or `John W` returns this exact user. Maybe the issue is related to a specific database ? Have you tried to reproduce it locally ?

Just for context : The PR itself originated from bad performance when searching on a system with multiple million users on it. So we needed to have an option to search more efficiently.

@rosario-vandebron Actually it is not intended to be used with `%`. But as this is the wildcard symbol for the database, i believe it will be just straight interpreted by the backend. Maybe the whole string should be escaped beforehand.

**Comment by DanielJoyce** [comment]
> @rosario-vandebron Actually it is not intended to be used with `%`. But as this is the wildcard symbol for the database, i believe it will be just straight interpreted by the backend. Maybe the whole string should be escaped beforehand.

Isn't this a SQL injection then?
