### ISSUE TITLE
Cache theme not cleared when restart keycloak service

### ISSUE THREAD

**Issue by Nannymeta** [keycloak/keycloak#11826]
### Describe the bug

Can't flush cache 

### Version

16.1.0

### Expected behavior

Cache is cleared and theme hot fix is effective

### Actual behavior

Can't clear theme cache

### How to Reproduce?

I've extend the keycloak theme and add a custom css.

I've deployed my files and restarted keycloak service. 
After i've modified a property in my css and then impossible to add the hot fix.

I've modified standalone.xml and standalone-ha.xml
````
<theme>
    <staticMaxAge>-1</staticMaxAge>
    <cacheThemes>false</cacheThemes>
    <cacheTemplates>false</cacheTemplates>
    ...
</theme>
````
restarted the service : 
````
service keycloak restart
````
At this point i can see my css hot fix.

As my modification are ok, i re-enable caching : 
````
<theme>
    <staticMaxAge>2592000</staticMaxAge>
    <cacheThemes>true</cacheThemes>
    <cacheTemplates>true</cacheTemplates>
    ...
</theme>
````
restarted the service : 
````
service keycloak restart
````
**Hot fix modifications disappear....**

**Comment by lmller** [comment]
Maybe this [old issue](https://issues.redhat.com/browse/KEYCLOAK-17767) adds more info

**Comment by stianst** [comment]
The WildFly based distribution of Keycloak has been deprecated since Keycloak 17 (February 2022), and will no longer be available in Keycloak 20, which is due to be released soon.

For this reason we're closing this issue as it is related to the WildFly based distribution. Please migrate to the new Quarkus distribution as soon as possible.
