### ISSUE TITLE
KEYCLOAK-17116 Copy of Browser Flow overrides an original one

### ISSUE THREAD

**Issue by koponkin** [keycloak/keycloak#12012]
### Describe the bug

I was trying to create a custom authentication flow in order to use a new default Idp. To do that I copied Browser flow and edited `Identity Provider Redirector` on a copy. This change was applied to the original one. It can lead to a big issue if you try to change it on prod.

### Version

11.0.2, 12.0.2

### How to Reproduce?

Configure "Identity Provider Redirector" for Browser flow with Default Identity Provider=1111
Copy Browser flow
Change "Default Identity Provider" on the copy to 2222
Check Browser flow -> Identity Provider Redirector -> Default Identity Provider. It equals "2222" instead of "1111"

**Comment by d3hof** [comment]
+1 Same issue here, newly created flow. All copies are edited, if one is edited.

**Comment by mposolda** [comment]
@koponkin Thanks for the report. I am able to reproduce this. When copying the flow, we should also make sure to copy configuration (AuthenticatorConfigModel) instead of using the old one.

For now, I am adding to Keycloak 22. But not guaranteed that we will fix as we may have other priority.

If anyone from the community is able to fix this before, it will be welcome! Please comment here that you want to work on this issue. See "Contributors" section under https://www.keycloak.org/community for more details.
