### ISSUE TITLE
accept-encoding: identity should be accepted

### ISSUE THREAD

**Issue by darjeeling** [keycloak/keycloak#12177]
### Describe the bug

using [vector](https://vector.dev/) to scrap `/metrics` for scraping keycloak metrics.
but keycloak refused to response.

as I reported to vector and I got response 
```
According to the HTTP spec here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

      4. The "identity" content-coding is always acceptable, unless
         specifically refused because the Accept-Encoding field includes
         "identity;q=0", or because the field includes "*;q=0" and does
         not explicitly include the "identity" content-coding. If the
         Accept-Encoding field-value is empty, then only the "identity"
         encoding is acceptable.
The identity encoding (as you indicate Vector is sending) MUST be acceptable by any remote server. 
```

### Version

18.0

### Expected behavior

it should report metric with header "accept-encoding: identity"

### Actual behavior

```
curl -v -H "Accept:" -H "accept-encoding: identity" http://localhost:8080/metrics
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> accept-encoding: identity
>
< HTTP/1.1 406 Not Acceptable
< content-length: 69
<
* Connection #0 to host localhost left intact
* 
```

### Anything else?

reported to [vector github](https://github.com/vectordotdev/vector/issues/12804)

**Comment by pedroigor** [comment]
@darjeeling The problem here is not related to the `identity` content-encoding but you are not setting a specific content type. The server won't understand the format you want.

You should either leave it empty or set `application/json`, or `text/plain`, or `*/*`.

I'm closing because it is not an issue. Feel free to re-open if you still think it is an issue.

**Comment by hhromic** [comment]
Hi @pedroigor, I'm coming from the linked issue in the Vector repository.
What you say is a good point as @darjeeling should not have used an empty `-H "Accept:"` flag.
However, `curl` is a bit clever and is actually not sending the `Accept` header because is empty:
```
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> accept-encoding: identity
>
```

In this case (the absence of an `Accept` header), the server should assume that the client accepts all types, i.e. `*/*`. This is defined in the HTTP spec here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
```
If no Accept header field is present, then it is assumed that the client accepts all media types.
```

**Comment by pedroigor** [comment]
@darjeeling Testing locally shows that the header is there, running your command. If you remove that header from cURL, the server should respond properly.

**Comment by hhromic** [comment]
> @darjeeling Testing locally shows that the header is there, running your command. If you remove that header from cURL, the server should respond properly.

When you remove the `-H "Accept:` explicit flag from `curl`, then it will send its default `Accept: */*` header/value. Probably explaining why it works like that. If the keycloak server is not accepting the request _without_ an `Accept` header, that is incorrect behaviour as it should assume an `Accept: */*` in that case.

**Comment by pedroigor** [comment]
OK, I'm convinced :)

However, this issue is related to how SmallRye Metrics works and we should be talking with them about this behavior. 

Created https://github.com/smallrye/smallrye-metrics/issues/497.

**Comment by pedroigor** [comment]
FYI, this should only be fixed when we upgrade Quarkus. I won't expect it to happen soon because we are now forced to use the version of RHBQ which is based on 2.7.

If we can get a patch release from Quarkus in meantime, that would be nice.

For now, I hope you can somehow set a content-type for now.

**Comment by hhromic** [comment]
@pedroigor no problem and thanks for the quick fix!
I already suggested to the Vector maintainers (the client application) to add an `Accept: text/plain` header for now to the requests for a more precise HTTP request without breaking anything.

**Comment by darjeeling** [comment]
@pedroigor @hhromic Thanks for your efforts and help.
you folks so nice!

**Comment by pedroigor** [comment]
Closing as it should be fixed once we upgrade Quarkus.
