### ISSUE TITLE
KEYCLOAK-19516 Bad Request - No state cookie - thrown when login page bookmarked

### ISSUE THREAD

**Issue by fjrial** [keycloak/keycloak#12240]
### Describe the bug

App-URL (Mocked): https://app.com 
Login-URL (Mocked): https://login.app.com 

User-Flow

The user visits the app URL https://app.com 
The user gets redirected to https://login.app.com/auth/realms/apprealm/protocol/openid-connect/auth?response_type=code&client_id=app&redirect_uri=https%3A%2F%2Fapp.com%2Fsso%2Flogin&state=908f3683-960f-4c9e-ab65-a57145868789&login=true&scope=openid
The user bookmarks this page for future easy access
The user logs in 
The user gets redirected to https://app.com/sso/login?state=908f3683-960f-4c9e-ab65-a57145868789&session_state=0355f0ab-40a4-45c8-8a3d-10109ed992f8&code=44d874d5-f1b4-4aef-a3c1-fc4c8c229f76.0355f0ab-40a4-45c8-8a3d-10109ed992f7.6c2e7478-2aa5-4616-87c1-e1c1fde53ida
Every thing works fine and user closes browser (session gets closed)
Next time the user opens the bookmarked link (see link in step2)
The user logs in 
The use gets redirected to https://app.com/sso/login?state=908f3683-960f-4c9e-ab65-a57145868789&session_state=0355f0ab-40a4-45c8-8a3d-10109ed991d4&code=44d874e3-f1b4-4aef-a3c1-fc4c8c229f76.0355f0ab-40a4-45c8-8a3d-10109ed992f7.6c2e7478-2aa5-4616-87c1-e1c1fde53ida
The user gets a Bad Request 400 page
After calling application url or refreshing manually the app is processed
Manual Test-Flow

Open https://app.com 
Redirects to https://login.app.com/auth/realms/apprealm/protocol/openid-connect/auth?response_type=code&client_id=app&redirect_uri=https%3A%2F%2Fapp.com%2Fsso%2Flogin&state=908f3683-960f-4c9e-ab65-a57145868789&login=true&scope=openid
Manually change state code to something different / not existing
Process Login
400 / Bad request will appear

### Version

16.1.1

### Expected behavior

Keycloak version is for docker image provided here https://hub.docker.com/r/jboss/keycloak

### Anything else?

Issue created from here https://issues.redhat.com/browse/KEYCLOAK-19516

**Comment by pedroigor** [comment]
I'm not sure if this is an issue but rather an expected behavior.

The application lost the `state` it sent to the server so that future authorization responses from the server (sending the `code`)  won't be processed by the application as the application does not recognize the `state` anymore.

The reason why it works after a page refresh in the last step is that a new authorization request is sent along with a new `state`.

You can't change the `state` sent to the application when on the login page, otherwise a properly implemented OAuth2/OIDC client will complain about it.
