### ISSUE TITLE
Security bug: Timing Oracle @ Authorization Grant Request , CWE 208

### ISSUE THREAD

**Issue by drwetter** [keycloak/keycloak#12298]
### Describe the bug

Hi,

I am doing a pentest for a client of mine. Responsible disclosing the bug wasn't possible. It was just turned down as I wasn't the recent version I was testing this against. 
 
**I** was supposed to prove that this bug also exists in the latest version -- which I can't as it is a pentest and nobody will pay me for this. So this is my swift response on the response I just encountered. I am doing this because I suspect the bug exists also in the latest version and I want software to be secure.

### Details:
During an authorization grant request to a keycloak server I tried to figure out whether one can guess userids by observing the response time. HTTP request to the keycloak server was

![image](https://user-images.githubusercontent.com/8036727/171483017-e6d06e29-9459-40a7-bf33-643f47361283.png)

The hostname and HTTP ``Host`` header was the keycloak server. ``password`` was just an incorrect arbitrary one.

![image](https://user-images.githubusercontent.com/8036727/171483275-6b63617d-0027-4df5-85ca-905c6db6dc0d.png)

The column payload is the contents of the ``username`` variable above, the column starting with "Respon..." is the Response received time in milliseconds (was performed on a DSL).

If I order the request by response received time one can see that the requests with the existing usernames were responded significantly later (>100 ms) than the on-existing ones (<50ms), thus allowing the identification of usernames.

Usually that's the case when internally the real usernames are checked for their password -- hence the delay and the others just come back when the username isn't valid. It's recommended you add a baseline delay for the latter and some random time on any request.

An attacker can thus use e.g. so called dumps from the internet with just e-mail addresses and guess usernames (which in my case is the same. Otherwise a username dictionary would help). Once the usernames were identified, using a password list (in several projects @ github available) would then give full access. See also https://cwe.mitre.org/data/definitions/208.html .

As said this was discovered through a pentest. Atm I do not have access to the management interface. And probably I don't have access to the system anymore in a few days,

Fingerprinting the version tells me the keycloak version my client is using is between 15.0.2 and 13.0.1 . I haven't looked into the code whether the delay I suggested is implemented on recent versions as I spent a couple of hours already preparing the issue and reporting the bug.

For the sake of security it would be great if you or anybody reading this could check whether the security bug exists in 18.X too and if it does: fix that!

Cheers / thanks,

Dirk

### Version

~15.0.2

### Expected behavior

see above

### Actual behavior

see above

### How to Reproduce?

see above

### Anything else?

I am really scratching my head when people spent time reporting a security bug _why_ they are being turned down with such lame response. This may not shed a good light on the company behind this or the project -- which I normally appreciate.

**Comment by stianst** [comment]
Thanks for reporting this issue. I would suggest in the future that you use proper channels to report potential security vulnerabilities, see https://github.com/keycloak/keycloak/security/policy for more details.

With regard to this one I consider this a security hardening issue rather than a vulnerability. It boils down to pretty much OIDC resource owner client credential grant not simulating the password hashing step, which results in the difference in time between a valid user and an invalid user.

However, if you are worried about security the resource owner client credentials grant should not be used at all. It's deprecated in OAuth 2.1, and has been recommended to not use this flow at all for some considerable amount of time. The better hardening approach here is to disable usage of this flow within clients in your deployment of Keycloak.

When it comes to user enumeration attack like these they are pretty much impossible to prevent with modern authentication flows. Things like identity first login flows, passwordless authentication, delegated authentication, self-registration, etc. means that there will almost always be some mechanism to enumerate users if there is not sufficient protection in front of Keycloak. It's also very common that email address is used as the username, which can easily be identified through other sources. This puts more emphasis on the importance of verifying the user, over emphasis of protecting the user id, which can be achieved with OTP, WebAuthN, etc. to achieve stronger authentication than just passwords on their own.

Keycloak on its own is not a intrusion detection system, and for additional protection we recommended using such a solution in front of KC to prevent bot/enumeration attacks like these.

That being said, this is a valid issue, and one that can relatively easily be resolved, so we should incorporate a fix for this one.

**Comment by drwetter** [comment]
Hi @stianst ,

> Thanks for reporting this issue. I would suggest in the future that you use proper channels to report potential security vulnerabilities, see https://github.com/keycloak/keycloak/security/policy for more details.

be assured I tried. But frankly speaking I got aggravated because of the continuing dumb responses, so I was fed up and just posted it here. Don't know whether you have access to that security mailing list. If so you can check. 

> When it comes to user enumeration attack like these they are pretty much impossible to prevent with modern authentication flows. Things like identity first login flows, passwordless authentication, delegated authentication, self-registration, etc. means that there will almost always be some mechanism to enumerate users if there is not sufficient protection in front of Keycloak. It's also very common that email address is used as the username, which can easily be identified through other sources. This puts more emphasis on the importance of verifying the user, over emphasis of protecting the user id, which can be achieved with OTP, WebAuthN, etc. to achieve stronger authentication than just passwords on their own

For this case I believe it would suffice when keycloak would just prevent the oracle, like suggested (adding a baseline delay when usernames don't match so that they are kind of in line with the additional cycles spent when a password needs to be checked against. Then add some random noise. Doing this kind of checks since a longer time and my recommendation is always the above and a retest always showed that it is fine.)


> That being said, this is a valid issue, and one that can relatively easily be resolved, so we should incorporate a fix for this one

Thanks! 👍

**Comment by mposolda** [comment]
Adding to Keycloak 22 for now. But I am not 100% sure if it is postponed to later (depends if we have time).

If anyone from the community is able to improve this before, it will be welcome! Please comment here that you want to work on this issue. See "Contributors" section under https://www.keycloak.org/community for more details.

**Comment by mposolda** [comment]
Marking as "priority important" for now. We can probably use "dummy hash" approach like we're doing for "browser" authentication. See `AbstractUsernameFormAuthenticator.dummyHash` (we may extract this method to some parent to make sure it is called).
