### ISSUE TITLE
Clarify `transaction-xa-enabled` and add `transaction-jta-enabled`

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#12400]
### Description

The use of `transaction-xa-enabled` is misleading, as what you are actually setting is whether or not to use XA or JDBC transactions, and the Nayrana transaction manager is still being used.

There may be cases where it is desirable to disable all transactional capabilities and completely disable JTA, as in the use of CockroachDB. This is available by setting the `quarkus.datasource.jdbc.transactions` Quarkus property to `disabled`, but it's not currently possible using the `transaction-xa-enabled` Keycloak param.

We should:
1. Rename `transaction-xa-enabled` to `db-xa-enabled=true|false` to clarify that we are enabling the usage of non-XA data sources (but still using JTA).
2. Add a `transaction-jta-enabled=true|false` to actually remove JTA from the runtime.

### Discussion

https://github.com/keycloak/keycloak/issues/10430

### Motivation

To allow databases types to be used that do not work with a JTA transaction manager

## Problem

Currently, the Keycloak configuration property `transaction-xa-enabled` is converted to the Quarkus property `quarkus.datasource.jdbc.transactions` with the following mapping logic from [TransactionPropertyMappers.java](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java): 

| `transaction-xa-enabled` | `quarkus.datasource.jdbc.transactions` |
| --- | --- |
| `true` (default) | `xa` |
| `false` | `enabled` |

The [`quarkus.datasource.jdbc.transactions`](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.transactions) parameter indicates that it is to be set to `xa`, `enabled`, or `disabled` for "Whether we want to use regular JDBC transactions, XA, or disable all transactional capabilities. When enabling XA you will need a driver implementing javax.sql.XADataSource."

As suggested in the discussion [here](https://github.com/keycloak/keycloak/issues/10430#issuecomment-1145039545), the use of `transaction-xa-enabled` is misleading, as what you are actually setting is whether or not to use XA or JDBC transactions, and the Nayrana transaction manager is still being used.

Furthermore, there may be cases where it is desirable to disable all transactional capabilities and completely disable JTA (i.e. set `quarkus.datasource.jdbc.transactions` to `disabled`, which is not currently an option). This is true in the case of using CockroachDB, which appears to require both JTA to be disabled and to use JDBC transactions. 

## Proposal

1. Rename `transaction-xa-enabled` to `db-xa-enabled=true|false` to clarify that we are enabling the usage of non-XA data sources (but still using JTA).
2. Add a `transaction-jta-enabled=true|false` to actually remove JTA from the runtime.

## Implementation questions

1. Is it possible to rename `transaction-xa-enabled` to `db-xa-enabled` while maintaining some conversion of `transaction-xa-enabled` for backwards compatibility?
2. If we add `transaction-jta-enabled`, is the only impact that [this method](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java#L26) needs to return "disabled" if `transaction-jta-enabled=false`? Or are there other places where this needs to be done?
3. The [PropertyMapper](https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/PropertyMapper.java) builder doesn't like taking more than one source property. Is there a way that we could pass it two (that is not a hack)? Or should we just construct it manually?

**Comment by xgp** [comment]
@pedroigor Here's what I meant about having to hack around "the PropertyMapper builder doesn't like taking more than one source property". I'm not familiar with this code, so maybe you can see there is a more elegant way of doing this.

https://github.com/xgp/keycloak/blob/d0e8122a1a69874df4b50162f954489e085ffd61/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/configuration/mappers/TransactionPropertyMappers.java

**Comment by DGuhr** [comment]
Hi @xgp @pedroigor I took a deeper look in here and imo we should not introduce 2 new config variables that map to one quarkus config at all, but instead:
1) remove `transaction-xa-enabled=true/false`
2) substitute it by `transaction-mode=xa/enabled/disabled` - this would map "1 to 1" to the values of `quarkus.datasource.jdbc.transactions`

Reasons: 
1) does the trick
2) renaming `transaction-xa-enabled` would also introduce a breaking change, so does the whole substitution, so 
3) having 2 config options for one quarkus option, this could imo lead to bad UX. Example: What would happen when you set `db-xa-enabled=true` AND `transaction-jta-enabled=false`? Are transactions now disabled or in XA mode? same would go for `transaction-jta-enabled=true` in this example. Is now "xa" used or "enabled"? What would be the leading value here? Is it even deterministic?

wdyt?

**Comment by xgp** [comment]
@DGuhr 👍 Works for this use case. I'm not 100% sold that the name is a clear representation of what it does, but I agree that it does the trick, and will be the easiest route to solving this. One thought, is it problematic that we're introducing a "breaking change" by removing `transaction-xa-enabled`?

**Comment by DGuhr** [comment]
@xgp As problematic as every breaking change is, i'd say. I still think about a way of having "deprecated" config in our wrapping layer, where the builder uses (isDeprecated=true), a warning is shown to the user and internally the new config is set with the right value instead, but couldn't quite come up with sth yet due to other priorities. For now this would mean we'd have to add a section in the migration guide and this could only make it to new Major versions, so definitely targetted at 19 then iirc. But this breaking change would be there either way, so imo we should not go the 2 options path. I agree that the name is sth I just came up with, so if you have better suggestions for name/description, I'm open for everything :)

**Comment by xgp** [comment]
Sounds good to me. As long as the documentation in the guide is clear, I support the new name and deprecation of the old name. 👍

**Comment by pedroigor** [comment]
IMO, if we are going to do this change we should do it right.

Conceptually, `db-xa-enabled` and `transaction-jta-enabled` are two different things.

So far we have been basically doing `db-xa-enabled` to allow people using non-XA data sources when the database does not support it. But not really disabling JTA.

```
What would happen when you set db-xa-enabled=true AND transaction-jta-enabled=false?
```

AFAIK, nothing should happen and it should work. The problem is when you are setting a non-XA datasource and have XA-enabled.

```
Is now "xa" used or "enabled"? What would be the leading value here? Is it even deterministic?
```
Disabling `transaction-jta-enabled` automatically set `db-xa-enabled` to false.

**Comment by DGuhr** [comment]
working but still WIP Branch with 2 config options: https://github.com/DGuhr/keycloak/tree/iss12400_tx_mode - CI run looks kinda good (https://github.com/DGuhr/keycloak/runs/6971195350?check_suite_focus=true ) - Quarkus tests and database tests green, other step failures due to running it on the fork i guess. we'll see tomorrow, but i think this is near PR state. Would be nice if you could already try it out @xgp just to see if that would work for you. We discussed a bit today and this is what I came up with so-far. Maybe we make the `transaction-jta-enabled` config option hidden at first (meaning it doesn't show up in docs/config, but you are able to use it) until there's clarification around keycloak needing `enabled`, why `enabled` implies using Narayana, and until the cdb support is finished.

Btw: Is there a cdb container we could use to run a Testcontainers database test against? That would be nice.

**Comment by DGuhr** [comment]
@xgp yeh, pretty much the same logic, but leaving the jta config in our layer (removing the `to` and the default value) so we don't have the side effects of 2 config options mapping to one quarkus property. Thanks for the hint to the container and for trying it out :)

**Comment by xgp** [comment]
🥇
