### ISSUE TITLE
Make it possible to switch between BC and BC-FIPS libraries

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#12424]

**Comment by mposolda** [comment]
Some investigation around this:

The  https://github.com/keycloak/keycloak/issues/12522 was merged and hence current Keycloak main contains the support for build with 2 maven profiles:
1) Default profile, which uses non-fips bouncycastle libraries
2) fips140-2 profile, which uses FIPS bouncycastle libraries.

The details about how to build are here: https://github.com/keycloak/keycloak/blob/main/docs/fips.md .

However one point is, that these maven profiles might be useful just for the development. In the end, we may need single build with non-fips bouncycastle. If customers want to use FIPS at runtime, they might need to manually switch to BouncyCastle FIPS on the already builded Keycloak/RH-SSO.

I've tried to investigate how to replace non-fips bouncycastle with the fips bouncycastle on the already built distribution. It won't work to have both non-fips and fips BC on the classpath, so it is first needed to remove non-fips BC. However the bouncycastle JARS cannot be simply deleted from `KC_HOME/lib/lib/main` directory. It seems that quarkus has some type of "indexing" or something like that (details to be investigated) and it throws an error at startup if some JAR from the `lib/lib/main` directory is removed.

The alternative solution, which I found is:
- The Keycloak quarkus distribution will be built in a way that 2 bouncycastle JARs for `bcpkix-jdk15on` and `bcprov-jdk15on` will be put into the `KC_HOME/providers` directory during build rather than to the `KC_HOME/lib/lib/main` .

- Same applies for the `keycloak-crypto-default` JAR (this JAR does not yet exists, but might be introduced later - see https://github.com/keycloak/keycloak/issues/12625).

- This works fine in runtime as Quarkus uses single flat classloader, which simply combines all the JARs from `providers` directory together with the "core" jars from the directory `lib/lib/main`.

- So when customers want to switch to FIPS mode, they will remove non-fips bouncycastle from the `providers` directory and instead they add the bouncycastle-fips jars and `keycloak-fips1402` JAR.

- It may be some more elegant solution as quarkus property `quarkus.package.user-providers-directory` may support multiple directories and hence we won't need to directly use directory `providers` intended to be used by user JARs.

- Or some even better solution, which won't rely on the `quarkus.package.user-providers-directory` (`providers` directory) mechanism.

**Comment by stianst** [comment]
@mposolda have a chat with @pedroigor around how we can dist and switch between BC and BC FIPS ;)

**Comment by pedroigor** [comment]
@mposolda Do we expect multiple levels or we could just enable/disable FIPS using a  `fips-enabled=true|false`? For me, it is more user-friendly because you just need a boolean to disable/enable it. If in the future we want to support more levels we could perhaps add a specific option if needed.

Another alternative to your proposal is to:

* Ship both JARs into the distribution (not into the classpath)
* When passing the `fips-enabled` option our CLI is going to move JARs accordingly to make them available from the classpath

I would love to see FIPS enabled by just:

```
kc.sh start --auto-build --fips-enabled true
```

**Comment by mposolda** [comment]
@stianst @pedroigor Thanks Pedro for looking at this. Yes, ideal is, to enable/disable FIPS just at the startup without a need of any additional steps (ideally avoid the need for customers to manually copy/delete some files).

I think that your approach looks fine.

One alternative variant: Do you know if `quarkus.package.user-providers-directory` supports multiple directories? If it does, we can possibly have this property configured to use both the `providers` directory together with the directory, which will contain non-fips bouncycastle JARs. Something like:
```
quarkus.package.user-providers-directory=../providers,../bc-default
```

However when admin uses `fips-enabled=true` at startup, the `quarkus.package.user-providers-directory` would be changed in the background to something like `./providers,../bc-fips`, which is directory with `bouncycastle-fips` jars . WDYT? Maybe even simpler than copying files in the background? But it requires that `quarkus.package.user-providers-directory` supports multiple dirs (We can possibly add quarkus team to add support for this if they don't already?)

**Comment by mposolda** [comment]
@pedroigor One side-note (not directly related to the discussed problem): We may want to support also additional standards like `fips140-3` in the future. So instead of boolean property like `fips-enabled`, we may need something like: `fips=none|fips140-2|fips140-3`

**Comment by pedroigor** [comment]
> @stianst @pedroigor Thanks Pedro for looking at this. Yes, ideal is, to enable/disable FIPS just at the startup without a need of any additional steps (ideally avoid the need for customers to manually copy/delete some files).
> 
> I think that your approach looks fine.
> 
> One alternative variant: Do you know if `quarkus.package.user-providers-directory` supports multiple directories? If it does, we can possibly have this property configured to use both the `providers` directory together with the directory, which will contain non-fips bouncycastle JARs. Something like:
> 
> ```
> quarkus.package.user-providers-directory=../providers,../bc-default
> ```
> 
> However when admin uses `fips-enabled=true` at startup, the `quarkus.package.user-providers-directory` would be changed in the background to something like `../providers,../bc-fips`, which is directory with `bouncycastle-fips` jars . WDYT? Maybe even simpler than copying files in the background? But it requires that `quarkus.package.user-providers-directory` supports multiple dirs (We can possibly add quarkus team to add support for this if they don't already?)

I don't think it supports multiple user directories. I'm also not sure if they want to support that but we can try to come up with a PR. I see your point and it is indeed better than copying files around.

Do you want to go on this path?

**Comment by mposolda** [comment]
> > @stianst @pedroigor Thanks Pedro for looking at this. Yes, ideal is, to enable/disable FIPS just at the startup without a need of any additional steps (ideally avoid the need for customers to manually copy/delete some files).
> > I think that your approach looks fine.
> > One alternative variant: Do you know if `quarkus.package.user-providers-directory` supports multiple directories? If it does, we can possibly have this property configured to use both the `providers` directory together with the directory, which will contain non-fips bouncycastle JARs. Something like:
> > ```
> > quarkus.package.user-providers-directory=../providers,../bc-default
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However when admin uses `fips-enabled=true` at startup, the `quarkus.package.user-providers-directory` would be changed in the background to something like `../providers,../bc-fips`, which is directory with `bouncycastle-fips` jars . WDYT? Maybe even simpler than copying files in the background? But it requires that `quarkus.package.user-providers-directory` supports multiple dirs (We can possibly add quarkus team to add support for this if they don't already?)
> 
> I don't think it supports multiple user directories. I'm also not sure if they want to support that but we can try to come up with a PR. I see your point and it is indeed better than copying files around.
> 
> Do you want to go on this path?

Yes, exactly. Maybe worth trying this path? How do you suggest to proceed with this? Should we start discussion somewhere in the quarkus repository or write an email to some mailing list with proposing this?

But maybe step1 is to doublecheck if this is not supported already? :-) I can try to take a look tomorrow (unless you know from the top of your head where exactly in quarkus codebase this stuff is)?

**Comment by pedroigor** [comment]
It is not supported by looking at the code. That option only supports a single path.

We can talk about the change in more detail prior to proposing something. I think I have an idea where we should be changing  Quarkus. Perhaps, after looking at this together we can come up with either a proposal or a PR.
