### ISSUE TITLE
Change enum `ResourceType` to interface with `String` constants

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#12485]
There is enum `ResourceType`[1]. Within KEYCLOAK-9573 it was added that it can be specified custom type of the event and there can be as many of them as needed. When events then are searched by ResourceType, there is `RealmAdminResource.getEvents` where there is passed `List<String> resourceTypes` as one of its parameters. The List of strings is transformed into enums and passed into `AdminEventQuery`, where it is again transformed into strings and used for search. When queried by your custom resource type it can only be obtained all custom resources regardless of their actual value. 

Proposal is to change enum ResourceType into interface and instead of enum items have String constants there with exactly same values. That way we'd use Strings from top to bottom and it'll allow to query custom events by its actual value. 

[1] https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/events/admin/ResourceType.java

**Comment by mhajas** [comment]
The PR was reverted because it caused regression in the admin console. The admin console contains a filter option for querying events with a specific `resourceType`. There is an endpoint that is supposed to return all possible `resourceType`s so the admin console suggests what are possible options for filtering. This was broken. We need to rethink how to return the correct list of options with regards to changes suggested in the issue.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
