### ISSUE TITLE
[KEYCLOAK-19863] 100.64.x.x/10 range is incorrectly marked as external

### ISSUE THREAD

**Issue by thpham** [keycloak/keycloak#12572]
### Describe the bug

If the keycloak realm setting is "external", then keycloak detects this 100.x.x.x IP address as external client request.

But,

100.64.0.0/10 | Carrier-grade NAT

100.64 falls in the bogon IP range https://ipgeolocation.io/resources/bogon.html

This is aanoying especially with kubernetes IPs pods beeing choosen in that range. (ex. AWS EKS with that secondary VPC range)

So this ticket is raised so that keycloak should allow these to be considered internal.

relates to: https://issues.redhat.com/browse/KEYCLOAK-19863

### Version

12.0.4

### Expected behavior

So this ticket is raised so that keycloak should allow this CGNAT range to be considered internal.

### Anything else?

This could most probably be fixed in the [following method](https://github.com/keycloak/keycloak/blob/main/common/src/main/java/org/keycloak/common/enums/SslRequired.java#L51-L58).

**Comment by pedroigor** [comment]
@thpham We probably want to remove the `SSL Required` option from realm settings and instead decide if HTTP:

* It does not make sense to force TLS for some realms and not for others
* We can infer if TLS is required or not based on the server configuration like `proxy`, `hostname`, and `http-enabled` options.

I'm not 100% sure if we need this property at all as well as checks for SSL required in our endpoints. Keycloak should always be exposed through TLS and if not is because users must know what they are doing(e.g.: some corner case where HTTP is required). It also introduces additional complexity to our endpoints and additional care when working with them as you need to remember to make those checks.

**Comment by pedroigor** [comment]
Closed in favor of https://github.com/keycloak/keycloak/issues/17126.
