### ISSUE TITLE
GET /{realm}/users/{id}/groups ignores 'search' query parameter

### ISSUE THREAD

**Issue by zrezke** [keycloak/keycloak#12649]
### Describe the bug

The search parameter gets ignored completely, it always just returns the groups the user is a member of, without filtering them with the search parameter.

### Version

15.1.1

### Expected behavior

If you provide the search query parameter, the endpoint should filter group names using the search query.

### Actual behavior

When you provide a search parameter that doesn't match any group name (or anything else for that matter) it still returns all of the users groups.

### How to Reproduce?

Send a valid http request: GET /{realm}/users/{id}/groups
It will return the useres groups.
Now send the same request with an invalid search appended => GET /{realm}/users/{id}/groups?search=blablablabla
It will still return the same groups altho none of them match "blablablabla"

### Anything else?

https://www.keycloak.org/docs-api/15.1/rest-api/index.html#_users_resource
search for -> GET /{realm}/users/{id}/groups

**Comment by rmartinc** [comment]
@zrezke For what I see in the [code](https://github.com/keycloak/keycloak/blob/18.0.1/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L875-L881) in order to filter the search filter you should pass `search`, `first` and `max` parameters. Try doing something like:  `/{realm}/users/{id}/groups?search=blablablabla&first=-1&max=-1` or any other values.

**Comment by zrezke** [comment]
Huh, yea this works. Thanks @rmartinc. I think it would be a good idea to add this to the docs as it is not mentioned anywhere.

**Comment by rmartinc** [comment]
I see @suichangyin has sent a little PR to fix that in the code. Let's see what keycloak admins say about it.
