### ISSUE TITLE
Clearify the use of `db-url-properties`

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#12720]
### Description

In the keycloak documentation (https://www.keycloak.org/server/all-config) it simply says about `db-url-properties`:

> Sets the properties of the default JDBC URL of the chosen vendor.

However, in what format does that need to be provided? What if I want to use multiple?

**Comment by col-panic** [comment]
Just stumbled over this one, I am using the env value `KC_DB_URL_PROPERTIES` to set parameters on the mysql database like `"useSSL=false&serverTimezone=Europe/Zurich"` and found out, that I have to prepend the `?` sign to the string.

It's confusing, as I thought, that `KC_DB_URL_PROPERTIES` would imply to being set after the `?` already ...

**Comment by mwalser** [comment]
We just ran into the same issue. Requiring the user to prepend `?` to the string is completely non-obvious and hard to discover.

IMHO this should happen automatically.

**Comment by andre-nascimento-rh** [comment]
Hello, @ctron,


We will only improve the description message for the option `KC_DB_URL_PROPERTIES` in the docs, in order to emphasize that the User/Developer need to provide also the first character for the specific DBMS syntax.

We opted out to solve this issue like that because the format for properties specified in JDBC URL differs for various DBMS vendors. Some DBMS use `?`, but the other ones use `;` for defining props in the JDBC URL. Moreover, the delimiter for props differs as it can be `&` or `;` so the User/Developer needs to be aware of how to specify these properties for the chosen DBMS in that matter. 

Thus, we don't see a big benefit to automatically putting the specific char at the beginning of the props section.

Thanks for your proactivity in opening this issue. And feel free to add more comments or thoughts.

**Comment by ctron** [comment]
@andre-nascimento-rh sounds reasonable, as long as the documentation explains what is required, that is good. Better good documentation than bad magic.

**Comment by mwalser** [comment]
There is the [DriverManager.getConnection(String url, Properties info)](https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html#getConnection-java.lang.String-java.util.Properties-) API where you can pass the connection properties separately as Properties object.

Is there any reason not to use this API? Currently it seems like Keycloak is doing string concatenation to incorporate the KC_DB_URL_PROPERTIES into the JDBC URL. In my opinion it would be much cleaner to parse KC_DB_URL_PROPERTIES into a Properties object and use the API designed for exactly this use case.

This would also solve this issue since there is no ambiguity on how to separate the properties part from the rest of the JDBC URL

**Comment by andre-nascimento-rh** [comment]
Hello, @mwalser ,

In my view, you suggested a good approach. 

I'd like to know what does the `storage` team think about it: @hmlnarik and @ahus1 

Thanks.

**Comment by ahus1** [comment]
I see that there are a lot of configurations starting with `db-url-` to configure parts of a JDBC URL. I'd argue the only property I ever used is `db-url` to specify a complete JDBC URL. 

So I'd go as far as retiring the options `--db-url-database`, `--db-url-host`, `--db-url-port` and `--db-url-properties` altogether.
