### ISSUE TITLE
keycloak client authorization policy restric only user in group can login not work

### ISSUE THREAD

**Issue by ly123-liu** [keycloak/keycloak#12880]
### Describe the bug

we have a client app use keycloak to authenticate , and we hope keycloak can restric only user in some group can login to our client app.

read doc in https://www.keycloak.org/docs/latest/authorization_services/index.html,  and we try this: 
realm-clients-settgins - choose confidential access type and Authorization Enabled 

realm-clients-Authorization , delete default policy and permission, and create group policy restric only specific group , and create permission in permission tab with above group , then we tried to login , still any user can login with keycloak ,why is that ,can anyone help ? thanks

### Version

keycloak 17

### Expected behavior

keycloak can restric only user in some group can login to our client app

### Actual behavior

keycloak authorization policy not work

**Comment by pedroigor** [comment]
Thanks. The expected behavior is not supported and authorization services can only protect resources for a particular client.

There is no integration with the authentication flows so you can't restrict users to log in.

There is a community extension that should help with that. I'm not sure though if it is still working with the latest releases. See https://github.com/cloudtrust/keycloak-authorization.

**Comment by siilike** [comment]
https://github.com/sventorben/keycloak-restrict-client-auth
