### ISSUE TITLE
Keycloak 18.0.2 mixed content issue.

### ISSUE THREAD

**Issue by nloke** [keycloak/keycloak#12913]
### Describe the bug

First off I want to state that I have read https://github.com/keycloak/keycloak/issues/11807 and a lot of documentations and articles. I still don't think https://github.com/keycloak/keycloak/issues/11807 has fixed all mixed https/http issue.

I am deploying keycloak 18.0.2 on EKS with the HTTPS terminating on the ALB.
After a lot of struggle and research, I have manually changed the frontend URL in the DB directly and also changed the redirect_uri to have https in it, I am now able to see the dashboard and click to admin console and have the redirect_uri all being allowed and now I can finally Login.

However after login. I will get unexpected error because for the following API calls that does not have HTTPS in it.

```
http://identity-test.somedomain.net/auth/admin/realms?briefRepresentation=true
http://identity-test.somedomain.net/auth/admin/serverinfo
http://identity-test.somedomain.net/auth/admin/realms
```

I never seen all these issues or even need to do changes directly in DB. I am previously using 16.1.1 but am forced to upgrade as that version has issues with Direct Naked Impersonation Feature.

Below is my setting.
KC_DB=postgres
KC_DB_URL_HOST=rds.amazonaws.com
KC_DB_URL_PORT=5432
KC_DB_URL_DATABASE=postgres
KC_DB_SCHEMA=keycloak_test
KC_DB_USERNAME=xxx
KC_DB_PASSWORD=xxx
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KC_HOSTNAME=identity-test.somedomain.net
KC_HOSTNAME_ADMIN=identity-test.somedomain.net
KC_HOSTNAME_STRICT=false
KC_HTTP_RELATIVE_PATH=/auth
KC_HTTP_ENABLED=false
KC_HOSTNAME-STRICT-HTTPS=true
KC_PROXY=edge

### Version

18.0.2

### Expected behavior

I should be able to easily access the admin console after installation. 

### Actual behavior

After so many research and hack around DB values, I am still NOT able to access the admin console.

I am currently stuck at this step where 

```
http://identity-test.somedomain.net/auth/admin/realms?briefRepresentation=true
http://identity-test.somedomain.net/auth/admin/serverinfo
http://identity-test.somedomain.net/auth/admin/realms
```

is not carrying the right protocol, should be https not http and for this I am truly running out of idea where they are coming from. Before the setup of the "Frontend Url" in the realm settings would have taken all these into account properly.

**Comment by nloke** [comment]
![image](https://user-images.githubusercontent.com/2836771/177217095-d7d7cbc2-1e81-47fe-b4fa-7b83c5320752.png)

**Comment by nloke** [comment]
![image](https://user-images.githubusercontent.com/2836771/177217349-894d9d67-b019-4fed-aeda-9eb675178037.png)

**Comment by jlmartins-sf** [comment]
Hi @nloke ! Have you solve this ?

**Comment by ymbcxb** [comment]
Hi @nloke ! Have you solve this ? I have the same problem.

**Comment by nloke** [comment]
Hi @ymbcxb  Still no luck. Have tried different NLB and ALB in AWS and still having same issue. We are currently stuck with Keycloak 17.X for the time being, which at least worked a little better for us where the  Direct naked impersonation worked for us with the hope that some experts from the Keycloak community will have a look into this.

**Comment by abstractj** [comment]
@nloke have you tried our latest releases? Do you have the reproducible steps outside of EKS? That would be fantastic for our team.

@andre-nascimento-rh do you have any plans to look at this? If not, I'd suggest unassigning the issue, and follow up with @vmuzikar

**Comment by andre-nascimento-rh** [comment]
@abstractj, my plan is to work on this from tomorrow.

**Comment by bonzo71** [comment]
@andre-nascimento-rh please let us know if you have any outcomes of your work. It is also a pressing problem for me...

**Comment by andre-nascimento-rh** [comment]
Hello, @bonzo71 ,


I tried to reproduce your issue in my local environment. I created a "docker-compose" file describing: Keycloak-18.0.2 + PostgreSQL + Nginx-Proxy-Manager (https://nginxproxymanager.com/). I used the `nginx-proxy-manager` because I wasn't able to reach a properly environment in AWS with ALB).

I set almost the same Environment Variables as you set:

`
      KC_DB: postgres
      KC_DB_URL_HOST: [my postgresql container]
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: [xxx]
      KC_DB_SCHEMA: [xxx]
      KC_DB_USERNAME: xxx
      KC_DB_PASSWORD: xxx
      KEYCLOAK_ADMIN: ciam-admin
      KEYCLOAK_ADMIN_PASSWORD: [xxx]
      KC_HOSTNAME: keycloak-v18.[xxx]
      KC_HOSTNAME_ADMIN: keycloak-v18.[xxx]
      KC_HOSTNAME_STRICT: false
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTP_ENABLED: false
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: false
`

I created a self-signed Certificate + Key using the `OpenSSL` tool (https://dadhacks.org/2017/12/27/building-a-root-ca-and-an-intermediate-ca-using-openssl-and-debian-stretch/).

In `nginx-proxy-manager` Admin Console, I created a `Proxy Host` pointing to my Keycloak-v18 docker container, using the `HTTP` schema, pointing to the Keycloak HTTP Port (9081). On `SSL` tab, I set the Certificates + Key + Intermediate Certificate that I created via `OpenSSL`.

And everything worked properly.

Than probably you must make sure your AWS ALB are correct.

**Comment by bonzo71** [comment]
Hello @andre-nascimento-rh !
Thank you for doing the lab! Much appreciated.

Is this variable "PROXY_ADDRESS_FORWARDING" not depreciated in 18.02? I can't see it [here](https://www.keycloak.org/server/all-config)

I was talking to AWS Support and it seems like there is nothing they can do if the problem is that the failing API calls are using HTTP protocol and port 443.  I wanted to add an additional HTTP listener to redirect all traffic to HTTPS but I can't have 2 listeners using the same port...

I am struggling to understand why these 3 requests:
-/auth/admin/realms
- /auth/admin/realms?briefRepresentation=true
-/auth/admin/serverinfo

are using HTTP, not HTTPS...
Thanks

![image](https://user-images.githubusercontent.com/114991201/203314409-62972cef-8c46-4b05-8117-fb8f6ff68309.png)

**Comment by andre-nascimento-rh** [comment]
Hello, @bonzo71,


You're right. The "PROXY_ADDRESS_FORWARDING" property was deprecated and has no effect in my Keycloak-v18 container.

Besides that and aforementioned, the solution assembled as described in my previous message is working properly:

![image](https://user-images.githubusercontent.com/90404766/203534160-f2771cac-5a1b-44cb-a0af-2c0ecfebdaee.png)

**Comment by zgldh** [comment]
The key point is `KC_PROXY: edge`

**Comment by AyaDEV** [comment]
SOLUTION !!!!!!!!

The key:        in the master realm, keep the theme like that.

<img width="1844" alt="github-issue" src="https://github.com/keycloak/keycloak/assets/45827083/be704e2c-be5a-4e47-85d2-39737822e08c">

**Comment by datmt** [comment]
If you are setting up keycloak without HTTPS behind a proxy, this could help (as it worked in my case)
My Caddy Config
```
http://your-site.xyz.io {
  redir https://{host}{uri} permanent
}
https://your-site.xyz.io {
  tls internal

  reverse_proxy keycloak:8080 {
    header_up X-Forwarded-Proto https
    header_up X-Forwarded-For {remote_host}
    header_up X-Forwarded-Host {host}
    header_up Host {host}
  }
}
```

Keycloak config:
```
KC_PROXY=edge
KC_HTTP_ENABLED=true
PROXY_ADDRESS_FORWARDING=true
KC_PROXY_HEADERS=xforwarded

```
More details here: https://datmt.com/backend/setup-keycloak-26-behind-caddy-proxy/

**Comment by SaschaLiebmann** [comment]
> If you are setting up keycloak without HTTPS behind a proxy, this could help (as it worked in my case) My Caddy Config
> 
> ```
> http://your-site.xyz.io {
>   redir https://{host}{uri} permanent
> }
> https://your-site.xyz.io {
>   tls internal
> 
>   reverse_proxy keycloak:8080 {
>     header_up X-Forwarded-Proto https
>     header_up X-Forwarded-For {remote_host}
>     header_up X-Forwarded-Host {host}
>     header_up Host {host}
>   }
> }
> ```
> 
> Keycloak config:
> 
> ```
> KC_PROXY=edge
> KC_HTTP_ENABLED=true
> PROXY_ADDRESS_FORWARDING=true
> KC_PROXY_HEADERS=xforwarded
> ```
> 
> More details here: https://datmt.com/backend/setup-keycloak-26-behind-caddy-proxy/

thanks alot  PROXY_ADDRESS_FORWARDING and KC_PROXY_HEADERS did it for my traefik problem
