### ISSUE TITLE
Quarkus based Keycloak in a docker container works only on port 8443

### ISSUE THREAD

**Issue by aruehl** [keycloak/keycloak#12933]
### Describe the bug

The quarkus keycloak inside a docker container works only correct, if the exposed docker port is the same as the quarkus keycloak port (8443).
Otherwise whether the admin console nor the account console starts correctly, because there are some links which are always adressed with the quarkus (8443) port.

For the account console it seems the `${authUrl}` and `${baseUrl}` variables are incorrect.

For the admin console the `/realms/master/protocol/openid-connect/3p-cookies/step1.html `URL is always generated with the 8443 port.

### Version

18.0.2

### How to Reproduce?

Start a quarkus based keycloak and expose the HTTPS port for example on the default HTTPS port 443.

**Comment by DGuhr** [comment]
Hi @aruehl there is an already merged addition to the guides that explains this scenario and the solution. https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/containers.adoc#exposing-the-container-to-a-different-port - in short: use `hostname-port` if you need another port (for standard http/s ports the use of proxy=<value> would also do, as the usage of proxy assumes keycloak is exposed on standard ports)

I will close this issue, feel free to reopen if something is missing

**Comment by aruehl** [comment]
@DGuhr  I have already tried this, but it doesn't work.

My keycloak.conf
```
db-url=jdbc:postgresql://kc-db/keycloak
db-username=keycloak
# db-password=<using ENV>

hostname=idp.knusel.me
hostname-port=443
hostname-path=/auth
```

I'm requesting the console over https://idp.knusel.me/auth/admin/master/console/


Here is the source of the console page
```html
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><link id="favicon" rel="icon" href="/auth/resources/delki/admin/keycloak.v2/favicon.ico"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Web site to manage keycloak"><title>Keycloak Administration Console</title><style>.container,
    .container-fluid,
    #load-container {
      padding: 0;
      margin: 0;
    }

    .container,
    .container-fluid,
    #load-container {
      width: 100vw;
    }

    .keycloak__loading-container {
      height: 100vh;
      width: 100%;
      background-color: #f0f0f0;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-direction: column;
      margin: 0;
    }

    #loading-text {
      z-index: 1000;
      font-size: 20px;
      font-weight: 600;
      padding-top: 32px;
    }</style><link rel="stylesheet" href="/auth/resources/delki/admin/keycloak.v2/styles.1653b4622917b89da7e4.css"></head>

<body style="height: 100%;">
  <script id="environment" type="application/json">
    {
      "loginRealm": "master",
      "authServerUrl": "https://idp.knusel.me:443/auth",
      "authUrl": "https://idp.knusel.me/auth",
      "consoleBaseUrl": "/auth/admin/master/console/",
      "resourceUrl": "/auth/resources/delki/admin/keycloak.v2",
      "masterRealm": "master",
      "resourceVersion": "delki",
      "commitHash": "04237c0eb32bf838e866b879b3637d1eca326151",
      "isRunningAsTheme": true
    }
  </script>

<div id="app" style="height: 100%"><div class="container container-fluid" id="load-container"><div class="keycloak__loading-container"><span class="pf-c-spinner pf-m-xl" role="progressbar" aria-valuetext="Loading..."><span class="pf-c-spinner__clipper"></span> <span class="pf-c-spinner__lead-ball"></span> <span class="pf-c-spinner__tail-ball"></span></span><div><p id="loading-text">Loading the admin console</p></div></div></div></div><noscript>You need to enable JavaScript to run this app.</noscript><script src="/auth/resources/delki/admin/keycloak.v2/webpack-runtime.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/lib-index-916de6ed.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/lib-EmptyState-25333d4a.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/lib-react-core.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/4359.js"></script><script src="/auth/resources/delki/admin/keycloak.v2/index.js"></script></body></html>
```
All resources and subpages are responded with http status 200 or 204. So everything seems to be adressed correct.

PS: I did found a posibility to reopen.

**Comment by DGuhr** [comment]
@aruehl I re-opened it, and thanks for reaching back out with more information! 

This seems to be an inconsistency when using `KC_HOSTNAME_PORT` and standard ports (443 for HTTPS, 80 for HTTP). A workaround for you right now would be to not use `KC_HOSTNAME_PORT=443` but use `KC_PROXY=passthrough` (assuming you use TLS with certs in your container).

I tried it out using this dockerfile, not-working pieces are commented out:

```
FROM quay.io/keycloak/keycloak:19.0.1
WORKDIR /opt/keycloak
COPY id.keycloak.test-key.pem /opt/keycloak/conf/
COPY id.keycloak.test.pem /opt/keycloak/conf/
USER root
RUN chmod 644 /opt/keycloak/conf/id.keycloak.test-key.pem
RUN chmod 644 /opt/keycloak/conf/id.keycloak.test.pem
USER 1000
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin
ENV KC_HOSTNAME=id.keycloak.test
# doesn't work as :443 is added to authServerUrl in javascript, but it should not be added there because it is a standard port and should be omitted
# ENV KC_HOSTNAME_PORT=443
# works instead with standard ports
ENV KC_PROXY=passthrough
ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/id.keycloak.test.pem
ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/id.keycloak.test-key.pem
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

With `HOSTNAME_PORT=443` the welcome page is reachable, but clicking on administration console results in an inifinite loading screen because the port is added in the JS. With proxy it is not.
 
@pedroigor I think we should check if standard HTTP/S ports (80/443) are used for `HOSTNAME_PORT` and set it to -1 / nothing then to prevent 443/80 being added to the js, but not sure where to add this check exactly. Can you hint me to the specific code that sets the `HOSTNAME_PORT` value in the `DefaultHostnameProvider`, or provide a PR? would be great!

**Comment by aruehl** [comment]
@DGuhr I already have this configuration in use (as workaround), but I find it a bit odd. 

Thanks for confirming that there is currently no other way.

**Comment by pedroigor** [comment]
@aruehl Using a port other than `8443` should work. Here is an example:

```
docker run --name keycloak -p 443:8443  -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=change_me -v {my-keystore-file-path}:/opt/keycloak/conf/server.keystore quay.io/keycloak/keycloak:19.0.1  start --hostname=mykeycloak --health-enabled=true --cache=local --proxy=passthrough
```

Is that what you want to achieve?

**Comment by aruehl** [comment]
@pedroigor yes, I'm running it in this setup. It is also described three posts ago by @DGuhr, but it looks a bit odd and not straight forward.
Do you mean this is correct setup and not a workaround?

**Comment by pedroigor** [comment]
Yes, it is. I guess you find it odd because of the `proxy` setting, right?

FYI, we are working on two more options to hostname that should bring the same level of configuration used before when using the legacy distribution. See https://github.com/keycloak/keycloak/pull/13681.

Basically, you would then set `hostname-url=https://idp.knusel.me` and have scheme, host, port, path, etc, resolved from this base URL you provide.

The reasoning behind forcing setting a `proxy` is that we make an assumption that in most situations the server is running behind a proxy and anything other than that is a corner case. So, for those deploying Keycloak behind a proxy using TLS, most of the time they are OK by just providing the `hostname` and `proxy` options. For such use cases, the configuration is simple.

However, the assumption we make is not always true and we can not push that on people. Like you are trying here, you also want to make it easier to deploy without a proxy, we also want to make it easier to expose the server using plain HTTP (although not recommended), or expose both frontend and admin using different URLs, etc.

So in general, those two options should be of great value and avoid a lot of confusion/issues from the community,

**Comment by aruehl** [comment]
OK. Thanks for clarifying.
