### ISSUE TITLE
Issue in creating Realm, Users, Clients in keycloak 

### ISSUE THREAD

**Issue by Priyaboliset** [keycloak/keycloak#12969]
### Describe the bug

When I am trying to create Realm, Keycloak users, Client, Theme using the yaml files in https://www.keycloak.org/getting-started/getting-started-operator-kubernetes, status of those CR's are showing as created without any error but in the keycloak UI am not able to see the created one

### Version

18.0.2

### Expected behavior

When we create Realm, Keycloak users, Client, Theme using the yaml files in https://www.keycloak.org/getting-started/getting-started-operator-kubernetes, in the keycloak UI we should be able to see the realms, users, clients

### Actual behavior

When I am trying to create Realm, Keycloak users, Client, Theme using the yaml files in https://www.keycloak.org/getting-started/getting-started-operator-kubernetes, status of those CR's are showing as created without any error but in the keycloak UI am not able to see the created one

**Comment by robson90** [comment]
@Priyaboliset have a look here https://github.com/keycloak/keycloak-realm-operator

**Comment by vmuzikar** [comment]
@Priyaboliset Thanks for the report and sorry for the late reply. I believe this issue is related to the old Operator which is now deprecated. If you believe it is still valid for the [Realm Operator](https://github.com/keycloak/keycloak-realm-operator), feel free to reopen the issue in that repo and please include as detailed steps to reproduce as possible.
