### ISSUE TITLE
Setting hostname-admin=localhost redirects to keycloak.example.com

### ISSUE THREAD

**Issue by myfirstnameispaul** [keycloak/keycloak#13063]
### Describe the bug

When loading`http://localhost:8080/admin/`, I am redirected to `http://hostname/...` and the redirect fails.

### Version

18.0.2

### Expected behavior

The admin console login screen loads on `http://localhost:8080/admin/master/console/`.

### Actual behavior

When loading`http://localhost:8080/admin/`, I am redirected to `http://hostname/...` and the redirect fails.

### How to Reproduce?

I have configured `keycloak.conf` with `hostname=keycloak.example.com` and `hostname-admin=localhost`.

I ssh directly into the Keycloak server with:

    ssh -L 8080:localhost:8080 203.0.113.36

In the browser I load `http://localhost:8080` and the welcome page loads.

The link to the Administration Console is `http://localhost:8080/admin/`.

When I click the link, I end up being redirected to `keycloak.example.com` and the page shows `Invalid parameter: redirect_uri`.

Same result when I try to load `http://localhost:8080/admin/master/console/`.

Also same results with port `8443` in browser when logging in with:

    ssh -L 8443:localhost:8443 203.0.113.36

### Anything else?

When I very first configured Keycloak, I set `hostname=localhost` and the page loaded and I could log in.

**Comment by DaviGia** [comment]
I am experiencing the exact same problem (on EKS with keycloak 18.0.2 deployed through the bitnami helm chart). To change server configuration I've declared the following initialization scripts:

``` sh
kc.sh start --auto-build --proxy=edge --hostname=<my-public-domain> --hostname-path=keycloak
```

I've an ingress that exposes both my frontend and my keycloak instance (on relative path /keycloak). I'm using nginx as ingress controller.

If I set keycloak in production mode (using the script above) I am able to login through keycloak login form and enter the system. The problem is that if I try to access the admin console (both from another public domain or from k8s port forwarding) when I click in "Administration Console >" link in the admin landing page I'm being redirect to the `<my-public-domain>` with an **Invalid parameter: redirect_uri**.

My desiderata is the following:

- enable production mode for keycloak server
- expose keycloak in a relative path
- do not expose admin console publicly (but only through k8s port forwarding)

Is there a way to achieve this?

**Comment by pedroigor** [comment]
@myfirstnameispaul Please consider looking the latest releases as we did some improvements to the hostname configuration.

For instance, you can now set a full base URL using the `hostname-url` and `hostname-admin-url ` options instead of tweaking with several options like `hostname`, `hostname-path`, etc.

The guide is also updated https://www.keycloak.org/server/hostname.

**Comment by timsolov** [comment]
Also observe this issue on `Keycloak 21.1.1 on JVM (powered by Quarkus 2.13.7.Final)`:

I run my keycloak with command: `start --proxy edge --hostname-strict-https=false --hostname-url="https://my.domain/auth/" --hostname-admin-url=http://127.0.0.1:8080/ --http-enabled=true`

Do ssh connection to the host: `ssh -L 8080:127.0.0.1:8080 my.domain`

And when I go to: `http://127.0.0.1:8080/admin/` in my browser keycloak redirects me to: `https://my.domain/auth/admin/master/console/#error=login_required&state=ad414059-d67b-470f-8510-49582fe2d24a`
And freezes page with `Loading the Admin UI` sentence at the center.

I anticipate full login process on internal network using only `127.0.0.1` host.

Do you have any solution?

**Comment by vmuzikar** [comment]
@timsolov Feel free to open a separate issue for this.

`hostname-admin` options only affect admin console resources, not login flows which always use the frontend endpoints. See https://www.keycloak.org/server/hostname

**Comment by michaelwindsor** [comment]
Hello,

Is there still a solution available? I have the same issue if i am using the ssh tunnel to access the admin console.

br
Michael

**Comment by vmuzikar** [comment]
@michaelwindsor I'd suggest opening a new issue for this. We rewrote the whole Hostname provider in Keycloak 25, the issue might not be present there anymore.
