### ISSUE TITLE
JSON logging contains unstructured log lines

### ISSUE THREAD

**Issue by Thomasdezeeuw** [keycloak/keycloak#13108]
### Describe the bug

When setting `KC_LOG_CONSOLE_OUTPUT=json` I would expect all output from Keycloak to be in the JSON format, that doesn't seem to be the case.

### Version

18.0.2

### Expected behavior

I would expect all output to be in the JSON format.

### Actual behavior

As can be seen from the log below a number of rows aren't JSON.

```log
Updating the configuration and installing your custom providers, if any. Please wait.
2022-07-14 10:22:07,611 INFO  [org.keycloak.common.Profile] (build-16) Preview feature enabled: declarative_user_profile
2022-07-14 10:22:08,125 WARN  [org.keycloak.services] (build-16) KC-SERVICES0047: slight-handle-action (com.slight.auth.handle.HandleActionFactory) is implementing the internal SPI required-action. This SPI is internal and may change without notice
2022-07-14 10:22:08,283 WARN  [org.keycloak.services] (build-16) KC-SERVICES0047: slight-handle-validation (com.slight.auth.handle.HandleValidationFormFactory) is implementing the internal SPI form-action. This SPI is internal and may change without notice
2022-07-14 10:22:08,283 WARN  [org.keycloak.services] (build-16) KC-SERVICES0047: slight-handle-writing (com.slight.auth.handle.HandleWritingFormFactory) is implementing the internal SPI form-action. This SPI is internal and may change without notice
2022-07-14 10:22:10,545 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 3838ms
{"timestamp":"2022-07-14T10:22:11.817Z","sequence":8404,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.common.Profile","level":"INFO","message":"Preview feature enabled: declarative_user_profile","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"c0b7dc6e502e","processName":"QuarkusEntryPoint","processId":1}
```

### How to Reproduce?

Run `KC_LOG_CONSOLE_OUTPUT=json /opt/keycloak/bin/kc.sh start`.

**Comment by DGuhr** [comment]
@Thomasdezeeuw I guess you are using `start --auto-build`, `build` or `start-dev` in the command you actually invoke by looking at the logs. This command actually invokes a `build` under the covers, which is the first stage as described [here](https://www.keycloak.org/server/configuration#_configuration_commands_and_stages). 

The important part in the docs  is  "before starting the server". In this stage, Keycloak and the underlying quarkus server is not started, resulting in the logger being initialised with a very minimal configuration and the log handler configuration not being evaluated. 

This first "build" stage is meant to run before actually starting up Keycloak, e.g. as part of a CI pipeline. In order to get rid of these logs when starting up, either invoke a `build` beforehand, or if you are using containers, create an [optimised docker image ](https://www.keycloak.org/server/containers#_building_your_optimized_keycloak_docker_image) where the "builder" part could e.g. be created in your CI pipeline and pushed to your registry as base for the actual "runtime image".

I will close this ticket for now, as it is actually expected behaviour. Feel free to re-open when you think it has severe consequences, but to be honest, unfortunately I don't think we can do much about it. (@pedroigor wdyt?)

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw I guess you are using `start --auto-build`, `build` or `start-dev` in the command you actually invoke by looking at the logs. This command actually invokes a `build` under the covers, which is the first stage as described [here](https://www.keycloak.org/server/configuration#_configuration_commands_and_stages).

I was using a local Docker image which didn't have the build step done yet. On production we build before hand and everything works fine their, thanks for looking into this.

> I will close this ticket for now, as it is actually expected behaviour. Feel free to re-open when you think it has severe consequences, but to be honest, unfortunately I don't think we can do much about it. (@pedroigor wdyt?)

I'm fine with closing the issue, the only suggestion I have is to maybe add a note about this in the documentation, cause it caught me by surprise.
