### ISSUE TITLE
Change the `--optimise` option to `--optimized`

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#13141]
### Description

The `--optimise` option name is not yet the best we can have to indicate what happens when it is used. There is no optimisation and the server is basically skpping the `build ` prior to starting the server.

I would change it to either `no-build` or keep the original `no-auto-build`. The former is shorter and explicitly states what the server is doing.

**Comment by stianst** [comment]
`--optimise` implies "run some optimisation", so this is not only the best name, but just plain broken name in my opinion.

I'd prefer something that reflects what the user wants to do, which is "use the prebuilt image I already built before". Something like:

* prebuilt
* use-prebuilt

**Comment by DGuhr** [comment]
> `--optimise` implies _"run some optimisation"_, so this is not only the best name, but just plain broken name in my opinion.
> 
> I'd prefer something that reflects what the user wants to do, which is _"use the prebuilt image I already built before"_. Something like:
> 
> * prebuilt
> * use-prebuilt
> 
> `no-build` or `no-auto-build` is better than `optimise`, but also doesn't convey the correct message, as it says more _"disable auto-build", which is not quite what the user is wanting to do.

Up front: I am not hard on the name, but let's review a few assumptions:

1) it's actually called `--optimised`, not `--optimise` - at least for me a small but important change in meaning. 
2) FYI: We looked at your suggestions [here](https://github.com/keycloak/keycloak/discussions/10451#discussioncomment-2249856) and as we also had differing opinions, we made a little vote with the intent to change later on. it was 3:1:1 (iirc) for `--optimised`.

> I'd prefer something that reflects what the user wants to do, which is _"use the prebuilt image I already built before"_. 

Here's a different view: Imo what a user really wants to do, is starting Keycloak in an optimized way for startup time and so on. That's exactly what `kc.sh start --optimised` tells you, without any technical interna (that can change/be extended by other optimizations in the future). 

I [overhauled](https://github.com/keycloak/keycloak/blob/f0229314b8fad0aaaa763f9da1b5f6c950450613/docs/guides/src/main/server/configuration.adoc) the config guide to reflect this and the changes that come with the desertion of `--auto-build`, and I found it nice to read and not bothering with any internal stuff, so even when step 1 would change for some reason in the future, step 2 might still be self-contained and true, reflecting the actual goal, and our "public api" would not need to change, bc. `--optimised` could still be used even when the whole concept of a "build" fades away for some reason.

> `no-build` or `no-auto-build` is better than `optimise`, but also doesn't convey the correct message, as it says more _"disable auto-build", which is not quite what the user is wanting to do.

apart from the arguments for "--optimised" above, which I still consider superior to no-build or no-auto-build, I'd argue that something that starts with a negative ("no") being an optimisation (faster!) is somewhat weird. But yeh, in that favor I'd also prefer `--prebuilt`, even if it refers to a technical interna instead of the actual intention. 

My ranking: 
1) `--optimi[zs]ed`
2) `--pre-built`
3) something else than `no-build/no-auto-build` 😁 
4) no-build/no-auto-build

btw: shouldn't this be a discussion instead of an issue? For me, we have no issue ;)

**Comment by pedroigor** [comment]
It is an issue so that we can track this change before 19.

I would leave it as `optimized` or change it to `no-build`. I don't quite like the `prebuilt` or `use-prebuilt`.

Also not hard and I think we just need a final word to make the change.

Btw, perhaps we should change `optimise` to `optimized` ? Looks more common and I notice that some tools like `snowpack` (used during our build) use `optimize` with a `z`.

**Comment by DGuhr** [comment]
Closed by https://github.com/keycloak/keycloak/pull/13263 (forgot the issue link, my bad)
