### ISSUE TITLE
Cannot configure multiple category-specific log level

### ISSUE THREAD

**Issue by dpulrichth** [keycloak/keycloak#13285]
### Describe the bug

[The documentation](https://www.keycloak.org/server/logging) gives this example for setting category-specific log levels:

```
bin/kc.[sh|bat] start --log-level=INFO,org.hibernate:debug,org.hibernate.hql.internal.ast:info
```

However, when running this command it results in the following error message

```
Option '--log-level' expects a single value (category:level)
Try 'kc.bat start --help' for more information on the available options.
```

This persists even if the `log-level` value is quoted (single or double quote).

### Version

18.0.0

### Expected behavior

Different log levels can be set for any number of categories.

### Actual behavior

Only a root level OR a category-specific log level can be configured.

### How to Reproduce?

See above

**Comment by DGuhr** [comment]
Hi @dpulrichth for windows, its just hard to add this via command line because of escaping issues. I would suggest you use keycloak.conf instead. That said, we have working functional [tests](https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/src/test/java/org/keycloak/it/cli/dist/LoggingDistTest.java#L77) in our testsuite that use double quote escaping, so normally it should work with these. I'll close here for now, if you still experience problems feel free to reopen :)
