### ISSUE TITLE
Quarkus / map storage integration: Allow custom storage-implementations

### ISSUE THREAD

**Issue by dominikschlosser** [keycloak/keycloak#13445]
### Description

The map storage integration in quarkus doesn't allow the configuration of custom storage-implementations via cli-parameters. The reason for this is this code in org.keycloak.quarkus.runtime.configuration.mappers.StoragePropertyMappers:

```java
private static Optional<String> resolveMapStorageProvider(Optional<String> value, ConfigSourceInterceptorContext context) {
    try {
        if (value.isPresent()) {
            return of(value.map(StorageType::valueOf).map(StorageType::getProvider)
                    .orElse(StorageType.chm.getProvider()));
        }
    } catch (IllegalArgumentException iae) {
        throw new IllegalArgumentException("Invalid storage provider: " + value.orElse(null), iae);
    }

    return value;
}
```

Only pre-defined values in the StorageType-enum are allowed.

As we are planning to implement a custom storage-implementation, it would be great to be able to register it via standard-configuration.

**Comment by hmlnarik** [comment]
@dominikschlosser Thank you for the report! We are very much interested in your use case.

In Keycloak 19, we have provided preview of the new store. The CLI parameters are experimental exactly for the reason of shaping them after understanding the use cases by the community.

Could you please provide further details on how you would like the integration to shape?

**Comment by dominikschlosser** [comment]
We are planning to implement an Apache Cassandra-based storage implementation. We already implemented it via the old (private) SPIs and are currently investigating the new store API.
We are also planning to open source this storage-implementation.

It would be great to be able to configure it like this:

```
kc.sh start --storage=custom --storage-provider=cassandra
```

The same would apply for overwriting certain storage-areas:

```
kc.sh start --storage=jpa --storage-area-realm=custom --storage-area-realm-provider=cassandra
```

**Comment by ahus1** [comment]
@dominikschlosser - this should be possible once we make the CLI options more dynamic. There will be a future GitHub issue for that. 

To be most aligned with the existing map storages, I'd suggest a future CLI as 

```
kc.sh start --storage=jpa --storage-area-realm=cassandra
``` 

As an intermediate solution until the options are fully dynamic, I'd suggest you could work with a local build or create a PR that could consist of the following: 

* change `throw new IllegalArgumentException("Invalid storage provider: " + value.orElse(null), iae);` to `return value` 
  This would keep the current mapping provided in the StorageTypes, but will pass-through all other CLI options. 
* remove `.expectedValues(StorageType.values())` from `StorageOptions` in all placed to prevent Quarkus from validating the option - specifying a storage option that is unknown would still lead to an exception as there would be no known provider. 
* enhance `AbstractMapProviderFactory.getProviderFactoryOrComponentFactory` to throw a meaningful `ModelException` when no provider can be found (instead of throwing an NPE as of today)

The usual disclaimer: All storage options are experimental for now, so they might change.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
