### ISSUE TITLE
RHEL (FreeIPA) default mapper fetches fullName instead of firstName

### ISSUE THREAD

**Issue by dmgeurts** [keycloak/keycloak#13492]
### Describe the bug

Default deployment and added an LDAP user federation.

Log into Keycloak with a test user and noticed the surname is listed twice in the account name. Mapper under the LDAP federation is correctly set to firstName.

### Version

19.0.1

### Expected behavior

firstName should only retrieve the first name not the full name.

### Actual behavior

The firstName mapper object retrieves the fullName

### How to Reproduce?

Clean build server, add FreeIPA LDAP user federation and login to Keycloak with an LDAP account.

**Comment by dmgeurts** [comment]
Worked it out, I was reading the parameters the wrong way round. `firstName` is a Keycloak attribute and the LDAP Attribute is, you guessed it... Dumb-ass me didn't read properly!

Changing the LDAP attribute for firstName from cn to givenName resolved my issue.

Thank you for graciously setting me straight, sorry for wasting your time.

**Comment by slominskir** [comment]
This is actually a bug.   It's a very very old bug.   When you create an LDAP storage provider Keycloak automatically creates mappers and the automatically created mapper for first name is wrong for FreeIPA.  See: https://issues.redhat.com/browse/KEYCLOAK-8062

This continues to be a bug because the logic and code to automatically generate mappers is terrible (plus, the test framework was terrible when I first submitted a fix for this):

https://github.com/keycloak/keycloak/blob/52f58b5f28a78b1c23569b3a446df5104387919c/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java#L320
