### ISSUE TITLE
locale attribute not set after registration

### ISSUE THREAD

**Issue by ghost** [keycloak/keycloak#13505]
### Describe the bug

When a user creates a new account using the direct registration link of our application the user's locale is not saved as an attribute. If the user explicitly switches the current language by the language dropdown, the attribute is set, even if they just switch to english and back to german.

See also [this SO question](https://stackoverflow.com/questions/66208538/keycloak-locale-not-set-after-registration) describing the very same behaviour.

The registration link in our app is like this

https://<server>/auth/realms/<realm>/protocol/openid-connect/registrations?client_id=<id>&response_type=code&ui_locales=de&kc_locale=de&redirect_uri=<callback_url>

as mentioned [here ](https://stackoverflow.com/a/53264417/2217962) and in the referred keycloak mailing list archive.

### Version

17.0.1

### Expected behavior

Every user should have a "locale" attribute after registration, containing the language used during registration.

### Actual behavior

"locale" attribute is not set at all.

### How to Reproduce?

* Start keycloak
* Use registration link from above
* Register a new user
* Go to user detail page - locale dropdown is empty
* Read user attrbutes - locale is not set

**Comment by stohr2566** [comment]
I also encountered this issue and decided to debug it and find out why. 
The Attribute was not present, but a cookie with `KEYCLOAK_LOCALE=xx` was. 

https://github.com/keycloak/keycloak/blob/8a82b6b58720ea3ad93d24dea2f62893f54303c2/services/src/main/java/org/keycloak/services/util/LocaleUtil.java#L47

Might it be reasonable to fallback to this cookie for when no attribute is present?

**Comment by rmartinc** [comment]
The locale can be empty in keycloak. That means that the user is OK with the default locale presented by the server in that browser. This is because the updater just assigns the attribute if the user changed the locale in the combobox, if not changed it's just left empty ([here](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/requiredactions/UpdateUserLocaleAction.java#L21-L37)) I suppose you can change the behavior creating your own [required action](https://www.keycloak.org/docs/latest/server_development/#required-action-walkthrough) that always assigns the locale if it's empty in the user. The default locale for a user can be obtained from the session: 

```java
String localeTag = session.getContext().resolveLocale(user).toLanguageTag();
```

We can change this behavior but, right now, it's just like this. So not a bug for the moment.

**Comment by GioviQ** [comment]
I mapped locale attribute to a claim, so when my API endpoint is called, I should be able to init some tables in italian or english at the first login of the user. But now it is not possible.
