### ISSUE TITLE
KC_HTTP_RELATIVE_PATH or http-relative-path doesn't work on build process 

### ISSUE THREAD

**Issue by bdoubrovine** [keycloak/keycloak#13514]
### Describe the bug

I use keycloak with container build. 

During my docker build, I used `RUN /opt/keycloak/bin/kc.sh build --http-relative-path=/auth` to set kc.http-relative-path

When I deploy my image, `kc.sh show-config` return `kc.http-relative-path =  / (PersistedConfigSource)`

I also tried ENV KC_HTTP_RELATIVE_PATH=/auth.

### Version

19.0.1

**Comment by pedroigor** [comment]
@bdoubrovine Starting with `19` we default to run an "automatic" build when running the `start` command.

Please, see https://www.keycloak.org/server/configuration and https://www.keycloak.org/2022/07/keycloak-1900-released.html.

What might be happening is that:

* You are running a `build` and setting the  `--http-relative-path=/auth` option
* When starting, an implicit `build` happens and the server does not see that option set again and reverts it back to the default which is `/`

What you can do is:

* Use the new `--optimized` option to avoid running a `build` prior to starting the server
* Just run `start --http-relative-path` without necessarily building your own container image. This approach introduces an additional overhead because a `build` will happen when starting the container, but it might be OK for you.
