### ISSUE TITLE
the user (unregistered user) has full control over custom attributes

### ISSUE THREAD

**Issue by mhrsalehi** [keycloak/keycloak#13581]
### Description

according to the Keycloak [docs](https://www.keycloak.org/docs/latest/server_development/index.html#registration-page) to add custom user attributes we can edit the registration template, for example, add the following snippet to the form:

```
<div class="form-group">
   <div class="${properties.kcLabelWrapperClass!}">
       <label for="user.attributes.mobile" class="${properties.kcLabelClass!}">Mobile number</label>
   </div>

   <div class="${properties.kcInputWrapperClass!}">
       <input type="text" class="${properties.kcInputClass!}" id="user.attributes.mobile" name="user.attributes.mobile" value="${(register.formData['user.attributes.mobile']!'')}"/>
   </div>
</div>
```
with this, the custom attribute (mobile) was added to the user. but the user (unregistered user) has full control over these custom attributes, the user can inspect and edit the HTML page to add any other custom attribute (or edit), by changing id and name.

### Discussion

https://stackoverflow.com/questions/73242310/how-to-prevent-users-from-adding-custom-attributes-in-keycloak-registration

### Details

see StackOverflow question:
https://stackoverflow.com/questions/73242310/how-to-prevent-users-from-adding-custom-attributes-in-keycloak-registration

**Comment by lexcao** [comment]
From my instigation on this, I found these codes:
https://github.com/keycloak/keycloak/blob/ec808d28bb224fc243edd334aa549a8cf8d94ca7/server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java#L347-L349
and 
https://github.com/keycloak/keycloak/blob/ec808d28bb224fc243edd334aa549a8cf8d94ca7/services/src/main/java/org/keycloak/userprofile/LegacyAttributes.java#L24-L34
and 
https://github.com/keycloak/keycloak/blob/ec808d28bb224fc243edd334aa549a8cf8d94ca7/server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java#L76-L82

When converting form data to user attributes on user registration flow, 
it checks the `LegacyAttributes#isSupportedAttribute` and `DefaultAttributes#isSupportedAttribute` if `declarative-user-profile` feature is enabled.

It only checks the `name.startsWith("user.attributes")` for legacy attributes,
while checks the read-only attribute for default attributes, which is always `true` when not found in the attribute meta.

I don't know if it is intentional behavior.
It needs the Keycloak team to check.

**Comment by abstractj** [comment]
@mhrsalehi you have some options to mitigate the issue, based on what I learned from @pedroigor:

* Enable User Profile. Such capability was added to solve those kinds of issues (https://www.keycloak.org/docs/latest/server_admin/#enabling-the-user-profile)
* If you are using legacy user profile (default), provide your own validations if implementing the FormAction SPI.

**Comment by pedroigor** [comment]
Yeah, this should be covered by the user profile.
