### ISSUE TITLE
higher network io with map storage for create and list entities when compared with legacy store with no cache

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak#13698]
### Describe the bug

higher network io with map storage for create and list entities when compared with legacy store with no cache

### Version

nightly (8/5/2022)

### Expected behavior

this ticket is more around investigating the high network io, than any issue which is manifested cause of that higher resource utilization.

expected behavior for this would be to be predictable with the high network io and understand the cause for that.

### Actual behavior

we see higher network io when compared with legacy store with no cache enabled
![image](https://user-images.githubusercontent.com/3415105/183906667-5222739c-673e-4787-a52d-46ec440e9019.png)

Top row: Legacy Store Cache disabled
Middle row: Map Store
Bottom row: Legacy Store Cache enabled

and we could confirm the high data transmission is between postgres transmit and keycloak receive, most likely from SELECT statements
![image](https://user-images.githubusercontent.com/3415105/183907070-6639098b-12c6-4e47-accd-01de6ae37a19.png)

### How to Reproduce?

bring up the keycloak quarkus distro with the following startup options

```
--set db-pool-initial-size=50 --set db-pool-min-size=50 --set db-pool-max-size=50 --set storage=jpa --set database=postgres
```

run the load test from [keycloak-benchmark](https://github.com/keycloak/keycloak-benchmark/tree/main/benchmark) project using the below command

```
./bin/kcb.sh --scenario=keycloak.scenario.admin.CreateUsers --server-url=https://keycloak.XXXX/ --client-secret=XXXXX --users-per-sec=30 --ramp-up=30 --measurement=300 --ramp-down=30 --user-think-time=3
```
note: if you use the minikube based provisioning from the keycloak-benchmark project, we could see the observability metrics that are shared with this ticket.

**Comment by hmlnarik** [comment]
One potential cause could be repetitive obtaining of realm and client in here:

https://github.com/keycloak/keycloak/blob/7bf4ac7983abd066ad2f6accb5510bd0771bd88e/services/src/main/java/org/keycloak/services/resources/admin/AdminRoot.java#L164-L175

If that is so, caching the read realm and client would solve the issue. This is expected to be delivered with #13641.

**Comment by sguilhen** [comment]
I've added a new "mixed" storage to the benchmark project, that essentially sets all storages to JPA except for user sessions, auth sessions, login failures, and single use objects, which are all using hotrod.

Then I've run the tests, which required enabling prepared transactions in Postgres, and the results were pretty much the same as reported by @kami619 . The network IO between KC and the DB still peaked at around 23 MiBps. So we have

| Map Store JPA  | Map Store Mixed Mode |
| ------------- | ------------- |
| 23.3 MiBps | 23 MiBps  |

Interestingly, I've noticed a performance drop (response time) when using mixed mode compared to using JPA for all stores:

| Legacy Store | Map Store JPA  | Map Store Mixed Mode |
| ------------- | ------------- | ------------- |
| 17 ms | 28 ms  | 41 ms |

The values above were obtained consistently through multiple runs of each scenario. I think it has to do with extra TX coordination happening in mixed mode compared to the all-JPA scenario, but this is just a guess atm.

I then paired with @vramik yesterday to share the experience of working with the benchmark, and we've tried some other scenarios to narrow down what could cause the higher network IO in the new map store. First we moved users to hotrod, but I started getting KOs after a while due to DB connection depletion (no idea why this is happening in this scenario, needs further investigation). I then switched users to CHM, just to see the impact on the network IO. Again, the results didn't change and the same network IO graph appeared in Grafana, with the same peak values.

We then switched to the next "suspect" - realms. I've moved users back to JPA, and put realms on CHM. So the setup is the same as the mixed setup used in the first tests, but with realms switched over to CHM. This time the impact was **huge**, with network IO peaking at **1 MiBps**. Summarizing:

| Legacy Store  | Map Store Mixed Mode | Map Store Mixed Mode With Realms on CHM |
| ------------- | ------------- | ------------- |
| 5.8 MiBps | 23 MiBps  | 1 MiBps |

So the conclusion is that it is safe to say that Keycloak fetching realms in the new store is causing the difference in network IO, which on Map Storage is 4 times higher than the legacy store. We need to investigate now if we're fetching the realm multiple times during the requests, and if we can avoid bringing the whole realm JSON field by moving other fields to generated columns (or perhaps even other tables, like required actions).

**Comment by vramik** [comment]
Thank you @sguilhen! For the sake of completeness there are only these fields in separate generated columns currently: https://github.com/keycloak/keycloak/blob/c6f13363b95d0738b43018d528fc861555bdd548/model/map-jpa/src/main/java/org/keycloak/models/map/storage/jpa/realm/delegate/JpaRealmDelegateProvider.java#L54-L58 

and accessing any other field triggers additional round-trip to the DB to obtain the json.

**Comment by hmlnarik** [comment]
These are important results, thank you @sguilhen and @vramik.

We could potentially save the load if there was a simple cache for JPA persistent objects: Key would be a combination of an object `ID` and `@Version` columns (i.e. `[JpaRootEntity.getId(), JpaRootEntity.getVersion()]` pair), value would be the parsed entity.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
