### ISSUE TITLE
Silent OIDC by providing access tokens

### ISSUE THREAD

**Issue by sharonchansy** [keycloak/keycloak#13750]
Hello,

I am using keycloak to broker Microsoft as IdP to log in to my service. I already set up a working OIDC flow as follows: A login to my web app is redirected by keycloak-js-adapter to Microsoft's login page, when user inputs microsoft account credentials, keycloak completes the OIDC process and redirects to my service.

Now my service is wrapped inside a Microsoft Teams tab application. From Microsoft Teams I want to use the Microsoft Authentication Library (MSAL): https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-acquire-cache-tokens
This will silently get the Microsoft login session being used to login the Teams app itself, and return the id token, access token, refresh tokens.

However, I still need keycloak to handle logging into my service. The keycloak-js-adapter redirects to Microsoft login page, which does not take the tokens.

My question is, how do I integrate these two flows? Is it possible to provide the OIDC tokens to keycloak, so that keycloak does not require the user to login Microsoft again?

Appreciate any hints. Thanks a lot.

**Comment by lexcao** [comment]
Hi, I am currently studying a way to use Keycloak with Google one-tap login, 
I think there may be the same method to achieve login.

It could log in into IDP silently if you have an `id token` from MS.
You could follow these steps:

1. extract `email` from `id_token` from MS
   - the `decodeToken` method can be copied from [keycloak.js](https://github.com/keycloak/keycloak/blob/ab431e3bd9b50dc913148cc8f90c8930815511d1/adapters/oidc/js/src/keycloak.js#L1022)
```
const email = decodeToken("${idTokenFromMS}").email;
```

2. login silently
```
keycloak.login(
  {
    prompt: "none",
    loginHint: email, // this is the email from encoded
    idpHint: "ms" // this is your MS IDP alias
  }
)
```
---
**Note:**
It does not work with `Google` and `Microsoft` Identity provider, 
you need to configure the `OIDC` identity provider.

The reason is the `Pass Login Hint` setting is **false** by default and these two IDPs are nowhere to configure. Please refer to these issues #12864 and #8374

The workaround is integrating your MS with the new OIDC identity provider,
both IDPs could be the same configuration but different alias.

**Comment by lexcao** [comment]
Hi, @tiennguyen1293 
I have not tried MS Teams and ElectronJS.
From my understanding, it would work fine in an iframe if it supports Content Security Policy (CSP).

Let's say for example when using it for MS Teams in an iframe.
We're going to direct MS to log in silently, which means the login URL is from MS
and the origin of the iframe is `https://login.microsoftonline.com/` (just e.g.).
So it would work when `https://login.microsoftonline.com/` configure properly  CSP on iframe.

**Comment by daviddelannoy** [comment]
> Hi, I am currently studying a way to use Keycloak with Google one-tap login, I think there may be the same method to achieve login.

Hi @lexcao,

Did you suceed in integrating Keycloak with Google One tap login ? using the method you described ? 
You log in on Google, then you login silently using keycloak JS adapter with `prompt:"none" `, without any token exchange ?

**Comment by lexcao** [comment]
@daviddelannoy  Yes, suceed.

What do you mean `without any token exchange`?
There should be code to token with Google login silently.

**Comment by daviddelannoy** [comment]
Hi @lexcao 

Yes I have suceeded too.
Sorry for the bad sentence, I meant : without calling explicitly the external to internal token exchange endpoint manually.

**Comment by lexcao** [comment]
Hi @daviddelannoy 
> without calling explicitly the external to internal token exchange endpoint manually.
Yes

**Comment by jonkoops** [comment]
Closing this issue as it's a discussion, and therefore not actionable. Feel free to start a discussion in the forums.
