### ISSUE TITLE
HOSTNAME_ADMIN option is missing from HostnameOptions ALL_OPTIONS array

### ISSUE THREAD

**Issue by fidgi** [keycloak/keycloak#13850]
### Describe the bug

According to the code in [HostnameOptions class](https://github.com/keycloak/keycloak/blob/e3ece8244fff0206b029b9539257fdf2626b6c13/quarkus/config-api/src/main/java/org/keycloak/config/HostnameOptions.java) , the HOSTNAME_ADMIN option is defined but not added to the ALL_OPTIONS array.

As a consequence it may not be accessible to the configuration properties mappers .

Is this by purpose ?

### Version

main

### Expected behavior

HOSTNAME_ADMIN should have its entry in the HostnameOptions ALL_OPTIONS array

### How to Reproduce?

N/A (it's just from source code analysis)

**Comment by DGuhr** [comment]
Hey @fidgi thanks for spotting this. I created a small fix in #13917 

IIRC we don't use the ALL_OPTIONS array currently, but reference the Options we want directly in the propertymappers, so this has no direct impact (the CI will tell otherwise, but e.g. the CI help includes the option even if it is not added to the array, see [here](https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/src/test/resources/org/keycloak/it/cli/approvals/cli/help/HelpCommandTest.testStartHelp.unix.approved.txt#L93)), but that may change in the future, so better to add it.

**Comment by pedroigor** [comment]
Thanks, all.

The proper fix should be to remove that code pattern from the code base. As you mentioned we don't use it for anything. Created https://github.com/keycloak/keycloak/issues/13947.
