### ISSUE TITLE
 Host Header Injection Vulnerability issue

### ISSUE THREAD

**Issue by Mango2020** [keycloak/keycloak#13966]
### Describe the bug

Our application has integrated keycloak to do the authentication. When we do the dynamic scan for it, there is "Host Header Injection" vulnerability issue. 

Header X-Forwarded-Host added to request: appscanheaderinjection.com. How can I disable the X-Forwarded-Host or add the whitelist for it? Thanks.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/61238245/186451528-2a500013-d223-4937-8be5-4e30ff59cf7d.png">

### Version

jboss/keycloak:15.0.2

**Comment by darius-m** [comment]
If you have Keycloak behind a proxy, you may have the proxy set the header for you, which MAY help - for example you could set the following when in nginx: `proxy_set_header X-Forwarded-Host $host:$server_port;`.

**Comment by Mango2020** [comment]
@darius-m Thanks for your rapid response. We do not have the proxy and we want to disable the proxy and prevent adding X-Forwarded-Host in the HTTP request header. We set the KC_PROXY=none, but it did not work. Can you share other solutions on disabling the X-Forwarded-Host or how can we check the HTTP X-Forwarded-Host Header against a whitelist of known domains? Thanks in advance.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/61238245/186552540-0aaeb6df-0816-486b-b8ab-bada8fad96c8.png">

**Comment by ashishtchaudhari** [comment]
Our pen testing team also reported this. However, we got it around with it for now, by white listing the domain name in our WAF configuration. However, it would be great if we can have solution for this on Keycloak side as well.

**Comment by Mango2020** [comment]
@ashishtchaudhari Thanks so much for your workaround.

**Comment by stianst** [comment]
Please see our security policy on responsible disclosure of potential security related issues:
https://github.com/keycloak/keycloak/security/policy

This issue comes down to the fact that you are running an older version of Keycloak and have enabled it to accept these headers (they are not enabled by default) without configuring a fixed hostname for Keycloak. Please upgrade and also refer to the documentation on how to properly configure Keycloak behind a reverse proxy.
