### ISSUE TITLE
Single sign out failure with some OIDC clients: Missing parameters: id_token_hint

### ISSUE THREAD

**Issue by peacepenguin** [keycloak/keycloak#14010]
### Describe the bug

When using sharepoint subscription edition (SE) as an OIDC client against Keycloak, Single-sign-out is not working correctly. Signing off from sharepoints "log off" button starts the RP-initiated log-off flow, but it results in a keycloak error page in the browser:

Missing parameters: id_token_hint

Ideally sharepoint should be providing the 'id_token_hint' query param to fix this issue. But we should be able to overcome this in keycloak by following the RP-initiated logout OIDC spec a little closer.

Keycloak has a good logout mechanism already for RP-initiated logout, where if the 'id_token_hint' and 'post_logout_redirect_uri' are BOTH NOT present, keycloak asks the user in the browser: "Do you want to logout?"

The issue occurs in OIDC clients like sharepoint, that only send the single query param: 'post_logout_redirect_uri'. In this case an error is shown in the browser by keycloak when attempting RP-initiated logout: "Missing parameters: id_token_hint"

The OIDC spec says that "id_token_hint" is recommended, but not required to be sent by the RP. Also "post_logout_redirect_uri" is optional. Here though it seems that keycloak is treating "id_token_hint" as required anytime the "post_logout_redirect_uri" param is present.

https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

In this condition, where "post_logout_redirect_uri" is provided by the RP during an RP-initiated logout, but the "id_token_hint" is not provided, i believe that keycloak should instead show the question to the user: "Do you want to logout?" instead of showing the error message implying that the 'id_token_hint' is a required query param.

It is important to note that the RP-initiated logout spec also specifies that the RP should send the 'id_token_hint' if the 'post_logout_redirect_uri' is sent, but again is only 'recommended' by the spec. So sharepoint is soft-violating a "recommended" param that should be fixed by microsoft. But keycloak is hard-violating the spec by treating the same "recommended" param, as a 'required' param, which results in the error message instead of falling back to the "Do you want to logout?" interactive flow.

### Version

19.0.1

### Expected behavior

an oidc client (RP), when implementing single sign off, using an RP-initiated logout, that only provides a single query param: 'post_logout_redirect_uri' should result in a keycloak page asking: "Do you want to logout?"

### Actual behavior

an error page is shown to the user in the browser from keycloak, and no logoff is performed.
error message:
"Missing parameters: id_token_hint"

### How to Reproduce?

To see the bug: against any default keycloak instance, goto the realm's openid-connect logout URL and include the single URL query parameter: 'post_logout_redirect_uri'

like this example from sharepoint se's generated RP-initiated URL:

https://sso.labx.loc/realms/labx-loc/protocol/openid-connect/logout?post_logout_redirect_uri=https://labx-sp.labx.loc/_layouts/15/SignOut.aspx

To see the expected behavior: against any default keycloak instance, goto the realm's openid-connect logout URL without the 'post_logout_redirect_uri' query param:

https://sso.labx.loc/realms/labx-loc/protocol/openid-connect/logout

**Comment by peacepenguin** [comment]
I've created and tested a fix for this condition with a simple pull request. It sets the flag to force a user confirmation instead of throwing the error when 'post_logout_redirect_uri' is presented without token_id_hint or client_id. This matches the OIDC specification for RP-initiated logout.
https://github.com/keycloak/keycloak/pull/14049

**Comment by mposolda** [comment]
@peacepenguin Thanks for this issue and for your PR.

Your statements here makes sense, and I understand the specification in a similar way as you. However the problem is that changing it this way would break Keycloak compatibility with OIDC conformance testsuite for RP-Initiated logout profile. 

For more details, there is this test in the OIDC conformance testsuite, which tests that using `post_logout_redirect_uri` parameter alone should throw an error: https://www.certification.openid.net/log-detail.html?log=0Wz45IQpTNMGrQL&public=true

On the other hand, this OIDC test was created against the previous draft of the Logout specification, which mentioned that `id_token_hint` is mandatory in case that `post_logout_redirect_uri` parameter is used (and the previous draft did not had support for the `client_id` parameter at all). It is possible that testsuite testsuite will be updated in the future to remove this test (or update it somehow). In that case, I would be more then happy to change the behaviour according your PR. But before this is done, I am marking your PR as "on hold".

**Comment by peacepenguin** [comment]
@mposolda thanks for the details on this. I'll investigate what it takes to get the conformance test suites updated to the current OIDC spec. Looks like the repo for the suite is here: https://gitlab.com/openid/conformance-suite

**Comment by peacepenguin** [comment]
The OIDC conformance test suite is indeed out of alignment with the current published spec. There's now an issue in the upstream OIDC conformance test repo describing this miss-alignment with the published spec here:
https://gitlab.com/openid/conformance-suite/-/issues/1090

Makes sense to wait till the OIDC test suite is updated before Keycloak should be updated to remain compliant with the recently updated spec.

**Comment by mposolda** [comment]
@peacepenguin Just one additional note: I am fine that if `post_logout_redirect_uri` is provided alone for some reason (without `id_token_hint` and without `client_id`), then the error is not thrown. However I am not very keen to automatically redirect to `post_logout_redirect_uri` after logout in that case. In other words, I am more towards to not throw the error, but rather either:
- Ignore the `post_logout_redirect_uri` parameter and have the same behaviour like if not any parameter is provided.
- Show another prompt to the user before redirect where he needs to confirm redirect. Something like `Click here to redirect to https://my-post-logout-redirect-uri` . In this case, the `post_logout_redirect_uri` won't be verified in Keycloak as user will need to confirm the redirect and hence it is his responsibility. I can add that I am not 100% sure about this and I would add it just in case that this behaviour is allowed in the OIDC RP-Initiated Logout specification (I will try to comment on the "openid" issue to clarify if specs should be updated in that case).


The reason is, that when `post_logout_redirect_uri` is available alone and Keycloak is supposed to verify it, then we need to use the method `RedirectUtils.verifyRealmRedirectUri(session, redirectUri)`, which is already deprecated in the current Keycloak. This method is very bad for both performance and security (needs to iterate over all realm clients and check their redirect URI and allows the "Open Redirect attack" as long as any single client in the realm is configured with the wildcard redirect_uri like `*`). Note that the `client_id` parameter (or `id_token_hint`) is exactly used for this case to make sure that `post_logout_redirect_uri` is verified against correct client.

Sorry I did not mentioned this before. I see the requirement for the "Automatic redirect" is not mentioned in the description of this issue, however it is mentioned in the OIDC issue https://gitlab.com/openid/conformance-suite/-/issues/1090 , which is what I am concerned.

Also one note, We recently added backwards compatibility switch in the latest Keycloak main, which allows that error is not thrown in case that `post_logout_redirect_uri` is used alone. See latest docs https://github.com/keycloak/keycloak-documentation/commit/5a6a302d2f0bd068e9cc3f16377fff2bd9d7630c . So you can possibly already use this switch. However it is a plan to possibly remove these switches in the future (likely Keycloak 23 release).

**Comment by peacepenguin** [comment]
@mposolda yes this all makes sense. Odd that the spec was updated to no longer require client_id nor id_token_hint, when the previous spec versions required it, I assume for these exact reasons you've brought up.

I suppose the spec is still in draft form, so these types of back-and-forth ideas may take some time to settle fully. client_id at least makes sense to be 'required' to overcome the performance issues. And we could always index the allowed redirect values in the database to make it performance scalable if the spec demands that it be a required function.

I can also put a proxy in front of sharepoint where if it sees the header "post_logout_redirect_uri", to append the client ID it's been configured with to overcome the initial problem with sharepoint's OIDC implementation when used against keycloak till the dust settles on the spec. Perhaps someone with a microsoft support contract would be willing to open a paid support issue with MS to get them to simply add at least the client_id to their implementation. But in the current form of the spec, microsoft may not agree that needs to be done at all. And MS's own ADFS OIDC server is certainly not up to spec either. It just blindly ignores the redirect uri, and logs you out without confirmation, no matter what parameters are provided.

Appreciate the dialogue here, very informative.

**Comment by peacepenguin** [comment]
Some good discussion on which way to go next for the spec and associated conformance tests is happening at the below link. For anyone that wants to weigh in on how to handle these situations where the spec is somewhat ambiguous on how to handle OIDC clients that only send "post_logout_redirect_uri" : https://gitlab.com/openid/conformance-suite/-/issues/1090

Interesting to note the spec doesn't specify that the OP (keycloak) MUST actually redirect the user. So completely ignoring the single param "post_logout_redirect_uri" does appear to be a valid option under the current spec. Prompt the user for logout or not, and don't redirect, just like if there was no params provided at all. That might be the only sane approach until the spec is clarified further for this situation.

**Comment by panva** [comment]
FWIW, a couple notes: 

The reason client_id was added is because for a lot of valid use cases keeping the ID Token around was in place ONLY for the case of using it for logout purposes and implementers objected to this. The result of which was that RPs had to give up control over the final destination, which was a very bad experience for users, hence client_id (and possibly, deployment specific logout_hint) was added.

There was significant pushback to making client_id REQUIRED because of existing, for years used and working, implementations based on the old behaviour which is why it is OPTIONAL. A future new specification which would obselete the existing (to be soon final) one would probably update client_id to be REQUIRED.

It is expected that only validated, pre-registered redirect uris be used, in that sense - only passing post_logout_redirect_uri must still not redirect. The dubious part is whether the request should be processed (ending in a generic success page) or not (an error page like previously).

I've also added notes to the conformance suite tracker.

**Comment by mposolda** [comment]
@panwa Thanks for the points. I agree that when only `post_logout_redirect_uri` is sent alone (none of `client_id` and `id_token_hint` present), then it will be best to either show an error or ignore the `post_logout_redirect_uri` (EG. proceed with the logout, but display the page like `You are logged-out` after the logout is finished without redirecting to the `post_logout_redirect_uri`).

I personally don't care which one of them is better option. Keycloak currently displays error, but we can possibly change to ignore `post_logout_redirect_uri` . But will be very nice to update the specification to make this more clear what should be done.

Thanks for the info about the `client_id` being possibly REQUIRED in the future version of the specification.

**Comment by peacepenguin** [comment]
I personally vote for ignoring the 'post_logout_redirect_uri' in keycloak when it's the only param provided. As it 'shouldn't' error since the spec allows the single param on its own. And bonus, the conformance test will still pass as it's coded today, since it fails when the redirect is actually followed.

Then, as an optional config directive in keycloak, it would be great to allow the redirect too when performance isn't a concern for the redirect url lookup. This would allow the default keycloak to be spec compliant, and pass conformance tests by default. Then at the cost of performance and potentially security, the admin could adjust the behavior to allow the performance impacting redirect_uri lookup and allow the subsequent redirect to occur for particular clients.

**Comment by mposolda** [comment]
@peacepenguin This backwards compatibility switch is already done in latest KEycloak main. See the docs: https://github.com/keycloak/keycloak-documentation/commit/5a6a302d2f0bd068e9cc3f16377fff2bd9d7630c . Does it work to you or do you expect something different?

One concern is, that we plan to remove this (it's planned more as backwards compatibility switch).

**Comment by peacepenguin** [comment]
Yes the compatibility switch works. I'm now just suggesting it shouldn't be removed at all until the spec is further clarified, or it should even be enhanced to be a setting per client.

I really just have issue with the code comment: "backwards compatibility switch will be removed in some future version". 

As it's no longer a backwards compatibility switch. This was coded into keycloak between draft0/1, when for a short time "token_id_hint" was showing as required per the spec, when it was not previously required. Now the current draft 3 (soon to be 'final v1') of the spec has reverted again, where token_id_hint is NOT required, nor client_id. So the spec has flip-flopped on us, after the backwards compatibility switch was put in place.

So to me it's no longer a temporary compatibility thing, it's now a needed setting in order to remain compliant with the arguably vague spec as it exists today.

I'm thinking it would make more sense to have the compatibility switch GUI toggle per client, labeled as "allow post logout redirect when no token_id_hint nor client_id is given". This would allow keycloak to only have to search for matching redirect URL's on clients with that flag set. This would allow keycloak to be fully spec compliant, pass the OIDC tests by default, and it solves the theoretical performance issue of allowing keycloak to have to lookup redirect uri's across all its clients for a matching post_redirect_uri when that is the only param given.

**Comment by robertmx** [comment]
for me the compatibility switch does not work on keycloak 19.0.1. I still get the id_token_hint error when hitting the logout endpoint with just the `post_logout_redirect_uri` parameter.

**Comment by peacepenguin** [comment]
Looks like the OIDC Test Suite has been updated recently to include new tests for proper OIDC spec alignment - I'm going to run test suite 5.0.3 which includes the new tests against my Keycloak Pull request modified build and see if any behaviors fail. 

Once we confirm the OIDC test suite is final-spec-compliant, Keycloak can then either merge my pull request, or create a new approach to bring Keycloak into alignment to match the updated test suite and finalized logout spec.

For reference: updated test suite for logout issue was closed as completed, related commits have made it into the test suite 5.0.3:
https://gitlab.com/openid/conformance-suite/-/issues/1029

**Comment by peacepenguin** [comment]
The OIDC conformance tests still fail incorrectly against the Pull Request build. The oidc test suite issue has been re-opened:

https://gitlab.com/openid/conformance-suite/-/issues/1090

The points of contention of the OIDC Spec itself, vs the OIDC Test suite is this:

From the final OIDC spec:
> the OP MUST NOT perform post-logout redirection unless the OP has other means of confirming the legitimacy of the post-logout redirection target

From the current OIDC test suite code:
src/main/java/net/openid/conformance/openid/OIDCCRpInitiatedLogoutNoIdTokenHint.java
Line 18 incorrectly states:

"The OP must not redirect back and must either show an error screen or confirm with the user if they want to logout"

Clearly the OIDC test suite is still not interpreting the spec correctly. Keycloak for example has the ability to 'confirm the legitimacy of the post-logout redirection target' as defined in the spec. At the cost of performance, but at the benefit of being 100% spec compliant.

**Comment by mposolda** [comment]
@peacepenguin As we discussed 13 days ago (Comments https://github.com/keycloak/keycloak/issues/14010#issuecomment-1235115048 and https://github.com/keycloak/keycloak/issues/14010#issuecomment-1235695881), I think that when the `post_logout_redirect_uri` is sent alone (without both `id_token_hint` and `client_id`), Keycloak should by default either throw an error or ignore post_logout_redirect_uri. In your PR, I see that that user will need to confirm logout, but still, it will be allowed to redirect and verify the given `post_logout_redirect_uri` against all clients (as discussed before, this is concern for both performance and security). I don't think that this should be allowed by default.

As discussed above, Keycloak has backwards compatibility switch, which can be passed when starting Keycloak. For example:
```
bin/kc.[sh|bat] --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start-dev
```
When this is used, there is exactly the behaviour, which you want per my understanding. In other words, it is allowed to send just `post_logout_redirect_uri` alone and verify against all clients.

We originally planned to remove this flag, but we can possibly re-consider and keep it. That will allow the behaviour you want (as long as the flag is enabled when starting Keycloak). If we go this way, we can possibly:
- Close your current PR https://github.com/keycloak/keycloak/pull/14049
- Instead new PR can be sent to the documentation repository https://github.com/keycloak/keycloak-documentation . This section can be updated https://www.keycloak.org/docs/latest/server_admin/#_oidc-logout and the flag `legacy-logout-redirect-uri` can be documented. Still it will be good to add some warning in this docs that for performance and security reasons, it is recommended to avoid this flag and use `id_token_hint` or `client_id` when sending request to logout endpoint. Will this be OK to you?

**Comment by peacepenguin** [comment]
That sounds great. I think that would work well.

Thanks!

**Comment by peacepenguin** [comment]
@mposolda i've confirmed the flag is working well in production. And agree, we can close out pr 14049, and use this flag instead. Just a couple odd things about this flag and its documentation.

--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true

The documentation needs to be updated with both these actual outcomes of using the flag:
1. The flag allows the legacy URL query param:  redirect_uri  to be used by OIDC Clients during logout. (This is against the current OIDC Spec which says to use  post_logout_redirect_uri  instead, and thus, requires a special startup flag, this is good, for compatibility with old RP's coded to the old OIDC spec, and is well documented what it does)

2. The flag allows an OIDC Client to only send 'post_logout_redirect_uri' without id_token_hint nor client_id. (This brings keycloak in line with the actual current published spec, which does NOT require id_token_hint nor client_id to be provided during an RP-initiated logout. This functionality of the flag is not documented anywhere, except here in this issue report).

So item 1 makes perfect sense, and is already well documented. Item 2 is weird though, it's not documented that this behavior exists, and its odd that a 'compatibility flag' is needed to bring keycloak into alignment with the current-published-and-recently-finalized OIDC spec. And certainly this compatibility flag cannot be removed in v23 as its now required for full spec compliance.

Perhaps we move item 2's functionality into a separate startup flag like "--allowRPinitiatedLogoutwithOnlyPost-logout-redirect-uri=true" to remove the confusion of the compatibility flag's dual functionality. Then in v23 we can drop "redirect_uri", as that's allowed to be removed, since the spec removed that param entirely.

**Comment by cwchristerw** [comment]
I need to create new issue because when I login with using Identity Broker (realm B) to realm A and logout, Keycloak doesn't send client_id or id_token_hint and I'll get this `Missing parameters: id_token_hint`.

**Comment by mposolda** [comment]
@peacepenguin Sorry for late response. Closed your PR as discussed above as we're never going to allow by default to allow `post_logout_redirect_uri` parameter given alone (without at least one of `client_id` or `id_token_hint`) to trigger verifications against all realm clients.

I am adding to backlog to eventually look at the docs. On the other hand, it is still highly recommended for both security and performance reasons to avoid using the flags, but rather update your applications to use either `id_token_hint` or `client_id` parameters.

**Comment by mposolda** [comment]
@cwchristerw Your issue is something different than this one. I think it is in fact https://github.com/keycloak/keycloak/issues/10164 . Hopefully that one is fixed soon in Keycloak 22 (no promise).

**Comment by saravanpa-aot** [comment]
is this fixed ? Which version probably might have the fix?
