### ISSUE TITLE
Locale switcher is broken on error page

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#14025]
### Describe the bug

When switching locale on the error page the user is redirected to `http://localhost:8080/?kc_locale=no/`, and the locale is not changed.

### Version

main

### Expected behavior

User stays on the error page, which is switched to the selected locale

### Actual behavior

Redirects to `http://localhost:8080/?kc_locale=no/`

### How to Reproduce?

1. Fresh Keycloak installation
2. Enable internationalization for the realm
3. Open `http://localhost:8080/realms/master/nosuch`
4. Select a different language in the language drop-down
5. You should now be redirected to `http://localhost:8080/?kc_locale=no/`

**Comment by stianst** [comment]
The correct solution here is to handle the kc_locale switcher in https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/error/KeycloakErrorHandler.java correct (and also update the links). 

LoginActionsService shows how kc_locale is handled by the login UI:
https://github.com/keycloak/keycloak/blob/3c00dba8add782332dc7db9817d15f9f8ffa1a7f/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L270-L280

**Comment by stianst** [comment]
Previous attempt at fixing this here: https://github.com/keycloak/keycloak/pull/8702

**Comment by stianst** [comment]
Another attempt at fixing it: https://github.com/keycloak/keycloak/pull/8362

**Comment by stianst** [comment]
This is most likely also an issue on the info page

**Comment by mposolda** [comment]
@stianst Yes, I am aware that this is an issue on the info pages. And one side-note is, that in most cases, we don't have authenticationSession when the Info page is displayed (session was possibly already removed before due it was not needed to maintain the server state as the user cannot continue with the current authentication - sometimes he can click "Back to application"). I think we don't know the current user as well due to this (as the SSO session may not exist).

However it seems that locale cookie can be updated though.

**Comment by mposolda** [comment]
@stianst I am assigning to @douglaspalmer, who recently started to look at the similar issue (probably same cause as this one).

And it seems we should try to handle all those things at the same time.

**Comment by SamTV12345** [comment]
Is this issue really fixed? I have the problem that it does change in the url but not in the website. I'm on 20.0.1.
