### ISSUE TITLE
Spring Boot redirect URI does not include X-Forwarded-Prefix

### ISSUE THREAD

**Issue by StijnCaerts** [keycloak/keycloak#14077]
### Describe the bug

A Spring Boot application with Keycloak running behind a proxy would use the `X-Forwarded-*` headers to construct the correct URLs in responses. Spring Boot uses a `ForwardedHeaderFilter` to read these headers. It seems like Keycloak doesn't use this information to construct the `redirect_uri`parameter when a login is triggered. The `ForwardedHeaderFilter` isn't used yet when Keycloak will redirect to the login page.

### Version

12.0.4

### Expected behavior

Call to a proxied protected endpoint triggers a redirect with the correct `redirect_uri`

```http
GET /protected HTTP/1.1
X-Forwarded-Host: my.proxy.com
X-Forwarded-Prefix: /app/
X-Forwarded-Proto: https
```

Expected response:
```http
HTTP/1.1 302 
Location: https://my.keycloak.com/auth/realms/myrealm/protocol/openid-connect/auth?response_type=code&client_id=myclient&redirect_uri=https%3A%2F%2Fmy.proxy.com%2Fapp%2Fprotected
```

### Actual behavior

Call to a proxied protected endpoint doesn't use the `X-Forwarded-Prefix` when constructing the `redirect_uri`.

Actual response:
```http
HTTP/1.1 302 
Location: https://my.keycloak.com/auth/realms/myrealm/protocol/openid-connect/auth?response_type=code&client_id=myclient&redirect_uri=https%3A%2F%2Fmy.proxy.com%2Fprotected
```

### How to Reproduce?

Make sure `ForwardedHeaderFilter` is enabled by adding it manually or enabling the property `server.forward-headers-strategy=framework`.
Then send request using the `X-Forwarded-*` headers.

**Comment by mposolda** [comment]
Adding to Backlog as Spring adapters are low priority and Keycloak team won't have time to look at this in the near future. Anyone is welcome to look at this (after confirm that this is Keycloak bug and not incorrect usage/configuration mistake) and eventually send PR to fix this.

**Comment by JeroenAdam** [comment]
Could this be related?
https://keycloak.discourse.group/t/invalid-redirect-uri-for-valid-redirect-uris-with-https/3454/12

This is about a Spring Boot app and a proxy server for SSL termination.
During the 2nd redirect (token already obtained), Keycloak does redirect to http instead of https.
I'm having to change the url manually to https, then it works fine and for a long time in my browser.
But launching a private navigation window reveals the issue, Keycloak always redirects back to http instead of https.
I've tried many things as running Keycloak (v21) with start-dev --proxy edge (and without), no solution found.

**Comment by stianst** [comment]
Spring adapters have been deprecated for a long time, and will be removed in Keycloak 25. For more information look at https://www.keycloak.org/2024/03/keycloak-2400-released.html.
