### ISSUE TITLE
DefaultBruteForceProtector leverages a single thread to write success/failed events

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#14084]
### Describe the bug

https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/managers/DefaultBruteForceProtector.java uses a single thread/queue to update the database for success/failed login attempts.

The idea behind it is to prevent multiple concurrent writes to overwrite each-other. The problem with that though is most installation of Keycloak is leveraging a cluster with multiple nodes, which means this doesn't really do anything other than introduce a bottleneck. 

This is a follow-up to https://github.com/keycloak/keycloak/pull/7748, where it was observed that during both success and failed login attempts a wait of up to 5 seconds is introduced waiting for the queue to process the event. It can be questioned if this is a good idea or not for failed login attempts, but it certainly isn't a good idea to do this for successful logins. 

### Version

main

**Comment by stianst** [comment]
@mposolda @hmlnarik FIY

**Comment by mposolda** [comment]
@stianst Regarding the concurrent updates, in the old store based on infinispan, this should not be an issue already. In case that 100 concurrent threads calls `userLoginFailure.incrementFailures()`, then the final count should be really 100. No "lost update" should be possible. This applies to cluster and cross-dc as well. I am not sure if this is handled in the new store, but I guess it is (or should be possible)?

I see the possible benefit of the "worker thread" to reduce the count of updates to the model. As typically if attacker tries brute force, he will possibly done very big amount of login requests for same user in very short time (EG. 100 login requests every second to login user `john`). So I see that worker can queue the login attempts and then call `increase(100)` every second instead of have 100 separate calls to `incrementFailures()` as it is now. The current approach adds potential to DoS IMO and will be nice to improve it IMO.

However another option is, that we can possibly implement "the queue approach"  at the level of the store itself? In this case, we will likely implement just in the new store though? In that case, it will be fine to remove the thread from DefaultBruteForceProtector IMO.

**Comment by mposolda** [comment]
@stianst Yes, sure. Currently it doesn't add any value from DoS perspective. My point was if we want to add this capability and add support for something like `increment(100)`. In that case, it would makes sense to me to leverage the thread for implement this "queue approach".

But if we handle DoS with reverse proxy or Akamai, then I am all for removing thread. It is not needed at all for preventing concurrent writes as those are already handled at the model level (at least in the old store).

**Comment by mposolda** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.
It will be helpful if:
- You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
- If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it will be also welcome to close this issue
- If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.

**Comment by mposolda** [comment]
Removing from triage. This is tracked in the epic for review Brute force detection.
