### ISSUE TITLE
Inconsistent user locale

### ISSUE THREAD

**Issue by nuix-awilliams01** [keycloak/keycloak#14085]
### Describe the bug

If a user signs into Keycloak without modifying the selected locale, the user's locale will be switched to the default locale instead of the default locale for the browser.

### Version

18.0.2

### Expected behavior

The locale used on the sign in page should be used after authentication.

### Actual behavior

The users default locale is used after they authenticate

### How to Reproduce?

Steps to reproduce:
1. Open incognito/private browser window
2. Change language to non-default value
3. Sign into Keycloak
4. Close browser window
5. Open incognito/private browser window
6. Sign into Keycloak without modifying language selection 

### Anything else?

I was able to make a hacky work around by creating a custom theme and adding the following to the JS script section
```
document.getElementById('kc-form-login').action = document.getElementById('kc-form-login').action +  '&kc_locale=${locale.currentLanguageTag}'; 
```
The custom theme extended the keycloak theme and modified the action [here](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login.ftl#L9)

This issue also occurs for admin console.

**Comment by mposolda** [comment]
I am closing this as it is possible that this issue is already fixed in latest Keycloak 21. Please check with Keycloak 21 (which will be released relatively soon, likely later this week) and re-open if you can still reproduce it.

Also please update the description in that case as it is not clear what is the issue at all based on your description. For example the sentence `the user's locale will be switched to the default locale instead of the default locale for the browser.` looks very confusing to me as I don't know what locales exactly are you referring to for various steps.

For example please add:
- What is the application you are trying to sign in? Is it Keycloak account console or some different application in step 3? If it is Keycloak account console, please try to add what exactly is the user's language described in the account console (which is user preferred locale). Also what is the realm default language? What is prefered locale in the browser, which is sent in `Accept-Language` headers? And what languages you are trying to switch back/forth in the steps?
