### ISSUE TITLE
Cannot refresh RPT tokens

### ISSUE THREAD

**Issue by GithubUser8080** [keycloak/keycloak#14165]
### Describe the bug

When getting a normal JWT, and then exchanging it for an RPT using username password flow, the RPT contains a "refresh_token". Using this refresh token to get another RPT returns 

```
{
   error: "invalid_grant",
   error_description: "Session doesn't have required client"
}
```

Reproduce:

1. Get a bearer token

```
form data:

  grant_type=password
  scope=openid
  username=myusername
  password=mypassword
  client_id=my frontend client
```

2. Get an RPT

```
form data:

 grant_type=urn:ietf:params:oauth:grant-type:uma-ticket
 audience=my backend client
```

3. Try to refresh the RPT

```
form data

  grant_type=refresh_token
  refresh_token={the rpt.refresh_token}
  client_id=my frontend client
```

### Version

11

### Expected behavior

The RPT should be refreshed, and we should get an new RPT immediatelly

### Actual behavior

The reported error is displayed

**Comment by mabartos** [comment]
@GithubUser8080 Thanks for creating this issue. I see that you've specified the Keylcloak version 11 in this ticket. Have you tried to reproduce it with the latest version or the latest upstream code?

**Comment by GithubUser8080** [comment]
@mabartos i just tried it with a newer version and got the same. Is there an official documentation on how to use the refresh_token of an RPT? Thanks

**Comment by mabartos** [comment]
@GithubUser8080 Ok. Please, take a look at the official documentation for Authz services [1]. You should be able to find there everything related to this issue. You can also take a look at the code related to the error message [2]. Moreover, take a look at the particular test for the RPT refresh token [3].

I assume this issue is not a bug, as this is quite a common approach related to RPT for what tests are passing, and there wasn't any other issue report. However, I'll leave this ticket open, and if you don't manage to make it works, we can discuss other steps. WDYT?

Thanks!

[1] https://www.keycloak.org/docs/latest/authorization_services/index.html#_service_overview
[2] https://github.com/keycloak/keycloak/blob/173ff10141eb5407fac2b9606994e305ad909846/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L173-L184
[3] https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/authz/UmaGrantTypeTest.java#L402

**Comment by GithubUser8080** [comment]
Thank you for the information and the quick response. I think i found my issue 

If you get a token for public client A (my frontend) -> exchange for RPT with audience client B (backend) -> refresh RPT with client_id = A -> you get this error

If you get a token for secret client B (backend) -> exchange for RPT for audience B -> refresh with client B = it works.

Not sure if this is a bug or not. If that is expected, then we can close the issue

**Comment by momyyao** [comment]
@mabartos In my case, the client is the same but we are getting the same error response.  From my investigation, I see the following code in `TokenManager.validateTokenReuse`:
```
        int currentCount = clientSession.getCurrentRefreshTokenUseCount();
        if (currentCount > realm.getRefreshTokenMaxReuse()) {
            throw new OAuthErrorException(OAuthErrorException.INVALID_GRANT, "Maximum allowed refresh token reuse exceeded",
                "Maximum allowed refresh token reuse exceeded");
        }
```
By throwing the exception, `TokenManager.validateTokenReuseForRefresh` will detach the `clientSession` from `userSession`:
```
            try {
                validateTokenReuse(session, realm, refreshToken, clientSession, true);
                int currentCount = clientSession.getCurrentRefreshTokenUseCount();
                clientSession.setCurrentRefreshTokenUseCount(currentCount + 1);
            } catch (OAuthErrorException oee) {
                if (logger.isDebugEnabled()) {
                    logger.debugf("Failed validation of refresh token %s due it was used before. Realm: %s, client: %s, user: %s, user session: %s. Will detach client session from user session",
                            refreshToken.getId(), realm.getName(), clientSession.getClient().getClientId(), clientSession.getUserSession().getUser().getUsername(), clientSession.getUserSession().getId());
                }
                clientSession.detachFromUserSession();
                throw oee;
            }
```
As a result, any refresh token request with the same refresh token will result in the "Session doesn't have required client" error.
Since `realm.getRefreshTokenMaxReuse()` is coupled with `realm.isRevokeRefreshToken()`.  Should you check for the flag as well in  `TokenManager.validateTokenReuse`?

**Comment by belinde** [comment]
Could it be related to https://github.com/keycloak/keycloak/issues/15330?

**Comment by mabartos** [comment]
@mposolda @pedroigor Guys, do you know any more details if it's a real issue or not? Thanks

**Comment by pedroigor** [comment]
Sorry for the late reply. It is not an issue as public clients can refresh tokens (RPT).

**Comment by GithubUser8080** [comment]
> Sorry for the late reply. It is not an issue as public clients can refresh tokens (RPT).

The reported issue is that they can't, if the RPT is for an audience of a secret client. Was this fixed, or is it intended? Thank you

**Comment by GithubUser8080** [comment]
The use case is that the frontend requests an RPT to communicate with a backend protected with RPT permissions, so we are required to get an RPT from the frontend (public) client, do our calls, then eventually refresh it to continue the communication.

**Comment by pedroigor** [comment]
@GithubUser8080 I mean this https://github.com/keycloak/keycloak/pull/23394. I'm sending that test because I did not find a specific one using a public client to refresh tokens.

If you are still using version 11, please check in latest versions.

**Comment by pedroigor** [comment]
Please, let me know if the test case from https://github.com/keycloak/keycloak/pull/23394 covers the reported use case.

There is a separate issue though about the audience not being set after a token refresh. I'll create an issue for it.

**Comment by GithubUser8080** [comment]
@pedroigor Thank you, i just tried on a new keycloak installation and it works! The audience for the token that is given after refresh is not the original confidential client provided in "&audience=backend" however, but "account", if that is the issue you are referring to.

**Comment by pedroigor** [comment]
Thanks, I've created https://github.com/keycloak/keycloak/issues/23399.
