### ISSUE TITLE
Password Blacklist false positives

### ISSUE THREAD

**Issue by skhro87** [keycloak/keycloak#14386]
### Describe the bug

I have Keycloak version `18.0.0` running, using this blacklist:
https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt

When trying to reset a password, the following passwords are consistently refused as blacklisted even though they are not on the blacklist:
```
qJ9BsBnZXTuefUDK360HcD64
Wt6%CK%pki%bCLGm76xpP39r
```

I have tried several times, in 3 independent different deployments, with the same result.
The issue occured since version `12.0.4`

I have found this issue:
https://github.com/keycloak/keycloak/issues/8982
But I don't think it is related, since the issue discusses random probability, while my problem is consistent refusal of above passwords.

### Version

18.0.0 (but the issue occured since 12.0.4)

### Expected behavior

Passwords like below should not be blacklisted when using the blacklist below.

Blacklist:
https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt

Passwords:
```
qJ9BsBnZXTuefUDK360HcD64
Wt6%CK%pki%bCLGm76xpP39r
```

### Actual behavior

Passwords are blacklisted:

```
Error! Invalid password: password is blacklisted.
```

### How to Reproduce?

1. Setup Keycloak version `18.0.0`

2. Add blacklist:
https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt

3. Add blacklist to password requirements

4. Try to reset user password with one of the following:
```
qJ9BsBnZXTuefUDK360HcD64
Wt6%CK%pki%bCLGm76xpP39r
```

**Comment by lz101010** [comment]
> I have found this issue:
https://github.com/keycloak/keycloak/issues/8982
But I don't think it is related, since the issue discusses random probability, while my problem is consistent refusal of above passwords.

This is in fact related, because as it states there in #8982:

> bloom filter [...] is super efficient [...] at the cost of the occasional false positive

The "occasional false positive" is occasional in the sense that for a given set of passwords, the bloom filter will incorrectly determine that some of those passwords are weak. And for those specific passwords, it will always determine that they are weak.

It's not occasional in the sense that for a given password the bloom filter will sometimes determine that it's weak.

---

So what now? As you can see in the [fork](https://github.com/bkuker/keycloak/commit/52f4c8ac40042b390e0e3f47afe6a605e0d68ea2) referenced in #8982, the false positive rate is configurable at the cost of more memory (by internally adapting the bloom filter to use more hash functions).

A more modular approach would be to write an extension that makes this value configurable via environment variables.

**Comment by sschu** [comment]
This PR should help: https://github.com/keycloak/keycloak/pull/14411

**Comment by rmartinc** [comment]
Yep, this is a duplicate of #8982.

**Comment by skhro87** [comment]
Thanks, indeed it is a duplicate.
Closing for now, and I hope the PR can be merged soon.
