### ISSUE TITLE
Make the domain part of the urls in emails configurable

### ISSUE THREAD

**Issue by Fristi** [keycloak/keycloak#14513]
### Description

The domain of the urls in emails is set to the same domain the admin console is accessed by. Allow to override this by an configuration option in the admin it self

### Motivation

The domain part of the urls in emails like resetting the password is derived from the context you are in. For example if you create a user in the admin console and send the user a password reset, the domain of the url is set to the same domain the admin console is accessed by. This causes trouble for us because we run the admin console via protected url which is only accessible via VPN and not for front facing users.

Therefore the request to make this url configurable

**Comment by stianst** [comment]
Have you configured the hostname settings for Keycloak? See https://www.keycloak.org/server/hostname

The URL in emails should be the frontend URL, and not the admin URL, if you are exposing the admin console/endpoints through a different URL.

**Comment by Tristan971** [comment]
> The URL in emails should be the frontend URL

This causes some issues, notably that then a realm can only be logged into through that host, due to the login form using the frontend URL as submit URL rather than the context one.

This means that you can then only login via the public hostname, and thus you couple your auth system to your public ingress (which isn't really ideal...)

**Comment by lanormerh** [comment]
@Fristi I have the same use case. You marked it as completed. Did you manage to make it work?
