### ISSUE TITLE
Admin event not have id in representation afrer change First & Last name

### ISSUE THREAD

**Issue by zavndw** [keycloak/keycloak#14704]
### Describe the bug

After editing First or Last name the user, in the admin event not have id user in representation

### Version

19.0.2

### Expected behavior

have id user in representation and its attributes, this behavior was in version 17, 18

### Actual behavior

Created admin event not have id in representation and not have user attributes

### How to Reproduce?

change First & Last name users

**Comment by lxmnk** [comment]
User representation if `firstName` changed (`id` and `attributes` missing):
```json
{
  "username": "test.user.1",
  "enabled": true,
  "emailVerified": true,
  "firstName": "Test",
  "lastName": "User",
  "email": "test.user.1@test.com",
  "requiredActions": []
}
```

User representation if any attribute changed:
```json
{
  "id": "0e663c40-a32d-4d0e-99cb-fe7b6cba3ec8",
  "createdTimestamp": 1664794557498,
  "username": "test.user.1",
  "enabled": true,
  "totp": false,
  "emailVerified": true,
  "firstName": "Test",
  "lastName": "User",
  "email": "test.user.1@test.com",
  "attributes": {
    "foo": [
      "bar"
    ]
  },
  "disableableCredentialTypes": [],
  "requiredActions": [],
  "notBefore": 0,
  "access": {
    "manageGroupMembership": true,
    "view": true,
    "mapRoles": true,
    "impersonate": true,
    "manage": true
  }
}
```

**Comment by rmartinc** [comment]
Hi @zavndw!

The UserRepresentation in the event is what the server received in the endpoint. I mean, if the endpoint receives a full user to update it puts the full user rep, but if the endpoint receives just a few attributes to update only those attributes are set in the admin event. If you see [the code](https://github.com/keycloak/keycloak/blob/19.0.2/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L201) the representation added to the event is what it's received. This has not changed in version 19.

I think that, in your case, the issue is the new admin console. It just sends those few attributes in the Details tab, and more attributes in the attributes tab. If you change to the previous console you will probably see the same data as before.

Don't know what to think. This is working exactly as before. In general you cannot trust the data in the representation because it's just what it was received at the endpoint level (the data requested to be updated).

Hope it helps!

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now.
