### ISSUE TITLE
Keycloak.v2 build tools and documentation

### ISSUE THREAD

**Issue by maartenraes** [keycloak/keycloak#14801]
### Description

Keycloak v19.0.0 introduced theming support from scratch, starting from the folder `keycloack.v2`
We however noticed the usage of old and deprecated build tools and documentation seems to be missing on general usage and implementation. 

- `npm audit` finds 17 vulnerabilities, of which 7 of high severity.
- It also reveals that some quite old versions of dependencies are used, eg 2 years old `snowpack` and `rollup-plugin-postcss` versions (both part of the vulnerabilities).
- Is there a reason that `react-scripts` is not used and older and less popular build-tools are favoured? 
- The usage of `npm:@pika/react@^16.13.1`; pika is no longer maintained and it seems odd that the new way of providing Keycloak themes is using an strongly outdated version of `react`

Is there any information about the future roadmap of theming support, is there a new template in progress that would be released in a future version? 
If we would like to implement enhancements and provide pull-requests to update these dependencies, are there any guidelines that we would have to comply with or a general direction what the plans are with this theme? 

### Discussion

https://github.com/keycloak/keycloak/discussions/11598

### Motivation

The DX is currently below standard to develop a custom theme for Keycloack. 
Security vulnerabilities are a possible issue when using deprecated and/or old build tools and packages.

**Comment by ssilvert** [comment]
Hi @maartenraes.  The `keycloak.v2` version of account console is actually more than 2 years old.  It has not been maintained as well as I would have liked because we had to concentrate on the new admin console.

We are currently in the process of updating the account console code and the toolchain to match what we are using for the new admin console.  There is an initial PR here: https://github.com/keycloak/keycloak-ui/pull/3410

Suggestions and comments are welcome.
