### ISSUE TITLE
[JS Adapter] Usage of 'Keycloak' as type is wrongly marked as deprecated

### ISSUE THREAD

**Issue by Undestor** [keycloak/keycloak#14871]
### Describe the bug

Importing 'Keycloak' from 'Keycloak-JS' and using it as a type will result in a deprecation warning:

e.g.
```
import Keycloak from "keycloak-js";

let keycloak: Keycloak
```
results in a deprecation warning: 'Construct a Keycloak instance using the `new` keyword instead.'

### Version

19.0.2

### Expected behavior

'Keycloak' can be used as a type without a deprecation warning

**Comment by lexcao** [comment]
Hi, 
There is the same keyword named `Keycloak`.
One is the function and the other is the class.

https://github.com/keycloak/keycloak/blob/f80a8fbed0940f28e8a23ebcdc5469c7299c0457/adapters/oidc/js/dist/keycloak.d.ts#L357-L363

I have not reproduced this on my IntelliJ IDEA.
<img width="390" alt="image" src="https://user-images.githubusercontent.com/14901139/195597257-ccf7eec7-7db4-4a1a-85bf-6b947b6256dd.png">

Could you please provide more info on this?
Such as typescript version, IDE ...

**Comment by Undestor** [comment]
Hi,
yes, but since the function and class have the same name, its seems that the static code analysis cannot differ between them.
![image](https://user-images.githubusercontent.com/2678459/195616147-3f140c52-44b4-4644-abc3-c1fefbf460f5.png)
![image](https://user-images.githubusercontent.com/2678459/195616293-19deb389-d78e-4928-8a33-4e230a26adfb.png)

Typescript version: 4.5.5
IDE: VSCode, 1.72.0

The Sonar Analysis also shows an error because of the deprecation. So i don't think its related to the IDE

**Comment by jonkoops** [comment]
This must be something that was fixed some time ago as I cannot reproduce this issue. For me the type doesn't show as deprecated unless it's actually used in a deprecated manner:

![](https://user-images.githubusercontent.com/695720/228818657-2a8dde43-da0a-460b-8f4e-432d645b9b62.png)

See my [example code](https://stackblitz.com/edit/typescript-xnes17?file=index.ts1).

I'm going to consider this resolved, likely this was a but in TypeScript that has since been fixed. If this still occurs let me know and I will re-open the issue.
