### ISSUE TITLE
Weird export/re-import behaviour regarding `post.logout.redirect.uris`

### ISSUE THREAD

**Issue by famod** [keycloak/keycloak#14884]
### Describe the bug

We started seeing invalid redirect uri errors during logout in some of our environments.

I found out that the erroneous ones were missing the `+` setting in `post.logout.redirect.uris` / `Valid post logout redirect URIs`.
These environments don't use our realm import optimization (which we only use for dialy dev support to swiftly spin up a fresh KC container).
The dev environments which do use that import were not affected.

That's when I found a weird behaviour:
- bootstrap a fresh KC container and populate our realm with our (slow) script that executes `kcadm.sh` many times
- check admin console (v2): custom client does *not* have the `+` setting!
- export the realm via `kc.sh export --file  ... --users same_file`
- check the exported json: `post.logout.redirect.uris` is missing entirely for the custom client (consistent with what you see in UI)
- throw away the container and its database
- bootstrap a fresh KC container but this time let it import the previously exported file (via `--import-realm`)
- check admin console (v2): custom client *now does* have the `+` setting!
- export the realm and check the json: the custom client now has `"post.logout.redirect.uris": "+"` (consistent with what you see in UI)

Why is the `+` added on realm import?
Or coming from the opposite side: Why isn't it there from the beginning?

This effect is the reason why we found the problem so late on our non-dev environments; every dev was using the import and logout was fine there...

### Version

19.0.3

### Expected behavior

Consistent handling of the `+` setting, symmetric Import/Export.
To have a working logout OOTB I'd say `+` should be the default/initial value but I'm probably missing something.

### Actual behavior

Asymmetric import/export; `+` is added during import for unknown reasons (maybe because realm imports from older KC versions shall receive `+` automatically?)

### How to Reproduce?

See description.

### Anything else?

cc @mposolda @tgerakitis

**Comment by famod** [comment]
Btw, I was able to create the client with the `+` setting by adding `-s 'attributes={"post.logout.redirect.uris":"+"}'` to the `kcadm.sh create clients` call.

**Comment by reda-alaoui** [comment]
I have the same issue. All my clients are created by api calls to `realms/{realm}/clients-registrations` endpoint, so not caused by the UI I guess.

**Comment by reda-alaoui** [comment]
Just found https://github.com/keycloak/keycloak/issues/10135
I make my client add `post.logout.redirect.uris` to the request payload:
```json
{
  "attributes": {
    "post.logout.redirect.uris": "+"
  }
}
```

**Comment by douglaspalmer** [comment]
This comes down to 2 conflicting design decisions we wanted to allow clients to not set any valid post logout redirect URIS and, for backwards compatibility we wanted to add '+' to old clients so that they performed as they used to.

I think the best way forward is to use Redirect URIs whenever Post Logout Redirect URIs aren't set.

**Comment by mposolda** [comment]
@douglaspalmer +1. The info about `-` can be added to the tooltip message for the related to the `Post Logout Redirect URI` in the admin console .

Also I've just figured that we don't have documentation about this switch`Post Logout Redirect URI` here: https://www.keycloak.org/docs/latest/server_admin/index.html#con-basic-settings_server_administration_guide and mention that  . It might be good to add the documentation about this switch and mention about `+` and `-` semantics for this.

**Comment by sschu** [comment]
Could there be a case where you actually don't want to allow any post_logout_redirect_uris? Entering some invalid String like "-" instead of just none does not feel right to me. I am also wondering how many people are actually using the same or different URIs for redirect and post logout redirect. If everybody was using the same anyways, separating the two would not have made that much sense. So assuming people use different URIs, I think the current design is fine. Maybe not adding the "+" on import is the right way to go. I assume you don't know which version an export was created with anyways - so adding a "+" might actually be a problem if it was exported from a current version and no post logout redirect uris should be valid.

**Comment by mposolda** [comment]
@sschu Most people likely use same "redirect URIs" for login and logout and Keycloak always historically worked that way. 

There can be rare cases where you want different set of URIs and also it is possible that some clients don't need any Post Logout Redirect URIs at all (after logout triggered by this client, Keycloak will simply display the info screen `You are logged-out` instead of redirecting back to the client). Also OIDC specification treats these as 2 different set of URIs.

On the other hand, there were not much requirements from the community to separate redirect urls for login and logout.

Due the fact that it is not easily possible to cover all the corner cases with nice backwards compatibility behaviour, I am more inclined to just fallback to `Valid Redirect URIs` in case that `Post Logout Redirect URIs` are not set, which should help to avoid issues similar to this one. For those rare cases where people want different set of URIs or not Post Logout Redirect URIs at all, they can use `-` as special value, which seems completely fine to me as we already have `+` as "special meaning value". We may need to add this tooltip to `Post Logout Redirect URI` and also document it.

**Comment by mposolda** [comment]
@sschu yes, I also think the latter case happens much more rarely. So yes, I would consider nothing and `+` to be defacto the same thing.

**Comment by sschu** [comment]
I agree, adding another migration is probably not enough bang for the buck.

**Comment by douglaspalmer** [comment]
https://github.com/keycloak/keycloak/pull/15298
