### ISSUE TITLE
Add EdDSA/Ed25519 to WebAuthn Signature algorithms

### ISSUE THREAD

**Issue by devnull09** [keycloak/keycloak#15000]
### Description

Currently, the supported Signature algorithms for WebAuthn only include the ECDSA options with the mandatory but controversial NIST curves. https://en.wikipedia.org/wiki/Elliptic_Curve_DSA#Concerns

With an increasing number of authenticators supporting EdDSA/Ed25519 for WebAuthn, this would allow for an alternative fallback algorithm if implemented in keycloak.

https://www.w3.org/TR/webauthn/#typedefdef-cosealgorithmidentifier

### Motivation

Avoiding the security concerns listed here: https://en.wikipedia.org/wiki/Elliptic_Curve_DSA#Concerns

Additionally, with an increasing use of WebAuthn/Fido2, a fallback algorithm should be provided in case of future vulnerabilities due to implementation mistakes or cryptological findings.

**Comment by Iodun** [comment]
I am currently trying to connect my Keycloak with an OpenLDAP for user federation which uses Ed25519 certificates.

With **spi-truststore-file-hostname-verification-policy=ANY** I get the following error:
`javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: 1.3.101.112`

With **spi-truststore-file-hostname-verification-policy=WILDCARD** I get the following error:
`java.security.InvalidKeyException: cannot identify EdDSA public key`

I think the problem is that the official Keycloak 19 and 20 docker images are still using JDK 11, which does not support Ed25519.
According to the latest Keycloak 20.0 release JDK 17 is now officially supported:
https://www.keycloak.org/2022/11/keycloak-2000-released

Is my problem related to this issue here or should I open a new issue?
And are my assumptions actually correct?
