### ISSUE TITLE
E-mail accounts validation during the registration process

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#15024]
### Describe the bug

During the registration proccess an user is able to register herself with the same username as the email ID of another existing user. We should prevent that from happening.

## Workaround

- Enable "Email as username" flag or disable "Login with email" in the login settings

### Version

>= 19.0.3

### Expected behavior

- Not allowing the registration of an e-mail as username if it's already associated with an existing user.

### Actual behavior

- Allowing the registration of e-mail as username with the same e-mail ID of an existing user.

### How to Reproduce?

1. Register a user with username `test` having `test@test.com` as e-mail
2. Register another user with username `test@test.com`

**Comment by Vividious** [comment]
I don't know if that's enough in this case but I've created PR with the propose solution.

**Comment by hmlnarik** [comment]
The core of this bug is to ability for clash of username and email addresses when login with email is enabled.

Thus I would question the validity of the expected behaviour:

> Not allowing the registration of an e-mail as username if it's already associated with an existing user.

How would that help in the following situation:

1. User `a` registers with email `admin+mydomain@example.com`
2. User `admin@example.com` registers with email `admin@evil.example.com`
3. User `a` changes their email to `admin@example.com`

This creates ambiguity as of which user would be logged in when `admin@example.com` is entered as a username, which in turn fails to meet the expectation of not creating a clash of username and email.

Therefore I would not consider this bug resolvable until we find more proper solution.

One of the solutions would be e.g. _when a username contains `@` sign, it is never matched against username_. There may be others.

**Comment by abstractj** [comment]
@keycloak/core, could you please update the milestone if not accurate?

**Comment by rmartinc** [comment]
@abstractj I have tested this with current main and I cannot reproduce. I suppose all the changes for User Profile have fixed it. If nobody says something different I will close this as already fixed.

**Comment by pedroigor** [comment]
@rmartinc I agree the issue, as described here, should not happen at all.

When e-mail as user name is enabled, there are validations to prevent creating/updating users if the e-mail is already bound to another user. Also, the username is updated to match the e-mail so they are the same.

There are situations where you can end up in a similar situation like when allow duplicate e-mails. But even in this case, the authentication should fail with the given message:

```
Multiple users with email 'alice@myrealm.org' exist in Keycloak.
```

However, you can end up in a situation where you register a user with `victim@myrealm.org` as the username where the e-mail `victim@myrealm.org` is bound to another user as an e-mail. In this case, if the `Login with email` is disabled you will end up authenticating using the account for the attacker as hist username is `victim@myrealm.org`.

Not sure if this is an issue because they are indeed different accounts but it does bring a lot of some confusion. Perhaps this is what this issue is mainly about.

Perhaps we can think on some approaches to mitigate this from happening?

**Comment by abstractj** [comment]
> However, you can end up in a situation where you register a user with `victim@myrealm.org` as the username where the e-mail `victim@myrealm.org` is bound to another user as an e-mail. In this case, if the `Login with email` is disabled you will end up authenticating using the account for the attacker as his username is `victim@myrealm.org`.
> 
> Not sure if this is an issue because they are indeed different accounts but it does bring a lot of some confusion. Perhaps this is what this issue is mainly about.
> 
> Perhaps we can think of some approaches to mitigate this from happening?

@pedroigor @rmartinc what Pedro mentioned is possible. Added to that, there's a chance of users being locked outside the server considering that e-mails are public knowledge. For example, with login with e-mail enabled:

1. Ricardo registers himself as ricardo@keycloak.org
2. Pedro registers himself using ricardo@keycloak.org and attempts to brute force Keycloak
3. Ricardo is locked outside the server.

**Comment by rmartinc** [comment]
@abstractj But in step 2 Pedro woud receive a `Email already exists.` if the the realm is not configured to allow duplicated emails (duplicated emails is only configurable if login with email is disabled), or am I wrong?

**Comment by abstractj** [comment]
> @abstractj But in step 2 Pedro woud receive a `Email already exists.` if the the realm is not configured to allow duplicated emails (duplicated emails is only configurable if login with email is disabled), or am I wrong?

@rmartinc you are correct Ricardo, I experimented it with multiple scenarios, and I wasn't able to reproduce the issue anymore. From my pov, we can close the issue.

@pedroigor do you have anything that you would like to add? Would be ok to close it?

**Comment by abstractj** [comment]
@rmartinc @pedroigor closing it based on our discussion.
