### ISSUE TITLE
Doublecheck if real FIPS host available in GH actions

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#15069]
Currently we emulate testing FIPS on GH actions. This is done by using same java security file with same security providers and configuration as is used on the real FIPS host (RHEL 8.6 FIPS enabled host with FIPS enabled OpenJDK). However it can be better if we can directly test on the FIPS enabled host with FIPS enabled JDK if possible.

It is possible that Fedora has some FIPS images, which can be directly consumed by GH actions. This needs to be investigated...

**Comment by mposolda** [comment]
It will be nice if we manage to test on RHEL on GH actions (see #12422), but not 100% sure if it is possible.

**Comment by stianst** [comment]
There's [UBI](https://access.redhat.com/articles/4238681) images, and ability to run [jobs within a container](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container).

That should in theory work assuming we can instruct the container that it should start in FIPS mode, while it's not running on a RHEL host in FIPS mode.

**Comment by stianst** [comment]
@miquelsi FIY as this is related to RHEL8/9 testing on GitHub Action.

**Comment by rmartinc** [comment]
Investigation:

-  When enabling FIPS fedora/rhel peforms two things: enabling FIPS crypto profiles for different softwares (nss, java, openssl,...) and adding a kernel option `fips=1` to boot/initrd.
- The kernel option (besides I suppose more things) creates a `/proc/sys/crypto/fips_enabled` file set to `1`. This is the flag that everything else is looking to see if the system is fips enabled.
- In the case of Java it checks that file (it really relies on nss, but it finally checks it) and, if configured, it changes the configuration to be FIPS (it can be disabled with a system prop even when the file is `1`). The crypto policies also enforces more restrictive security options that are imported to the configuration.
- So, in order to use fips in java OOTB, we need a kernel with the fips option enabled at boot. Regarding docker/podman both rely on the host, if the container runs on a fips enabled kernel host, the flag is inherited and fips is also enabled in the container. The container must be a fips capable system like fedora or rhel.
- Using github actions the linux host is ubuntu which is never going to be fips enabled. This point blocks common configuration and using a fedora/rhel container does not matter. We can execute `fips-mode-setup` command but it is never going to able to add the boot option. So a workaround is needed to use github-actions.
- There are some workarounds we can do to enable/simulate fips. I have tested some of them but I think that the most real is adding the flag file. This [simple project](https://github.com/rmartinc/github-actions) performs it. The ubuntu host that github gives has everything we need to compile a fake kernel module that creates the `fips_enabled` file (just that, nothing more is done). We can compile the module and execute `insmod` in the action. After that a fedora docker for example can be started and be fully configured to be FIPS compliant (being java, all the Java is fully configured to be FIPS although the kernel is a fake). Check the [ci.yml](https://github.com/rmartinc/github-actions/blob/main/.github/workflows/ci.yml). A final step adds [an entrypoint](https://github.com/rmartinc/github-actions/blob/main/.github/scripts/run-fedora.sh) that installs the needed packages on fedora, executes the `fips-mode-setup` and run the maven. The sample project just ensures the proc file is `1` and the java is using a FIPS `SecureRandom` implementation.

I'm checking right now how the CI for keycloak works in this setup (ubuntu host + fedora container).

**Comment by mposolda** [comment]
@rmartinc Thanks again for this nice analysis! As we discussed yesterday, it can be nice to use UBI/RHEL instead of Fedora in the "final" version of this PR. See comment above from Stian for some details about UBI. We are targeting newest RHEL 9 (or UBI-9). This will allow us to resolve also #12422 at the same time with this issue.

IMO we don't need to care much about jenkins pipeline, GH actions is sufficient IMO.

We can hopefully switch both "FIPS UT" and "FIPS IT" runs to this instead of running them on Ubuntu as it is today.

**Comment by rmartinc** [comment]
Initial PR sent: https://github.com/keycloak/keycloak/pull/16973
