### ISSUE TITLE
Docker deployment example is not working as HTTPS is required

### ISSUE THREAD

**Issue by hahahannes** [keycloak/keycloak#15084]
### Describe the bug

Hi!

When following the steps from the Docker tutorial [https://www.keycloak.org/getting-started/getting-started-docker](https://www.keycloak.org/getting-started/getting-started-docker), you will not be able to access the admin console as HTTPS is required. 

### Version

19.0.3

### Expected behavior

Access to the admin console as described in the tutorial

### Actual behavior

`HTTPS required` error message.

### How to Reproduce?

```
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.3 start-dev
```

### Anything else?

As discussed in #15018 #14666, HTTPS should be enforced in production mode but can be disabled in proxy mode. I guess, it would make sense to either inlcude certs in the example or to enable proxy mode.

**Comment by stianst** [comment]
By default Keycloak requires HTTPS to be enabled for external IP addresses, if you access Keycloak with an internal IP address this is not required and the example is working just fine.

**Comment by hahahannes** [comment]
Thank you very much for the information! I just thought that the getting started might be outdated. Because when I run the docker run command and access `http://localhost:8080/admin`, as described by the guide, a `HTTPS required` message is shown

**Comment by stianst** [comment]
Hm, If you access it via `http://localhost:8080` it shouldn't require HTTPS. That works fine for me, does `localhost` translate to some different IP address or something on your end?

**Comment by thorastrup** [comment]
I know this is an old issue, but i had the same issue where running the following always ended in `HTTPS required`:

```shell
docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.2.5-0 start-dev
```

I "solved" the issue, but updating my docker daemon (maybe a restart would have been enough though), and restarted.. this fixed the issue. Not sure why this occured to begin with though, since i didn't have issues with it earlier (same day).. so i blame docker and maybe Apple as well, since I am on a MacOS machine... some weirdness with the docker network at least
