### ISSUE TITLE
MapStorage: Provide query names as hint for custom implementations which are not able to directly translate QueryParameters

### ISSUE THREAD

**Issue by dominikschlosser** [keycloak/keycloak#15345]
### Description

We are currently developing an Apache Cassandra based implementation of MapStorage. Cassandra uses a "query first" approach to data modeling, which means that the data model is designed with all possible queries in mind.
The new generic approach inside of MapStorage ("QueryParameters" and "ModelCriteriaBuilder") assumes that all storage implementations are able to translate such dynamic queries to database queries.

Since in reality there is a limited amount of actual queries, we suggest to add a "query name hint" to the relevant operations (read and delete with parameters) in MapKeycloakTransaction. This would allow us to better map the query to a predefined query and table in cassandra.

If you support this idea, we could contribute the change ourselves aswell.

### Motivation

Support a more diverse range of storage implementations.

**Comment by dominikschlosser** [comment]
> Cassandra integration would be great addition to Keycloak. Are you planning to share your project to public? Contribute your code to Keycloak or put it to some public repo?

We plan to release it as a standalone extension, independent of core Keycloak. We are currently still struggling with problems like the one described here. An alternative we are looking at is to replace the logic layer within the storage, i.e. UserProvider, RoleProvider, etc. 
This way we don't have the described problem with the QueryParameter, but we move on an unsupported (?) path.

> There also people asking for more flexibility in query processing which means down the road, queries might not be that predictable anymore.

There is already flexibility, especially in the Admin Console (Dynamic Search). With the Cassandra implementation come a few restrictions that we are aware of. The query-first approach prevents absolute flexibility in queries.
However, especially for the "hot path", i.e. during a login process or when issuing tokens, I can't imagine too much flexibility at the moment.

**Comment by hmlnarik** [comment]
Thank you for the offer to contribution.

For the time being, a query can have its name determined from the `ModelCriteriaBuilder`, say a `realm_id=? and user_id=?` would correspond to `userById`. However the ability to extend the queries should be perserved to allow further extension of Keycloak features without need to touch the base store layer, and for that reason the query names should be not predefined.

Yet there is a possible intermittent solution: for any storage implementation in the need to enumeration can implement a method (say `getAlias`) of its `ModelCriteriaBuilder` to return an alias (say `userById`) of its instance, when known, or throw an `CriterionNotSupportedException` otherwise.

In tree store, there is a need for revamped `DefaultModelCriteria` where this logic could be plugged into. This might be considered in the future, and I will check if I can easily push the changes to `DefaultModelCriteria` that could help in this effort.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
