### ISSUE TITLE
Clarify supported version(s) of PostgreSQL

### ISSUE THREAD

**Issue by dalbani** [keycloak/keycloak#15411]
### Description

The documentation at https://www.keycloak.org/server/db#_supported_databases specifically mentions that PostgreSQL version 10 is supported.
I'm wondering though if this actually means 10 *and above*.
If I look in the codebase and at the integration tests in particular, I see many references where the Docker image `postgres:latest` is used (which is version 15 at the time of writing).
For example in code:
- https://github.com/keycloak/keycloak/blob/main/.github/workflows/ci.yml#L369
- https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java#L97
- https://github.com/keycloak/keycloak/blob/main/testsuite/model/src/test/java/org/keycloak/testsuite/model/parameters/JpaMapStorage.java#L62
- https://github.com/keycloak/keycloak/blob/main/operator/src/main/resources/example-postgres.yaml#L19

But also in the documentation:
- https://github.com/keycloak/keycloak/blob/main/docs/tests-db.md
- https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/other/jpa-performance/README.md

So, given that all the tests pass, i suppose that version 15 *is* compatible in practice.

Still, I'm curious what you think of the current setup, and if it would be good idea to use an explicit version instead of `latest`. And, even better, to run the tests for several versions of PostgreSQL.

Or, after all, Keycloak uses such a basic set of SQL/JPA features that there's no reason to make it more complex than it is currently implemented?

**Comment by dalbani** [comment]
It's interesting to note by the way that the codebase tends to use specific versions when it comes to MariaDB.
As in:
- https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/src/main/java/org/keycloak/it/junit5/extension/DatabaseContainer.java#L98
- https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/pom.xml#L165

**Comment by radiodup** [comment]
I've done a test with kc 16.1.1 and pg 14.6
https://github.com/keycloak/keycloak/issues/10767
Not a developer nor associated to the project.
I think, we could publish result test for different versions. 
I would like to get a performance test, to reduce deployment risk, but that should be covered by application testing,

**Comment by ahus1** [comment]
This has been updated for the upcoming version Keycloak 22: The current main branch is tested with PostgreSQL 15 explicitly. The version we test with is documented in the root pom.xml file, and will also be published in the docs once they have been released: 

https://github.com/keycloak/keycloak/blob/main/pom.xml#L139-L149

The next release will show something like the following: 

![image](https://github.com/keycloak/keycloak/assets/3957921/5b1dc665-948d-4e5c-a169-f45bbda83cd4)

The docs are clear in this regard: Keycloak supports PostgreSQL, and we test on a (now recent) version, and publish this in our docs. What remains is that we still test only one version of PostgreSQL with Keycloak. This might be tackled in #21350

If someone wants to test a different version, they can fork this repository, change the version in the pom.xml and run the tests on their own environment or via GitHub actions. 

The one thing that will be tackled in this issue is that some configurations in https://github.com/keycloak/keycloak/blob/main/quarkus/tests/integration/pom.xml don't use the container versions specified in the root pom.xml
