### ISSUE TITLE
Process to add Custom Image using DockerFile

### ISSUE THREAD

**Issue by kvishal2203** [keycloak/keycloak#15423]
### Area

admin/ui

### Describe the bug

HI,

I want to add custom UI file on the docker image but i couldn't find docker image anywhere. Please help me with the docker image or alternative approach to do the same.

### Version

20.0.1

### Expected behavior

Our own custom theme has to be published on the startup page.

### Actual behavior

It's Running on its own UI.

### How to Reproduce?

Adding custom files either to image or alternate approach

**Comment by lexcao** [comment]
Hi, @kvishal2203 
For the docker image? There may be some misunderstanding.

If you are saying customizing the `image` of the container in docker, please refer to [this guide](https://www.keycloak.org/operator/customizing-keycloak)

Otherwise, assuming you are describing the picture of custom UI, please refer to [this doc](https://www.keycloak.org/docs/latest/server_development/index.html#adding-an-image-to-a-theme).
Pictures should be packaged in the theme jar as well.
