### ISSUE TITLE
Referrer missing from header in SAML assertion request

### ISSUE THREAD

**Issue by vschs007** [keycloak/keycloak#15802]
### Area

account/api

### Describe the bug

trying to send an saml assertion and its missing referrer from request header .

### Version

15.0.2

### Expected behavior

it should put referrer in req header

### Actual behavior

no sending referrer in req header

### How to Reproduce?

create a saml request flow

**Comment by jsorah** [comment]
This is due to Keycloak defaulting to [no-referrer](https://github.com/keycloak/keycloak/blob/main/server-spi-private/src/main/java/org/keycloak/models/BrowserSecurityHeaders.java#L33) as a [Referrer Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy).

What would be the need for having the referrer present? Even if this were not the default policy, it is not a header guaranteed to be present and users could modify or remove it from their requests.

**Comment by patrickjennings** [comment]
This is expected behavior by Keycloak for security and privacy reasons. We'll close this out as expected behavior.
