### ISSUE TITLE
Client Sessions Timing Out Too Early - Ignoring Client Level Session Settings

### ISSUE THREAD

**Issue by chris-m-dp** [keycloak/keycloak#15829]
### Area

core

### Describe the bug

Early expiration issues occur for clients using the Authorization Code grant type when Client level settings of Client Session Idle or Client Session Max have greater values than the corresponding Realm level token settings of SSO Session Idle, SSO Session Max, Client Session Idle and Client Session Max.

For example: 

```
Realm: 
	SSO Session Idle: 12 hours
	SSO Session Max: 12 hours
	Client Session Idle: 5 minutes
	Client Session Max: 1 hours

Client: 
	Client Session Idle: 30 mins
	Client Session Max: 12 hour
	
```
In these circumstances, Client Sessions expire too early. In the example above, the client session expires when the session is idle for about 8 or so minutes rather than the expected 30 minutes.

When an attempt is made to refresh a token, the following error occurs:

```
	"error": "invalid_grant",
	"error_description": "Session doesn't have required client"
```
   
This happens as the the client session has been removed from cache (Infinispan). Note: the expiry times on the tokens have been calculated correctly. The issue is in the cache expiry logic.

The problem was introduced with this PR https://github.com/keycloak/keycloak/pull/7736 and was logged as an issue in the Red Hat repository https://issues.redhat.com/browse/KEYCLOAK-17111. It looks like the issue is not explicitly logged in this repository.

The logic in the SessionsTimeout class takes no account of the Client level settings for Client Session Idle and Client Session max.  

### Version

18.0.2, 20

### Expected behavior

For the example given in the bug description with the settings below, the Client Session should not expire before it has been idle for at least 30 mins or active for 12 hours. 

```
Realm: 
	SSO Session Idle: 12 hours
	SSO Session Max: 12 hours
	Client Session Idle: 5 minutes
	Client Session Max: 1 hours

Client: 
	Client Session Idle: 30 mins
	Client Session Max: 12 hour
	

```

### Actual behavior

For the example given in the bug description with the settings below, the Client Session is expiring after the user is idle for about 8 minutes. 

```
Realm

	SSO Session Idle: 12 hours
	SSO Session Max: 12 hours
	Client Session Idle: 5 minutes
	Client Session Max: 1 hours

Client: 
	Client Session Idle: 30 mins
	Client Session Max: 12 hour
	
```

### How to Reproduce?

1. Start a fresh Keycloak instance.
2. Create a test realm
3. Create a test client in the test realm that uses OpenId connect with an Access Type of public
4. Create a test user in the test realm 
5. Configure the session idle/max settings.
```
Realm:
SSO Session Idle: 12 hours
SSO Session Max: 12 hours
Client Session Idle: 5 minutes
Client Session Max: 1 hours
Test client:
Client Session Idle: 30 mins
Client Session Max: 12 hours
```
6. Use a REST API client to  obtain an access token and refresh token for the test user via the Authorization Code grant type.
7. Wait 15 minutes.  Note: it is important not to use the Keycloak admin console to view sessions during this time as this stops the user session being idle.
8. Use the Keycloak admin console to view the test user's sessions.   It can be observed that the client session is no longer linked to the user session.
9. Try to  use the refresh token to obtain a new access token.  An error occurs - see below 

```
"error": "invalid_grant",
"error_description": "Session doesn't have required client"
```
 

### Anything else?

We have worked around this issue by setting no values for the Realm level Client Session Idle and Max settings. This means that the cache expiry logic uses the SSO Session Idle and SSO Session Max on the Realm which are (naturally and unsurprisingly) higher than our client expiry time-outs. We are effectively using these Realm level settings to control expiry of cached client sessions.  We're using the settings of Client Session Idle and Client Session max on each of our clients to manage the actual expiry of tokens.

**Comment by mposolda** [comment]
Assigning to you to triage as this is related to what you were recently working on.

**Comment by rmartinc** [comment]
Hi @chris-m-dp!

The settings at client level are only for token management and not for session values as discussed in #9896. So the idea is setting for client overrides smaller values than in the realm configuration. If you set the other way around, 5m idle in the realm and 30m in the override at client level, the refresh token expires in 30m while the session is invalidated in 5m. So there is an error after 5m because the client session associated to the token is not there anymore.

You can assign values the other way around, default 30m, and override at client 5m. That will generate shorter lifespan tokens but the session is still alive and can be reused.

@mposolda WDYT? Do we modify the code again to calculate the life for tokens to the shorter value (realm or client)? Clarify again the tooltip? Is it OK as it's now?

This is driving me a bit crazy. :smile:

**Comment by mposolda** [comment]
@rmartinc My vote is to clarify the tooltips for "Client timeouts" to make it clear from the tooltips that their values must be smaller than corresponding "User Session timeouts" at the realm level (if it is not mentioned on those tooltips already). I suppose this applies for both "idle" and "max" timeouts?

I am not sure if using shorter from both values helps much? As I afraid that people will again claim the error (For example with 5m idle at realm and 30m override at client level, I bet there would be another bug reports like "Why my token is not valid for 30 minutes, but just for 5 minutes?" etc :-) So my vote is to rather clarify the tooltips to force people using sensible configuration :-)

Question: Does it affects also tooltips for "Client Session Idle" and "Client Session Max" from realm settings?

**Comment by rmartinc** [comment]
> I suppose this applies for both "idle" and "max" timeouts?

Yes, it does. Makes no sense setting bigger values at client level than realm level on both values.

> Does it affects also tooltips for "Client Session Idle" and "Client Session Max" from realm settings?

Yes, we can clarify them too because it's more or less the same. If you set at realm level "sso session max" 10m and "client session max" 20m the user session is going to disappear before so setting a bigger values is also meaningless. The idea is "sso session max" should be the biggest value, then you can make client session shorter using "client session max" (at realm level affects both, tokens and sessions). At client level you can specify the values too, but those only affects the tokens, so they should be also shorter than client session values (this issue).

:smile: I will prepare another PR for the tooltips.

**Comment by betalb** [comment]
Any reason why it can't affect session ttl? I'm facing opposite issues: I have huge sso session max/idle and much smaller values on client level. Issued token are indeed short lived, but sessions keep stacking in cache. And this is what exactly I wanted to avoid.

My idea was to have short living sessions for selected clients with client_credentials grant

**Comment by rmartinc** [comment]
@betalb Finally we have managed a big rework about this topic in #17525 and the changes in documentation are being managed in #20967 (not merged yet). So since keycloak 22 the client level settings also affect the client session itself, not just the token expiration claims.

You can try this in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).

**Comment by rmartinc** [comment]
I'm closing this now the documentation changes are also merged. If you see any issue please re-open or file a new issue. Thanks!

**Comment by betalb** [comment]
> @betalb Finally we have managed a big rework about this topic in #17525 and the changes in documentation are being managed in #20967 (not merged yet). So since keycloak 22 the client level settings also affect the client session itself, not just the token expiration claims.
> 
> You can try this in the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly).

Thank you, I will try to test this, but our build depends on custom extension, and considering javax -> jakarta switch in this release, this doesn't look like easy test. Do you have any pubic maven repo with SNAPSHOT versions of keycloak jars?
