### ISSUE TITLE
Creation of Realm with no name through REST API

### ISSUE THREAD

**Issue by cjohnson-ironiq** [keycloak/keycloak#15848]
### Area

account/api

### Describe the bug

While importing a realm file through the CLI using the `/admin/realms` endpoint, if the `realm` value/argument is not provided then KeyCloak will successfully create a realm with no name. While you can easily then add the `realm` value to the imported JSON file and re-import, you're stuck with this empty-named realm. 

I've attached an image of the result:  
![image](https://user-images.githubusercontent.com/110685194/205745873-75abca36-1669-422f-bf17-c19e18c77e40.png)

While a funny bug, you're unable to select this realm in the GUI (redirects to master). Additionally, all of the REST API endpoints depend on a non-empty string for the realm name, so I'm not sure how I should delete this mistake. 

### Version

20.0.1

### Expected behavior

I'd expect the server to send back an HTTP 400 or something of the sort to indicate that this doesn't make any sense. 

### Actual behavior

Server responds with an HTTP 201 and acts like everything is fine in the world.

### How to Reproduce?

Import a realm through the REST API by sending a POST request to `/admin/realms` with a non-existent realm name. You're unable to do this in the GUI as far as I'm aware.

### Anything else?

The REST API docs should also reflect that the `realm` member of the `RealmRepresentation` is required

**Comment by cjohnson-ironiq** [comment]
This is still an issue in 20.0.2, as well.

**Comment by patrickjennings** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  
It will be helpful if:

-   You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
-   If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
-   If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
-   If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by darwinsubramaniam** [comment]
Hi 
I also found that if we create the realm name using "%20" , the realm is not usable . I can see the realm under the Keycloak UI but selecting , does not load  any realm setting page

<img width="296" alt="image" src="https://github.com/keycloak/keycloak/assets/4163586/0a49b2e1-6876-4cd5-9dac-4f79abcb66d2">

The realm creation should also implement regex and not null conditions.

**Comment by pedro-hos** [comment]
I am working on that, should sent the PR today later

**Comment by pedro-hos** [comment]
I am wondering if I should use 

https://github.com/keycloak/keycloak/blob/5fc4dd03adcde6751ee140921afc3795fe04eff0/server-spi-private/src/main/java/org/keycloak/utils/ReservedCharValidator.java#L52

instead of the way that I have made to validate the special characters.

**Comment by pedro-hos** [comment]
Hi @mposolda can you please review the PR and assign it to me? Thanks

**Comment by pedroigor** [comment]
Should be fixed by https://github.com/keycloak/keycloak/pull/25836.
