### ISSUE TITLE
Login template doesn't localize ${client.name} for master realm admin console

### ISSUE THREAD

**Issue by AconiteX** [keycloak/keycloak#15842]
### Area

admin/ui

### Describe the bug

In the login theme template (theme/login/template.ftl), printing `${client.name}` will return a nonlocalized phrase of `${client_security-admin-console}` as the output when attempting to login to the master realm admin console instead of a label specifying the client as the master realm console.

### Version

18.0.0

### Expected behavior

Some defined phrase like "Master Realm Admin Console" should display in place of `${client.name}` given the master realm admin console isn't an actual client. 

### Actual behavior

Prints `${client_security-admin-console}`

![image](https://user-images.githubusercontent.com/63141077/205707201-ef39aff3-2c49-46aa-b64f-b6a166ad09c5.png)

### How to Reproduce?

In themes/login/template.ftl, add `${client.name}` to be output to the page then attempt logging into the master realm admin console at `/auth/admin`.

**Comment by mabartos** [comment]
@AconiteX Thanks for creating this issue. 

I wouldn't consider this as a bug. The property `client.name` only determines which key for localized messages should be used, but the localization is not executed at all. It's not intended to achieve this way.

In order to display the required localized client name, you can use this:
`${advancedMsg(client.name)}`

Here is the result:
![image](https://user-images.githubusercontent.com/38039883/206248245-0ec186d1-88d4-41d5-8126-dd26b6bb51ac.png)
