### ISSUE TITLE
Full Realm Representation not returned through GET /{realm}

### ISSUE THREAD

**Issue by cjohnson-ironiq** [keycloak/keycloak#15877]
### Area

account/api

### Describe the bug

While the [documentation](https://www.keycloak.org/docs-api/20.0.1/rest-api/index.html#_realmrepresentation) indicates that the RealmRepresentation schema is returned when hitting `GET /{realm}`, it appears that some values are missing. For example, when I import a new realm, I'm able to send `requiredActions` and the server sets the realm value with no issues. However, when I request for this realm, I don't receive this field.

Fields in `RealmRepresentation` not returned:
 - accountTheme
 - adminTheme
 - authenticationFlows
 - authenticatorConfig
 - components
 - defaultLocale
 - displayName
 - displayNameHtml
 - emailTheme
 - eventsExpiration
 - federatedUsers
 - keycloakVersion
 - loginTheme
 - passwordPolicy
 - protocolMappers
 - requiredActions
 - userFederationMappers (not sure if this falls into the category of 'user' or 'client' representations)
 - userFederationProviders (same)

Some of these fields seem to be returned if values are set in them (e.g. `passwordPolicy`), others (`requiredActions`) are never returned regardless of their state. The inconsistent behavior in what is returned in the REST API for the realm makes it more difficult to develop around.

Similar issue: #14663 

### Version

20.0.1

### Expected behavior

All values in `RealmRepresentation` are returned.

### Actual behavior

Some values in `RealmRepresentation` are returned.

### How to Reproduce?

Create a realm, set some values, call the REST API to get the realm.

### Anything else?

When I export a realm with no groups/clients/whatever, I get a file that is much larger than if I call the REST API. Not sure if these are calling different functions in the back.

**Comment by cjohnson-ironiq** [comment]
Note that the fields I've listed in the initial report is from me just going through the `RealmRepresentation` object and searching for each field in the returned Realm JSON. It may be incomplete due to human error or what have you.

**Comment by sschu** [comment]
Could it be that these realm attributes are just not set and therefore not returned? According to https://www.keycloak.org/docs-api/20.0.1/rest-api/index.html#_realmrepresentation, all the fields are optional so I guess the behaviour is exactly as specified.

**Comment by cjohnson-ironiq** [comment]
Also noting this is still an issue in 20.0.2

**Comment by cjohnson-ironiq** [comment]
Note: you can interact with the Realm Required Actions values using this endpoint: `GET /{realm}/authentication/required-actions` and others. However, you can't send the `config` value if creating/updating a required action unless you like HTTP/500 errors.

**Comment by jsorah** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  There are certainly a few items pertaining to the Admin API that could be improved and it needs some consideration how best to move this forward.

It will be helpful if:

-   You can verify if still applicable in latest Keycloak released version. If not, then it is welcome to close this issue.
-   If you figure that this may not be a valid bug (for example just a mistake in configuration etc), it is also welcome to close this issue
-   If still applicable in latest version, it will be welcome to add the comment as well, that this was still reproduced with latest Keycloak version as it is very valuable info. Anyone is welcome to comment with this or add other relevant comments to this issue.
-   If you figure this is valid bug and you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.
