### ISSUE TITLE
Keycloak Java  adaptor not working with Bearer token only

### ISSUE THREAD

**Issue by vamsikrishna-VK31** [keycloak/keycloak#16010]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

adapter/java-cli

### Describe the bug

In keycloak UI ,I have created a client with authorization and in Java keycloak adaptor side i put bearer only true for authorization .  when i run the code  still it's asking client credentials. Can you please help on this?

### Version

19.0.3

### Expected behavior

In keycloak UI , create client with authorization and in Java keycloak adaptor side i put bearer only true for authorization .  when i run the code  it need to work with token only not with  client credentials

### Actual behavior

In keycloak UI ,create client with authorization and in Java keycloak adaptor side i put bearer only true for authorization .  when i run the code  still it's asking client credentials

### How to Reproduce?

create client with Authorization in keycloak and in Java adaptor set bearer only true and runs the code then it will ask client credentials

**Comment by pedroigor** [comment]
When using authorization services client should not be configured as bearer because the policy enforcer requires obtaining tokens (using client credentials) from the token endpoint in order to properly fetch the protected resources.

Please look at https://www.keycloak.org/docs/latest/authorization_services/index.html#_enforcer_overview and https://github.com/keycloak/keycloak-quickstarts/tree/latest/app-authz-jee-servlet.
