### ISSUE TITLE
Add account2 tests to Keycloak CI

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#16038]
Account2 is not tested in the base testsuite, but rather in a separate module (other/base-ui). There's also some login tests in this module.

We should enable account2 testing in GitHub Actions. Question is if we should keep these as a separate module or move them to the base tests.

Also, find it strange that we have two login forms tests here, when the majority of login forms testing is in the base tests.

**Comment by miquelsi** [comment]
For a few months the New Account Console tests have failed to compile. The root cause is [this line](https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/other/base-ui/src/test/java/org/keycloak/testsuite/ui/account2/AbstractAccountTest.java#L70), which tries to find out if we're testing Keycloak or RH-SSO. Since the product reference was removed ([commit](https://github.com/keycloak/keycloak/commit/97ae90de888362c82f6e87ef699035e573ca70ff#diff-08b8752e3233fbecddd3d7b31428b8521581d1d625efcdb0e52b71e10345eb43)), we should do a small refactor to address this.

At first glance, I would add a system property to specify the theme we want to use, defaulting to "keycloak.v2".

**Comment by stianst** [comment]
@miquelsi we won't have an RH-SSO theme, so we can just refactor the tests to fix it to `keycloak.v2` theme.

**Comment by miquelsi** [comment]
Enabling Firefox only for now. Created follow up issue for adding Chrome #16546.
