### ISSUE TITLE
User profile attributes only writable at registration time by users

### ISSUE THREAD

**Issue by Tristan971** [keycloak/keycloak#16054]
### Description

Allow user profile attributes to be:
- user-defined at registration
- only editable by admins afterwards

### Motivation

We want our users to be able to pick a username at signup, but we do not want them to be able to change it later themselves. Instead, only admins should be able to do that.

### Details

We currently can't achieve this as these are our options:
- If the realm has non-editable usernames, then admins cannot edit usernames
- If the realm has editable usernames, but user profile attribute username is only viewable by users, then the username field doesn't show up on the registration page at all (and neither does the password one, fwiw), which makes registration impossible
- If the realm has editable usernames, and user profile attribute username is editable by users, then users can change their username on their own

**Comment by lexcao** [comment]
I think you could try this [Declarative User Profile](https://www.keycloak.org/docs/latest/server_admin/index.html#enabling-the-user-profile).

**Comment by Tristan971** [comment]
We are using it at the moment; the issue is specifically that making an attribute (the username) admin-only editable, it isn’t prompted at registration anymore.

**Comment by pedroigor** [comment]
@Tristan971 In order to properly address this and other use cases, we should allow configuring permissions on a per-context basis.

Basically, a context in the user profile is one of REGISTRATION, ADMIN API, ACCOUNT, etc. Today, when you set permissions to an attribute they are enforced in every single context.

What we could do is allow setting permissions on a per-context basis so that you can have the attribute writable during registration by the user and read-only for others. Plus making it editable for the ADMIN API context.

It should be quite trivial to implement this. However, the main challenge is how to build a good UI on top of it :)

**Comment by Tristan971** [comment]
Sounds perfect indeed :-)

As for the UI side, I only use the API but I do appreciate that there’s a lot of complexity you have to model visually in the admin console indeed 😅

**Comment by mposolda** [comment]
Closing this one as it is super-seded by another issue https://github.com/keycloak/keycloak/issues/25575 , which adds additional flexibility and should support this use-case among others.

**Comment by agerchev** [comment]
Hello, 

We have the same use case as described here. I understand, that there is a planned upgrade of the functionality, but till then, 
what would be the right way to implement such restrictions. 

We thought that we can implement custom validator by inheriting the AbstractStringValidator 
but how can we get the UserProfileContext to properly implement the checks ?

@pedroigor, @mposolda  

Best regards, 

Atanas
