### ISSUE TITLE
The search does not work if only partial information is entered

### ISSUE THREAD

**Issue by Paul6552** [keycloak/keycloak#16139]
### Description

![image](https://user-images.githubusercontent.com/25934591/208877106-23bd9dc8-d079-497a-97e9-f1ef6cf916f9.png)

When something is entered into the search, the information (first name, last name, email) must be completely correct for the user to be displayed.

**Example:**
If I search for `Karin` I get all users with Karin.

But do I enter `arin` I dont get any User.

The same is with the email address. If I enter the whole email address, I get the user. However, if I only enter part of the email address, I get nothing.

**Example email address:**
Example user Karin has `example@wonderful.com`

If I search for `exampl` I get all users with an emailadress starting with `exampl`. If I enter `ample` I get nothing.

**Comment by rd-robert-avram** [comment]
:+1: 
Solidarity act of the day:
Just wanted to say we've encountered this issue as well.
The search seems to be a `.startsWith(<search-term>)` query.

**Comment by sschu** [comment]
Which is by design. If you search with fixed prefix, you can still use database indexes. If you search with wildcard in the beginning you will have to do full table scans which can be very slow, depending on the number of users. 

Btw. you can add a wildcard in the beginning when searching to make this explicit - but it might be slow.

**Comment by Priska2** [comment]
You can use %xyz% to make a lookup with just partial information.
