### ISSUE TITLE
java.nio.charset.UnsupportedCharsetException: cp0 when running keycloak in nanoserver container

### ISSUE THREAD

**Issue by sbaeurle** [keycloak/keycloak#16226]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

When trying to start keycloak using `kc.bat` only `start --optimized` works as expected.

All other command fail with `java.nio.charset.UnsupportedCharsetException: cp0`.

### Version

19.0.2

### Expected behavior

Expect all other commands to work as well.

### Actual behavior

Command fails with exception mentioned above.

### How to Reproduce?

Use one of the nanoserver based tags of https://hub.docker.com/_/eclipse-temurin.

Copy keycloak into container and build using` /keycloak/bin/kc.bat build`. 

Try to execute any 'interactive' command when executing the docker container.

### Anything else?

Appending `-Dsun.stdout.encoding=UTF-8 -Dsun.err.encoding=UTF-8` to `JAVA_OPTS_APPEND` solves this issue.
May be a good idea to append this to the standard arguments in kc.bat (since this file is probably only use on windows systems)

If needed I can create a small PR myself, to improve the batch script

**Comment by sbaeurle** [comment]
Quick follow up, should i create a PR for this issue? Shouldn't be that large imo

**Comment by Pepo48** [comment]
@sbaeurle thanks for the report! The PRs from the community are always very welcomed, so feel free to create one.

I assume that this one is related to your specific way of use/container environment, since I wasn't able to reproduce it on a full-fledged Windows VM.

You can always check current environment properties via:
`java.exe -XshowSettings:properties -version`

Besides the two properties you already mentioned, there is also `file.encoding`, which I remember using in the past in order to solve similar issues during building the project/running the testsuite.
