### ISSUE TITLE
admin ui cannot be isolated to hidden domain

### ISSUE THREAD

**Issue by burner-account** [keycloak/keycloak#16299]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

- I have isolated the admin ui to its own domain (hidden.com).
- Integration into apps is done with another domain (public.com)..
- my keycloak resides under /auth
- I followed the information which paths to expose from https://www.keycloak.org/server/reverseproxy
- kc v20.0.2, k8s v1.26.0

Problem: 

As soon as i try to load `hidden.com/auth/admin/master/console/`, the admin UI on  makes a request to `public.com/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html`. This is the only resource fetched from `public.com` and this collides with isolation.

My "hidden.com" cannot reach "public.com" and i like it that way. 

Result:

`hidden.com/auth/admin/master/console/` does neither load nor redirect, admin can't login.

Can you tell me how to do it right if it is not a bug? Thanks!

### Version

v20.0.2

### Expected behavior

When loading the admin ui i expect all resources to be consistently loaded from the same domain.

### Actual behavior

While loading most resources from the correct domain, the admin ui seems to do some special trick to decide from which domain to load the `/realms/master/protocol/openid-connect/3p-cookies/step1.html` - and gets it wrong.

### How to Reproduce?

-  have the admin ui isolated on its own domain (hidden.com).
- for Integration into apps and as main frontend use another domain (public.com)
- maybe put keycloak under /auth
-  follow the information which paths to expose from https://www.keycloak.org/server/reverseproxy

### Anything else?

There are related (closed) issues, but those do not seem to cover the split-domain topic.

**Comment by stianst** [comment]
The Admin UI/REST APIs do not provide their own OpenID Connect endpoint, as such redirects to the public URL for the Keycloak server for this part, so this is intentional.

**Comment by Persi** [comment]
@stianst Calling this intentional without any solution sounds strange for me. This bug blocks using Keycloak Adminconsole in isolated environments. Just because the adminconsole does not provide it's own oidc endpoint, does not mean it could fetch this resource via internal domain. If this resource has to be provided via internal domain explicitely, I think Keycloak should do that.

In addition, this problem just occured since Keycloak 20 (more specifically, since we switched to quarkus release) for us. Until KC 19 the provider running Keycloak for our customers could access the adminconsole via internal domain.

**Comment by stianst** [comment]
> @stianst Calling this intentional without any solution sounds strange for me. This bug blocks using Keycloak Adminconsole in isolated environments. Just because the adminconsole does not provide it's own oidc endpoint, does not mean it could fetch this resource via internal domain. If this resource has to be provided via internal domain explicitely, I think Keycloak should do that.
> 
> In addition, this problem just occured since Keycloak 20 (more specifically, since we switched to quarkus release) for us. Until KC 19 the provider running Keycloak for our customers could access the adminconsole via internal domain.

There's no bug here. You can isolate the admin console (which is an app within Keycloak) with a reverse proxy. The admin console uses a different app (the login) part to get tokens, which is on the public URL. So what is the actual issue here? Other than the wrong assumption that admin console provides its own oidc provider.

**Comment by Persi** [comment]
The provider is hosting a reverse proxy in front of all applications to route traffing accordingly.

The problem here is, that within this isolated environment the public domain of Keycloak cannot be accessed and not even resolved, so it is impossible for the administrator to login to the admin console, as downloading and resource from the public doamin, e.g. `publicdomain/auth/realms/master/protocol/openid-connect/3p-cookies/step1.html` fails.

**Comment by burner-account** [comment]
> There's no bug here.

Well, to make everybody happy i am willing to re-report this as a feature request.

Keycloak delivers all isolation puzzle pieces - but one. It would be just sooo nice, to have this part coverd by Keycloak itself and not by another layer around it.

**Comment by Persi** [comment]
@burner-account did you create the mentioned feature request?
