### ISSUE TITLE
CVE-2022-3143 - wildfly-elytron: possible timing attacks via use of unsafe comparator

### ISSUE THREAD

**Issue by tanadeau** [keycloak/keycloak#16652]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

CVE reported by Trivy in latest 20.0.3 Docker image.

https://nvd.nist.gov/vuln/detail/CVE-2022-3143

### Version

20.0.3

### Expected behavior

CVE is remedied or response about why Keycloak isn't vulnerable to exploit.

### Actual behavior

No response so far

### How to Reproduce?

Scan image with Trivy.

**Comment by Morl99** [comment]
According to the [RedHat Bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2124682) this has been fixed in the following versions:

- wildfly-elytron 1.15.15
- wildfly-elytron 1.20.3

Is it possible to update the Quarkus distribution used by Keycloak to either?

**Comment by Morl99** [comment]
@abstractj you are right, sorry about that. I got confused by the information in Bugzilla that states, that the issue is fixed in 1.20.3 and that the issue is closed. I guess I do not understand the release workflow that is used here. Is there anything that we can do to craft a release? I guess the issue is fixed on the main line of the project, right?

My very limited understanding of the issue at hand is, that timing differences would need to be observable from an outside attacker. I wonder which case in keycloak could be suspectible to such an attack?

**Comment by abstractj** [comment]
@Morl99 no problem and it was also confusing to me. I reported the issue to people responsible for Bugzilla. The release workflow can be different from project, to project, so I cannot speak for the WildFly Elytron team.

Speaking about Keycloak, we should have a micro release available soon, our team is wrapping up the final details.

From my understanding, CVE-2022-3143 affects the following packages: https://security.snyk.io/vuln/maven?search=CVE-2022-3143. All those packages were bumped to 1.20.1, so I believe we should be safe if we consider that CVE-2022-3143 impacts versions equal to, and less than 1.15.15 of Elytron.

**Comment by cturkalj** [comment]
Decompiling 1.20.1 shows that the vulnerable method calls (java.util.Arrays.equals) are still present. 
So the Trivy report seems be accurate.

**Comment by JanEgner** [comment]
Unfortunately, this CVE is still flagged for the Keycloak 21.0.2 Docker container from quay.io  (by Trivy/OWASP Dependency Track, in this case). That is perhaps due to several wildfly-elytron jars included which are still on version 1.20.1, e.g.:

`-rw-rw-r-- 1 keycloak root   138842 Mar 30 11:06 org.wildfly.security.wildfly-elytron-credential-1.20.1.Final.jar`
`-rw-rw-r-- 1 keycloak root    23833 Mar 30 11:06 org.wildfly.security.wildfly-elytron-credential-source-deprecated-1.20.3.Final.jar`
`-rw-rw-r-- 1 keycloak root    23857 Mar 30 11:06 org.wildfly.security.wildfly-elytron-credential-source-impl-1.20.3.Final.jar`

Looks a bit inconsistent.
