### ISSUE TITLE
Cannot change dateFormat/timeFormat in admin theme

### ISSUE THREAD

**Issue by bilias** [keycloak/keycloak#16766]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I cannot change the date and time format listed in admin ui (sessions/events,users etc)
Ideally I would like to set it globally.

### Version

20.0.3

### Expected behavior

custom admin theme should be able to alter admin-messages

### Actual behavior

admin-messages remain the same

### How to Reproduce?

I've created themes/MYTHEME/admin directory with:
theme.properties
```
parent=keycloak.v2
```
and messages/admin-messages_en.properties with
```
# Angular date filter format strings: https://docs.angularjs.org/api/ng/filter/date
#dateFormat=shortDate
#timeFormat=mediumTime
dateFormat=dd/MM/yyyy
timeFormat=H:mm:ss
```
I've set MYTHEME as admin theme in realm settings->themes
However date/time format does not change.

I''ve tried re-building, deleting caches, restart and running with --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false

nothing changes

**Comment by jonkoops** [comment]
The `keycloak.v2` theme is not using AngularJS so it's no longer possible to set these values and change the date and time formatting. Instead this is done based on the user's configured locale ([see code](https://github.com/keycloak/keycloak-ui/blob/97339a616d1ae62c24972ecc31a9c71e3a07d812/apps/admin-ui/src/utils/useFormatDate.ts)).

We are no longer relying on a date formatting library, instead the [internationalization API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) of the browser is used. This allows us to ship less code and is more maintainable as it is updated independently of our code.

Caveat (if you can call it that, it's intended behavior) is that this does not allow you to customize the way dates look in the formatting process.

Since we have no control of this we cannot implement the feature you are requesting here. Also for the aforementioned reasons we want to rely on a standardized system, rather than a configurable library.

**Comment by jonkoops** [comment]
As mentioned we are not using the browser's locale but the configured locale for the user in Keycloak.
