### ISSUE TITLE
New user from identity provider not having attribute mapped to user federation (LDAP)

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#16848]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

I use SAML as an Identity provider, and LDAP (AD) for user federation.
I added two hardcoded-ldap attributes: `userPassword` and `pwdLastSet` as a mapping for the ldap provider.
When I create a new user via the console, these attributes are correctly set.
However, when a user first logs in via SAML, the user is indeed created on LDAP, but these attributes aren't set.

### Version

20.0.3

### Expected behavior

I'd expect  the ldap attributes that I set up on the ldap provider would be written to a new user, regardless if the user creation is manual via console or when it is created after a login via SAML.

### Actual behavior

Creating a user manually results in successful attribute mapping as defined on the ldap mappers. It doesn't work with SAML - the user is created, but the attributes aren't mapped.

### How to Reproduce?

1. Create two hardcoded-ldap-attribute mappers, one for `userPassword` (set to `${RANDOM}`), the other for `pwdLastSet` (set to `-1`).
2. Create a new user manually - check on AD, the attributes are set.
3. Now create that user by logging in via an external SAML identity provider - the attributes are not created.

**Comment by hmlnarik** [comment]
This seems to be an issue with identity brokering. @keycloak/core, could you please have a look at this one?

**Comment by rmartinc** [comment]
@oculos After checking this, I think the problem is not if the user is created via console or brokering. The root cause is https://github.com/keycloak/keycloak/issues/14286 that introduced this regression. The hardcoded attribute previously was created always at first but now (if using delayed creation until mandatory attributes are filled) can happen that the attribute is not created cos it's set as read-only.

I think a workaround is being sure all mandatory attributes have the option "Force a default value" to true and that way never delay the creation.

Nevertheless I'm working in send a PR.

**Comment by oculos** [comment]
> @oculos After checking this, I think the problem is not if the user is created via console or brokering. The root cause is #14286 that introduced this regression. The hardcoded attribute previously was created always at first but now (if using delayed creation until mandatory attributes are filled) can happen that the attribute is not created cos it's set as read-only.
> 
> I think a workaround is being sure all mandatory attributes have the option "Force a default value" to true and that way never delay the creation.
> 
> Nevertheless I'm working in send a PR.

Thanks a lot @rmartinc . I am going to try to see if I get it to work the way you are describing.
