### ISSUE TITLE
v20.0.2 attempts to URL decode same string up to 5 times for unclear reasons

### ISSUE THREAD

**Issue by ae-govau** [keycloak/keycloak#16851]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Code was added in v20.0.2 to repeatedly (up to 5 times) URL decode `redirect_uri` before using it:
https://github.com/keycloak/keycloak/commit/da8d61616399d5c4e4c470c16dd6b0bd98f2b656#diff-8a42999224cc18191469006d9c48d36f83917774badfe5b103e259380318043cR158-R193

This is unusual. Generally whether a thing is encoded or not is clearly specified. "Optional" encoding can lead to exciting behavior, and RFC 6749 makes no mention of this: https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3

It's quite possible that there was a very good reason to add this, but there's no any clear info that I could find as to why (there's not enough info the the phrase "Avoid path traversal vis double-url encoding of redirect URI") and that's nearly certainly worth a comment, as this seems like quite unusual behaviour.

### Version

20.0.3

### Expected behavior

To read the code and understand why a variable is optionally attempted to be decoded up to 5 times.

### Actual behavior

Read the code and be puzzled.

### How to Reproduce?

Read https://github.com/keycloak/keycloak/commit/da8d61616399d5c4e4c470c16dd6b0bd98f2b656#diff-8a42999224cc18191469006d9c48d36f83917774badfe5b103e259380318043cR158-R193

### Anything else?

While I don't think this has specifically caused an issue for us, we've seen unusual behaviour (502 - we're behind Nginx and suspect the request/response size may have increased for some uses) in 20.0.3 (since updating from 20.0.0) so am reviewing the changes. This one seems quite imprecise and left me puzzled.

**Comment by timesy** [comment]
I have a problem, where I am accessing a resource with a slash in its name. The URL I am calling is encoded as `/admin/building%20a%2Fb` where "building a/b" is the name of the ressource. When I load the page again it is then decoded to `/admin/building%20a/b` (so a new path /b is added) instead of `/admin/building%20a%2Fb`.

I think this is because it is decoded multiple times by this commit?

**Comment by mposolda** [comment]
@ae-govau The reason of this commit was security issue. For example when you had your client configured with valid redirect URL like `https://my-host.com/foo/*` , you were able to create `redirect_uri`, which was able to redirect for example to `https://my-host.com` or `https://my-host.com/some-very-unsafe-path` . Some more details can be seen for example from underlying commit https://github.com/keycloak/keycloak/commit/1987c942f527b9f3bbf2a86ba71ba8ae0154ac37 or from the GH advisory itself https://github.com/advisories/GHSA-g8q8-fggx-9r3q (and related links).

In your environment, do you have some more details on when 502 can happen? It seems that rather of this, it can be more related to the other bug https://github.com/keycloak/keycloak/issues/17192, which was fixed in recent 21.0.1. So if you have a chance to upgrade to 21.0.1 and confirm if issue still happens for you, it can help.

@timesy Could you please confirm if the redirect worked as expected in previous version, but doesn't work anymore? And can you confirm what are your "Valid Redirect URIs" configured for your client? (feel free to replace host with some fake). Am I assume correctly that:
- You have "Valid Redirect URIs" configured on client with something like `https://my-host.com/admin/building/*`
- From your application, you use `redirect_uri=https://my-host.com/admin/building%20a%2Fb`
- In previous Keycloak version, you were redirected after login to `https://my-host.com/admin/building%20a%2Fb`, but in newest version, you are redirected to something like `https://my-host.com/admin/building%20a/b` . Is it correct?

**Comment by timesy** [comment]
@mposolda Thank you for your answer! For testing I downgraded to 19.0.3.

- "Valid Redirect URIs": `https://my-host.com/*`
- Redirect URI in application: ` https://auth-host.com/realms/Realm/protocol/openid-connect/auth?client_id=clientid&redirect_uri=https%3A%2F%2Fmy-host.com%2Fadmin%2Ffake%2520fake%252092%252F72%2F3`
- URL after redirect: 
  - 19.0.3: `https://my-host.com/admin/fake%20fake%2092%2F72/3`
  - 20.0.3: `https://my-host.com/admin/fake%fake%2092/72/3`

**Comment by mposolda** [comment]
@timesy Thanks!

Adding to Keycloak 22 to doublecheck if this can be improved...
