### ISSUE TITLE
FedoraProject package

### ISSUE THREAD

**Issue by LecrisUT** [keycloak/keycloak#17066]
### Description

Any plans to provide upstream packages for keycloak?

**Comment by LecrisUT** [comment]
@stianst Explanation?

**Comment by stianst** [comment]
@LecrisUT sorry to close without explanation, but we do get a huge amount of issues created and don't always have time to answer everything. Honestly, I don't know what you are talking about. If you are talking about publishing RPMs for Keycloak that's not something we're planning, and very likely never will do. Please use discussions rather than issues for questions in the future though.

**Comment by LecrisUT** [comment]
Yes, I am referring to publishing an RPM to src.fedoraproject.org. I believe this would be valuable.

Are there licensing or design issues that prohibit keycloak to be published like that? If we contribute with a working copr, would you reconsider it, or at least support the maintenance of the copr repo by adding a webhook to automatically trigger the builds on tags?
