### ISSUE TITLE
Issue with "User-Initiated Action Lifespan"

### ISSUE THREAD

**Issue by AntonioMT88** [keycloak/keycloak#17165]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

hi there, i'm implementing some keycloak api for my application (we do not want the users to acced directly to the admin panel) and i believe i've found an issue with the admin api.

This is my code:

`
        RealmResource realmResource = keycloakHelper.getInstance().realm(realmName)

        RealmRepresentation realmRepresentation = realmResource.toRepresentation()

        realmRepresentation.setActionTokenGeneratedByUserLifespan(newLifeSpan)

        realmResource.update(realmRepresentation)
`

If i send a newLifeSpan value very high (let's say 100000) and then i go to keycloak admin panel, this is the result

<img width="491" alt="Screenshot 2023-02-17 alle 11 32 08" src="https://user-images.githubusercontent.com/49096095/219627223-02e21abe-0cac-404d-90e6-3592bc51a38f.png">

this is causing that, when i get the verification email, i read that the validation link will be enable for an amount of time mesuread in minutes (and not in hours or day as i espect).
am i doing something wrong or it is indeed a bug?

### Version

20.0.3

### Expected behavior

the code must automatically calculate the right amount of minutes/hours/days or there must be some parameter that let me specify the unit measure.

### Actual behavior

it save a wrong value without specifying the unit measure

### How to Reproduce?

try the code i share (with newLifeSpan = 100000) will be enough

**Comment by mposolda** [comment]
I think that this is UI issue, but looks like relatively low priority to me.

Cause: The lifespan specified to RealmRepresentation (or admin API) is always specified in seconds. Then UI automatically transforms into some more proper measure (minutes, hours or days) according to the value specified. Admin console itself allows to specify only minutes, hours or days, so it is fine. The problem is, that if the value is specified manually by admin REST API is not divisible by 60, it cannot be transformed into "minutes". However "seconds" are not available as unit in the UI.

How to fix: I am not sure what we can do here? Maybe add "seconds" back as a valid unit to display (just in case that value is not divisable by 60) as displaying "1" is not very user-friendly?

@AntonioMT88  Workaround is to make sure that your value is divisable by 60 (For example you use 100020 or 99960 instead of 100000).
