### ISSUE TITLE
Impossible to extend VerifyEmailActionTokenHandler

### ISSUE THREAD

**Issue by MariiaAlekseichuk** [keycloak/keycloak#17194]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

It's impossible to extend VerifyEmailActionTokenHandler because it has field TOKEN_TYPE = "verify-email", which used as ID for it's factory AbstractActionTokenHandler, so we can't create 2 factories with same ID. 
Also, as it described in dics:  Implementations have to override getId() to return value that must match precisely the value of typ field in the action token. But typ "verify-email" is already used, so I can't create second factory for this this typ.

### Version

17.0.0

### Expected behavior

It's possible to extend VerifyEmailActionTokenHandler

### Actual behavior

It's impossible to extend VerifyEmailActionTokenHandler

### How to Reproduce?

try to extend VerifyEmailActionTokenHandler :)

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now. If anyone has suggestion how to improve the SPI, so it is more extendable, it can help.

**Comment by graziang** [comment]
An ActionTokenHandler is selected using the type of the action token as provider id of the handler: https://github.com/keycloak/keycloak/blob/b3321cb26e9c6ccc0dc85e4e3fed7dba9cca54f3/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L676


A possible solution could be to get all the ActionTokenHandlers and use `getTokenClass()` somehow (or a new `getTokenType()` method in the `ActionTokenHandler` that return the token type of the related action token) to filter the handler instead of using the provider id. This way you can have multiple handlers for a single action token. 

At this point there are two ways to edit the [handleToken](https://github.com/keycloak/keycloak/blob/b3321cb26e9c6ccc0dc85e4e3fed7dba9cca54f3/services/src/main/java/org/keycloak/services/resources/LoginActionsService.java#L513) method:

- Keep selecting just one handler, but using the new approach, this allows you to extend `VerifyEmailActionTokenHandler` with different id [by disabling the unused provider]( https://www.keycloak.org/server/configuration-provider) ( --spi-action-token-handler-verify-email-enabled=false) 

- Run multiple handlers for a single action token. The challenge with this approach is that the response of the `handleToken` method is used as a response of the action token Keycloak Endpoint.
 
WDYT?

**Comment by graziang** [comment]
@MariiaAlekseichuk starting from version 21.1.1 is possible to extend an existing provider by implementing the `order()` method in your custom implementation and make sure that it has a higher order than the `VerifyEmailActionTokenHandler` implementation.
More details [here](https://www.keycloak.org/docs/latest/server_development/index.html#_override_builtin_providers).

**Comment by mposolda** [comment]
@graziang Thanks for the investigation!
@MariiaAlekseichuk Closing this issue as this should be already possible. Please re-open in case you still see the issues with the suggestion above.
