### ISSUE TITLE
Exported JKS file from Keycloak is corrupted

### ISSUE THREAD

**Issue by chagraoui** [keycloak/keycloak#17221]
### Before reporting an issue

- [x] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

After upgrading from Keycloak version 15.1.1 to 20.0.3, the JKS file exported from Keycloak appears to be corrupted.

### Version

20.0.3

### Expected behavior

After exporting the JKS file from Keycloak, the file should be a valid and recognizable JKS keystore format, and should be viewable using the keytool command or other Java KeyStore viewer.

### Actual behavior

After exporting the JKS file from Keycloak and attempting to view its contents using the keytool command, the following error is displayed:

`keytool error: java.security.KeyStoreException: Unrecognized keystore format.`

The exact command used was:

`keytool -list -v -keystore the-downloaded-file.jks
`

### How to Reproduce?

1. create a client type SAML
2. Navigate to the "Realm Settings" tab for the desired realm
3. go to Keys tab
4. click on export button 
5. fill out the export form (including selecting the "JKS" as Archive format )
6. click on export button 
7. Attempt to open the JKS file using a Java KeyStore viewer or other tool
 
keytool -list -v -keystore the-downloded-file.jks

```
erreur keytool : java.security.KeyStoreException: Unrecognized keystore format. Please load it with a specified type
java.security.KeyStoreException: Unrecognized keystore format. Please load it with a specified type
```

**Comment by mposolda** [comment]
I am not able to reproduce. This might be already fixed. Please try to reproduce with the latest Keycloak 21 release (it will be likely released this week, maybe even today) and please re-open just if applicable with latest release as well.

Few other considerations:
- What is the java version you're using to run Keycloak?
- What is the java version you're using to run keytool?
 
On linux, you can use commands like `which keytool` and `which java` to doublecheck it uses the correct stuff. It will be ideal if you try with both keycloak and keytool using same java and if you Java 17 as that is the version supported by Keycloak since Keycloak 22. I am using OpenJDK 17 with Keycloak and OpenJDK 17 and OpenJDK 11 on Ubuntu when running keytool (both worked fine for me).
