### ISSUE TITLE
Upgrading from operator version 20 to 21

### ISSUE THREAD

**Issue by scpcy** [keycloak/keycloak#17523]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

Upgrading from 20 to 21 is not possible as CRDs version is the same with major breaking changes.

### Version

20

### Expected behavior

Upgrading without the need to delete all Keycloak objects.

### Actual behavior

You need to delete all Keycloak objects.

### How to Reproduce?

Install operator version 20
Add Keycloak object for multiple keycloak deployments
Try to install operator version 21

**Comment by scpcy** [comment]
The problem occurs when we are trying to update from candidate channel 20-alpha (19.0.3 CRDs) to 21 (fast channel)

**Comment by Pepo48** [comment]
Hi @scpcy, can you, please, provide more information about the steps/commands you execute and the exact error message you get? Thanks!

**Comment by ptpcy** [comment]
hi @Pepo48 , i work with @scpcy.

the background is the following:
* we have multiple keycloak-operators running in the same cluster and we would like to upgrade *some* of them.
* currently all keycloak operators are on version 20-alpha of the **candidate** channel. the CRD version is `k8s.keycloak.org/v2alpha1`
* **important: keycloak operator v20-alpha candidate deploys keycloak version 19**
* we want to upgrade some of keycloak operators to version 21 of the **fast** channel. the CRD version is `k8s.keycloak.org/v2alpha1`
* there are breaking changes between the CRDs of the the two keycloak operators. this is an issue because CRDs are cluster resources, and as a result one version of the operator fails/breaks

issues:
what's the proposed upgrade plan, given that some of the operators must be running version keycloak operator v20-alpha candidate and others keycloak operator v21 fast?

**Comment by Pepo48** [comment]
Hi @ptpcy, thanks for the detailed explanation. I got confused initially, because based on the initial issue description I thought we talk about upgrading from version 20 to version 21. Just for the clarification, in the past we released the new keycloak-operator 18 and 19 as 20.0.0-alpha.x version in order to avoid conflicts with the legacy operator. This lasted until the keycloak-operator 20 release, where the legacy operator reached EOL and the new operator is recommended to use.

Based on what you mentioned you already use the new operator, which is great 😊. You mentioned Keycloak 19 which probably reflects to 20.0.0-alpha.4 version (or higher). Regardless, we're indeed talking about upgrading from Keycloak 19 to Keycloak 20/21.

As I stated in my previous answer, there were breaking changes between keycloak-operator 19 and 20. From the link above:

> _In order to use the newest version of the Keycloak Operator, the manual reinstallation and upgrade of your CRs are required. There’s no automated migration._

So that's my recommendation when it comes to upgrading from 19 to 20/21.
Let me know in any case.
Thanks!

**Comment by ptpcy** [comment]
@Pepo48 , thanks for the detailed response.

the problem is that given the breaking changes in the CRD it is not possible to have multiple versions of the keycloak operator running in the same cluster. this could have been avoided if the versions of the CRD were different.

* 20.0.0-alpha.4 `k8s.keycloak.org/v2alpha1`
* 20/21 `k8s.keycloak.org/v2alpha2`

thanks!

**Comment by Pepo48** [comment]
@ptpcy, I appreciate the issues caused by breaking changes. The thing is that the versions 18 and 19 of the new operator were tech preview releases. With the version 20 (which was the first non-tech preview release) we added new functionality as well as a number of improvements, which some of them resulted to the breaking changes.

Thus, we strongly recommend to you to use a newer version of the operator. What you can do is to delete the old operator (while the deployment can still run) and deploy a new one, which will then override the CRDs.

**Comment by ptpcy** [comment]
noted with thanks.
