### ISSUE TITLE
Theme resource common path is always /keycloak/common

### ISSUE THREAD

**Issue by brecht-vermeersch** [keycloak/keycloak#17569]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

My theme properties are:
```
parent=base
import=common/doqmind <<<<<
styles=style.css
stylesCommon=style.css
```

The url loaded for the commonpath is always /common/keycloak/style.css.

I think the bug is caused by these lines of code:
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/forms/login/freemarker/model/UrlBean.java#:~:text=getResourcesCommonPath

```java
  public String getResourcesCommonPath() {
        URI uri = Urls.themeRoot(baseURI);
        return uri.getPath() + "/common/keycloak"; <<<<<<
    }
```

### Version

21

### Expected behavior

the import specified in the theme properties get used

### Actual behavior

it always uses the keycloak/commons

### How to Reproduce?

/

**Comment by gvonroten** [comment]
@mposolda
This change seems to break our theme: We have a common folder for things to use in login and account, so we have import=common/<themename> in our theme.properties. The change in this issue means that now things in common/keycloak are not found anymore (for example, there is a 404 for node_modules/patternfly/dist/css/patternfly.min.css because it is looking for it in common/<themename>).
What would be the correct way for us to configure our theme so that we can use our own common files but also common/keycloak files?

**Comment by douglaspalmer** [comment]
The fix for this was incorrect. Common path should not be set by the value of import. https://github.com/keycloak/keycloak/pull/20873 introduces a separate property "common" to override the common path.
