### ISSUE TITLE
`JpaUserProvider` count methods are inconsistent with `searchForUser`'s param filter handling

### ISSUE THREAD

**Issue by shankaryadavy9** [keycloak/keycloak#17581]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

Hello Keycloak team,

I have implemented a custom user federation in Keycloak 20.0.5, which is backed by some external services. Everything was working fine until I added some clients with service accounts enabled. The issue I'm facing is that the **firstResult** parameter is always being calculated incorrectly. Specifically, when I click on the next page in the admin console or hit the admin API with parameters like **first=20&max=20**, the **firstResult** variable value is calculated as **(first - no of service accounts)**. I have tested this many times and confirmed that the issue only arises when clients with service accounts are enabled.

When I remove all clients with service accounts, the **firstResult** parameter is calculated correctly, and everything works as expected. However, this is not a feasible solution for my use case as I need to have service accounts enabled for some clients.
![image](https://user-images.githubusercontent.com/43490933/224482467-da0cc2e3-fb03-417e-a868-180ac0955a97.png)

I believe that this issue is causing problems with my custom user federation implementation and breaking my integration. I would appreciate it if you could look into this issue and provide any guidance or advice on how to resolve it.

Thank you for your help.

### Version

20.0.5, 21.0.1

### Expected behavior

**firstResult** parameter must have the exact value passed from the API call.  

### Actual behavior

**firstResult** parameter is influenced by services accounts

### How to Reproduce?

Just add a custom user federation, a couple of clients with service a/c and click two times on the next page in the admin console

**Comment by mhajas** [comment]
The cause of this is that this:
https://github.com/keycloak/keycloak/blob/2bb9de1a8cff4acdf33851a9c9856ff9be483c71/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L672-L699

works differently than this
https://github.com/keycloak/keycloak/blob/2bb9de1a8cff4acdf33851a9c9856ff9be483c71/model/jpa/src/main/java/org/keycloak/models/jpa/JpaUserProvider.java#L798-L865

We should refactor this so all methods using params work the same way.

More specifically, this issue is caused by the fact that count methods do not honour `keycloak.session.realm.users.query.include_service_account` filter parameter.
