### ISSUE TITLE
[UX Review] Align the question mark with the tag in the Export tab

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak#17696]
In the Export settings page, the question mark and the tag should be in one row. So we can align the question with the tag.

<img width="1054" alt="Screen Shot 2022-02-14 at 11 05 38 AM" src="https://user-images.githubusercontent.com/53931519/153793887-f53194aa-b7f2-48c4-b13c-f8aa491667d8.png">

# This is blocked on https://github.com/patternfly/patternfly/issues/5168

**Comment by agagancarczyk** [comment]
> Hi @agagancarczyk! We are still working on a fix for this issue in Patternfly.
> 
> I investigated this bug on the react side (see [patternfly/patternfly-react#8140](https://github.com/patternfly/patternfly-react/pull/8140)), however following the discussion in that PR, we determined that the solution is not on the react side and will likely require breaking-change CSS updates ([see issue here](https://github.com/patternfly/patternfly/issues/5168)).
> 
> This issue has been prioritized by the core developers for our upcoming breaking change release.

Hi @jenny-s51 could you please let me know if there is any progress on this? Thanks a mill!

**Comment by jonkoops** [comment]
I'd prefer not to load font icons where possible, they come with a performance penalty of loading all icons, even if you use only a couple. They also have to be fully loaded before they can be presented, where an in-line SVG can be shown immediately, avoiding layout shifting and content flashing. It also requires additional `aria` attributes, as otherwise screen readers interpret it as text.

**Comment by agagancarczyk** [comment]
Thanks @jenny-s51 & @jonkoops !

Due to PatternFly not providing a fix, and the workaround not meeting our expectations, I am closing this issue.
