### ISSUE TITLE
"Test authentication" doesn't work for an existing user federation provider (LDAP)

### ISSUE THREAD

**Issue by flipp5b** [keycloak/keycloak#18321]
### Describe the bug

"Test authentication" button shows an error message for an existing user federation provider (LDAP): "Error when trying to connect to LDAP. See server.log for details. LDAP test error". It looks like Keycloak sends the wrong password during the test.
If we switch back to the old admin UI, the same button works fine. It shows a "Success! LDAP authentication successful" message.

### Version

17.0.1

### How to Reproduce?

1. Create a new user federation provider (LDAP) and close an editor.
2. Choose the newly created provider in a list and open it for editing.
3. Click on "Test authentication" button.
4. See an "Error when trying to connect to LDAP. See server.log for details. LDAP test error" message in a popup.

**Comment by 297297sid** [comment]
Describe the bug
"Test authentication" button shows an error message for an existing user federation provider (LDAP): "Error when trying to connect to LDAP. See server.log for details. LDAP test error". It looks like Keycloak sends the wrong password during the test.
If we switch back to the old admin UI, the same button works fine. It shows a "Success! LDAP authentication successful" message.

Version
17.0.1

Expected behavior
No response

Actual behavior
No response

How to Reproduce?
Create a new user federation provider (LDAP) and close an editor.
Choose the newly created provider in a list and open it for editing.
Click on "Test authentication" button.
See an "Error when trying to connect to LDAP. See server.log for details. LDAP test error" message in a popup.
Anything else?
 same issue
