### ISSUE TITLE
Updating client property "baseUrl" leads to NullPointerException

### ISSUE THREAD

**Issue by dierberg** [keycloak/keycloak#19081]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

PUT to https://localhost:8080/realms/DFE/clients-registrations/default/ \<clientId\>

with valid access token and body    ' { "baseUrl" : "http://1.2.3.4" } ' gives a NullPointerException in 

{
  "log": "\tat org.keycloak.services.clientregistration.policy.impl.ClientScopesClientRegistrationPolicy.beforeUpdate(ClientScopesClientRegistrationPolicy.java:71)\n",
  "stream": "stdout",
  "time": "2023-03-16T15:15:46.856999256Z"
}

### Version

20

### Expected behavior

Update is accepted

### Actual behavior

Error  500 : {"error":"unknown_error"}

### How to Reproduce?

Try to update baseUrl of an existing client

**Comment by mposolda** [comment]
Adding to Backlog with label `Help wanted`. Keycloak team won't have time to look at this in the near future. But community contribution is welcome to look at it and eventually fix it. See the "Contributors" section under https://www.keycloak.org/community .

It seems that NPE happens on this line - probably because client is null and wasn't correctly established:
```
List<String> requestedDefaultScopeNames = context.getClient().getDefaultClientScopes();
```

It looks like a usage problem (maybe client authentication failed during sending ClientRegistration request or something), but Keycloak should handle this in better way that throwing NPE and rather display some more friendly message

**Comment by dierberg** [comment]
It's a empty/missing body of http request that causes the NPE.

**Comment by jonkoops** [comment]
If you have a good idea on how to fix this feel free to open a PR for @dierberg. That would help us out a lot.
