### ISSUE TITLE
Impossible to filter group by name using kcadm get groups with -q flag

### ISSUE THREAD

**Issue by J-Are** [keycloak/keycloak#19138]
### Describe the bug

Hi,
I am trying to get information of specific group using this command from a Kubernetes pod using **docker.io/jboss/keycloak:14.0.0** image:`kcadm get groups -r <my_realm> -q name=<groupname>` (kcadm is an alias for /opt/jboss/keycloak/bin/kcadm.sh_).
Unfortunately, the comand returns all the groups in my realm but it did not filter by name as expected.

Another strange thing is if I run with -q flag setted on toto, it also returns all the groups:
`kcadm get groups -r <my_realm> -q name=toto`

I don't understand why -q flag works for get users command, e.g: `kcadm get users -r <my_realm> -q username=<username>`

Thank you in advance for your help
Julien

### Version

14.0.0

### Expected behavior

bash-4.4$ kcadm get groups -r sdp -q name=group-one
[ {
  "id" : "<id_1>",
  "name" : "group-one",
  "path" : "/group-one",
  "subGroups" : [ ]
}
]

### Actual behavior

bash-4.4$ kcadm get groups -r sdp -q name=group-one
[ {
  "id" : "<id_1>",
  "name" : "group-one",
  "path" : "/group-one",
  "subGroups" : [ ]
}, {
  "id" : "<id_2>",
  "name" : "group-two",
  "path" : "/group-two",
  "subGroups" : [ ]
}, {
  "id" : "<id_3>",
  "name" : "group-three",
  "path" : "/group-three",
  "subGroups" : [ ]
}
]

### How to Reproduce?

- Deploy a keycloak install with 14.0.0 version.
- Run a container from docker.io/jboss/keycloak:14.0.0 image
- kcadm config credentials --server <url_of_your_keycloak_server>/auth --realm master --user <keycloak_admin_user> --password <keycloak_admin_password>
- Create multiple realm groups
- Run **kcadm get groups -r <my_realm> -q name=<groupname>**

**Comment by andre-nascimento-rh** [comment]
Hello, @J-Are ,

Thanks for your issue reporting.

I'm gonna investigate this issue by trying to reproduce the error.

I'll keep you informed.

Thanks in advance.

**Comment by andre-nascimento-rh** [comment]
@J-Are ,

Sorry, unfortunately, given our limited team resources, I still didn't find time availability to try to reproduce this issue, but I hope to make this test in the next upcoming days. 

Thank you for your understanding.

**Comment by vmuzikar** [comment]
Since this issue is more related to the REST API limitations, reassigning to core.

**Comment by rmartinc** [comment]
Hi everybody!

The `kcadm` get operation uses the `-q` or `--query` parameter to add query parameters to the call. The parameters you can add are the ones that the endpoint manages (you can check the [rest api](https://www.keycloak.org/docs-api/23.0.4/rest-api/index.html) for the valid query parameters you can use). So for example to find an exact group via name you need to do something like:

```
./kcadm.sh get groups -r <realm> -q search=<group-name> -q exact=true
```

For example in my laptop:

```
./kcadm.sh get groups -r master -q search=parent -q exact=true
[ {
  "id" : "7135b8d8-9214-4b75-99ed-394b7bf05017",
  "name" : "parent",
  "path" : "/parent",
  "subGroupCount" : 1,
  "subGroups" : [ ],
  "access" : {
    "view" : true,
    "viewMembers" : true,
    "manageMembers" : true,
    "manage" : true,
    "manageMembership" : true
  }
} ]
```

You are using the query parameter `name` which is not defined in the groups endpoints (the only query parameters are briefRepresentation, exact, populateHierarchy, q and search). So that parameter value does nothing and performs the default search.

I'm closing this as I think this was not understood OK.
