### ISSUE TITLE
Sort subgroups

### ISSUE THREAD

**Issue by npriebe** [keycloak/keycloak#19348]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Hi,

I have updated my Keycloak from 19.0.2 to 21.0.1.
Now I have the problem that the groups are not sorted. It doesn't matter whether I create new groups or move existing ones.

However, if I now set up a new Keycloak instance, the sorting works properly when creating and moving groups.

Here an example of my groups:

![Screenshot from 2023-03-27 08-13-14](https://user-images.githubusercontent.com/54103655/227857072-3e598e0c-d969-40c4-ab89-5f10a4e56dd8.png)

### Version

21.0.1

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-

**Comment by vramik** [comment]
Hello @npriebe, thanks for the report. Could you please share more information regarding database you're using?

**Comment by npriebe** [comment]
Hi @vramik , my Keycloak is running under Docker for now the database is running under a MySQL server.
The server data are:

Server type: MySQL
Server version: 5.7.12 - MySQL Community Server (GPL)
Protocol version: 10
Server charset: cp1252 West European (latin1)

**Comment by vramik** [comment]
Thanks @npriebe, could you please elaborate a bit more on the sorting itself? I was digging in a code and found out that top level groups should be sorted by its name:https://github.com/keycloak/keycloak/blob/e9accaf387471d4baf227cb3a138ffdcc4a8474f/model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java#L38

while subgroups have no ordering what so ever (unless sorted by ui): https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/models/jpa/entities/GroupEntity.java#L31

I got consistent finding with both migrating from 19.0.2 to 21.0.1 and 21.0.1 started from scratch.

If the issue is about sorting subgroups, I'll change it enhancement.

**Comment by npriebe** [comment]
Thank you for your efforts @vramik

I had tested this again and as it is described in the code, the top groups are sorted cleanly.
Furthermore, I had also looked again since which version the groups already exist in my keycloak. I have been using Keycloak since version 4.8.2 and in this version the groups already existed. Maybe they were already in the wrong order at that time.

I had also set up a completely new keycloak from scratch, where these problems did not occur afterwards. So it could really have been a problem with the group UI at the time.

It would therefore make sense if the sub-groups were also sorted by name as standard, so that this is consistent with the top groups.

**Comment by vramik** [comment]
Thanks @npriebe, I agree it makes sense to sub-groups to be sorted as well. As it's not a regression I'll switch the issue to enhancement.

**Comment by transducer** [comment]
We would also like to see sorted subgroups.

**Comment by npriebe** [comment]
@vramik In which version will the improvement be available? Could you possibly add a milestone to the issue?

**Comment by vramik** [comment]
@npriebe it should be available in 23.0.0.
