### ISSUE TITLE
id_token_hint param is rejected in PAR request

### ISSUE THREAD

**Issue by frelibert** [keycloak/keycloak#19355]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

id_token_hint is an optional request param on the auth endpoint, as defined in the oidc spec.
It is accepted and available in authenticators when using the standard keycloak /auth endpoint.
However, when using PAR, this parameter is rejected because it is not listed as a known parameter (which it should be as it is defined in the oidc core specification) and therefore limited to 200 chars, which is too little considering an id_token_hint is a signed jwt.

### Version

18.0.2

### Expected behavior

Regardless whether using the standard auth endpoint or the PAR endpoint, request params as defined in the specs, should be available in the session during authentication flow processing.

### Actual behavior

id_token_hint is not available as it is rejected because not seen as a known parameter and therefore limited to 200 chars.

### How to Reproduce?

ad a real encoded id_token as id_token_hint (should be more then 200 chars) to a PAR request.

### Anything else?

Fix to apply:

[https://github.com/keycloak/keycloak/blob/aa9744246c634a408ac3fa30fb8d0f2d82aee060/services/src/main/java/org/keycloak/pr
otocol/oidc/endpoints/request/AuthzEndpointRequestParser.java#L78](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java#L78)

Add a line to set the id_token_hint if it was added to the request

allready exists: OIDCLoginProtocol.ID_TOKEN_HINT
property idTokenHint to add in request object: https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthorizationEndpointRequest.java

**Comment by frelibert** [comment]
Not to forgetl
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java#L299
The updateAuthenticationSession should also add an authNote if id_token_hint was set.

**Comment by frelibert** [comment]
Not to forgetl
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/endpoints/AuthorizationEndpoint.java#L299
The updateAuthenticationSession should also add an authNote if id_token_hint was set.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. So I am adding to Backlog. Anyone is welcome to send the PR with fixing it (after confirm that this is still reproducible and is valid issue). See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

@frelibert Since you already almost figured it, maybe you can send PR for this? There is also `ParTest` in our testsuite where the new automated test for this can be possibly added.

**Comment by frelibert** [comment]
Thank you for your answer.
I'll take some time to prepare a PR.

**Comment by mposolda** [comment]
It will be good to at least make sure that `id_token_hint` parameter doesn't throw the error in PAR request when used.

Even better might be to properly support `id_token_hint` parameter and hence establish the used username based on the `id_token_hint` and hence for instance make sure that user is prefilled on the username/password form. However this might be quite complex task and hence not strictly needed for solving this issue.

**Comment by arso** [comment]
> @frelibert Since you already almost figured it, maybe you can send PR for this? There is also `ParTest` in our testsuite where the new automated test for this can be possibly added.

Hi @mposolda, I have been trying today to fix this issue. However, I hit the the small roadblock that  comes from my lack of knowledge of the code base and keycloak domain itself. 
As per suggestion I had a look into `ParTest` where I simply  [copy pasted one of the cases](https://github.com/keycloak/keycloak/pull/23323/files#diff-6c02727cf1d6bc6bf0794fa7db2a987349398cae2468c2e0b0b33bd118f70724) what uses successful login with PAR parameters and added a random string to `id_token_hint`.  With debugger attached I can see that after my changes this param is not filtered out, nor trimmed. However, I  was unable to find how to verify this from the test perspective. 

My current understanding (please correct me if I'm wrong), after reading the specs, is that `id_token_hint` is used on logout so  effectively what I would have to do would be to call ` oauth.doLogout(...)` and somehow do assert there. 

Do you have tips where to look at ?

**Comment by mposolda** [comment]
@arso Hi, just to clarify the `id_token_hint` parameter can be used in both:
- OIDC authentication endpoint as described in https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
- OIDC logout endpoint as descrined in https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout

I think it has different usage on both places. During logout, you can use `id_token_hint` in logout endpoint as a prove that logout endpoint was called by proper user and client (CSRF protection). Also it helps to identify client to redirect after successful logout. This is what we already support in Keycloak.

For login, the `id_token_hint` can be possibly used as a "hint" for authentication. Maybe it is possible to prefill some parameters on login form (EG prefill username based on the user from provided IDToken) or something else. Right now, we didn't support `id_token_hint` and we threw an error, which is what this bug is about. Your fix should help that error is not thrown, which is good. We still don't have proper support with `id_token_hint` with your fix, but that is fine. At least, the error is not thrown.
