### ISSUE TITLE
email is missing from account service

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#19401]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

`email` is no longer present in the `/realms/<realm>/account/` service.

### Version

21.0.1

### Expected behavior

`email` should be present as a named field, and there should be an entry in the `userProfileMetadata` attributres.

### Actual behavior

`email` is missing from the json response, both the named field and the `userProfileMetadata` attributes

### How to Reproduce?

In realm settings, set email as username
![image](https://user-images.githubusercontent.com/244253/228450473-9f8f1f8c-191e-405b-916c-3e8870f5f485.png)
set user profile enabled
![image](https://user-images.githubusercontent.com/244253/228450574-317e6bf9-d422-41c6-a931-4829af24bf82.png)
and verify/add that there is an email attribute in the user profile tab
![image](https://user-images.githubusercontent.com/244253/228450687-43e9f511-6618-4882-a5f2-3ad74ea6c07d.png)

Load the account console and log in as a user that has an email address set. Have the network tab open. See that email is not populated in the personal info form
![image](https://user-images.githubusercontent.com/244253/228450918-3313f20f-1496-42fa-83a7-baacb9c8e2c4.png)
and the email is missing from the json response, both the named field and the `userProfileMetadata` attributes
![image](https://user-images.githubusercontent.com/244253/228451090-f215253a-c2dd-4096-a051-aa9b6d62a89f.png)

**Comment by jsorah** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  

I can verify this issue still exists in 21.1.1, and one additional detail I'll add is when the e-mail is marked verified under the conditions mentioned in the initial report the `verified` param is never set to `true` in the account response.

If you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by xgp** [comment]
Thanks @jsorah I'll look to see if I can find out where the bug is happening.

**Comment by pedroigor** [comment]
Hey, @xgp. The original issue should be [fixed](https://github.com/keycloak/keycloak/pull/22326) and available since 22.0.0. As we are close to release 22.0.2, I would ask you to check the latest.

However, the UI is not showing the email field when its value is set to null. Regardless if the user profile setting is enabled or not. I'm looking into that.
