### ISSUE TITLE
Custom User Storage Provider doesn't look up users after saving changes

### ISSUE THREAD

**Issue by sasin-jonas** [keycloak/keycloak#19638]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

When using a custom user provider and configuring it, everything works as expected.
I am able to log in with users from this federation and I can see them in the 'Users' tab.

After trying to edit the provider (User federation -> Provider details) and saving changes, the provider no longer works as expected. (It is enough to 'fake' the changes - delete a single letter and revert - then save)

- I can still see the logs from the UserStorageProviderFactory `getConfigProperties()` and `validateConfiguration()` methods implementations
- I can no longer see the logs from the factory `create()` method (which was visible and invoked before the changes)

This problem started occurring after upgrading from 18 to 21

Current workaround:

- delete the provider and configure it again
- disable and re-enable the provider (yes, this is enough for it to start working again)

I tried running KC with debug logs but can't see anything meaningful.
I do not see any problem with the plugin implementation (I was trying to check with the reference implementation: https://github.com/dasniko/keycloak-extensions-demo/tree/main/peanuts-userprovider)

### Version

21.0.1

### Expected behavior

Custom user provider still works as expected after saving changes.

### Actual behavior

The provider is fetching its configuration but is not invoked for searching the users.

### How to Reproduce?

- Keycloak extension for custom user provider
- configure a working example
- make changes to the configuration (or just fake changes) and save
- the keycloak doesn't invoke the implementation of the storage provider's `UserStorageProviderFactory` `create()` method
- after disabling and enabling the provider, everything should work again

**Comment by skreim** [comment]
We observed the same issue after upgrading from Keycloak 20.x to Keycloak 21.0.2.

I can also confirm that the `UserStorageProviderFactory#create` method is no longer invoked after applying a configuration change. The configuration change itself is properly processed and stored in the database and also the updated attributes are correctly shown afterwards.

The only workaround we found was deleting and re-creating the storage provider (which has other negative side effects for us because the component gets a new UUID assigned). 

From our point of view this is a critical regression.

**Comment by vramik** [comment]
I can confirm I was able to reproduce the issue.

**Comment by martin-kanis** [comment]
After debugging this I found the problem is most likely in UI. After creation of user storage provider, admin console sends a request with `enabled: ["true"]` 

![Screenshot from 2023-05-22 11-03-32](https://github.com/keycloak/keycloak/assets/3359545/d742fbe4-3765-45c7-92e3-ec56425356a5)

But when updating a user storage provider, there is `enabled: ["t"]`

![Screenshot from 2023-05-22 11-04-47](https://github.com/keycloak/keycloak/assets/3359545/e5506051-a2ae-4691-8757-e12ff38346a4)

This is then interpreted as `false` in CacheableStorageProviderModel#isEnabled by `Boolean.valueOf(val)`.

@jonkoops Given this is a "Keycloak 22" issue, can UI team asses/fix this with priority?

**Comment by martin-kanis** [comment]
@ssilvert FYI
