### ISSUE TITLE
Refresh token have a negative exp claim because TokenManager is vulnerable to integer overflow for long lasting sessions (YEAR 2038 bug)

### ISSUE THREAD

**Issue by ghilainm** [keycloak/keycloak#19671]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

Refresh tokens (access tokens probably also impacted) are generated with a negative expiry timestamp when the SSO session max length is set to a big value (several years).

The bug is located here in TokenManager class.

            int sessionExpires = userSession.getStarted()
                + (userSession.isRememberMe() && realm.getSsoSessionMaxLifespanRememberMe() > 0
                    ? realm.getSsoSessionMaxLifespanRememberMe()
                    : realm.getSsoSessionMaxLifespan());
            expiration = expiration <= sessionExpires ? expiration : sessionExpires;

This is known as year 2038 issue. https://en.wikipedia.org/wiki/Year_2038_problem

### Version

21.0.2

### Expected behavior

The expiry of the token is properly set.

### Actual behavior

The expiry of the token is set in the past.

### How to Reproduce?

Set a very long value for SSO max session and get a refresh token, for example 5400 days.

**Comment by jsorah** [comment]
Thanks for the report, but unfortunately due the amount of other reported issues and other priorities, Keycloak team does not have time to properly triage this bug. So preliminary added to Backlog for now.  

If you know how to fix it, you're welcome to contribute the fix for this. See the "Contributors" section here [https://www.keycloak.org/community](https://www.keycloak.org/community) for the details on how to contribute to Keycloak and eventually send the PR.

**Comment by bvandaele** [comment]
The same behavior is present in the KEYCLOAK_IDENTITY cookie returned to the web browser braking cookie authentication (see #25904).

**Comment by bvandaele** [comment]
The issue with token expiration seems to be fixed with commit ecf5228 which moved the computed expiration timestamp from int to long.
But it is still present on the cookie which is computed in org.keycloak.services.managers.AuthenticationManager where int is still used to hold the expiration timestamp.

**Comment by bvandaele** [comment]
It seems to be also due to the use org.keycloak.representations.AccessToken::expiration in org.keycloak.services.managers.AuthenticationManager::createIdentityToken  which use deprecated org.keycloak.representations.JsonWebToken::expiration.
org.keycloak.representations.JsonWebToken::exp should be used instead

**Comment by markbanierink** [comment]
I have created a PR to fix this: https://github.com/keycloak/keycloak/pull/27715
