### ISSUE TITLE
Account console v3 doesn't hide email field.

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#19791]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

In account console V3, if I go to user profile and set `email` to be not viewable, I will still see it in the V3 account UI.

### Version

main

### Expected behavior

email hidden

### Actual behavior

email seen

### How to Reproduce?

See above

**Comment by edewit** [comment]
To fix this we need a server side change as currently this information is not available in the account console api. I suggest that fields that shouldn't been visible for the user to not be in the response then no UI change is needed

**Comment by edewit** [comment]
So little bit more investigation it might be wrong, but it's only hidden when you can't edit it. I don't know, but what would you expect when you can edit, but you can't view the property?

**Comment by ssilvert** [comment]
I think we need to first consider what the REST API should return.  If the user can't view the attribute then the UI should never learn anything about it.  It's like the attribute doesn't exist.

If you can view but not edit, the REST API should let you know that.  It would send the attribute value but let the UI know that it should display as read-only.

If you can edit, but not view, then the only way the user can change the attribute is through a naked API call.  The UI should not know anything about it.  I kind of wonder if there is a use case for that.

**Comment by edewit** [comment]
@pedroigor something you could have a look at?

**Comment by pedroigor** [comment]
@edewit I'm closing this one because the permissions for the `email` attribute are now manageable through the user profile so that the metadata reflects how you set them.

However, the  `email` attribute is a special attribute in the sense that write permissions depend on whether the `update-email` feature is enabled or not. When this feature is enabled, the attribute is always marked as read-only because email updates should happen through a AIA.

That said, I'm closing this issue.
