### ISSUE TITLE
introspection_endpoint getting internal server error

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#19832]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I am using [keycloak operator v21.0.2](https://www.keycloak.org/operator/installation)
when i try to access `https://test.keycloak.org:8443/realms/master/protocol/openid-connect/token/introspect` getting An internal server error has occurred.

![image](https://user-images.githubusercontent.com/48629246/233301691-7d5984af-a8bd-42d1-89d9-409abccb0e57.png)

![image](https://user-images.githubusercontent.com/48629246/233301213-40877ce6-e5a3-49c5-8d33-62f6ec049101.png)

can one help me out here what is issue?

### Version

21.0.2

### Expected behavior

Should have return the `introspection_endpoint` value

### Actual behavior

NA

### How to Reproduce?

Install it from [here](https://www.keycloak.org/operator/installation)

### Anything else?

No

**Comment by sschu** [comment]
The introspection endpoint is an endpoint allowing you to introspect a token generated by Keycloak (see https://datatracker.ietf.org/doc/html/rfc7662). It has to be accessed using a POST request passing the token to be introspected. Since you are accessing the endpoint with a GET request, Keycloak correctly responds with status code 405 "Method not allowed". So this is not a bug.
