### ISSUE TITLE
When creating a client with a long description or long name (longer than 255 chars) the API 500s with "unknown_error"

### ISSUE THREAD

**Issue by savage-alex** [keycloak/keycloak#19931]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/api

### Describe the bug

When testing client creation I used lorum ipsum to put a reasonable description in and found no API string length validation and a 500 instead. 

### Version

17

### Expected behavior

Sending strings in bodies that are longer than the permitted length results in a 400 bad request with the validation error shared with the client

### Actual behavior

500 unknown_error

### How to Reproduce?

using postman create a client with the following body
{
"attributes": {},
"clientId": "{{$randomUUID}}",
"name" : "testing client creation",
"description" : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, asdasdsa",
"publicClient" : "false",
"protocol": "openid-connect",
"serviceAccountsEnabled" : true,
"standardFlowEnabled" : false,
"directAccessGrantsEnabled" : false
}

Reducing the string length to 255 it works fine

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably doesn't have time to look at this in the near future. Anyone is welcome to send the PR with fixing it. See the "Contributors" section here https://www.keycloak.org/community for the details on how to send the PR for this.

**Comment by PhilKes** [comment]
@mposolda I tried to take a look at this issue, but I am not sure yet what's the best way to fix this.

My first idea was to simply add the validation of the `description` and `clientId` maxLength in the 
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/services/src/main/java/org/keycloak/validation/DefaultClientValidationProvider.java#L131-L151

But the problem is the Exception that is thrown occurs in
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/services/src/main/java/org/keycloak/services/resources/admin/ClientsResource.java#L187
To be more specific:
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L348-L353
The `setProtocol` calls:
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/model/jpa/src/main/java/org/keycloak/models/jpa/ClientAdapter.java#L266
Which triggers the Exception to be thrown:
`Value too long for column "DESCRIPTION CHARACTER VARYING(255)"`

So adding the validation to the `DefaultClientValidationProvider.java` doesnt catch the Exception.

Should these validations rather be added to 
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L312
and
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L507
?

Also what about the TODO comment from @stianst about introducing a dedicated library for these validations?
https://github.com/keycloak/keycloak/blob/5603ee7b4684aba1134ca439594be718019c089e/services/src/main/java/org/keycloak/validation/DefaultClientValidationProvider.java#L131

**Comment by savage-alex** [comment]
Have you thought of having an OpenAPI definition for keycloak and then you could use that to perform the validation of any provided json vs its schema at the API controller level?
