### ISSUE TITLE
Admin UI hangs with many subgroups

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#19954]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

This was reported internally by Engin Atick from Claudia's team.  He has groups with thousands of subgroups.  When he tries to open the group section, the UI hangs and then errors out.

I have reproduced this using partial import of a group with 10,000 subgroups.  The old UI seems to handle it better.  With the old UI, the response is slow but it does work.

Here is a json you can import to create the groups:
[groups-10000-in-subgroup.zip](https://github.com/keycloak/keycloak/files/11326066/groups-10000-in-subgroup.zip)

### Version

main

### Expected behavior

Groups display

### Actual behavior

Freeze and crash

### How to Reproduce?

Use attached json to do partial import.  Then open groups section.

**Comment by ssilvert** [comment]
With 10,000 groups in the root, it works fine.
[groups-10000.zip](https://github.com/keycloak/keycloak/files/11326101/groups-10000.zip)

**Comment by edewit** [comment]
This due to the fact that we add fine grained authorisation to the groups, we could have the same performance once we don't do that

**Comment by ssilvert** [comment]
> This due to the fact that we add fine grained authorisation to the groups, we could have the same performance once we don't do that

How did you determine this @edewit?
Did you try it with code where we don't add the fine-grained access object?
Why does having sub-groups matter?

Maybe there is a more efficient way to add the access object.  If the original query for the groups already included the access object then that would be much faster.  Right now, we have to walk the tree and do a new DB call for each group.  But again, if that's the issue, I don't see why having a subgroup would matter -- unless my tree-walking algorithm is wrong.

**Comment by edewit** [comment]
> How did you determine this @edewit?

Well the only difference is that we changed the endpoint, so that must be the reason

> Did you try it with code where we don't add the fine-grained access object?

Yes by querying with the same endpoint as used in the old console. The page gets really slow as it's adding to much objects to the dom, but it still works. With the extended endpoint it fails on the server with timeouts.

>Why does having sub-groups matter?

Because groups are fetched with all there subgroups:
![image](https://user-images.githubusercontent.com/51133/234785762-3f19b6fb-379e-451a-bb30-73cfc70ab0cf.png)

> Maybe there is a more efficient way to add the access object. If the original query for the groups already included the access object then that would be much faster. Right now, we have to walk the tree and do a new DB call for each group.

For sure, I didn't want to update the 3 different implementations of group repositories just to add this access object. This extension endpoint was always meant as a temporary solution to show the storage team what we need in terms of changed endpoints.

If we want to fix this my suggestion would be to revert this endpoint change and continue to use the old one

**Comment by ssilvert** [comment]
> 
> If we want to fix this my suggestion would be to revert this endpoint change and continue to use the old one

But that breaks fine-grained authorization.  We need another option.

**Comment by edewit** [comment]
partially solved by #19991

**Comment by Redhat-Alice** [comment]
On Claudia's team we have been investigating this again as we try to move towards implementing a basic level of multi-tenancy. From our investigation it seems that part of the issue could be how the groups are loaded when requested by the admin rest-api

Specifically we believe these methods to be part of the problem: https://github.com/keycloak/keycloak/blob/c28eba6382c2dbdc5b5211e51b761aaa5a1efb28/server-spi-private/src/main/java/org/keycloak/models/utils/ModelToRepresentation.java#L212C1-L227C6

If the UI requests 20 groups max, the first 20 top level groups are loaded. Then, each of these groups has their hierarchy loaded in full (without pagination), and added to the results if they match the filters. 

In the case that no search was applied, all sub-groups match and are added to the result. 

In the case where there are 20 top level groups that each contain 20 subgroups, 420 groups are then returned from the endpoint if a max of 20 groups are requested. 

This balloons out to the case where you have one top level group that has thousands (or tens of thousands) of subgroups as well. 20 groups are requested by default, but an unlimited amount are potentially returned in the response. 

We believe that the solution to this problem would be to overhaul the API and UI to allow for lazy loading of subgroups, pagination of subgroups, and to move the burden of filtering and matching subgroups to the database rather than loading the entire stream and filtering on them in the API. 

The last of these changes would allow for search to potentially load "bottom-up" and match the group needed and return it and its parents without loading its siblings. This would also take advantage of the database engine to perform these matches in a more optimized way.
