### ISSUE TITLE
Expiring events can be disruptive / clearExpiredEvents and clear should use a LIMIT

### ISSUE THREAD

**Issue by kosta** [keycloak/keycloak#20073]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

In our keycloak instance, we enabled "Login Events" a few years ago but never enabled Expiration. At some point we noticed, the events entities table was multiple Gigabytes then. Thus, we enabled Expiration after 90 days.

A few days later we received reports of users not being able to login, receiving a status code of 500. The logs showed "Lock wait timeout" SQLErrors. Basically, inserting a new event into the EVENT_ENTITY table was rejected as the table was locked. The cause of the lock was a long-running SQL query `delete from EVENT_ENTITY where REALM_ID='most-used realm' and EVENT_TIME<2023-01-21T14:26:34+01:00`. This query tried to delete > 10 million events in a single query - a recipe of disaster in a transactional database. In the end, we truncated the table (after saving the most recent events first) which fixed the issue. However, we had a small outage due to this behaviour.

The related code is still in main branch currently:
https://github.com/keycloak/keycloak/blob/main/model/jpa/src/main/java/org/keycloak/events/jpa/JpaEventStoreProvider.java#L91

I would propose that the these DELETE statements use a LIMIT (e.g. of 10000) and are repeated while a number of rows are equal to the limit are affected by it. I can try to provide a PR if you are interested and you can maybe guide me on how to adjust the tests.

### Version

current version is affected

### Expected behavior

Old events are deleted without performance impact.

### Actual behavior

Deleting old events is very slow (can take multiple days) during which login events have a higher likelyhood to fail with http status 500 due to an SQLError.

### How to Reproduce?

* Insert 10 million rows into EVENT_ENTITY (can be "fake" events, but should have an EVENT_TIME older than e.g. 90 days)
* Run keycloak with Login Events enabled and expiration of e.g. 90 days
* See how the Sql query to clear old events is very slow
* See how login sometimes errors out with an SQLError e.g. "Lock wait timeout exceeded"

**Comment by jens-hammel** [comment]
We faced the same issue. Can somebody tell me if the problem is worse in a cluster because all instances try to run that expiration job.

**Comment by mposolda** [comment]
@kosta PR would be welcome.

I don't think that you need add automated test for this. The fact that functionality is still OK after your "tuning PR" is sufficient indication that it is OK. Leaving to you to test the limits in your environment if you have a chance. Also just a note that Keycloak has a tool, which allows to add big amount of various objects (like for instance events) into the DB. You can doublecheck it here: https://github.com/keycloak/keycloak-benchmark

**Comment by ashishtchaudhari** [comment]
Hi All,
This is indeed a problem. The customers not using auditing would not face the problem or even the customers with low user based would not face this. But we too observe this same problem in one of our customers environment. There are multiple issues as highlighted in the original thread.
a. In cluster environment all cluster tries to run the delete command which makes the matter worse.
b. If the table for event_entity is too big, if the delete query start getting into rollbacks, the data just keep growing.
c. There is no control on schedule as to when this deletion would execute. In our case, many times it start its execution in business hours causing quiet a bit of disruption.

The client has expressed his concerns over our services and we are tied with the limitations of Keycloak. While Keycloak is good in many aspects, in our scenario , this is leading to reputational damage.

I understand that the team is busy it other priorities , I would like to suggest the following which would potentially be a quick solution for now and help the environments where this is a big issue.
**Short term solution**
a. Allow the control to disable the expiration of events. The admins can write external scripts to clear the events. This will solve problem of inefficent query and also multiple queries getting executed in cluster environment.

**Long term solution**
a. As suggested in previous thread allow admin to give parameter for batched deletes.
b. Update the code to make sure that in cluster multiple executions do not happen. This can be done by using a table to control the schedule messages and indicate if a cluster node has picked up the message. If it has, then others cannot pick it.
b. Allow to define a schedule so that admins are in control to let this execute outside the business hours.

This will help to increase the stability of the solution.

Regards,
Ashish Choudhari

**Comment by ashishtchaudhari** [comment]
> We faced the same issue. Can somebody tell me if the problem is worse in a cluster because all instances try to run that expiration job.

Yes it is. We do experience it day in day out. Current work around to make it execute out side business hours is to do weekly restarts of keycloak outside business hour time. That way internal 24 hour clock of scheduler gets executed during the same time for future runs and the impact is minimized.

**Comment by kosta** [comment]
> @kosta PR would be welcome.

Sorry I no longer work at the company that used keycloak and I dont have time to do this atm. Could someone else step in?

**Comment by ashishtchaudhari** [comment]
@stianst -- Sorry to tag you, but I have seen you as one of the most active person in the community. Do you think this can be taken up in near future.
