### ISSUE TITLE
Searching for multiple types in the Events section gives an error

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak#20135]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

The request that's being made is:
http://localhost:8180/admin/realms/master/events?first=0&max=11&type=SEND_RESET_PASSWORD%2CUPDATE_CONSENT_ERROR

it should be 
http://localhost:8180/admin/realms/master/events?first=0&max=11&type=SEND_RESET_PASSWORD&type=CUPDATE_CONSENT_ERROR

the error is that arrays are being "stringified"
https://github.com/keycloak/keycloak/blob/8cb202eb290bd258049e3ddbe0c5ec50169c3192/js/libs/keycloak-admin-client/src/utils/stringifyQueryParams.ts#L20

### Version

main

### Expected behavior

the right request being made, this is the only place where arrays are used

### Actual behavior

![image](https://user-images.githubusercontent.com/51133/236005325-45baa547-b12e-4bcf-b8aa-82ffea62c593.png)

### How to Reproduce?

go to the events section and search for 2 event types

**Comment by betalb** [comment]
Faced the same issue, but before admin client was migrated to this repo (when it lived in separate repo), there was a workaround: it was possible to provide custom query args serialiser, which I used. But after upgrade it is no longer possible.

Below is modified version of serialiser that I've used.
Issue is not in linked line of code, the issue is caused by the fact that URLSearchParams is expecting entries (keys and values) to be strings, so it does to string on them implicitly.

```
function stringifyQueryParams(params) {
  return new URLSearchParams(
    Object.entries(params).flatMap(param => {
      const [paramName, value] = param;
      if (typeof value === 'undefined' || value === null) {
        return [];
      }
      if (typeof value === 'string' && value.length === 0) {
        return [];
      }
      // Default keycloak client query params serializer
      // doesn't work for realms.findEvents correctly.
      // We need to serialize event types as URL array params
      if (Array.isArray(value)) {
        return value.map(v => [paramName, v]);
      }
      return [[paramName, value]];
    }),
  ).toString();
}
```
