### ISSUE TITLE
Wrong text when creating a sub group

### ISSUE THREAD

**Issue by theute** [keycloak/keycloak#20166]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I'm nit-picking here, but should the text be:
**No sub group in this group** instead of **No groups in this sub group**
And then:
**You haven't created any sub groups in this group.**
And then:
**Create sub group**

![image](https://user-images.githubusercontent.com/311855/236265825-eb0e8e55-d25d-4fb7-b1ad-72ee9323703c.png)

### Version

21.1.1

### Expected behavior

As explained above

### Actual behavior

As explained above

### How to Reproduce?

Go to create a group, then a sub-group

**Comment by ssilvert** [comment]
Personally, I think the wording should be consistent with the tab.  It should say, "No child groups for group X".

The second line of text is not even needed.

**Comment by ssilvert** [comment]
I'm sorry.  We are not going to change this.  It turned into a longer discussion and it's just not worth the time.  Thanks for your feedback.

**Comment by ewoerner** [comment]
Maybe reconsider the decision of not changing anything? I had a hard time figuring out what the UI is actually doing, because the labels are just *plain wrong*:
![image](https://github.com/keycloak/keycloak/assets/6642053/3a305529-4d5a-41f8-a0e9-1fd14fe5df73)
The text "this sub group" implies that my demo group "Top Level Group" (which is referred to by "this") is a sub group, which it isn't.
