### ISSUE TITLE
User defined message bundles do not apply correctly to Admin Console

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak#20182]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

When applying message bundles defined by the user in the realm settings these do not show up properly in the Admin Console.

### Version

main

### Expected behavior

When defining a message bundle with the key `foo:bar.baz` and value `Hello World` this should be merged into the localization of the Admin Console under the namespace `foo` with the following structure:

```js
{
  bar: {
    baz: "Hello World"
  }
}
```

### Actual behavior

The message bundle is applied flatly, meaning that `bar.baz` ends up as the key without transforming it into a nested object. This means that messages such as the [option labels](https://github.com/keycloak/keycloak/blob/e50580c46501f3269d74f567189472a34a9fcdf4/js/apps/admin-ui/public/locales/en/clients.json#L2-L6) of the protocol type of a client cannot be localized.

Similarly namespaces are not taken into account, so if a label is defined with the key `foo` it will replace all labels in **every** namespace with the same key name. This might cause unexpected behavior when namespaces expect different values for a similar key (e.g. "Create user" and "Create client" could share the same `createLabel` key in their respective namepaces).

### How to Reproduce?

1. Enable localization under realm settings
2. Add a new message to the bundle with a key that overrides an existing label.

**Comment by MetaMmodern** [comment]
@jonkoops hi, is this a regression kr something that was always in keycloak?
We have a keycloak 18 instance and in admin ui when I add a localization I see only key/value table. Is nesting keys and namespaces something that was added in later keycloak versions?

**Comment by MetaMmodern** [comment]
@jonkoops I honestly couldn't find any info in release notes that this is now possible, so if you can share any docs on this I'd appreciate it. And thank you for fixes:) looking forward to updates;)

**Comment by ssilvert** [comment]
> @jonkoops I honestly couldn't find any info in release notes that this is now possible, so if you can share any docs on this I'd appreciate it. And thank you for fixes:) looking forward to updates;)

I think this is what you are looking for?
https://github.com/keycloak/keycloak/blob/main/docs/documentation/release_notes/topics/22_0_0.adoc#changes-to-custom-admin-console-messages

Also, there are some screen shots [here](https://github.com/keycloak/keycloak/issues/19611#issuecomment-1568980050) that show how to set it up.

**Comment by MetaMmodern** [comment]
@ssilvert mhm, yes, but it's in kc 22. which is not released yet. But thanks anyway. 
Dunno about console messages, I'm primarily going to use keycloak localization to store translations for my client code(react code) which is being built and stored as theme. In client code I'll request the locale files with i18next-backend from the Admin API(or a third-party backend service that has access to admin api). But I'll translate console and error messages as well I think, cause they are used in react code.
That's why I was looking for support for namespaces and nested keys. I think i18next in react will successfully consume the json localization provided by keycloak. If anything goes wrong I'll ping here again.
