### ISSUE TITLE
Role mappers must return a single value when they are not multivalued

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#20218]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Both built-in realm and client role mappers are not properly handling the `multivalued` attribute. Instead, `string`-typed claims are always set using a stringified JSON array.

It is also not behaving similarly to other mappers that also allow configuring single/multi-valued claims.

### Version

21.1.1

### Expected behavior

When setting the `multivalued` to `false`, the claim value should be a single string. If based on a list, only the first element is considered.

### Actual behavior

When setting the `multivalued` to `false`, the claim is still represented as an array when the values come from a list.

### How to Reproduce?

* Change either the role or client role mappers to use single-valued claims (`multivalued==false`)
* Issue an access token for a user with multiple roles and note that a stringified JSON array is set to the claim

**Comment by pedroigor** [comment]
@mposolda Do you know why we are processing multivalued claims differently like this https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/mappers/AbstractUserRoleMappingMapper.java?

Looks like it's been there since https://github.com/keycloak/keycloak/pull/3859. I'm not sure if we should return a stringified JSON array when a claim is single-valued (same behavior as other mappers).

**Comment by mposolda** [comment]
@pedroigor AFAIK we process it differently because it was contribution from @thomasdarimont to support multi-valued this way (maybe due the integration with some other system..). And IMO it makes sense as roles are usually multiple values when some other attributes, which have mappers with `Multivalued: false` are usually single-valued user attributes.

@thomasdarimont Do you remember the use-case behind https://github.com/keycloak/keycloak/pull/3859 ?

I am not sure about backwards compatibility if we change the behaviour... As I suppose that there might be people using this, which expects that mapper would return something like:
```
"roles": "[my_role]" 
```
instead of:
```
"roles": "my_role" 
```
Do we want to introduce another switch for the behaviour like the 2nd one?

What should be done when there is multiple roles? Do we throw error or just add the 1st found role?

**Comment by mposolda** [comment]
@pedroigor @thomasdarimont One additional note: The tooltip for "Multivalued" for role mappers mentions this:
```
Indicates if attribute supports multiple values. If true, the list of all values of this attribute will be set as claim. If false, just first value will be set as claim
```
So in theory, we can break backwards compatibility and just change the behaviour to return only 1st role and avoid returning the array-like string.
@thomasdarimont Are you aware of any use-case, which would be broken by this change?

**Comment by thomasdarimont** [comment]
The use case behind #3859 was to be able to render a collection as explicit array instead of it's string representation.
I think the logic for just returning the first item when multivalued is set to false comes from working with multi-valued attributes. 

So given a value such as the result of `List.of("role1", "role2", "role3")`   with claim type set to `String`   the current implementation does the following:
- if `Multivalued=true`, then the claim value will be `["role1", "role2", "role3"]`
- if `Multivalued=false`, then the claim value will be `"role1"`

I'm currently not aware of another use-case for this. Since a "potential" multi valued attribute can currently be a List or a single string, client libraries will probably render this value as a List anyways (like is done for the aud claim).  So changing the implementation to return a list with a single item in that case might be okay.

**Comment by pedroigor** [comment]
I see.

Currently, we are actually returning a stringified JSON array when `multivalued` is set to `false` when mapping roles.

Looks like it is ok to return the first element (similar to other mappers) only as a string.

@thomasdarimont @mposolda However, does it make sense at all to make the built-in role mappers single-valued? Why you would want that? 

I would say the configuration will be simpler if we just expect roles mapped as a JSON array all the time.
