### ISSUE TITLE
keycloak-admin-client does not url-encode client id and secret for basic auth as defined in RFC6749

### ISSUE THREAD

**Issue by sschu** [keycloak/keycloak#20564]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/client/node

### Describe the bug

According to [RFC6749 section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1), client id and secret need to be URLencoded before being base64 encoded for basic auth.
This is related to https://github.com/keycloak/keycloak/issues/11908.

### Version

21.1.1

### Expected behavior

Client ID and secret are first URL-encoded and then Base64-encoded for basic auth.

### Actual behavior

Client id and secret are only Base64-encoded for basic auth.

### How to Reproduce?

Check source code.

### Anything else?

The respective code is  https://github.com/keycloak/keycloak/blob/7502a31421d8d80483cb840e35696dfb2634ba3f/js/libs/keycloak-admin-client/src/utils/auth.ts#L82

**Comment by jonkoops** [comment]
This is already taken care of by [this line](https://github.com/keycloak/keycloak/blob/7502a31421d8d80483cb840e35696dfb2634ba3f/js/libs/keycloak-admin-client/src/utils/auth.ts#L86), which will make the Fetch API encode this properly.

**Comment by sschu** [comment]
@jonkoops That would really surprise me - this should only have effects on the body of a request (and we are talking about basic auth headers here). Also the correct order is first url-encode and then base64 encode which is not what x-www-form-urlencoded is doing.

**Comment by jonkoops** [comment]
@sschu I can't seem to find any implementation looking around on the web that does this (at least in JS land). It seems that [Appendix B.](https://datatracker.ietf.org/doc/html/rfc6749#appendix-B) mentions this encoding should happen. But it also looks like this mime type is [now registered](www.iana.org/assignments/media-types).

Do you know of any implementation you can reference that does it this way?

**Comment by jonkoops** [comment]
We were previously using Axios to do this for us, but we got rid of it because it was too heavy as a dependency. Looking at their code, it looks like they do [partially encode](https://github.com/axios/axios/blob/21a5ad34c4a5956d81d338059ac0dd34a19ed094/lib/adapters/xhr.js#L75-L79) at least the password for requests on the client. And [not at all](https://github.com/axios/axios/blob/21a5ad34c4a5956d81d338059ac0dd34a19ed094/lib/adapters/http.js#L351-L355) for code that runs in Node.js.

So it looks like this is widely implemented incorrectly in popular libraries, but that doesn't mean we can't do better. I'll re-open this and fix it. It would be really nice if there was some kind of standardized test suite for this spec that we could implement.
