### ISSUE TITLE
REST API Documentation ref wrong

### ISSUE THREAD

**Issue by stefanwendelmann** [keycloak/keycloak#20700]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

docs

### Describe the bug

https://www.keycloak.org/docs/latest/server_development/#additional-resources

->API Documentation 
-> https://www.keycloak.org/docs/21.1.1/api_documentation/#admin-rest-api-documentation
-> https://www.keycloak.org/docs-api/21.1/rest-api/ 
-> 404

Correct URL would be: 
https://www.keycloak.org/docs-api/21.1.1/rest-api/

Source File:

docs/documentation/api_documentation/topics/overview.adoc

### Version

21.1.1

### Expected behavior

Correct path to api docs

### Actual behavior

404

### How to Reproduce?

https://www.keycloak.org/docs/latest/server_development/#additional-resources

->API Documentation 
-> https://www.keycloak.org/docs/21.1.1/api_documentation/#admin-rest-api-documentation
-> https://www.keycloak.org/docs-api/21.1/rest-api/ 
-> 404

**Comment by jonkoops** [comment]
@stefanwendelmann feel free to submit a PR with a fix :+1:

**Comment by andregmoeller** [comment]
I quickly examined the issue to determine its cause. If you look at the [overview.adoc](https://github.com/keycloak/keycloak/blob/21.1.1/docs/documentation/api_documentation/topics/overview.adoc) file, you can see that the broken links are composed as follows
```
{apidocs_javadocs_link}[{apidocs_javadocs_name}]
{apidocs_adminrest_link}[{apidocs_adminrest_name}]
```

Upon investigating how `apidocs_javadocs_link` and `apidocs_adminrest_link` are formed, I discovered the following code:
```
:apidocs_javadocs_link: https://www.keycloak.org/docs-api/{project_versionDoc}/javadocs/
:apidocs_adminrest_link: https://www.keycloak.org/docs-api/{project_versionDoc}/rest-api/
```
see https://github.com/keycloak/keycloak/blob/main/docs/documentation/topics/templates/document-attributes.adoc#L81-L83

Consequently, the issue seems to lie with the value of `project_versionDoc`. By searching for ":project_versionDoc:" in [21.1.1](https://github.com/keycloak/keycloak/tree/21.1.1), I found several [document-attributes.adoc](https://github.com/keycloak/keycloak/blob/21.1.1/docs/documentation/topics/templates/document-attributes.adoc#L8) files that contain the line `:project_versionDoc: 21.1`. When examining the [files](https://github.com/keycloak/keycloak/blob/main/docs/documentation/topics/templates/document-attributes.adoc#L8) in branch main, the value `DEV` is assigned to `project_versionDoc`. So it might be an automatic process that sets the wrong value. Performing a blame on a tagged 21.1.1 version of [document-attributes.adoc](https://github.com/keycloak/keycloak/blame/21.1.1/docs/documentation/topics/templates/document-attributes.adoc#L8) revealed that the change was introduced with the commit ["Set version to 21.1.1"](https://github.com/keycloak/keycloak/commit/0ca0a5fa4459d97c4d769fec15b4ba99c3824314), seemingly originating from a GitHub action.

Although I cannot determine the exact GitHub action responsible for this issue, it appears that the problem lies within this particular GitHub action.

**Comment by andregmoeller** [comment]
I am pretty sure, I found the problem: https://github.com/keycloak/keycloak/blob/main/set-version.sh#L17
