### ISSUE TITLE
[Declarative User Profile] Attributes tab doesn't dipslay attributes, values get lost and multi values get stored as single ones

### ISSUE THREAD

**Issue by jbman** [keycloak/keycloak#20837]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

user-profile

### Describe the bug

User attributes are no longer shown in the attributes tab.
![image](https://github.com/keycloak/keycloak/assets/789496/4aa35f24-081d-4e85-aff8-fae7575dd4d1)

They are only shown in the User details tab.
![image](https://github.com/keycloak/keycloak/assets/789496/bc3cdab4-131c-4ed3-93d3-00fc004ab1b3)

## Bugs

* When adding a user attribute at Attribute tab, other existing stored attribute values get lost
* When editing a multi value user attribute at the user details tab (e.g. modify "A,B" to "A,B,C", it is stored as single comma separated value "A,B,C")

### Version

21.1.1

### Expected behavior

- No data gets lost when adding attribute values
- Multi value attributes are not stored as single value when edited
- Attributes tab displays all stored attributes 

### Actual behavior

see section "Describe the bug" 

### How to Reproduce?

1. Define two attributes in the declarative user profile (in the screenshots above "tel" and "orgs" is defined).
2. Add "tel: 1111", "orgs: A" and "orgs:B" in the attributes tab
3. Modify "orgs: A,B" to "orgs: A,B,C" in user details tab will store it as "A,B,C"
4. Add attribute "tel: 1234" in attributes tab will delete the orgs value

**Comment by jbman** [comment]
If the User Details tab has a working multi-value support, the attributes tab is not needed any more in combination with declarative user profile. However without the profile, it is still needed to see or add any key. 
Therefor I think it would be fine to keep it always available (independent of User profile enabled or not.) It should display all stored values as it did in Version 20. Would be good if sorted by keys (which isn't the case in Version 20)

**Comment by ssilvert** [comment]
IMO, the attributes tab is always needed because you might want to store attributes that have nothing to do with User Profile.  These could be private attributes that don't show up on the user details page and/or don't show up in account console and registration.  So the attributes tab serves as a place to store metadata that is associated with a user.

I don't think User Profile is intended to have multi-value support at the moment but it might be something we want to do in the future?

I think this bug is caused by allowing the "metadata" attributes to overwrite the User Profile attributes (and vice versa).  The UI should not allow this.

@pedroigor @edewit Do you agree with what I said above?

**Comment by pedroigor** [comment]
@ssilvert This [filter](https://github.com/keycloak/keycloak/blob/483246e24b5120f089c8426ed643cd04ab46ed89/js/apps/admin-ui/src/user/UserAttributes.tsx#L38) is causing the attributes not shown in the attributes tab to be removed. As they are not sent, the server does a `PUT` and removes the attribute.

The problem with updating values through the user details page is due to the lack of multivalued attributes support there, so they are not sent as an array. As per discussed with @ssilvert.

The user profile is very strict about the attributes you can manage. If the attributes don't have metadata they are ignored and not persisted. Otherwise, they are "manageable" and their values are persisted through account and admin APIs.

However, @ssilvert mentioned the use case where you don't want to show specific attributes on the user detail page but manage them separately as they are very application or business specific. They might not make sense at that tab, so you would use the attributes tab for that. Not 100% sure if justifies having a separate tab for these specific attributes. I'm lacking valid use cases. Perhaps a different discussion.

**Comment by pedroigor** [comment]
If you do not change the multivalued attribute in the user details (e.g.: orgs) but only a single-valued (e.g.: tel), then the values are kept and the UI sends a request using a JSON array.

However, if you change the `org` attribute in the user details page, the value is sent from the UI as a string.

**Comment by Tristan971** [comment]
A couple of related quirks (in 21.1.1):

![2023-06-30 02_29_37](https://github.com/keycloak/keycloak/assets/875533/a8141e97-49bf-46e0-a287-29b40abe7bdd)

The username field is completely absent from the user view if username profile attribute permissions don't allow admin to view them.

![image](https://github.com/keycloak/keycloak/assets/875533/87bcf4ca-a2fc-4f77-b867-ca217d6093a1)

![image](https://github.com/keycloak/keycloak/assets/875533/a34345ec-dd09-4255-8534-7060ecc445e4)

Now that makes sense, and is actually a welcome change (having those permissions actually work). Though, interestingly:
- usernames were hidden when not viewable by user/admin
- emails were still visible even when not viewable by user/admin
- usernames show as editable when editable by admin, despite username change being disabled on the realm (and editing it just doesn't apply the change)

This is still generally going in the right direction imo (besides the fact that attributes should still probably be duplicated across both tabs).

Edit permission business (for usernames) relates to #16054 as well I'd say

**Comment by florianschiller** [comment]
Hello,

In some of our use cases, technical attributes are stored for our users. We want to show these attributes to our admins, but in the current implementation they overload the details page.
It would therefore make sense for us, instead of removing the attributes page when the declarative user profile is enabled, to be able to use annotations to control whether attributes are displayed on the details or attributes page. It would be highly appreciated if you could add the possibility for such an annotation.

**Comment by ssilvert** [comment]
> Hello,
> 
> In some of our use cases, technical attributes are stored for our users. We want to show these attributes to our admins, but in the current implementation they overload the details page. It would therefore make sense for us, instead of removing the attributes page when the declarative user profile is enabled, to be able to use annotations to control whether attributes are displayed on the details or attributes page. It would be highly appreciated if you could add the possibility for such an annotation.

I've gone back and forth on my opinion here.  But finally I've embraced the idea that the old attributes tab should go away when user profile is enabled.  The reason is that everything you wanted to do with the attributes tab can be done with user profile, only better.   I say better because with user profile you have many options to provide metadata that controls validation and also which UI controls are used to edit the data.

@florianschiller As for your use case, those technical attributes you describe could/should be defined in a separate attribute group.  Then those attributes will be rendered on the Details page in their own special section, complete with a "Jump" link.

I do foresee a use case where you have so many attributes that it won't make sense to display them all on the same tab.  Maybe that is your situation, @florianschiller?  So I could see us adding an annotation to an attribute group that gives the UI a hint that it should display the attribute group in its own tab.

**Comment by florianschiller** [comment]
Hello @ssilvert ,

Thank you for your quick reply.

> I've gone back and forth on my opinion here. But finally I've embraced the idea that the old attributes tab should go away when user profile is enabled. The reason is that everything you wanted to do with the attributes tab can be done with user profile, only better. I say better because with user profile you have many options to provide metadata that controls validation and also which UI controls are used to edit the data.

I agree with you. The more I think about the removal of the attributes page, the more I like the idea. Thinking back, one of our biggest obstacles while introducing the declarative user profile was, that new attributes just disappear, when they are not part of the declarative user profile. This circumstance was difficult to convey to our projects. Removing the attributes tab completely nullifies this issue, which makes the UI a lot more user friendly.

> @florianschiller As for your use case, those technical attributes you describe could/should be defined in a separate attribute group. Then those attributes will be rendered on the Details page in their own special section, complete with a "Jump" link.

Yes, that's the way we want to implement it now. It's not the best solution, because the attribute are still displayed while creating a user via the admin console and lead to confusion in our projects, but it alleviates the issue greatly.

> I do foresee a use case where you have so many attributes that it won't make sense to display them all on the same tab. Maybe that is your situation, @florianschiller? So I could see us adding an annotation to an attribute group that gives the UI a hint that it should display the attribute group in its own tab.

I'm currently talking about around 5 to 6 user attributes, which are created by some of our plugins and are therefore of a technical nature. It's not a lot, but they clutter the details page nonetheless. Such an annotation as you described would fully satisfy our use case.

**Comment by ssilvert** [comment]
@florianschiller User creation is a use case I had not thought of.  It does make sense that a user creation and/or registration screen could be simplified and you might not want all the attributes shown at that time.  Your use case of admins creating users is one situation.  And it's often the case that you want user registration to be as short as possible so you can get new users signed up without a lot of noise.

So it sounds like we are talking about two possible enhancements:
1.  Add the ability to specify that an attribute group should be shown on its own named tab.
2.  Add the ability to specify that an attribute should not be shown during user creation.

@pedroigor WDYT?

**Comment by edewit** [comment]
@ssilvert we should create a new issue for this?

**Comment by jbman** [comment]
In 22.0 there also still the issue that an array of values gets stored as one comma separated String.
Will 22.0.1 have some handling to retain array multi-values? Is there an issue for this?

**Comment by edewit** [comment]
@jbman there is a PR that will fix this when you add the right annotations https://github.com/keycloak/keycloak/pull/21180

**Comment by jbman** [comment]
Thanks @edewit for the Annotation solution. This means that adding annotations is needed as migration steps to prevent unwanted data modification by Keycloak admin users?
Would be better if upgrading doesn't bring this risk. If no annotation is present but field has array value, a default multi-value String component could be used.

Note: We operate many instances and on these instances many realms are managed by different admins. Would be difficult to analyze all attributes and add the annotations where appropriate.

**Comment by jbman** [comment]
Thanks, great to have array detection implementation within #21808!
