### ISSUE TITLE
Uncaught server error: java.lang.NullPointerException: Cannot invoke org.keycloak.protocol.LoginProtocolFactory.setupClientDefaults(org.keycloak.representations.idm.ClientRepresentation, org.keycloak.models.ClientModel) because providerFactory is null 

### ISSUE THREAD

**Issue by JoachimVeulemansSecuRoad** [keycloak/keycloak#20918]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

When adding a new client by importing a configuration file from VMWare Cloud Director, I am getting the following error:
`Uncaught server error: java.lang.NullPointerException: Cannot invoke org.keycloak.protocol.LoginProtocolFactory.setupClientDefaults(org.keycloak.representations.idm.ClientRepresentation, org.keycloak.models.ClientModel) because providerFactory is null `

I am using SAML.

Example tutorial: [configure-vcloud-director-to-use-keycloak-identity-as-saml-provider](https://bakingclouds.com/configure-vcloud-director-to-use-keycloak-identity-as-saml-provider/)

### Version

21.1.1

### Expected behavior

Keycloak should create the client with the settings in the XML file.

### Actual behavior

Keycloak error

### How to Reproduce?

Configure SAML on a VMWare Cloud Director
Export metadata
Import metadata when creating a new client
Click 'Save'
See error

**Comment by mposolda** [comment]
I am adding to Backlog as this is low priority issue and Keycloak won't be able to look into it into the near future. Anyone is welcome to investigate this and eventually contribute the fix for this if needed.

From the info provided, I am not even sure if it is the Keycloak issue. It can be rather as the issue of the 3rd party provider (VMWare Cloud Director) that it provides incorrect data. But not sure...

**Comment by Gerardwx** [comment]
I got the same error trying to import a configuration file from elasticsearch. 
[example.xml.txt](https://github.com/keycloak/keycloak/files/13649921/example.xml.txt)
