### ISSUE TITLE
Avoid calls to Control Plane when the secondary resource is in cache

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#21109]
### Description

We can avoid HTTP calls to the Control Plane kube-apiserver when the secondary resource is already in a cache. 

Also mentioned on this line, where the attached issue is already resolved:
https://github.com/keycloak/keycloak/blob/2beedcc4c7222ac8498e582ff3175a9e6f60f416/operator/src/main/java/org/keycloak/operator/controllers/KeycloakController.java#L106-L108C1

**Comment by shawkins** [comment]
I had worked through this a little more broadly with https://github.com/keycloak/keycloak/commit/39dda134bc6358bcb7545f79ce1f886d674111b6 but was getting ahead of myself since it was built on top of changes from #20933 which haven't been included yet.

The only real problems to usage of the cache are making decisions like the one in #20906 to delete the stateful set - if the statefulset is coming from the cache we'll want to do one final fetch before making the decision to delete the old one, or change the logic to be reactive to a 422 error.  Otherwise until the cache is updated, which in some corner cases may take a while, we'll keep re-deleting the statefulset if we're still getting other events.
