### ISSUE TITLE
During password reset, the baseURL is not shown on the info page after browser restart

### ISSUE THREAD

**Issue by pxnis** [keycloak/keycloak#21127]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

If the user closes their browser after requesting a reset-credential email, the redirect_uri is forgotten when the user clicks the link in the email.

NOTE: This is expected behaviour (see the discussion on this issue), but the fact that the link "Back to application" is not shown on the info page after password-reset is not expected and this should be fixed (See https://github.com/keycloak/keycloak/issues/21127#issuecomment-1882737532 for the details).

### Version

18 (RH-SSO 7.6)

### Expected behavior

1. User opens the following endpoint: `{KEYCLOAK}/realms/{REALM}/protocol/openid-connect/forgot-credentials?client_id={CLIENT_ID}&response_type=code&redirect_uri={REDIRECT_URI}`
2. User enters email and submit
3. User closes browser
4. User clicks reset-password link in email
5. User enters password twice and submits
6. User is sent to `/auth/realms/{REALM}/login-actions/required-action` endpoint and shown the message `Your account have been updated`. There should be link "Back to application" with the baseUrl of the client corresponding to {CLIENT_ID}

### Actual behavior

In step 6, There is no link "Back to application" with the baseUrl of the client corresponding to {CLIENT_ID}

### How to Reproduce?

See "Actual behavior" (step 6 is the error, which is different from the expected behavior).

If the user does NOT close the browser (skips step 3), everything works as expected.

### Anything else?

I was directed to use the `/forgot-credentials` endpoint in #20867

**Comment by jonkoops** [comment]
Is this bug still present in the latest version of Keycloak?

**Comment by pxnis** [comment]
I don't know.. I currently don't have access to a KC 21 environment.
We are running the latest version of RedHat SSO (7.6), which is based on KC 18.
This issue will also be reported on the RH-SSO enterprise support system.

**Comment by mposolda** [comment]
This is not strictly a bug, but expected behaviour in Keycloak, which we discussed many years back.

In the cases when:
- User opens link from the email in the different browser (EG. User started the flow from his client application in Firefox, but then the link from the email is opened in Chrome)
- User restarted browser in the meantime

There is also possibly not client session on the application side. Hence we don't automatically redirect to the application, but display the info page like `Your account has been updated` . In this case that your client has `Base URL` set, there should be also link like `Back to application` where user can click and eventually start new login flow from his client application. Do you see this link `Back to application`? If not, then maybe just set of `Base URL` to client settings page in Keycloak admin console should help.

We can consider this as RFE to have option to automatically redirect (probably to `Base URL`) in such cases, but not 100% sure if we do it and if it is prioritized.

As a workaround, you can possibly update some FTL templates (I think `info.ftl`) to possibly redirect automatically to client's base URL. Hopefully it can be done with some javascript snippet.

**Comment by pxnis** [comment]
Thank you for your reply.

In our case, the redirect either resume or start a new application client session.
Therefore we would like the redirect to persist through browser change/restart.
It would provide a better user experience in our case.
As suggested, we can make a workaround using our theme templates.

I'm not exactly sure was "RFE" abbreviates, but I guess it's a feature request?
If so, I support it :)

**Comment by pxnis** [comment]
Also regarding your question about the "Back to application" link.
This did not appear. The standard theme had some link-conditions, which was not met.
I adjusted our custom FTL to always show the link, if a base URL is set.

**Comment by mposolda** [comment]
@pxnis Thanks. I've just checked the behaviour and I agree that the fact that "Back to application" link is not shown is not good. So switching back to bug and raising priority of this.
