### ISSUE TITLE
State transfer never completes

### ISSUE THREAD

**Issue by martin-kanis** [keycloak/keycloak#21256]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

storage

### Describe the bug

In https://github.com/keycloak/keycloak/pull/21240 we made `awaitInitialTransfer` configurable to fix a flaky model test. The root case of this problem is tracked by ISPN jira https://issues.redhat.com/browse/ISPN-14982.

Once the ISPN jira is resolved and root cause is found, we should investigate if any further steps are needed on Keycloak side.

### Version

21.1.1

### Expected behavior

Initial state transfer never timeouts

### Actual behavior

Initial state transfer timeouts in a model test in ~1 from 100 runs.

### How to Reproduce?

taskset 1 `for run in {1..20}; do mvn test -f testsuite/model/pom.xml -Plegacy-jpa+infinispan-offline-sessions-preloading -Dkeycloak.logging.level=debug -Dtest=OfflineSessionPersistenceTest; done > out`

or run 

mvn test -f testsuite/model/pom.xml -Plegacy-jpa+infinispan-offline-sessions-preloading -Dkeycloak.logging.level=debug -Dtest=OfflineSessionPersistenceTest

100 times

**Comment by ahus1** [comment]
@martin-kanis - Infinispan 14.0.13.Final has landed in main, and is about to be backported to 22.

Please have a look at this what else needs to be done for this issue. From what I see it would be great to re-verify that the fix is working. If there were workarounds added, please remove them and then backport them to 22. Please add/remove tasks as you see fit. Thanks!
