### ISSUE TITLE
LDAP Filter doesn't delete users from keycloak DB

### ISSUE THREAD

**Issue by oksumoron** [keycloak/keycloak#21359]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

I sync all users from Active Directory to keycloak, after that I apply LDAP filter as I want to sync only users from particular AD group. Keycloak behaves strange: all users remain in database in table user_entity but users outside my group dissapear from user list in UI along with some users from my group.
When I search something in user list OR restart keycloak, users start dissapearing from database by 20-30 every time, and users from group start to appear in user list.

### Version

i tried 18.0.0, 20.0.5 and 21.1.2

### Expected behavior

After applying ldap filter and sync,  users that fit the filter should remain in database and those don't fit should be deleted.

### Actual behavior

After applying ldap filter and sync,  all users remain in database and dissapear from it by 20-30 rows after every database operation (such as search or keycloak restart )

### How to Reproduce?

1. create 50 users in active directory
2. sync all of them in your keycloak
3. add any LDAP filter, ie  (email=jdjshfjkdk)
4. sync all users again

**Comment by rmartinc** [comment]
@oksumoron I think that the synchronization of users in the ldap provider never deletes users that have been removed from ldap. If you check the [code](https://github.com/keycloak/keycloak/blob/22.0.0/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProviderFactory.java#L543) the users found in ldap are created or updated, but there is second loop to delete users that are in db and not in ldap.

So, in your case, the users in the filter should be created/updated by the synch but the users that are not returned by the filter remain in the database. Those users are being removed as soon as they are retrieved by the application (it can be the UI, a login or whatever). The user is [validated](https://github.com/keycloak/keycloak/blob/22.0.0/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L171-L176) against the ldap provider and it's detected as not present and deleted at that point in the internal db. That's why they start being removed by chunks (they are deleted as they are being retrieved by the UI). 

So, I think that the synch process is not going to delete users, at least it's not done that way. Apart from that, did you see a problem or issue with current behavior? Are there users not being created/updated by the synch or users that appears later in the app that should ont be there because of the filter?

**Comment by rmartinc** [comment]
@oksumoron Any update on this?

**Comment by rmartinc** [comment]
@oksumoron I'm closing the issue. If you need something more please re-open it or file a new issue. Thanks!
