### ISSUE TITLE
When export Realm using command , Keycloak Threw [JDBC resources leaked ] error

### ISSUE THREAD

**Issue by owenJiao** [keycloak/keycloak#21479]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

import-export

### Describe the bug

When I did export realm operation in docker container using command ks.sh, the keycloak threw some warning message [(main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 1 Statement(s)]  which lead to export fail.
![截屏2023-07-06 下午5 19 08](https://github.com/keycloak/keycloak/assets/35132388/7a3db48d-2ab5-4d44-93dd-d2779f7e3560)

### Version

quay.io/keycloak/keycloak:18.0.0

### Expected behavior

I hope I can export all my realms from keycloak 18,  because I want to upgrade keycloak from 18 to 21, so I need to migrate all data in keycloak 18 to 21, Could you provide me some tips ? Thank you very much.

### Actual behavior

null

### How to Reproduce?

1: Enter docker 
   docker exec -it 3b99592e038c /bin/bash

2: Run command in docker 
   ./kc.sh export --dir /tmp/mydata/

**Comment by ahus1** [comment]
To upgrade from one KC version to another, use the database backup/restore instead of export/import as it is much more efficient. 

The warning might be investigate separately, and might already be fixed in the latest release. The real problem here is the "Error while exporting policy". Run Keycloak in verbose mode like

```
./kc.sh --verbose start ...
```

to see the contents of the exception thrown in keycloak. 

Instead of pasting a screenshot, post the text contents here as it makes searching for the error message a lot simpler. 

Once you have the stack trace, add a comment to this issue and the investigation can continue.

**Comment by owenJiao** [comment]
Got it, Thanks a lot. I close this issue
