### ISSUE TITLE
Deactivating user after send update password email results "Invalid username or password"

### ISSUE THREAD

**Issue by dmartinol** [keycloak/keycloak#21473]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

When a deactivated user tries to open the link to update its password, a popup error appears with a misleading message.

### Version

21.1.1

### Expected behavior

We would expect the "Account is disabled, contact your administrator." message.

### Actual behavior

The "Invalid username or password" error appears.

### How to Reproduce?

- create a user with no creds in master realm
- reset the creds by sending the update password email
- disable the user
- open the link in the email
the error message is "Invalid username or password"

**Comment by pedroigor** [comment]
@dmartinol Isn't a more specific message exposing too much information and possibly allowing user/name enumeration?

**Comment by dmartinol** [comment]
There is no username exposure in the proposed message, which is already mapped and displayed in other use cases: “Account is disabled. Please contact your administrator.”

**Comment by pedroigor** [comment]
Yeah, we are not exposing the username. However, it indicates the user exists. That is my point.

@rmartinc @mposolda Wdyt?

**Comment by rmartinc** [comment]
@pedroigor @dmartinol I think that the message can be changed to be more precise. Because this is a login using an action token, so the token should be stolen and used in the period of time the token is valid. Besides the information saying the user is disabled does not even mention the username (although I suppose in the token there will be more info). So, if the token is valid (signature and so on) and the user is deactivated, I think we are not exposing something the attacker wouldn't know before. But very low impact issue. My vote is to move it to backlog and ask for help.

**Comment by pedroigor** [comment]
@rmartinc That is a good point in favor of a more specific message. If the attacker gets access to the link, he knows there is a user somewhere. The fact the action token is bound to a specific user should also avoid enumeration (I missed that) as you are operating within the scope of a single user.

@dmartinol Sorry for bringing this up but we had issues with this type of attack and whenever I see changing messages from the server for critical flows this comes up again in my head.

I think I'm convinced we can have a more specific message then.
