### ISSUE TITLE
DN with RDN that contains trailing backslash is imported incorrectly into Keycloak

### ISSUE THREAD

**Issue by bp974** [keycloak/keycloak#21797]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ldap

### Describe the bug

When connecting Keycloak to an AD LDAP server with a DN that has a trailing backslash in one of the RDNs, the DN is imported incorrectly. 

AD DN: `CN=Test User\\\\,OU=Users,DC=example,DC=com`

But when imported and viewed in Keycloak it is no longer a valid DN. 

Keycloak LDAP_ENTRY_DN: `CN=Test User\\\\,OU,DC=example,DC=com`

This causes login and parsing issues for the entity that is imported. 

### Version

20.0.2, 21.1.2

### Expected behavior

Expected behavior is that the entity with a DN containing an RDN with the trailing backslash would be imported correctly with the same DN as seen in the AD server. eg `CN=Test User\\\\,OU=Users,DC=example,DC=com`

### Actual behavior

Actual behavior is that the entity with a DN containing an RDN with the trailing backslash is imported incorrectly and the entity cannot be used in Keycloak. eg `CN=Test User\\\\,OU,DC=example,DC=com`

### How to Reproduce?

Install Keycloak and connect to an Active Directory LDAP server that has an entity with a DN containing an RDN with a trailing backslash. eg `CN=Test User\\\\,OU=Users,DC=example,DC=com`

**Comment by bp974** [comment]
This issue is very similar to https://github.com/keycloak/keycloak/issues/21818 and possibly can be tackled at the same time.

**Comment by mhajas** [comment]
Thank you for the report @bp974. I was able to reproduce this and this is indeed a bug. The issue is here:
https://github.com/keycloak/keycloak/blob/697cd8595bb56a8f1adcaf2db0751d8748336b1b/federation/ldap/src/main/java/org/keycloak/storage/ldap/idm/model/LDAPDn.java#L57-L76

We split `dnString`  by `,` however, we need to support escaping for `,` character so we split only when there is no `\\` before `,`. This is the case for your entry: `CN=Test User\\,OU=Users,DC=example,DC=com`, and for that reason it ignores `OU` attribute and assumes `OU` string is part of `CN`.

One possible solution here is to detect this situation by counting the number of `=` in the resulting split groups. 


I created a test reproducer for this. To run this run model tests with profile `legacy-jpa-federation+ldap+infinispan` :
https://github.com/mhajas/keycloak/commit/a9001f8aa69f23ab4f6b0777c726549dc1aacd9e

**Comment by ahus1** [comment]
Thank you @mhajas for triaging, adding a "help wanted" tag if someone from the community wants to pick it up before we have the time to do so.
