### ISSUE TITLE
User isn't able to configure WebAuthnPasswordless credentials through WebAuthnPasswordlessAuthenticator

### ISSUE THREAD

**Issue by dasniko** [keycloak/keycloak#21815]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication/webauthn

### Describe the bug

When having configured the WebAuthnPasswordlessAuthenticator in an authentication flow, when this step is set to "Required" and the user doesn't have WebAuthnPasswordless Credential configured, the error "credential setup required" is shown, but the user can't configure the corresponding credentials.

### Version

22.0.1

### Expected behavior

The user should be able to configure the credential through the associated Required Action.

### Actual behavior

Error "credential setup required" is shown.

### How to Reproduce?

Configure an authentication flow with the WebAuthnPasswordless Authenticator as "Required" step and login with a user which has no WebAuthn Credential.

### Anything else?

This error comes up, as the factory method `isUserSetupAllowed()` of the `WebAuthnPasswordlessAuthenticatorFactory` returns `false`

https://github.com/keycloak/keycloak/blob/54f8c8d2530c998ac50daeee399131e86c2dfff8/services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnPasswordlessAuthenticatorFactory.java#L58-L60

but should IMO return `true`, as the method `setRequiredActions(...)` in the provider class `WebAuthnPasswordlessAuthenticator` sets RequiredAction(s) to the AuthSession:

https://github.com/keycloak/keycloak/blob/54f8c8d2530c998ac50daeee399131e86c2dfff8/services/src/main/java/org/keycloak/authentication/authenticators/browser/WebAuthnPasswordlessAuthenticator.java#L64-L70

**Comment by mposolda** [comment]
@dasniko Thanks for the report, but this is not a bug, but expected behaviour. As you pointed it is done on purpose due the security.

Right now, authentication flows should be configured in a realm in a way that user first authenticates some other way (password, IDP, Kerberos, ...) and then in his account console, he can add "WebAuthn Passwordless" security key and then use it for further authentications. See https://www.keycloak.org/docs/latest/server_admin/index.html#_webauthn_passwordless for an example how the flow can look like.

For improving the experience, you can try to create "Feature request", but not a bug.
