### ISSUE TITLE
Allow to specify different hosts for HTTP and HTTPS listeners (https-host)

### ISSUE THREAD

**Issue by jirutka** [keycloak/keycloak#21929]
### Description

Configuration option `http-host` specifies the host to listen on for both HTTP and HTTPS listeners, so we cannot let HTTPS listen on `0.0.0.0` and HTTP on `127.0.0.1` (localhost) only. I’d like to add a new option `https-host` that will work the same as `http-host`, but only for the HTTPS listener.

### Motivation

When Keycloak is running behind a reverse proxy on a different machine with re-encryption, but we want to run healthchecks or `kcadm` directly against Keycloak from the same machine.

**Comment by shawkins** [comment]
No quarkus issue was created for this, and would require running yet another http server. Let's just reject this rather than leaving it open indefinitely. The proxy is more than capable of not allowing http traffic to the exposed http port and you can still run things from the same machine using the appropriate hostname.

**Comment by shawkins** [comment]
Reopening as this was worked upstream. Blocked until quarkus 4 / Keycloak 27.
