### ISSUE TITLE
Client Session Max set never expires is not working anymore since 22.0.0

### ISSUE THREAD

**Issue by johgoe** [keycloak/keycloak#21927]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

A standard 

{"error":"invalid_grant","error_description":"User session not found"}

### Version

22.0.1

### Expected behavior

The user is able to login to the session as usual

### Actual behavior

The login is not succesful. There always occurs a CODE_TO_TOKEN_ERROR with the following response

```
{"error":"invalid_grant","error_description":"User session not found"}
```

### How to Reproduce?

Configure a client to "Client Session Max" = "never expires" in the Advance Settings 

![grafik](https://github.com/keycloak/keycloak/assets/1584475/d4badc93-d1ab-4bf4-8cc5-b868c519abf6)

Try to login with this client for a webui

### Anything else?

I'm not sure but I think the problem happens in SessionExpirationUtils.calculateClientSessionMaxLifespanTimestamp

In case of "Never expires" clientSessionMaxLifespanPerClient will be -1 after this line.
```
String clientSessionMaxLifespanPerClient = client == null? null : client.getAttribute(OIDCConfigAttributes.CLIENT_SESSION_MAX_LIFESPAN);
```

I think it was introduced with

https://github.com/keycloak/keycloak/pull/17525/files

**Comment by rmartinc** [comment]
@johgoe Yes, you are right, although I fear that this configuration didn't work before either, or at least completely. I mean, previously the client session will expire anyway, although it was usable, not like now.

As you commented the problem is in the [SessionExpirationUtils](https://github.com/keycloak/keycloak/blob/22.0.1/server-spi-private/src/main/java/org/keycloak/models/utils/SessionExpirationUtils.java#L116-L121). It gets -1 from the client and when it's added it results in a time in the past.

But thinking out loud, what should happen if client session does not expire? The user session will expire (because it cannot be configured to not expire), so the client session is expired anyway although it's still there (it cannot be accessed). Does makes sense at all that client sessions don't expire but the user session will always expire? I think that no. (Same for idle.)

AFAIK the only way to have not expiring sessions is using offline sessions and setting the `Offline Session Max Limited` to `off`. But even in that case setting the `Client Offline Session Max` to `Never expires` makes no sense, because client session does the same than the user session (`Offline Session Max Limited` controls if they expire or not, the only thing we can do is setting a lower time in client session once enabled). Here there is room for improvement, but in the other direction, a offline client session can have a expiration although the user session never expires (at least that makes sense).

IMHO we should do the following:

1. Remove the `Never Expires` from the client configuration option. It makes no sense. Does someone remember why it was added?
2. Protect the calculation from getting negative numbers that make no sense.
3. Improve the calculation with the case explained before. When setting `Offline Session Max Limited` to `off` at realm level the client level can override and setting an expiration.

This is a regression because, although the previous configuration didn't work as expected either, the current situation is even worse.

@johgoe @mposolda WDYT? Am I missing something?

**Comment by johgoe** [comment]
@rmartinc I agree that this settings make no sense, from my point of view. So I also suggest to remove the setting for future versions. 
I guess the real issue about this setting is not to keep the feature, but inform the administrator about an illegal setting that should must be fixed with a valid value. Maybe in a warning for an existing configurations in the log could be very helpful. It takes us some time to find the reason for our login issues.

**Comment by rmartinc** [comment]
@johgoe My idea is protecting the value for negative numbers at calculation (point 2). That would make it work as before with an incorrect -1 value (it will use realm settings). In point 1 we can do something to mark the -1 value is wrong, like red warning or something. But OK, if you think `Never Expires` makes no sense I will start with the changes the next week.
