### ISSUE TITLE
there is no hostname-strict-https options in configuration list 

### ISSUE THREAD

**Issue by amiramirifar2** [keycloak/keycloak#22116]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

docs

### Describe the bug

In [Configuring the hostname](https://www.keycloak.org/server/hostname) page at frontend section you refer to hostname-strict-https option but it seems there is no option in configuration list in [All configuration](https://www.keycloak.org/server/all-config)  page

### Version

last

### Expected behavior

null

### Actual behavior

null

### How to Reproduce?

add hostname-strict-https in configuration list if still exists or remove it from other guides

**Comment by vmuzikar** [comment]
This is intentional but I wonder if we should make the option more visible? WDYT @keycloak/cloud-native @pedroigor

**Comment by amiramirifar2** [comment]
yes of course
if specific configuration is available so it is better to add in configuration list❤️

**Comment by pedroigor** [comment]
@amiramirifar2 @vmuzikar IMO, we should think about removing that option from the documentation and eventually removing it from the configuration.

@amiramirifar2 Is there any use case you are trying to solve with that option? Or are you just reporting an inconsistency in docs?

**Comment by amiramirifar2** [comment]
i think that this flag is usable for launching keycloak in prod mode with http port (for some purpose) but i have not any way to know this flag is available or not to use it

**Comment by pedroigor** [comment]
@amiramirifar2 Sorry for the late reply.

We should avoid it because of the reasons I pointed out before.

We introduced the `hostname-url` (and `hostname-admin-url`) with the goal of reducing the number of options in the `Hostname` category (and reducing a bit of complexity) while still allowing operators to force a specific frontend URL. You should be better with this option.

**Comment by vmuzikar** [comment]
This issue has been created against Hostname v1 implementation. Due to its complexities and high maintenance costs we decided to rewrite it from scratch as Hostname v2 which will be part of Keycloak 25 and will be replacing v1. For more context please see #24252.

We believe this issue has been resolved with Hostname v2. We encourage you to give it a try even before Keycloak 25 is released and report back any issues you run into. You can use the [nightly builds](https://github.com/keycloak/keycloak/releases/tag/nightly) for it. See also the [migration notes](https://github.com/keycloak/keycloak/blob/main/docs/documentation/upgrading/topics/changes/changes-25_0_0.adoc#new-hostname-options) and [new docs](https://github.com/keycloak/keycloak/blob/e7dd5c1991e938ad2aa03e9c8b18cac6820dc7df/docs/guides/server/hostname.adoc).
