### ISSUE TITLE
Cannot enter the account via ssh

### ISSUE THREAD

**Issue by scientific-computing-user** [keycloak/keycloak#22125]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

Cannot enter the account via ssh

### Version

latest

### Expected behavior

To be able to ssh

### Actual behavior

No entry

### How to Reproduce?

Try to ssh my account
ssh login.customer.local
(galoren@login.customer.local) Password:

### Anything else?

No

**Comment by ssilvert** [comment]
Is the UI involved here?

Switching to core team for now.

**Comment by rmartinc** [comment]
@scientific-computing-user I don't even understand what you are trying to do. Can you elaborate more what is this issue about?

**Comment by jonkoops** [comment]
Closing this issue due to lack of information. Feel free to open a new issue, but make sure you know how to [ask a good question](https://stackoverflow.com/help/how-to-ask) (stolen from Stack Overflow, but applies here too). Also, if you have a question rather than a bug, please start a discussion instead.
