### ISSUE TITLE
Convert KeycloakIngress to a dependent resource

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#22206]
### Description

KeycloakIngress presents some challenges in conversion.  The first issue is that the basic dependent resource logic does not handle a null desired state - but we want to remove the Ingress if it has been disabled on the CR.  

The next issue is that more about the direction this logic will take in the future - it seems like we're going to need one dependent resource type for kubernetes, and another for openshift that directly creates routes rather than ingresses.

cc @csviri

**Comment by csviri** [comment]
>  but we want to remove the Ingress if it has been disabled on the CR.

I think what you request here is covered fully in workflows feature:
https://javaoperatorsdk.io/docs/workflows

(Note that even if you don't use managed dependent resource, there is standalone mode also for workflows just like for dependent resources)

Workflows provide `reconcilePrecondition`, where the precondition implementation just checks the spec of the primary resource. We have exactly this in the sample:
https://github.com/java-operator-sdk/java-operator-sdk/blob/077bbc2f224ee7fcc9da933aefd6c46aa51f95dd/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/WebPageManagedDependentsReconciler.java#L21-L22

The condition: 
https://github.com/java-operator-sdk/java-operator-sdk/blob/077bbc2f224ee7fcc9da933aefd6c46aa51f95dd/sample-operators/webpage/src/main/java/io/javaoperatorsdk/operator/sample/dependentresource/ExposedIngressCondition.java#L11-L15


> The next issue is that more about the direction this logic will take in the future - it seems like we're going to need one 
dependent resource type for kubernetes, and another for openshift that directly creates routes rather than ingresses.

This can be modeled as two dependent resources with different preconditions. But we can take a look if we can find a better way.

**Comment by shawkins** [comment]
> This can be modeled as two dependent resources with different preconditions. But we can take a look if we can find a better way.

That seems sufficient.  We can ensure that the conditions are mutually exclusive.

**Comment by ahus1** [comment]
> ... and another for openshift that directly creates routes rather than ingresses.

@shawkins - I know that OpenShift creates a Route for every Ingress, and at least all annotations one would need for Routes can be added to Ingresses as well. In what scenario would I like to create a Route directly?
