### ISSUE TITLE
prompt: 'login' doesn't recreate a new session or reset SSO Session Max

### ISSUE THREAD

**Issue by yelhouti** [keycloak/keycloak#22205]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

authentication

### Describe the bug

There doesn't seem to be a way to ask the user to re authenticate to reset the max session age, to prevent the session they are using from expiring.

### Version

nightly

### Expected behavior

I would expect /realms/realm/protocol/openid-connect/auth?promp=login to recreate a new session or at least extend the the lifetime of the current session.

### Actual behavior

There is no way to extend a session

### How to Reproduce?

Configure a new realm with:
SSO Session Max: 2 minutes
Try to find a way to extend the session.

**Comment by sschu** [comment]
I don't really think this is a bug. Session max is session max because it is the maximum length of the session. If you want the user to reauthenticate to not make a session expire, you should probably reauthenticate against the session idle timer because that will actually expire the session first. 

You might also have a look at step-up authentication that also allows you to force reauthentication after certain times: https://www.keycloak.org/docs/latest/server_admin/#_step-up-flow

**Comment by rmartinc** [comment]
@yelhouti The max session age is exactly that, the max time a session is maintained in keycloak. Using a re-authentication with promp=login just uses the same session so the creation time is not modified (because the creation time is the creation time). The idea is that you set the max session age to something logical for you, and then idle timeout is used to close abandoned sessions. If the session would be extended doing that there would be other users complaining that the max session age does not work, which is a reasonable complaint.

Closing this as it's working as expected.
