### ISSUE TITLE
Group Membership token mapper adds no claim instead of empty list since Keycloak 22 

### ISSUE THREAD

**Issue by lathspell** [keycloak/keycloak#22340]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

In Keycloak 20.0.5, a group membership token mapper would add `groups: []` to an OAuth2 JWT if the user was in no groups.
In Keycloak 22.0.1, the same configuration creates an JWT with no `groups` claim at all.

This can lead to problems with clients who check for an "empty arrays" value of an existing claim as the claim itself is no longer present.

Was this change intended behaviour or accidental? 

### Version

22.0.1

### Expected behavior

The JWT should have the claim: `groups: []`

### Actual behavior

The JWT does not contain the claim `groups` at all

### How to Reproduce?

Add a OAuth2 Client with Group Membership token mapper and use "Evaluate" to see the access token of a user that is in no groups.

**Comment by rmartinc** [comment]
@lathspell No, this was not done on purpose and most probably I'm the guilty one. I think that it's because  https://github.com/keycloak/keycloak/issues/19767. The group membership mapper was done more or less in its own way, and with that fix it's now using the same code shared by the other attribute mappers. This general code always return null if empty list, and the claim is not added. I thought about the changes introduced in the claim name but not in this empty list / null modification.

But, I don't know, IMHO this is a proper usage and the app should take into account that the claim cannot be there. Besides it's what we are doing for all the other multi-valued claims and it generates shorter tokens. My vote is to maintain the new behavior. But I'll ask @mposolda and @pedroigor to see if they see it differently and we should revert the behavior.

**Comment by pedroigor** [comment]
The current behavior is the best and saves a few bytes while still making it possible to check whether the subject is a member of any group.

@lathspell This was not properly communicated via release/upgrade notes.

**Comment by cellux** [comment]
Having a group claim in the token whose value is an empty list indicates that:

1. Keycloak used the group membership token mapper when it generated this token,
2. Keycloak determined that the subject is not a member of any group, hence it set the value of the claim to the empty list.

If the token does not contain a group claim, that would mean (at least to me) that Keycloak did not use the group membership token mapper when generating this token.
