### ISSUE TITLE
LinkedIn as Identity provider not working

### ISSUE THREAD

**Issue by Sabotageur** [keycloak/keycloak#22383]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

oidc

### Describe the bug

When using for the first time LinkedIn as an Identity Provider, Keycloak sends by default the "r_emailaddress" oAuth2 scope, to which LinkedIn responds : 

> error : unauthorized_scope_error
> error_description = "r_emailaddress" is not authorized for your application

The issue seems to be at : https://github.com/keycloak/keycloak/blob/1d444ff86228b741f85fd68aacf6e06e9d53031d/services/src/main/java/org/keycloak/social/linkedin/LinkedInIdentityProvider.java#L58

```
		// email scope is mandatory in order to resolve the username using the email address
		if (!config.getDefaultScope().contains(EMAIL_SCOPE)) {
			config.setDefaultScope(config.getDefaultScope() + " " + EMAIL_SCOPE);
		}
```

### Version

22.0.0

### Expected behavior

Keycloak should only send the requested scopes when dealing with LinkedIn (in my case, openid, profile and email).

### Actual behavior

When calling LinkedIn, keycloak always add the "r_emailaddress" scope that LinkedIn doesn't accept.

### How to Reproduce?

- Set up a new app in LinkedIn
- Request access to the "Sign In with LinkedIn using OpenID Connect" product
- Create a new LinkedIn IdP in keycloak, using the clientId and secretId from LinkedIn
- Copy the keycloak redirect URL to the LinkedIn app
- Try to login

**Comment by rmartinc** [comment]
@Sabotageur For what I see LinkedIn now uses openid connect standard and (in theory) you don't need the specific LinkedIn provider (previously it was OAUTH and it needs some tweaks). You can configure the general OpenID Connect v1.0 provider for it. But sadly I have done a little test and I detected two issues in the LinkedIn implementation:

1. The [linkedin JWKS endpoint](https://www.linkedin.com/oauth/openid/jwks) does not add the "use" for the key. The [key should be valid for signing by spec](https://openid.net/specs/openid-connect-core-1_0.html#Signing). I configured the provider to use that key without jwks and passed this point.
2. The linkedin is not adding the nonce to the tokenID. That's also by [spec (point 11)](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) and should be there. Keycloak is checking that part. This point cannot be workarounded.

So the good news is that it seems that you don't need a special provider for linkedin from now on. Teh bad news is that OpenIDC general provider doesn't work with linkedin because IMHO LinkedIn is not following the standard in those two points. I will try to report both issues to linkedin and see what happens.

**Comment by Sabotageur** [comment]
Thanks for your help @rmartinc , I did try as well to use LinkedIn as a generic OIDC provider but ran into the same hurdles as you did (disabled the jwks but called it quits at the nonce error).

**Comment by rmartinc** [comment]
The previous social provider was used when you added the app `Sign In with LinkedIn` (like in this [link](https://www.linkedin.com/pulse/how-get-signin-linkedin-work-taric-andrade)). Now the app is `Sign In with LinkedIn using OpenID Connect` and the previous social provider is not valid anymore. It needs to be the general OpenID Connect provider but the are issues with it.

I have filed a case with LinkedIn explaining both issues but don't know how it will proceed or if they will comment to post the issues somewhere else. I also linked this issue just in case they want to comment here.

**Comment by rmartinc** [comment]
Just a little summary. I created an issue in LinkedIn with my personal account (https://www.linkedin.com/help/linkedin/solve) commenting about the issues and saying what was the proper way to continue with this. The case was closed saying this channel was not for developer-specific inquiries and I was redirected to ask in stackflow. I submitted [this question](https://stackoverflow.com/questions/76889585/issues-with-sign-in-with-linkedin-using-openid-connect) but I really think that this is not the correct channel to reach LinkedIn engineers. So I don't expect an answer. If someone knows what is the proper way of submitting API issues to LinkedIn let me know. :sweat:

We are going to wait a few weeks to see if someone answers in stackoverflow. If nothing happens, probably we will need to create a new social provider for LinkedIn that extends the general OIDC one and is tweaked to work with the current LinkedIn implementation.

**Comment by Olagold-hackxx** [comment]
I also faced the same issue with Redhat sso and haven't been able to find any working solution yet

**Comment by zeronyk** [comment]
So I am facing a somehow same issue. I want to use Keycloak as broker and link the Service to a [Community Management API](https://learn.microsoft.com/en-us/linkedin/marketing/community-management/organizations?view=li-lms-unversioned). However since this is not an IDP perse they do not support any oidc scopes at all. 
Which would not be a problem, when keycloak did not sent scope openid on every auth request for IDP. is there any option to change this ?
