### ISSUE TITLE
Redirect URI with encoded curly brackets rejected

### ISSUE THREAD

**Issue by brezelman** [keycloak/keycloak#22424]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

The OpenID Connect Login is being refused, if the client redirect uri contains encoded curly brackets, even if they are correctly configured as valid redirect uri in keycloak client configuration.
This was working fine until keycloak 15.0.5 at least.

### Version

22.0.1

### Expected behavior

Keycloak displays the login form for the specified realm/client.

### Actual behavior

Error message:

> We are sorry...
Invalid parameter: redirect_uri

### How to Reproduce?

1. Configure a OpenID Connect Client with a redirect uri containing encoded curly braces, e.g. http://clienthost/%7B123%7D/
2. Add  http://clienthost/%7B123%7D/ as valid Request URI in keycloak client configuration.
3. Client will open this login request: https://keycloakhost/realms/.../protocol/openid-connect/auth?client_id=...&redirect_uri=http%3A%2F%2Flocalhost%2F%257B123%257D%2F&response_type=code&scope=openid&state=...&code_challenge=...&code_challenge_method=S256&response_mode=query

### Anything else?

- Could reproduce this in keycloak 20.0.5, 21.1.0 and 22.0.1.
- Maybe similar to #16851.
- When using redirect uri http://clienthost/123/ (without encoded curly brackets) it's working fine and the login form is being displayed as expected.

**Comment by rmartinc** [comment]
@brezelman This is a bug because the method that validates the URIs uses the `KeycloakUriBuilder` that manages template expressions (things like `https://keycloak.org/{param1}?value={param2}`). And that method maintains the curly brackets when creating the URI,  so the URI is invalid later when using URI java class:

```
2023-08-14 15:23:07,014 DEBUG [org.keycloak.protocol.oidc.utils.RedirectUtils] (executor-thread-1) Invalid redirect uri: java.lang.IllegalArgumentException: Illegal character in path at index 39: http://localhost:8081/sample-rhsso/lala{123}
	at java.base/java.net.URI.create(URI.java:906)
	at org.keycloak.protocol.oidc.utils.RedirectUtils.toUri(RedirectUtils.java:173)
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:113)
	at org.keycloak.protocol.oidc.utils.RedirectUtils.verifyRedirectUri(RedirectUtils.java:63)
       ...
```

The `RedirectUtils` needs to not manage template parameters and encode the brackets as usual. This only happens if you use something with curly brackets (opening and closing) in the URL path. So the initial redirect URL cannot be like that right now.

I'll try to work on this when I have time. If someone is also interested in fixing it just let me know.
