### ISSUE TITLE
Localization: Admin UI doesn't pick up message bundles from realms other than master 

### ISSUE THREAD

**Issue by taaem** [keycloak/keycloak#22431]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

I use the User Profile functionality and inside Admin UI -> Users -> User detail I should be able to provide translated names, but this only works for non-english locales.

### Version

22.0.1

### Expected behavior

I add a custom property in the User profile section with a translated name `${customAttribute}`, then I add a message bundle with the correct translations `users:customAttribute`. Then I should see my `users:customAttribute` value in the User details page.

### Actual behavior

I see `customAttribute` written there, but if I do the same procedure for eg. german, than it works!

### How to Reproduce?

1. Add a new custom attribute with name `customAttribute` in the user profile.
2. Add a displayname of `${customAttribute}`
3. Add a message bundle `users:customAttribute`
4. Look at a user profile

### Anything else?

As far as I can tell, there is a difference between how the english translation is handled and any other. 

After my procedure I see that the Admin UI is loading the translations from: http://localhost:8080/admin/realms/master/localization/en

But if I switch the language to german the translations are loaded from: http://localhost:8080/admin/realms/my-realm/localization/de

Or if I don't login through the master realm the english translations also work and are loaded from: http://localhost:8080/admin/realms/my-realm/localization/en

**Comment by ssilvert** [comment]
I have verified this bug.  @taaem says it works fine for English, but not for other languages unless you are looking at master realm.  However, for me it is not working in other realms at all.  For realms other than master, I just see the key.

FYI, here are a few screen shots that show how to configure this feature: https://github.com/keycloak/keycloak/issues/19611#issuecomment-1568980050

**Comment by edewit** [comment]
I can't reproduce this for me it is working. I did needed to reload the UI though as this is something that is only loaded on initialisation

**Comment by edewit** [comment]
That mean regardless of what realm I select, when adding translations they should only be added to the realm I have logged in from. Then this screen shouldn't be on the realm settings IMO.

**Comment by jonkoops** [comment]
We should never have implemented a feature to add user defined labels to a realm in the first place. In this case the best approach would have been to allow user-provided values for `displayName` in each of the supported languages directly in the form where it is defined, rather then providing a key-like template expression which needs to get mapped 'magically' later (causing weird bugs and edge cases like these).

I'd like to discus how we handle this kind of user-defined content in a manner that is more logical both from a UX perspective and simplifies the storing of such content by placing it with the data of the model.

cc @xianli123 @pedroigor

**Comment by ssilvert** [comment]
> That mean regardless of what realm I select, when adding translations they should only be added to the realm I have logged in from. Then this screen shouldn't be on the realm settings IMO.

When you add a translation in Realm Settings it only applies to someone logged into that realm.     It means you are adding translations to a single realm rather than the whole theme.  So it obviously belongs in realm settings.

It's very confusing, but there was a legitimate use case for it once upon a time.  The basic problem is that since we have this nice UI for adding translations, people think that the UI is the preferred way to do it.  But really, it's only meant for a few edge cases. 

Most of the time, you would use properties files instead.  This provides translations for the whole theme rather than a particular realm.  Of course, now we have the json files that go with new admin and account consoles.  Sheesh.  Three ways to add translations!

@jonkoops I agree with you in principle.  And yes, that feature should have never been added because it is a usability nightmare.

**Comment by ssilvert** [comment]
We should probably put a warning message on the internationalization tab to let users know what they are doing is probably wrong and then point them to the documentation.

**Comment by xianli123** [comment]
I can't reproduce this issue. But I know what you are discussing. In my opinion, the translations in the master realm will apply all the realms. A translation created in a non-main realm only applies to that particular realm. 

> We should probably put a warning message on the internationalization tab to let users know what they are doing is probably wrong and then point them to the documentation.
Yes, I agree. We should add some messages to tell users about that mechanism.

**Comment by xianli123** [comment]
I can't reproduce this issue. But I know what you are discussing. In my opinion, the translations in the master realm will apply all the realms. A translation created in a non-main realm only applies to that particular realm.

> We should probably put a warning message on the internationalization tab to let users know what they are doing is probably wrong and then point them to the documentation.

Yes, I agree. We should add some messages to tell users about that mechanism.

**Comment by jonkoops** [comment]
> I agree with you in principle. And yes, that feature should have never been added because it is a usability nightmare.

@ssilvert I think my main problem with the current implementation is that it has become a bit of a dumping ground for all localization needs for content.

It's an incredibly poor UX to tell someone they need to enter some sort of string template (e.g. `${myLabelName}`) for their content,  and then add a label to some kind in an entirely different place such as the Realm Settings.

Not only from a UX perceptive this is poor. Although it might seem like a 'seperation of concerns' (data and localization), it is actually not, as it is user data that is being inputted, so it's really just data, just in different languages.

For example, a user could define a client with a localized name, add the label for it to the realm settings, and then delete the client at some point in the future. The problem is that the label still remains, left wandering in the database, as it 'might' be used somewhere (God knows where, if anywhere).

Whereas if the data was stored where it belongs, in the same record as the client itself, it would have simply been removed.

It is also a nightmare from a front-end perspective, as we have no way of knowing which labels will be used when. For example, if we were to localize the name of the client we must do the following:

1. Load information about the client, get the value of the name.
2. Evaluate this bespoke templating language for the name localization and find the used key (nothing prevents a user from doing `${someLabel} BLA BLA ${someOtherLabel}`.)
3. Request ALL user-defined labels, because we cannot filter these (as far as I am aware). Note, there are users which have THOUSANDS of these labels (seen this in bug reports complaining about performance).
4. Load all the labels into memory, then pick the labels that match the template and apply them.
5. Show the name of the client.

Note that we are actively encouraging this behavior, as it's the only way to localize fields in Keycloak. And we really need to stop incentivizing this.

I have some proposals in the works for this, but it will take me some time to jot things down. Most likely we should continue discussion around that under #16882.

**Comment by ssilvert** [comment]
> > I agree with you in principle. And yes, that feature should have never been added because it is a usability nightmare.
> 
> @ssilvert I think my main problem with the current implementation is that it has become a bit of a dumping ground for all localization needs for content.
> 
Definitely agree with this, and the sentiment that follows.

> 3. Request ALL user-defined labels, because we cannot filter these (as far as I am aware). Note, there are users which have THOUSANDS of these labels (seen this in bug reports complaining about performance).

I don't understand number 3.  We define all the keys for Keycloak apps like admin and account consoles.  We don't mean for Keycloak to be the repository for translations in third party apps.  So where do the thousands of labels come from?  Can you post a link to the bug reports?

**Comment by jonkoops** [comment]
> We don't mean for Keycloak to be the repository for translations in third party apps. So where do the thousands of labels come from? Can you post a link to the bug reports?

I can't find the exact post because it was a series of comments on a PR/issue I no longer recall. However I am sure the user in question mentioned they have a significant amount of labels defined in the realm settings.

**Comment by ssilvert** [comment]
> > We don't mean for Keycloak to be the repository for translations in third party apps. So where do the thousands of labels come from? Can you post a link to the bug reports?
> 
> I can't find the exact post because it was a series of comments on a PR/issue I no longer recall. However I am sure the user in question mentioned they have a significant amount of labels defined in the realm settings.

They are probably using it wrong.  But if it is a legit use case then we need to figure out if or how we support it.

I can't think of a legit use case unless they have thousands of user profile fields?

**Comment by jonkoops** [comment]
> They are probably using it wrong. But if it is a legit use case then we need to figure out if or how we support it.

Oh yeah, for sure they are abusing the system, I think to localize attributes?

**Comment by xgp** [comment]
> We should probably put a warning message on the internationalization tab to let users know what they are doing is probably wrong and then point them to the documentation.

@ssilvert Is there documentation? I'm currently stuck in the matrix of trying to figure out the **right** way to do this, and I haven't found any documentation.

This is all I've found:
- https://www.keycloak.org/2023/07/keycloak-2200-released.html#_changes_to_custom_admin_console_messages

**Comment by xgp** [comment]
> Note that for admin console V2, you will override json files instead of properties files.

Can you elaborate on what "override json files" means? For example, I have bundled an admin theme that uses `keycloak.v2` as its parent with a file at `theme/mycompany/admin/resources/locales/en/users.json` with the content
```json 
{
    "deleteConfirmCurrentUser": "Are you sure you want to permanently delete this user foobar"
}
```

But that does not seem to "override" it, rather it removes all keys that were in the default `users.json` file (except `deleteConfirmCurrentUser`) so the UI now only renders keys. Is the expectation that we'll copy the whole file and just change the values we need? So we basically have to update our theme with every release in case changes were made and new keys were added? 

Is there any other way to do it that doesn't have the requirement of copying the whole file?

**Comment by jonkoops** [comment]
> Is there any other way to do it that doesn't have the requirement of copying the whole file?

Currently for the new Admin and Account consoles this is not possible. Perhaps it should be, feel free to log an issue for that.

**Comment by xgp** [comment]
@jonkoops Thanks. Filed https://github.com/keycloak/keycloak/issues/22791

**Comment by antikalk** [comment]
In my opinion it would make sense to respect the `Realm Settings -> Localization` of the non-master realm. At the moment this is where to set localizations which are then applied at:

- The login theme (e.g. registration screen) 
- The realm specific admin console (`/admin/${realm_name}/console/` - this one picks up the realm specific localizations instead of the once from the master)

Where these localizations are currently not applied at:

- `/admin/master/console/` - when managing user details of a non master realm.
- Account Console (V2)

Imho having it in the theme comes with some big disadvantage: 

- You would potentially have to have a theme per realm (as different realms might need different user profile settings or different translations)
- You loose the possibility of managing the translations in the UI - also allowing admin users to self-service the translations.
- Changing or adding a translation would mean: adapting the theme, then packaging and deploying it.

**Comment by rmarcogaacorp** [comment]
In my case, the problem occurred in different setups when updating from 21.1 to 25.0, using the quay.io docker image.

It was fixed by going into the realm settings, themes, and selecting "keycloak.v3" for accountTheme and "keycloak.v2" for adminTheme, instead of "base"
