### ISSUE TITLE
User profile attributes not localized in account console V3

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak#22507]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

account/ui

### Describe the bug

I create messages in the localization tab of admin console --> Realm settings and use corresponding display name for my custom user profile attribute.  See https://github.com/keycloak/keycloak/issues/19611#issuecomment-1568980050 for setup instructions.

In account console V3, the key will show up instead of the localized display name.

### Version

main

### Expected behavior

See localized display name.

### Actual behavior

Displays key instead.

### How to Reproduce?

See description.

**Comment by ssilvert** [comment]
Hmm.  I wonder if this is broken because in admin console we are using a context like `users:fookey`.  If so, we need to align admin console and account console.  I'd like to also align registration if we can, but I'm not sure if that is easily doable.

**Comment by edewit** [comment]
@jonkoops has set it up that there are no dynamic translation keys, we just need to add the server side messages

**Comment by jonkoops** [comment]
That is correct, currently the only strings that are being loaded are those that are defined in the static JSON files (see [the implementation](https://github.com/keycloak/keycloak/blob/ddd42e9b7ba3b84831db9ec583a38d8629f29a25/js/apps/account-ui/src/i18n.ts)). In this case the API is expected to return fully localized labels for the fields (see [this discussion](https://github.com/keycloak/keycloak/discussions/16882)).

Localization of custom fields, or any sort of user-provided data structures, should be architected better. This should be a single mechanism to localize any user-defined resources on the store level. A proper user-interface needs to be defined on the admin side to input these strings where the resource is added, rather than in some black hole of random strings in the Realm Settings.

**Comment by edewit** [comment]
this is solved with the new renderer
