### ISSUE TITLE
realm-management Resource and Permissions naming convention

### ISSUE THREAD

**Issue by lorenzbaier** [keycloak/keycloak#22863]
### Description

Under the client "realm-management" -> Authorization tab one can create Resources, Scopes, Policies and Permissions.

If you create a Resource by hand, there is a text field for the Name, which suggests you can name it whatever you want.

But from what I have noticed it seems like the name must follow the naming convention "client.resource.\<guid-of-the-actual-client\>" for it to work when trying to add permissions for a client in the realm.

There should be some information on how to properly fill this field.
The same problem exists with the permission itself.

**Comment by ssilvert** [comment]
The reason for this is because the realm-management client is sort of special.  The resources and permissions are created when you enable fine-grained authorization on various Permissions tabs in the admin UI.  The instructions for this are documented in the Server Administration Guide.  https://www.keycloak.org/docs/latest/server_admin/#_admin_permissions

You can still create your own resources and permissions for the realm-mangement client, but they don't have any effect because there is no code that uses your custom resources.  

And as you discovered, if you create them exactly right, you can get something to work.  But they were never meant to be created by hand.

Also, if you try out the nightly build you will find that the naming convention is a little less cryptic.

**Comment by lorenzbaier** [comment]
I just find it a little misleading that you can see the realm-management client with the resources and permissions and even be able to edit without having the fine grained auth feature enabled.
