### ISSUE TITLE
User cannot be created via Admin UI if custom user attribute is required

### ISSUE THREAD

**Issue by enastevska** [keycloak/keycloak#23327]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

When having the user-profile feature enabled and having a custom user attribute marked as required, admin cannot create user via the Admin UI because the attribute is not displayed in the user creation screen, therefore cannot be provided. The field is only shown when editing user and can be set there (have to make the attribute optional)...

### Version

22.0.3

### Expected behavior

Admin is able to create user via Admin UI when having custom user attributes marked as required.

### Actual behavior

Admin is not able to create user via Admin UI when having custom user attributes marked as required.

### How to Reproduce?

1. Enable the user-profile and add new custom user attribute (for e.g locale) and mark it as required
2. Try to create user as an admin

**Comment by ssilvert** [comment]
I have reproduced this on the latest nightly.

**Comment by ssilvert** [comment]
This is a regression.  The problem is in this line:
```
  const isUserProfileEnabled =
    isFeatureEnabled(Feature.DeclarativeUserProfile) &&
    realm?.attributes?.userProfileEnabled === "true";
```
`realm` is undefined.

**Comment by antikalk** [comment]
Is the fix already included in the nightly build? If so, the issue still exists for me. On the create user screen no inputs for user profile attributes are rendered - if one is required the user can not be created of course. The issue seems to be that for the UserForm to render the UserProfileFields also a user has to be present at the moment:
https://github.com/keycloak/keycloak/blob/d8ff73e34f4cbaae18b9926a42d22a0aeda74854/js/apps/admin-ui/src/user/UserForm.tsx#L226-L228
The user is undefined in case of create user.

imho this is a general flaw of the user screens gathering the user profile metadata through the user details api. Instead maybe a dedicated endpoint in the ui-ext extension should be added, allowing for users with view-users or manage-users permissions to gather the user profile metadata for admin ui (create and edit user - no user entity necessary). When this would be refactored, it could also be addressed, that there is a [discrepancy between what the frontend thinks it gets and what the backend actually returns](https://github.com/keycloak/keycloak/issues/23443) for user profile metadata, resulting in user profile attribute validators to not work in the admin ui.

Afterwards the additional parameter and response data can be removed from the users api ...

**Comment by jonkoops** [comment]
@antikalk would you mind logging this as a new issue? That way we can triage it and make sure we don't lose track of it or forget to include the fix in a patch release.

**Comment by antikalk** [comment]
Done: https://github.com/keycloak/keycloak/issues/23507

**Comment by jonkoops** [comment]
Thanks!
