### ISSUE TITLE
Invalid Requester. Use of a wrong key when signing AuthnRequests

### ISSUE THREAD

**Issue by gaelayo** [keycloak/keycloak#23691]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

When setting "Want AuthnRequests signed" to `true` and "Signature algorithm" to `RSA_SHA512` in a SAML identity provider definition, keycloak still uses the `RS256` key in the realm, instead of a `RS512` one, even if there is one available with higher priority.

This leads to an "Invalid requester" error on the client side.

### Version

22.0.3

### Expected behavior

Keycloak should sign AuthnRequests with the RS512 key if it has higher priority instead of a RS256 key.

### Actual behavior

Keycloak do not use the RS512 key, and uses a RS256 key. If you even delete the RS256 key, it will create a fallback RS256 key instead of using the RS512 one.

### How to Reproduce?

Start by generating a RSA key on 4096 bits and the associated certificate:
```bash
openssl genrsa -out private.key 4096
openssl req -new -x509 -key private.key -out publickey.cer -days 30
```

Create a new keycloak realm `test_provider` that we will use as a SAML identity provider for the `master` realm.
In the master realm, define a new identity provider pointing to the `test_provider` realm. We will set **Signature algorithm** to `RSA_SHA512` and **Want AuthnRequests signed** to `on`. In the `test_provider` realm, we will create a saml client, that will check the signature of the authn requests. To do so, we go in the **Keys** tab of the client, and set **Client signature required** to `On`. We then import the certificate in pem format that we generated earlier.

Now, we import our private key to out `master` realm. Realm settings > Keys > Providers > Add provider > `rsa`.
We set priority to `101` to make sure it has higher priority than the default key, we import the previously generated key and certificate, and set the algorithm to `RS512`.

If we try to use the newly created provider, the client on `test_provider` will reject our request with "Invalid Requester". But if we modify the certificate to use the default "rsa-generated" certificate of the `master` realm, the signature will work.

In fact, there is even no need to define a new realm, we can just define a fake provider (with requestbin for example) and catch the AuthnRequest, and use a tool such as [https://www.samltool.com/validate_authn_req.php](https://www.samltool.com/validate_authn_req.php) to verify the signature. We will see that using the `rsa-generated` certificate works, but using our custom certificate does not.

### Anything else?

I used category `core` because I was not really sure about what category to pick, but this may need to be in an other one.

**Comment by rmartinc** [comment]
Hi @gaelayo !

The SAML provider always uses the RS256 active key (it's also the same for the IdP side). It doesn't matter the RSA method you select for signing (RSA_SHA256, RSA_SHA512, RSA_SHA512_MGF1,...). The reason is historical as initially only that key was there, and we cannot change old setups keys. Note the endpoint `/realms/{realm}/broker/{provider}/endpoint/descriptor` for the SP metadata also displays the RS256 keys. So everything is OK.

The problem here is that you expect that it's the RS512 when you select RSA_SHA512 but it's not, it's the current RS256 always (it doesn't matter the RSA algorithm selected for the signature). Priorities and so on are only for RS256.

This is not an issue and it's working as expected.

Regards!

**Comment by gaelayo** [comment]
Hello, and thank you for your response !

So if I want my custom key to be used, I need to mark my key provider as `RS256`, is that it ? But this key will still be used to generate a `RSA_SHA512` signature of the AuthnRequest, so everything would be fine.

This is the documentation I was using: [https://www.keycloak.org/docs/latest/server_admin/#saml-v2-0-identity-providers](https://www.keycloak.org/docs/latest/server_admin/#saml-v2-0-identity-providers), but I did not find anything related to the usage of the `RS256` key (but I could have found the `descriptor` endpoint), is there another page of documentation for this ? 

Moreover, it may be a bit far from the subject, but I am wondering why we need to specify the algorithm when creating a key provider. A same 4096-bit RSA key could do `RS256`, `RS512`, work with sha1, and so on. I don't really get how the signature algorithm is linked to the key. Do you maybe have any insight on this ?

Thank you very much

**Comment by rmartinc** [comment]
> So if I want my custom key to be used, I need to mark my key provider as RS256, is that it ?

Yes, exactly, use RS256 for SAML signing. There is one key by default for RS256. You can use that one or create a new one ([check realm keys in the doc](https://www.keycloak.org/docs/latest/server_admin/#realm_keys)). You can use the endpoint to see if the correct key is displayed there.

> is there another page of documentation for this ?

I think that no, and it would be probably good to say that RS256 is the algorithm used to locate the key when the "Want AuthnRequests Signed" option is ON. If you want you can send a PR changing this paragraph in the [documentation](https://github.com/keycloak/keycloak/blob/main/docs/documentation/server_admin/topics/identity-broker/saml.adoc?plain=1#L53).

> I don't really get how the signature algorithm is linked to the key. Do you maybe have any insight on this ?

I'm not completely sure about this question, but I think that this behavior was inherited from the OIDC protocol changes done when more algs were added. Initially there was only RS256, so SAML used the same algorithm to locate keys for signatures (that's why the saml provider calls to a method called [getActiveRsaKey](https://github.com/keycloak/keycloak/blob/22.0.4/services/src/main/java/org/keycloak/broker/saml/SAMLIdentityProvider.java#L174), no algorithm at all). When OIDC incorporated more algorithms than RS256 (ES256, RS512, HS512,...), realm keys were extended to use a different key for each algorithm. But SAML just continued using the same RS256. That's why I say the reason to use RS256 is historical.

**Comment by rmartinc** [comment]
Closing this @gaelayo. If you want to provide a PR for the documentation just re-open or file a new one. Regards!

**Comment by DemianD** [comment]
@rmartinc is it correct to say that when you chose `RSA_SHA512` as the signing algorithm for SAML, the signing key of `SHA512` will not be used but `SHA256` will? 

<img width="1509" alt="Image" src="https://github.com/user-attachments/assets/147e3c3f-ee72-4aa1-90ce-c9c171cce8fd" />

**Comment by rmartinc** [comment]
@DemianD I would say that SAML uses the `RS256` key for all RSA signatures. IIRC to code uses the [getActiveRsaKey](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/keys/DefaultKeyManager.java#L154-L157) to retrieve it and that method searches the active key using the `RS256` algortithm.

**Comment by DemianD** [comment]
Hi @rmartinc, thank you! I'm trying to understand the full purpose of the `signatureAlgorithm` field in the SAML identity provider. If it is not used for the RSA signatures, do you know what it is used for?

**Comment by rmartinc** [comment]
@DemianD The `saml.signature.algorithm` attriubte in the client is used in the SAML response. It is used to sign the response or the assertion when configured, for example, if you select default `RSA_SHA256`, the signed-info in POST binding is:

```xml
        <dsig:SignedInfo>
            <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <dsig:Reference URI="#ID_a04e422b-e724-4547-9d04-d39c315ee752">
                <dsig:Transforms>
                    <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </dsig:Transforms>
                <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <dsig:DigestValue>zOUHtOi+XMeIkOzldOAkVTGqIQX7ysWkq9j4U/py0eY=</dsig:DigestValue>
            </dsig:Reference>
        </dsig:SignedInfo>
```

But if you select `RSA_SHA_512` the signed info is:

```xml
        <dsig:SignedInfo>
            <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
            <dsig:Reference URI="#ID_c74a10fa-6ab0-477d-b7b6-b80ccd47c5f6">
                <dsig:Transforms>
                    <dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </dsig:Transforms>
                <dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/>
                <dsig:DigestValue>XMXN18DdyqUvgbHyYx+LTJij2Ts+VAvq+shR1+CVQpxo/l+yWWzHEnJN9MDRIVeQZ0592/6CD764MrX+0yZMlg==</dsig:DigestValue>
            </dsig:Reference>
        </dsig:SignedInfo>
```

What this issue was about is the RSA key used to sign (using one algorithm or the other), which is the one in the realm defined for `RSA256`.
