### ISSUE TITLE
[CI] Node.exe not recognized as valid Win32 application (Java Distribution IT, Quarkus IT)

### ISSUE THREAD

**Issue by wojnarfilip** [keycloak/keycloak#23695]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

ci

### Describe the bug

Lately there were errors on windows in Java Distribution IT and Quarkus IT jobs with execution of  `pnpm install --frozen-lockfile --ignore-scripts` command.

Error:
` Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm-install) on project keycloak-js-adapter-jar: Failed to run task: 'pnpm install --frozen-lockfile --ignore-scripts' failed. java.io.IOException: Cannot run program "D:\a\keycloak\keycloak\js\node\node.exe" (in directory "D:\a\keycloak\keycloak\js\libs\keycloak-js"): CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]`

### Version

main

### Expected behavior

Quarkus IT and Java Distribution IT should be passing.

### Actual behavior

Error with Node.js in JavaDistribution IT and Quartkus IT jobs

`Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (pnpm-install) on project keycloak-js-adapter-jar: Failed to run task: 'pnpm install --frozen-lockfile --ignore-scripts' failed. java.io.IOException: Cannot run program "D:\a\keycloak\keycloak\js\node\node.exe" (in directory "D:\a\keycloak\keycloak\js\libs\keycloak-js"): CreateProcess error=193, %1 is not a valid Win32 application -> [Help 1]`

### How to Reproduce?

Not clear as this is flaky behaviour

### Anything else?

Reference action runs:
https://github.com/keycloak/keycloak/actions/runs/6389624189/job/17341584983
https://github.com/keycloak/keycloak/actions/runs/6258874791/job/16994303411
https://github.com/keycloak/keycloak/actions/runs/6324894358/job/17175683119
https://github.com/keycloak/keycloak/actions/runs/6313350974/job/17141779462
https://github.com/keycloak/keycloak/actions/runs/6300070614/job/17102703740

**Comment by Pepo48** [comment]
This issue was earlier reported by @ahus1. I couldn't reproduce it manually and even in the CI it seems that it happens randomly. At least I couldn't spot a pattern.

Maybe also the UI team can help here, since the problem originates in [js module](https://github.com/keycloak/keycloak/blob/08838f77caad92d0ef7bd320494dce83ec034427/js/pom.xml#L44).

At the same time I noticed almost every [pnpm release](https://github.com/pnpm/pnpm/releases) since version 8.7.0 up to version 8.7.5 improves the installation/tarball extraction performance. Therefore, I tried to simply [bump the version](https://github.com/Pepo48/keycloak/commit/8780bc7f07026884c6772b5c3ff3cf9a60675f1e) and the [CI is green](https://github.com/Pepo48/keycloak/actions/runs/6411253412).
Again, this may be irrelevant, since the error seems to arise in a random fashion.

**Comment by justin-tay** [comment]
Experienced this locally a few times. The download of node is sometimes slow and ends up being corrupted causing the error.

I sometimes have to clear it and try again
```shell
mvn dependency:purge-local-repository -DmanualInclude=com.github.eirslett:node
```

- https://github.com/nodejs/build/issues/1993
- https://github.com/eirslett/frontend-maven-plugin/issues/882

**Comment by jonkoops** [comment]
As @justin-tay mentioned, this is a bug that exists in the plugin that we use to download node. Perhaps we can reduce the amount of timeouts by caching the `node` directory. I'll see if I can whip something up.

**Comment by Pepo48** [comment]
@justin-tay thanks for the feedback. You're correct, when we discussed this internally two weeks ago, I also assumed that this is caused by an inconsistent state on the agent.
