### ISSUE TITLE
Need support for .NET adapter with keycloak

### ISSUE THREAD

**Issue by magnuskkarlsson** [keycloak/keycloak#23939]
### Description

Need to provide support for .Net applications by having a .NET connector for RH-SSO in the same way as it is done with NodeJS / Java/ Javascript.

https://issues.redhat.com/browse/KEYCLOAK-19026

### Discussion

https://issues.redhat.com/browse/KEYCLOAK-19026

### Motivation

To support Windows plattform

**Comment by jonkoops** [comment]
Hi @magnuskkarlsson, thanks for logging an issue for this. Unfortunately we do not have the bandwidth to be building and maintaining new adapters, we're already struggling to do so for the existing ones we have.

The ecosystem as a whole around OAuth/OpenID Connect has matured quite significantly since Keycloak's inception, and we are now advocating that you make use of adapters provided by your ecosystem of preference (in this case .NET). Since Keycloak is based on open standards it should be interoperable with any standards-based library you choose.
