### ISSUE TITLE
Anomaly in the keycloak.v2 theme.

### ISSUE THREAD

**Issue by sekaijin** [keycloak/keycloak#24280]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Users tab:
  List of realm users.

When you have set up an identity provider (LDAP) with the options
READ_ONLY and Import users, it is impossible to get the list of imported users.

The filter search imports users and therefore does not display users that have already been imported.

The * search is a danger in the case of very large LDAP directories (more than 100,000 users)
It imports all LDAP users.
Fortunately LDAP paging limits import
but the result is neither the users present in the realm nor all the users in the federation.

The result only shows a mixture of users present in the realm + a few (1000) users imported without notice.

To obtain the real list of users registered in the realm you must select the kecloak theme and not the kecloak.v2 theme
searching with * always has the same default but the "view all users" button is present to list the realm users.

### Version

19.0.2

### Expected behavior

List all users in realm

### Actual behavior

import all users from ldap

### How to Reproduce?

create realm
create the user "lucifer"
add LDAP federation
select kecloak theme for admin console
go to User tab
click on "view all users"
=> you get "lucifer"
select kecloak.v2 theme for admin console
go to User tab
enter * on filter and clik filter button
=> you get "lucifer" and all (or many) LDAP users.

**Comment by rmartinc** [comment]
@sekaijin If you have a very large number of users the import should be done using the pagination feature. If not, the search will be limited to the number of results allowed by the different ldap server limits (max results, max time,...). So, in order to sync all your users, you need to enable the `pagination` and set a proper `Batch size` for you (something smaller to the limit you have in the ldap). When you do that the provider will search in batches using the PagedResults (1.2.840.113556.1.4.319) control. The LDAP server should support that control to work.

And yes the `*` search will do search over all your ldap. What do you want to do here? It's the same in the database, you get all the users in the internal database. We can limit searches to have at least three letters or similar but probably other users will complain about that change. Note that searches like this one are only done by keycloak administrators, the product will search using the username (for login for example).

**Comment by sekaijin** [comment]
The main problem is that each search imports unwanted ldap users.
In a few months of use, 80% of the users present in the keycloak database should not be there, because they were imported into the search result.
I think looking for a user in Ldap to import is a different function than listing users already there.
