### ISSUE TITLE
LDAPGroupMapperSyncTest is failing on MS AD

### ISSUE THREAD

**Issue by pdrozd** [keycloak/keycloak#24357]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

testsuite

### Describe the bug

This line causes a troubles when testing with AD:
https://github.com/keycloak/keycloak/blob/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/federation/ldap/LDAPGroupMapperSyncTest.java#L102

MS AD does not support adding the non existing item to group.

### Version

Version from main

### Expected behavior

The tests should be excuted on MS AD

### Actual behavior

The tests are not executed because of the error during import

### How to Reproduce?

Run the tests with MS AD

**Comment by rmartinc** [comment]
There are two issues detected by @pdrozd in AD related to recen changes:

* LDAPGroupMapperSyncTest: https://github.com/keycloak/keycloak/issues/20718 added a non-existent DN as a group member to test synchronization can cope with that use-case. In AD this is not possible because AD doesn't allow adding non-existent DN.
* LDAPProvidersFullNameMapperTest: https://github.com/keycloak/keycloak/issues/20718 used `postalCode` attribute as a multi-value attribute. AD defines `postalCode` as single-valued and fails.

Providing a PR for both issues asap.

**Comment by ahus1** [comment]
Closing manually, as it wasn't closed automatically when the change was merged to main due to a non-matching keyword in the PR.
