### ISSUE TITLE
Flaky test: org.keycloak.testsuite.cluster.GroupInvalidationClusterTest#crudWithFailover

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#24408]
## org.keycloak.testsuite.cluster.GroupInvalidationClusterTest#crudWithFailover
[Keycloak CI - Legacy Clustering IT](https://github.com/keycloak/keycloak/actions/runs/6654165594/job/18082159865) / [Pull Request #24225](https://github.com/keycloak/keycloak/pull/24225)

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
...
```

**Comment by mhajas** [comment]
I was not able to reproduce it locally nor in GitHub actions (I ran around 300 runs in GHA a no failure and 1000 runs locally).

The test is doing the following:
- We have 2 cluster nodes `node1` and `node2`
- We have a group `g1` with 3 attributes `attr1`, `attr2`, `attr3`
- Then we are doing the following steps
  1. Remove `attr3` on `node1`
  2. Kill `node1`
  3. Check that `node2` contains the correct version of `g1` (there is no `attr3`)
  4. Start `node1`
  5. Change `attr1` on `node1` -> kill `node1`
  6. Check that `node2` contains correct version of `attr1` -> start `node1`
  7. Change `attr2` on `node1` -> kill `node1`
  8. Check that `node2` contains correct version of `attr2` -> start `node1`

There are 5 failures reported in this issue and these happen in steps 6 and 8. What I tried locally is to run steps 5 and 6 1000 times and all of them passed.

Note: There is also one very weird run where there is a failure in step 6, however, the entity on `node2` contains also `attr3` which should have failed step 3 already.

It seems it may be the case this is already fixed since it hasn't failed for 18 days and during my investigation. I will close this issue but I will continue monitoring it and if it fails again I will investigate again.

What to try next: investigate what is the state of the Infinispan cache on `node2` during the steps above. I don't see any step where we load the group entry to the cache before each step where we are making a change. This can lead to reproducing the issue more often if it is caused by some stale cache data.
