### ISSUE TITLE
Private key appears in logging

### ISSUE THREAD

**Issue by frb42** [keycloak/keycloak#24533]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

When the log level of the Keycloak logs is set to debug, the private key for signature and encryption of the SAML request/assertion is logged multiple times. (Since for my tests I used the same key for signature and encryption, I am not able to say if this affects the signature key, the encryption key, or both of them. RSA encryption was used in my case.)

The first time the private key appears is right after starting the Keycloak application:
![grafik](https://github.com/keycloak/keycloak/assets/149802394/0b5ea64a-5617-4c8d-99d3-f253f38ce0b4)

When the SAML authentication request is sent to the identity provider, the private key is printed twice in the log:
![grafik](https://github.com/keycloak/keycloak/assets/149802394/b80c80b4-cbfe-4ec9-84f9-18c1f8b431fd)

### Version

22.0.5

### Expected behavior

Private keys should never appear in the log, no matter what the log level is.

### Actual behavior

Private keys are printed in the log if log level is set to debug.

### How to Reproduce?

Set log level of the Keycloak log to debug, start the application and send a SAML authentication request.

**Comment by jonkoops** [comment]
cc @abstractj

**Comment by abstractj** [comment]
@jonkoops from my perspective, this is a valid report. Logging private keys in debug logs, as described in the issue, is a significant security risk, although we do not recommend that users run Keycloak with debug logs enabled.

Additionally, if private keys have been exposed (even in internal logs), it is still possible to rotate these keys.

Considering that there are enough mitigations in place, I would say that it is important to fix it, but not urgent.

@keycloak/core removing the label triage as I consider it a valid issue. But please revert if you disagree.

**Comment by rmartinc** [comment]
The log is not from keycloak but from categories `org.hibernate.orm.results` and `org.hibernate.internal.util.EntityPrinter`. So they are general logs from the hibernate database access, they are printed in the same way any other table results because the PKs are stored in the database. Normally when you specify a debug you specify the needed category and not all (for example `--log-level=INFO,org.keycloak.saml:TRACE` to show trace on saml).

@pedroigor Do you think we can disable those categories at `application.properties` level? Or maybe we should limit general TRACE to `org.keycloak` and not to all? (Just brainstorming because this is mainly quarkus configuration.)
