### ISSUE TITLE
Invalid redirect_uri if it contains uppercase letters

### ISSUE THREAD

**Issue by Ketec** [keycloak/keycloak#24792]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

If uppercase letters are present, the redirect_uri validation fails.
It will not even match if it is added under client redirect_uri.

This problem was introduced with 21.1.2. Likely with https://github.com/keycloak/keycloak/commit/a1cfe6e24e5b34792699a00b8b4a8016a5929e3a

### Version

22.0.5

### Expected behavior

Case insensitive or sensitive behavior - at least one of those should work.

### Actual behavior

Invalid redirect_uri error

### How to Reproduce?

`redirect_uri=com.someapp.App://oauth2redirect`

client redirect uri list has `com.someapp.App://oauth2redirect` and/or `com.someapp.app://oauth2redirect`

**Comment by rmartinc** [comment]
@Ketec The lower case of the host is wrong [here](https://github.com/keycloak/keycloak/blob/22.0.5/services/src/main/java/org/keycloak/protocol/oidc/utils/RedirectUtils.java#L233-L240) and it's lowering the case for your custom scheme. Then the comparison is with the original scheme so they are different and invalid. The problem is that this erroneous lowering case can be complicated to fix because for example is not loweing the case for `https` protocol. I'll see what I can do.
