### ISSUE TITLE
Use optional realm attribute for authenticationrequest parameter max size/number validation configuration

### ISSUE THREAD

**Issue by mschallar** [keycloak/keycloak#25006]
### Description

1. It would be a security benefit if certain realms could have different i.e., more restricted values for the maximum size, and maximum number of additional parameters for an authentication request.
2. Also, the strategy to silently ignore additional request parameters that do not meet the requirements (number, length) is not suitable for everyone, as it does not enforce the fail-fast behavior.
3. Additional configuration support is also enabled by using a maximum size for all additional request parameter length combined.

1. The current values for `ADDITIONAL_REQ_PARAMS_MAX_MUMBER` is `5` and for `ADDITIONAL_REQ_PARAMS_MAX_SIZE` is `2000` (see https://github.com/keycloak/keycloak/blob/c0c0a80/services/src/main/java/org/keycloak/protocol/oidc/endpoints/request/AuthzEndpointRequestParser.java#L41).
2. The default behavior is still to silently ignore the additional request parameters. If the toggle is switched, an exception will be raised.
3. The default value is `Integer.MAX_VALUE`.

Configurable value enables customers to harden their keycloak instances realm specific by reducing the values according to their needs. All changes are backwards compatible and do NOT need any special configuration when updating keycloak the this version.

### Motivation

This feature would enable customers to optionally configure the maximum number of additional parameters, the maximum size of each parameter, whether fail-fast strategy should be used and whether an overall parameter limit should be enforced, without having the need to change the keycloak-core.

### Details

The idea was to be definitely backwards compatible and don't force any configuration when upgrading to a new keycloak version.

**Comment by sschu** [comment]
Related: #16545 .

**Comment by jbman** [comment]
Making this configurable already helps with tuning. Discarding values silently causes undetected errors. User comes back to the client but login may failed due to a missing parameter and failure is nearly impossible to find when in a debug message.
That's why I would prefer to have fail-fast, even though the user ends up at an error screen. 

If we make it configurable now it will become configuration interface. A reasonable fixed internal limit has the benefit that it should just work for usual cases. The main limitation is the silent restriction to 5 custom parameters. If semantics of the restriction are not changed I would just put that up to 20 and done.

But I'm also fine with the configuration approach. Just think configuration should not be required here.

**Comment by mschallar** [comment]
1. Indeed fail-fast would be fine. We could combine our two ideas?
2. With my proposal no one needs additional configuration, except they want to change the limits. My change is backwards compatible using the already existing default values (5, 2000) as fallback if no realm configuration is available.

**Comment by jbman** [comment]
@mschallar thank you, with fail-fast option this looks good to me! Backward compatible is also nice.

For all cases where the exception is thrown I would at least log to info. Would do this by always throwing the exception on the `AuthzEndpointRequestParser` and moving the fail-fast option out to the caller in a try-catch block. But that's a matter of de-duplication preference.

@sschu, @stianst  hope we can get this PR in. With defaults in the PR. Behavior would stay the same as-is by default, and there are more options to increase the DoS-Protection limits as well as the fail option when over the limits.

**Comment by mschallar** [comment]
@sschu Take a look, I added some tests.
