### ISSUE TITLE
Bug: KC_DB_USERNAME environment variable is causing a crash in latest version

### ISSUE THREAD

**Issue by stefannovak** [keycloak/keycloak#25010]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

When I build the following Dockerfile

```
FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://localhost:5432/
ENV KC_DB_USERNAME=postgres

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

And run it with the following command

`docker run -p 8080:8080 --network="host" -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_DB_PASSWORD=password my-image`

I get a crash.

```
2023-11-24 14:11:36,335 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation

2023-11-24 14:11:36,582 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@6af9fcb2

2023-11-24 14:11:36,582 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@6af9fcb2

ERROR: Failed to run 'build' command.
ERROR: Cannot invoke "io.smallrye.config.ConfigValue.withConfigSourceName(String)" because the return value of "org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(String, java.util.Optional, io.smallrye.config.ConfigSourceInterceptorContext)" is null
For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

I used this Dockerfile throughout version 22 without issue, and when I specify 22.0 as the version, it works as expected.

When I comment out the KC_DB_USERNAME, I get an expected crash about user authentication failing for Postgres. If I add the variable in my run command instead of the Dockerfile, the same crash happens. Therefore I believe it's KC_DB_USERNAME causing the issue.

I checked the migration guide and release notes for 23 and could not find anything referring to why KC_DB_USERNAME is failing now, which is why I'm reporting this as a bug. The closest I found was the "[kc.sh and shell metacharacters](https://www.keycloak.org/docs/latest/upgrading/index.html#migration-changes)" changes, but I believe that does not affect this environment variable.

### Version

23

### Expected behavior

The Dockerfile should successfully build and run.

### Actual behavior

The Docker image crashes when ran.

### How to Reproduce?

Use the following Dockerfile and connect it using your Postgres database

```
FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://localhost:5432/
ENV KC_DB_USERNAME=postgres

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

`docker build -t your-image .`

`docker run -p 8080:8080 --network="host" -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_DB_PASSWORD=your-password keycloak`

Of course change `--network="host"` and `localhost` in the `KC_DB_URL` string depending on your platform. [https://docs.docker.com/desktop/networking/#use-cases-and-workarounds-for-all-platforms](https://docs.docker.com/desktop/networking/#use-cases-and-workarounds-for-all-platforms)

**Comment by z0mb1ek** [comment]
same issue

**Comment by jbenguira** [comment]
same issue here as well

**Comment by AmsellemJoseph** [comment]
hey,
I've got the same issue since v23

**Comment by marviobezerra** [comment]
Same issue

**Comment by shawkins** [comment]
@stefannovak I was not able to reproduce this locally.  Could you try adding --verbose to the entrypoint and add the complete stack of the exception to this issue?

**Comment by premchavhan99** [comment]
I am also facing the same issue, sharing the verbose logs here:
`keycloak_1    | 2023-11-27 07:49:20,853 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[io.quarkus:quarkus-logging-json-deployment / runtime=false resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak_1    | 
keycloak_1    | 2023-11-27 07:49:20,853 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[io.quarkus:quarkus-logging-gelf-deployment / runtime=false resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak_1    | 
keycloak_1    | 2023-11-27 07:49:20,853 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[org.keycloak:keycloak-quarkus-server-deployment / runtime=false resources=null] to QuarkusClassLoader Augmentation Class Loader: PROD
keycloak_1    | 
keycloak_1    | 2023-11-27 07:49:25,179 DEBUG [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[/ runtime=true resources=null] to QuarkusClassLoader Deployment Class Loader: PROD
keycloak_1    | 
keycloak_1    | 2023-11-27 07:49:25,239 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation
keycloak_1    | 
keycloak_1    | 2023-11-27 07:49:28,660 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3fed2870
keycloak_1    | 
keycloak_1    | 2023-11-27 07:49:28,660 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3fed2870
keycloak_1    | 
keycloak_1    | ERROR: Failed to run 'build' command.
keycloak_1    | Error details:
keycloak_1    | java.lang.reflect.InvocationTargetException
keycloak_1    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak_1    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1    |         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak_1    |         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doReaugment(QuarkusEntryPoint.java:84)
keycloak_1    |         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
keycloak_1    |         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
keycloak_1    |         at org.keycloak.quarkus.runtime.cli.command.Build.run(Build.java:83)
keycloak_1    |         at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
keycloak_1    |         at picocli.CommandLine.access$1500(CommandLine.java:148)
keycloak_1    |         at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
keycloak_1    |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
keycloak_1    |         at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
keycloak_1    |         at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
keycloak_1    |         at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
keycloak_1    |         at picocli.CommandLine.execute(CommandLine.java:2170)
keycloak_1    |         at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentation(Picocli.java:218)
keycloak_1    |         at org.keycloak.quarkus.runtime.cli.Picocli.runReAugmentationIfNeeded(Picocli.java:154)
keycloak_1    |         at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:105)
keycloak_1    |         at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
keycloak_1    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak_1    |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak_1    |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak_1    |         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak_1    |         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
keycloak_1    |         at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
keycloak_1    | Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.config.ConfigValue.withConfigSourceName(String)" because the return value of "org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.transformValue(String, java.util.Optional, io.smallrye.config.ConfigSourceInterceptorContext)" is null
keycloak_1    |         at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:133)
keycloak_1    |         at org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers.getValue(PropertyMappers.java:47)
keycloak_1    |         at org.keycloak.quarkus.runtime.configuration.PropertyMappingInterceptor.getValue(PropertyMappingInterceptor.java:43)
keycloak_1    |         at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
keycloak_1    |         at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
keycloak_1    |         at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
keycloak_1    |         at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:323)
keycloak_1    |         at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.lambda$run$0(BuildTimeConfigurationReader.java:603)
keycloak_1    |         at io.smallrye.config.Expressions.withoutExpansion(Expressions.java:29)
keycloak_1    |         at io.quarkus.deployment.configuration.BuildTimeConfigurationReader$ReadOperation.run(BuildTimeConfigurationReader.java:603)
keycloak_1    |         at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.lambda$readConfiguration$0(BuildTimeConfigurationReader.java:424)
keycloak_1    |         at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
keycloak_1    |         at io.quarkus.deployment.configuration.BuildTimeConfigurationReader.readConfiguration(BuildTimeConfigurationReader.java:424)
keycloak_1    |         at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:150)
keycloak_1    |         at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:107)
keycloak_1    |         at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
keycloak_1    |         at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication(AugmentActionImpl.java:175)
keycloak_1    |         at io.quarkus.deployment.mutability.ReaugmentTask.main(ReaugmentTask.java:69)
keycloak_1    |         ... 26 more
keycloak_1    | JAVA_OPTS already set in environment; overriding default settings with values: -XX:MaxRAMPercentage=75.0`

**Comment by Morl99** [comment]
I have a similar problem, but I am chiming in, because we do not set the `KC_DB_USERNAME` parameter. This image fails with the identical error

```
FROM quay.io/keycloak/keycloak:23.0.0 as builder
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_CACHE_STACK=kubernetes
ENV KC_HTTP_ENABLED=true
ENV KC_FEATURES=account3
```

**Comment by Morl99** [comment]
And I am throwing in a commit that was added in 23 that at least touched the area where the exception is thrown:
https://github.com/keycloak/keycloak/commit/4c8724e7b1a1375810fade399ecced78a792e852

**Comment by shawkins** [comment]
@premchavhan99 thank you for the stacktrace.  The referenced line:

```
org.keycloak.quarkus.runtime.configuration.mappers.PropertyMapper.getConfigValue(PropertyMapper.java:133)
```
Seems to have no direct bearing on the message about the NPE.  There are no direct references to withConfigSourceName in keycloak, and the only one I see in quarkus https://github.com/quarkusio/quarkus/blob/dd5abd143f7d89a46b3a487313800417195b7d80/core/runtime/src/main/java/io/quarkus/runtime/configuration/QuarkusConfigValue.java#L110 looks like it would have caused other NPE messages to bubble up.  @geoand any ideas from the quarkus side?

cc @pedroigor

**Comment by Morl99** [comment]
> And I am throwing in a commit that was added in 23 that at least touched the area where the exception is thrown: [4c8724e](https://github.com/keycloak/keycloak/commit/4c8724e7b1a1375810fade399ecced78a792e852)

Yeah there is, see [this line](https://github.com/keycloak/keycloak/commit/4c8724e7b1a1375810fade399ecced78a792e852#diff-f681a3f8320c0f85b1bf524f7f503e205b9cade1cede83a5b1d38a0a5519c2ddR127) in the commit I referenced above.

**Comment by shawkins** [comment]
> Yeah there is, see [this line](https://github.com/keycloak/keycloak/commit/4c8724e7b1a1375810fade399ecced78a792e852#diff-f681a3f8320c0f85b1bf524f7f503e205b9cade1cede83a5b1d38a0a5519c2ddR127) in the commit I referenced above.

My appologies, I had assumed that change did not make it into 23 - I should have specifically checked the branch.  @pedroigor this definitely looks like a regression with the recent change.

**Comment by Morl99** [comment]
> For info, as I'm trying to update to 23, I worked around the issue with a custom entry point that sets `KC_DB_URL` from other components:
> 
> ```
> export "KC_DB_URL=jdbc:postgresql://$KC_DB_URL_HOST:$KC_DB_URL_PORT/$KC_DB_URL_DATABASE?user=$KC_DB_USERNAME&password=$KC_DB_PASSWORD&ssl=false".
> unset KC_DB_USERNAME
> unset KC_DB_PASSWORD
> unset KC_DB_URL_PORT
> unset KC_DB_URL_HOST
> unset KC_DB_URL_DATABASE
> 
> exec /opt/keycloak/bin/kc.sh "$@"
> ```
> 
> At least, on my environment, it seems to work. But definitely not a long term solution.

Nice! But beware, that this will break for all URL reserved characters in the password, like + or slash. If you can, set this from within helm and correctly percent-encode the password.

**Comment by geoand** [comment]
> 
Seems to have no direct bearing on the message about the NPE. There are no direct references to withConfigSourceName in keycloak, and the only one I see in quarkus https://github.com/quarkusio/quarkus/blob/dd5abd143f7d89a46b3a487313800417195b7d80/core/runtime/src/main/java/io/quarkus/runtime/configuration/QuarkusConfigValue.java#L110 looks like it would have caused other NPE messages to bubble up. @geoand any ideas from the quarkus side?

I can't think of anything off the top of my head, but maybe @radcortez does

**Comment by shawkins** [comment]
@geoand @radcortez sorry for the false alarm, this appears to be a recent regression that needs resolved on the keycloak side.

**Comment by geoand** [comment]
Gotcha, thanks for the update

**Comment by shawkins** [comment]
@Morl99 it's a simple fix to avoid the NPE, but I'd like to understand better why this isn't occurring on my system - why the mappedValue is null for some options - and have @pedroigor weigh in as well.

**Comment by Tomtom1410** [comment]
I have the the same issue. How do i fix it?

**Comment by vmuzikar** [comment]
@Tomtom1410 The fix will be part of 23.0.2 release.

**Comment by satanshiro** [comment]
when is 23.0.2 be released tried upgrading our dev environment and got the same issue

**Comment by syedhamzafaiz** [comment]
i am also trying to upgrade and getting this error in eks cloudwatch logs 

log": "Unknown option: '--auto-build'"
"log": "Try 'kc.sh start --help' for more information on the available options."

my docker file :

FROM --platform=linux/amd64  quay.io/keycloak/keycloak:24.0.1


ENV JGROUPS_KUBERNETES_VERSION 1.0.16.Final
# Downlaod JGroups KubePing extension
ADD --chown=keycloak:keycloak https://search.maven.org/remotecontent?filepath=org/jgroups/kubernetes/jgroups-kubernetes/$JGROUPS_KUBERNETES_VERSION/jgroups-kubernetes-$JGROUPS_KUBERNETES_VERSION.jar /opt/keycloak/providers/jgroups-kubernetes-$JGROUPS_KUBERNETES_VERSION.jar


# Add custom kubeping configuration file
COPY keycloak-settings/cache-ispn-kubeping.xml /opt/keycloak/conf

#Copy theme, plugins and extensions
WORKDIR /opt/keycloak/providers
COPY keycloak-theme/dist/ginmon-keycloak.jar ./ 
COPY script-mappers/target/script-mappers.jar ./
# uncomment for java 15+ adding the nashorn engine
# COPY script-mappers/target/providers/. ./
COPY sentry-extension/quarkus-logging-sentry-1.2.0.jar ./
COPY sentry-extension/quarkus-logging-sentry-deployment-1.2.0.jar ./
COPY sentry-extension/sentry-jul-6.1.4.jar ./
COPY sentry-extension/sentry-6.1.4.jar ./
COPY events-plugin/target/events-plugin.jar ./
COPY magic-link-plugin/target/magic-link-plugin.jar ./

ENV AWS_REGION eu-central-1
WORKDIR /opt/keycloak

#ENTRYPOINT ["bin/kc.sh", "build"]

**Comment by shawkins** [comment]
@syedhamzafaiz please do not comment like this on older issues - you may open a discussion about your question, but the answer is in the error message text. auto-build is not known option.
