### ISSUE TITLE
ServerRequestFilter / ServerResponseFilter not being picked up

### ISSUE THREAD

**Issue by dpulrichth** [keycloak/keycloak#25038]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

We have a LoggingFilter similar to the one described in the Resteasy Documentation (https://quarkus.io/guides/resteasy-reactive#the-jakarta-rest-way) included in Keycloak. This filter used to work up until Keycloak 22.0.5 but is not being picked up or logging in Keycloak 23.0.0.

The Release Notes for Keycloak 23.0.0 mention a change from Resteasy Classic to Resteasy Reactive (https://www.keycloak.org/docs/23.0.0/upgrading/#resteeasy-reactive). Howver, the filter itself does not use any Reasteasy dependency. I did find some similar filters inside the Keycloak code base itself, namely `CloseSessionHandler` and `KeycloakSecurityHeadersFilter` that are directly registered as part of the `getClasses` method of the `Application` class. I did not find an extension hook for registering our filter, however. 

### Version

23.0.0

### Expected behavior

`ServerRequestFilter` and `ServerResponseFilter` classes are picked up and run.

### Actual behavior

`ServerRequestFilter` and `ServerResponseFilter` classes are not running.

### How to Reproduce?

1. Build a simple Logging Filter like this https://quarkus.io/guides/resteasy-reactive#the-jakarta-rest-way
2. Package it into a jar file.
3. Copy jar file to Keycloak Providers directory
4. Start Keycloak and request a resource.

**Comment by alwibrm** [comment]
We're facing a similar issue with custom REST providers. We basically followed https://www.keycloak.org/docs/latest/server_development/index.html#_extensions_rest. The custom providers don't seem to be picked up anymore.

**Comment by dpulrichth** [comment]
I have been able to solve my original problem by re-writing the filter using the annotations (see https://quarkus.io/guides/resteasy-reactive#via-annotations) and including this dependency:

```
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy-reactive</artifactId>
        <version>3.2.9.Final</version>
        <scope>provided</scope>
      </dependency>
```

When I first attempted to include the dependency in the default `compile` scope, Keycloak wouldn't start and crashed with an Exception like this:
`io.smallrye.config.ConfigSourceFactory: io.smallrye.config.PropertiesLocationConfigSourceFactory not a subtype`

**Comment by ioemat** [comment]
This is probably related to #25847

**Comment by shawkins** [comment]
Can confirm the behavior described above. Will try to see if there's anything that can be done on the keycloak side, or if we'll need to open a quarkus issue.

**Comment by shawkins** [comment]
@vmuzikar @pedroigor digging more, this is related as mentioned in the description to the usage of KeycloakApplication.getClasses. 

We are hitting - https://github.com/quarkusio/quarkus/blob/11c724f566946b1fa4550e019be24b34c93e4476/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/scanning/ApplicationScanningResult.java#L44

filterClasses is defaulting to true because we have exclusions for KeycloakReadyHealthCheck and KeycloakApplication. 

So we end up discarding any user contributed ContainerRequestFilter or ResteasyReactiveContainerRequestFilter classes.

**Comment by vmuzikar** [comment]
@shawkins Is this something we can fix in 24? I don't think we document the use of Request and Response Filters, so it's considered unsupported? Thinking in terms if we should handle it as a regression.

**Comment by shawkins** [comment]
> Is this something we can fix in 24?

Not easily at first glance. This goes against usage assumptions when KeycloakApplication getClasses / getSingletons (singletons have also been deprecated).

> Thinking in terms if we should handle it as a regression.

Confirmed this scenario did work in 22. I'm guessing that the resteasy-classic stack was responsible for providing this functionality in that release.

> I don't think we document the use of Request and Response Filters, so it's considered unsupported?

Since it's just jax rs it seems like it should work - is there some documetation as to what subset is supposed to work?

Also I confirmed that the resteasy reactive annotation based approach described in https://github.com/keycloak/keycloak/issues/25038#issuecomment-1836260376 does work as expected, so at the very least there is a work around. Or if you want to document that it's the only allowed (supported?) path forward we can do that.

**Comment by sostrich** [comment]
I've had the problem that when I use the annotations as described in https://github.com/keycloak/keycloak/issues/25038#issuecomment-1836260376, I was not able to access e.g the KeycloakSession in any way, which would have been crucial for my filters to work.

**Comment by shawkins** [comment]
> I would assume that if somebody actually uses filters, doing something with the KeycloakSession might not be an unusual use case.

There seems to be some nuance here. The KeycloakSession is create by a handler via the KeycloakHandlerChainCustomizer. preMatching request filters seem to be running before the handlers, so the session is null at that time. If you remove the preMatching annotation parameter, you can have access to the session - but you'll need to do some extra checking to ensure the proxy is backed by a real session. Otherwise when the landing page or other unauthenticated resources are accessed there will be an exception.

```
class Filters {

    private static final Logger LOG = Logger.getLogger(Filters.class);

    @Context
    UriInfo info;

    @Context
    HttpServerRequest request;

    @Context
    KeycloakSession session;

    @ServerRequestFilter
    public void preMatchingFilter(ContainerRequestContext requestContext) {
        final String method = requestContext.getMethod();
        final String path = info.getPath();
        final String address = request.remoteAddress().toString();

        KeycloakSession s = null;
        try {
            if (session != null) {
                session.getContext();
            }
            s = session;
        } catch (RuntimeException e) {
            // should say something like Normal scoped producer method may not return null: org.keycloak.quarkus.runtime.integration.cdi.KeycloakBeanProducer.getKeycloakSession()
            System.out.println(e.getMessage());
        }

        LOG.infof("Request %s %s from IP %s session %s", method, path, address, s);
    }

}
```

**Comment by sostrich** [comment]
ah, interesting, thanks! This should solve our problem, Accessing the session in prematching filters worked using the `implements ContainerRequestFilter` way previously, but we can work around that part.

**Comment by shawkins** [comment]
@geoand @pedroigor I'm not sure what exactly to open as the upstream issue yet. The situation we have here is we're allowing users to install their own jax rs ServerRequestFilter / ServerResponseFilter. However the resteasy reactive scanning logic will discard them (https://github.com/quarkusio/quarkus/blob/11c724f566946b1fa4550e019be24b34c93e4476/independent-projects/resteasy-reactive/common/processor/src/main/java/org/jboss/resteasy/reactive/common/processor/scanning/ApplicationScanningResult.java#L44) because we are already using KeycloakApplication.getClasses and are specifically removing support for KeycloakReadyHealthCheck - this means that filterClasses is true and both allowedClasses and excludedClasses are non-empty. 

Should we be configuring things differently at the KeycloakApplication level, or do we need an enhancement?

**Comment by geoand** [comment]
I don't think you can do something in the current state, but I am also missing the context here.

**Comment by shawkins** [comment]
@stianst @vmuzikar do we still want this back ported even if filters are not officially supported?

**Comment by vmuzikar** [comment]
@shawkins I wouldn't backport it. Removed the label.

**Comment by dteleguin** [comment]
Great news it's back in KC25!

Just in case, JAX-RS providers are not limited to just filters (though probably that would be the most common case). ExceptionMappers were mentioned above; MessageBodyReaders/Writers are also an important use case as those would accompany custom REST endpoints.

There is a workaround for KC22..24:

```java
    @BuildStep
    @Produce(ArtifactResultBuildItem.class)
    void whitelistProviders(CombinedIndexBuildItem index, ApplicationResultBuildItem result) {
        Set<String> allowedClasses = result.getResult().getAllowedClasses();
        index.getIndex().getAnnotations(jakarta.ws.rs.ext.Provider.class).stream()
                .map(AnnotationInstance::target)
                .filter(t -> t.kind() == AnnotationTarget.Kind.CLASS)
                .map(t -> t.asClass().name().toString())
                .filter(s -> !s.startsWith("org.keycloak"))
                .forEach(allowedClasses::add);
    }
```

We added that to `org.keycloak.quarkus.deployment.KeycloakProcessor` inside or KC fork; for those who are on vanilla KC, I think this could be deployed as a small Quarkus extension if needed.

**Comment by dteleguin** [comment]
@hannahyun90 I think we have finally bumped into the same issue :confounded: have you managed to solve it? also, could you please elaborate on how exactly you re-deploy your local KC? I have restarted it a number of times and couldn't reproduce the issue. However, we're seeing it in Kubernetes.

**Comment by luzelmz** [comment]
@dteleguin I don't have experiences with quarkus extensions - just with keycloak extensions - and i don't get this code snipped to work.
Can you tell me something about your orderstructure,.. how you register this KeycloakProcessor class,..?

**Comment by viniciusd** [comment]
If anyone else comes across it, the solution on this other issue did the trick for me:
https://github.com/keycloak/keycloak/issues/26645#issuecomment-1927118948

Moving the providers to RESTEasy's `@ServerRequestFilter`/`@ServerResponseFilter`
