### ISSUE TITLE
Documentation link to https://openbanking-brasil.github.io/ broken

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#25089]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

External link to https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.html fails with 404.

The GitHub repo mentions that documentation has been moved, see https://github.com/OpenBanking-Brasil/specs-seguranca

### Version

main

### Expected behavior

Documentation links should work

### Actual behavior

Link is broken

### How to Reproduce?

https://github.com/keycloak/keycloak/actions/runs/7019244580/job/19096278203

### Anything else?

Source code is here:

https://github.com/keycloak/keycloak/blob/d954dfec5eb703382ac8a93ae7d1174832e716f7/docs/documentation/securing_apps/topics/oidc/fapi-support.adoc?plain=1#L32

**Comment by tnorimat** [comment]
I can browser the site that is reported to be broken by my browser (chrome).
https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID2-ptbr.html

**Comment by tnorimat** [comment]
@ahus1 IMO, the following might be appropriate for the documentation:

```
==== Open Banking Finance Financial-grade API Security Profile

{project_name} is compliant with the https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID3.html[Open Finance Brasil Financial-grade API Security Profile 1.0 Implementers Draft 3].
```

The reason is as follows.

- In Brazil, Open Banking Brasil started in 2021. It published the following two security profiles:

  - Open Banking Brasil Financial-grade API Security Profile 1.0 Implementers Draft 2
  - Open Banking Brasil Financial-grade API Dynamic Client Registration 1.0 Implementers Draft 2

- Keycloak 15 supported only the former and passed its conformance tests. Keycloak did not support the latter.
https://github.com/keycloak/kc-sig-fapi#open-finance-brasil-fapi-10-open-banking-brasil-fapi-10-was-renamed

- Also, Keycloak got certified as FAPI OP - Brazil Open Banking by OpenID Foundation.
https://openid.net/certification/

- From Implementer's Draft version 3, Open Banking Brasil was evolved into Open Finance Brasil.
https://openfinancebrasil.org.br/2022/11/17/qual-a-diferenca-entre-open-banking-e-open-finance/

- Central Bank of Brazil updated its site.
https://www.bcb.gov.br/en/financialstability/open_banking

- It published the following updated security profile:
   - [Open Finance Brasil Financial-grade API Security Profile 1.0 Implementers Draft 3](https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID3.html)

- Keycloak supported the updated security profile, and passed its conformance tests.
https://github.com/keycloak/kc-sig-fapi#passed-conformance-tests-per-keycloak-version

Considering the points above, it might be better to write that Keycloak is compliant with Open Finance Brasil Financial-grade API Security Profile 1.0 Implementers Draft 3.

**Comment by ahus1** [comment]
The old link now starts to work again, so the original problem of a broken link is solved. Therefore I'm closing this issue. 

Regarding the comment of @tnorimat, I'd this seems to be a valid update that should be in another issue.

**Comment by tnorimat** [comment]
@ahus1 Yes, I will create a new issue about it.

**Comment by pedroigor** [comment]
@tnorimat @ahus1 Based on the information from [here](https://openfinancebrasil.atlassian.net/wiki/spaces/OF/overview?homepageId=17367041) the change we just merged should point to the right document.
