### ISSUE TITLE
Admin UI not charging - Always is: Loading the Admin UI

### ISSUE THREAD

**Issue by dioni-dev** [keycloak/keycloak#25230]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

And it appears the following traces: Refused to frame 'http://new-auth.dev.company.com/' because it violates the following Content Security Policy directive: "frame-src 'self'".

(index):6587 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6587
chromewebdata/:1 Mixed Content: The page at 'https://new-auth.dev.company.com/admin/master/console/' was loaded over HTTPS, but requested an insecure resource 'http://new-auth.dev.company.com/realms/master/protocol/openid-connect/3p-cookies/step1.html'. This request has been blocked; the content must be served over HTTPS.

This is my ingress:

`root@dpozo:/home$ cat keycloak-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/issuer: lets-prod
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/proxy-headers: "X-Forwarded-Proto, X-Forwarded-For"
  generation: 17
  name: central-dev-keycloak
  namespace: central-dev
spec:
  ingressClassName: nginx
  rules:
  - host: new-auth.dev.company.com
    http:
      paths:
      - backend:
          service:
            name: central-dev-keycloak
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - new-auth.dev.company.com
    secretName: tls-secret
(base) root@dpozo:/home$`

In my statefulset KEYCLOAK_PROXY = edge, PROXY_ADDRESS_FORWARDING = true 

Could someone check it please?

### Version

17.3.1

### Expected behavior

it should be charge tha admin ui correctly

### Actual behavior

Not loading the ui

### How to Reproduce?

taking the same configuration as me

**Comment by jonkoops** [comment]
Looks like this bug was reported for an older version of Keycloak. We only actively support the latest version of Keycloak, please use the latest version and report it again if the issue persists.

That said, this sound like a Content Security Policy (CSP) configuration that is blocking things from loading, which you probably set yourself somewhere. I'd recommend loosening your CSP config to fix this.

**Comment by ggujabidze** [comment]
Hi, I have deployed Keycloak (from Bitnami helm chart) 2 days ago and faced exactly the same issue. As I have installed the latest version of chart, the keycloak version is 22.0.5.

I have wanted to deploy keycloak for internal PoC project, so tried to start with the very basic (least) configuration, so I can assure that I had not set CSP anywhere. If I know where can I set it besides the admin UI (which I found in documentation), I'll be more than happy to loosen that policy, to be able to access admin console. As now I'm completely blocked, as cannot even make initial configuration of product, because of inability to access admin console right after deploying it.

I have also attached the screenshot to better understand the issue. So, whenever I'm accessing the base url, it loads correctly, but as soon as I clock on 'Administration Console', I'm getting only infinite spinner. 

![Capture](https://github.com/keycloak/keycloak/assets/14991833/80616ac5-1c5d-48c8-9343-44429ba554bc)

I think the problem is that, despite the fact that I have configured tls, some resources still try to load from http. But I could not find the way, to modify that CSP.

Here is my helm values file, which basically sets only Ingress related staff and nothing more:

```
ingress:
  enabled: true
  ingressClassName: <myIngress>
  hostname: <myKeycloakHostname>
  annotations:
    cert-manager.io/cluster-issuer: <myCertManagerClusterIssuer>
    external-dns.alpha.kubernetes.io/internal-hostname: <myDNSHostname>
    kubernetes.io/tls-acme: "true"
  tls: true
```
Later I also tried to run it in do called 'Production mode' by enabling complete tls, but it didn't help.

I understand that deployment is packed by bitnami, but I think that issue come from default csp setting of the product itself and that's why I decided to search for solution here and found this latest issue.

If you will need any further details, I'll be glad to provide you them.

Thanks in advance for your assistance.

**Comment by kekersdev** [comment]
Experiencing the same issue, version 23.0.3

**Comment by jsnouffer** [comment]
We just started experiencing this issue with version 22.0.5. It would be great if this issue was re-opened.

**Comment by jonkoops** [comment]
I suggest tracking #24252 and #24252. This issue will not be re-opened.
