### ISSUE TITLE
Update uap-java to 1.6.1

### ISSUE THREAD

**Issue by dpulrichth** [keycloak/keycloak#25261]
### Description

User Agent Parser (`com.github.ua-parser.uap-java`) v1.6.1 has been released (https://github.com/ua-parser/uap-java/releases/tag/v1.6.1). This version uses a fixed Snakeyml Version to adress CVE-2022-1471. 

This CVE has been previously adressed in https://github.com/keycloak/keycloak/issues/21258 and is not reported by all image scanners, such as trivy. However, it is still listed when generating a SBOM for Keycloak as it is included as a transitive dependency.

An update to User Agent Parser 1.6.1 or higher should fix this.

**Comment by abstractj** [comment]
@douglaspalmer would you be able to check it?

**Comment by douglaspalmer** [comment]
The pull request from #21258 would fix this issue. We're not shipping the vulnerable jar but it is listed in the SBOM. https://github.com/keycloak/keycloak/pull/21509

**Comment by mdfrenchman** [comment]
@douglaspalmer this is still an issue in keycloak version 26.1.2
ua-parser.ua-java 1.54 is still referenced in the pom.xml flagging keycloak for the SnakeYaml CVE.

Adding 2.0 and excluding snake from ua-parser, didn't resolve the code scan finding. 
Is updating ua-parser an option? 
Or is this a false positive on the scan, since it's transitive?

Any additional info as to how to handle this critical finding would be appreciated. 
Thanks!
