### ISSUE TITLE
authorizationResponseIssParameterSupported returns true if compatibility option is enabled

### ISSUE THREAD

**Issue by jsaeb** [keycloak/keycloak#25419]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

It seems, that `authorizationResponseIssParameterSupported` can't be set to false.

### Version

23.0.1

### Expected behavior

When the recently implemented "Exclude Issuer From Authentication Response" option is enabled for a client, `authorizationResponseIssParameterSupported` should be set to false.

### Actual behavior

`authorizationResponseIssParameterSupported` still returns true when said option is enabled.

### How to Reproduce?

Enable the option and get the configuration for the client.

**Comment by mposolda** [comment]
@jsaeb I assume that when you're talking about "authorizationResponseIssParameterSupported still returns true" , you meant it is true in the response returned by OIDC Well-Known endpoint like http://localhost:8081/auth/realms/master/.well-known/openid-configuration . Is it correct?

In this case, it looks like a valid behaviour and not a bug. Note that OIDC Well-Known endpoint returns data about the realm. But the switch  "Exclude Issuer From Authentication Response"  is applicable only to single client. So when you switch "Exclude ISsuer from Authentication Response", you switch it just for one particular client. But all other realm clients may still support `iss` parameter and that's why "authorizationResponseIssParameterSupported still returns true" .

**Comment by abstractj** [comment]
@mposolda based on your comments, maybe we should close it?

**Comment by jsaeb** [comment]
I'm totally sorry for not replying.... Yes, after I've read the oidc-definitions on that topic it is clear, everything works correctly!
Thank you very much :)
