### ISSUE TITLE
OIDC IdP login_hint from keycloak to idp contains oid instead of username

### ISSUE THREAD

**Issue by toellbe** [keycloak/keycloak#25418]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We use an OIDC identity provider with login_hint activated. During the first login, the username is correctly transferred to the OIDC IdP via login_hint. After the user initial registration and logs in again, only the oid is passed as login_hint because the user does not have an email address.

We see the users oid under "identity provider links" in User ID AND Username. Here email seems to be required for the username and the login_hint is not based on the user's used username within the keycloak login form, but on the information in the identity provider link.

### Version

22.0.5

### Expected behavior

The login_hint to the IdP should be based on the username typed into the login form. Alternatively, the username of the Keycloak user should be used or better it should be the option to specify an alternative username attribute e.g. "upn"  in the OIDC identity provider.

### Actual behavior

oid ist stored as Username AND User ID as identity provider link if email attribute is missing. 

### How to Reproduce?

Create OIDC Identity Provider and login with a user without email attribute in IdP. to store email  attribute in keycloak use Mapper Attribute Importer upn to email.

**Comment by mposolda** [comment]
This might be a valid issue, but Keycloak team probably won't have time to look at this in the near future. Adding this to the backlog for now. Anyone is welcome to investigate this and possibly send PR to improve/fix this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details how to contribute to Keycloak.

From the description, it looks feasible to me to fallback to username instead of missing email as pointed in the comment. Hopefully we can do without additional configuration switch as there are already huge amount of configuration properties on IdP.
