### ISSUE TITLE
SSO breaks silently on double slash //

### ISSUE THREAD

**Issue by psuet** [keycloak/keycloak#25443]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When mistakenly using https://domain.tld//realms/master/protocol/openid-connect/auth (note the double slash behind the domain)  as authentication URL a user is requested to re-login besides having an active SSO session. This should either work correctly (reuse the active session for the realm) or fail transparently.

### Version

23.0.1

### Expected behavior

There are two possible behaviours I would expect:
- Either use the active session for the realm (and don't require re-login)
- or fail because of the invalid URL.

Both are reasonable, but the current behaviour is unexpected.

### Actual behavior

Besides having an active SSO session for the realm, we are requested to re-login. This re-login generates tokens as expected and specified by the client.

### How to Reproduce?

- Create Client
- Use correct Auth URL and login
- Use "wrong" Auth URL (with double slashes // somewhere after the domain)

### Anything else?

Using the containerized version of keycloak with traefik as frontend.

**Comment by rmartinc** [comment]
@psuet I suppose this is because the cookies are assigned to the path "/realms/xxxx" and are not sent by the browser to the server. So the login process starts again as new. I think that browsers sends cookies just comparing, not normalizing. Resteasy and jakarta restful ws spec normalizes the path before assign the method to execute the request. So we are trapped between specs. I don't think we want to fix this.

**Comment by jonkoops** [comment]
This issue has gone without activity for a while and seems to be a configuration problem, rather than a 'true' bug. We need to decide if there is an action to be taken here, if any, or close this issue.

I think this might warrant some shape of form validation to attend the user of their mistake, or simply prevent it from being configured in such a manner at all. I'm re-labeling this as an API/UI issue so this can be properly discussed.

**Comment by ssilvert** [comment]
I don't think this is something we will want to spend time on.  Closing.
