### ISSUE TITLE
Updating credentials preserves newlines/spaces in password

### ISSUE THREAD

**Issue by twobiers** [keycloak/keycloak#25491]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When setting credentials using the API or even from the UI, newlines and other special characters are preserved which might lead to unintended behaviour.

### Version

22.0.5

### Expected behavior

I would expect the Keycloak API to either trim leading/trailing empty characters away or validate the credentials value. Same is true for the UI.

### Actual behavior

Both the Keycloak API and Admin UI happily accept newline characters and leading/trailing spaces.

### How to Reproduce?

Visit the Admin UI and reset a users password with leading/ending spaces 

or update credentials using the API
```java
UserRepresentation userRepresentation = keycloakClient.realm("master").users().get("123456789");

CredentialRepresentation credentialRepresentation = new CredentialRepresentation();
credentialRepresentation.setTemporary(false);
credentialRepresentation.setType("password");
credentialRepresentation.setValue("  test  \n");

userRepresentation.setCredentials(List.of(credentialRepresentation));

keycloakClient.realm("master").users().get(userRepresentation.getId()).update(userRepresentation);
```

**Comment by darius-m** [comment]
Newlines may be a special case, since users expect that pressing "Enter" in a web form would trigger the submit form action, instead of adding a new line character (I don't think password inputs accept multiple lines, regardless), but spaces (including leading or trailing) and other special characters are absolutely valid characters in a password. Furthermore, aside from the non-printable ASCII characters and newlines, it would probably be wrong to consider other characters as invalid, since users can type their passwords in other languages (or even add emojis).

**Comment by twobiers** [comment]
I agree that Keycloak should do as less assumptions about valid characters in the password as possible. 
However, I think that every whitespace character **can** lead to unintended behavior by the user e.g. by copying from another source without trimming whitespaces, a base64 encoded k8s secret with a newline character coming from piping `echo "password"` into it without suppressing newline.

I think it is at least worth warning about in the Admin UI and clarify if the preservation is intended.

**Comment by mposolda** [comment]
Here it is questionable what should be correct behaviour. IMO it is better to allow whitespaces in the value instead of making assumptions on the credentials value as pointed above as in some cases whitespaces and special characters are valid values of some credential.

Keycloak team probably won't have time to look at this in the near future. Adding this to the backlog for now. Anyone is welcome to investigate this and possibly send PR to improve/fix this. See https://github.com/keycloak/keycloak/blob/main/CONTRIBUTING.md for the details how to contribute to Keycloak.

However the correct fix should not likely just blindly do triming. Maybe just some warning or something like this as mentioned in the last comment.
