### ISSUE TITLE
Docs: server_admin/topics/authentication/otp-policies.adoc

### ISSUE THREAD

**Issue by reaperb0t** [keycloak/keycloak#25509]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

File: server_admin/topics/authentication/otp-policies.adoc

### Version

23.0.1

### Expected behavior

The docs should provide clear information about how to apply OTP to users with LDAP integration enabled.

### Actual behavior

The docs do not describe the ability to utilize OTP with LDAP integration enabled. It appears that the OTP policy is triggered during new user registration, but if users log in via LDAP integration how would OTP policy be applied?

### How to Reproduce?

Please review the otp-policies documentation

**Comment by rmartinc** [comment]
@reaperb0t AFAIK there is no special configuration for OTP for users in LDAP. You just need the users to configure OTP (adding the required action `Configure OTP` for example) and have OTP in the login workiflow (default browser is enough). So to test, login into the account console with an ldap user, configure OTP in the `Signin in` page, and just logout and login again. Now the user should be requested to use OTP as 2FA in login.

That's why there is no special documentation for it, because there is no special configuration to configure OTP for ldap users.

**Comment by rmartinc** [comment]
Closin this because of inactivity..Please re-open or file a new issue if needed.
