### ISSUE TITLE
CVE-2023-4043 - Improper Input Validation vulnerability in org.eclipse.parsson:parsson

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak#25539]
### Description

Even though we are not vulnerable, we are affected by this CVE. The dependency is coming from JOSDK.

- Package Manager: maven
- Vulnerable module: org.eclipse.parsson:parsson
- Introduced through: org.keycloak:[keycloak-operator@999.0.0-SNAPSHOT](mailto:keycloak-operator@999.0.0-SNAPSHOT), io.quarkiverse.operatorsdk:quarkus-operator-sdk@6.3.4 and others

### Detailed paths

- _Introduced through_: org.keycloak:[keycloak-operator@999.0.0-SNAPSHOT](mailto:keycloak-operator@999.0.0-SNAPSHOT) › io.quarkiverse.operatorsdk:quarkus-operator-sdk@6.3.4 › io.quarkus:[quarkus-smallrye-health@3.2.9.Final](mailto:quarkus-smallrye-health@3.2.9.Final) › io.quarkus:[quarkus-jsonp@3.2.9.Final](mailto:quarkus-jsonp@3.2.9.Final) › org.eclipse.parsson:parsson@1.1
# Overview

Affected versions of this package are vulnerable to Improper Input Validation when parsing `JSON` files from untrusted sources. An attacker can exploit the built-in support for parsing numbers with large scale where the input text of a number can lead to much larger processing time than expected.

# Remediation

Upgrade `org.eclipse.parsson:parsson` to version 1.0.5, 1.1.4 or higher.

# References

- [GitHub Commit](https://github.com/eclipse-ee4j/parsson/commit/9dd5ad5f871f7b93654073a3f8ce3e1d9b8d9b31)
- [GitHub PR](https://github.com/eclipse-ee4j/parsson/pull/100)
- [GitLab Issue](https://gitlab.eclipse.org/security/vulnerability-reports/-/issues/13)
- https://www.cve.org/CVERecord?id=CVE-2023-4043

**Comment by vsun757** [comment]
Is keycloak actually vulnerable to this CVE or is it a non-issue in terms of attacks against keycloak?

**Comment by vsun757** [comment]
In other words, is this simply a vulnerability with a tool keycloak uses to deploy (JOSDK) instead of the codebase?

**Comment by abstractj** [comment]
> Is keycloak actually vulnerable to this CVE or is it a non-issue in terms of attacks against keycloak and could therefore be considered a false positive in terms of real vulnerabilities?

Parsson is a transitive dependency coming from JOSDK (Java Operator SDK), used to build our Keycloak Operator. From my limited knowledge, CVE-2023-4043 arises due to the built-in support for parsing numbers with large scale in Java, which has several edge cases. Considering that Parsson is used by JOSDK during the build time, rather than during the runtime, it is unlikely that we are vulnerable, considering that we do have control over our codebase.

@keycloak/cloud-native, is there anything that I'm missing?

**Comment by vmuzikar** [comment]
Parsson seems to be used as a runtime dependency via smallrye-health. We need to investigate if we're affected.

CC @metacosm @csviri

**Comment by metacosm** [comment]
To me, this seems more like something that needs to be addressed at the Quarkus level (if it needs to be addressed at all).

**Comment by vmuzikar** [comment]
@abstractj Do you want to be the reporter of this CVE in smallrye-health? Doesn't seem to be reported yet (at least I didn't  find a public issue).

**Comment by abstractj** [comment]
> @abstractj Do you want to be the reporter of this CVE in smallrye-health? Doesn't seem to be reported yet (at least I didn't find a public issue).

@vmuzikar it seems that they are already aware about it. The dependency was upgraded to 1.1.5 https://github.com/smallrye/smallrye-health/blob/main/pom.xml#L38. Can you think about any other project which we should communicate this issue, apart from Quarkus?

**Comment by vsun757** [comment]
Greetings All,

I just wanted to ask – what is the current status of this issue?

Thanks,

Victor

From: Václav Muzikář ***@***.***>
Reply-To: keycloak/keycloak ***@***.***>
Date: Tuesday, January 23, 2024 at 11:37 AM
To: keycloak/keycloak ***@***.***>
Cc: Victor Sun ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [keycloak/keycloak] CVE-2023-4043 - Improper Input Validation vulnerability in org.eclipse.parsson:parsson (Issue #25539)

Can you think about any other project which we should communicate this issue, apart from Quarkus? No, I'm not. Seems the parsson dependency in smallrye-health was updated in 4. 1. 0. In Quarkus, smallrye-health 4. 1. 0 will be included in 3. 7. 0


Can you think about any other project which we should communicate this issue, apart from Quarkus?

No, I'm not.

Seems the parsson dependency in smallrye-health was updated in 4.1.0<https://github.com/smallrye/smallrye-health/commit/739e4091732dddbb4772ca04cce8259ccd6de1f1>. In Quarkus, smallrye-health 4.1.0 will be included in 3.7.0 release<https://github.com/smallrye/smallrye-health/commit/739e4091732dddbb4772ca04cce8259ccd6de1f1>. Hence this should be fixed by #26203<https://github.com/keycloak/keycloak/pull/26203>.

**Comment by vsun757** [comment]
For the status, please follow up on the GitHub issue. This mailing list is
*only* for vulnerability reports into the codebase. Please, *do not* use it
to discuss anything associated with third-party libraries.

And please, *do not* make cross-post with this mailing list.

**Comment by abstractj** [comment]
> Greetings All, I just wanted to ask – what is the current status of this issue? Which keycloak version will it be fixed in? Thanks, Victor

Currently, we don't have any estimates. Parsson, identified as a third-party dependency, comes from the Operator SDK. Also worth to mention that Keycloak is not vulnerable to this CVE, only affected. 

The issue should be fixed with the upcoming upgrade to the new version of Quarkus.

**Comment by shawkins** [comment]
This was addressed by the 3.7 upgrade. With 3.8.4 we are now on version 1.1.5
