### ISSUE TITLE
Incorrect JSON format returned in case of existing user (with user federation)

### ISSUE THREAD

**Issue by limsedan** [keycloak/keycloak#25778]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When Keycloak is configured with an LDAP user federation and a user of this federation already exists as a local account (when email is username and therefore unique), the API request GET /users returns the following payload (version 23.0.3) : 
```json
{
	"error": "unknown_error"
}
```
In version 23.0.0, when I first discovered this error, it returns a wrongfully formed payload such as : 
```json
[
    {
		"id": "id",
		"createdTimestamp":  1703277986,
		"username": "username",
		"enabled": true,
		"totp": false,
		"emailVerified": false,
		"firstName": "firstName",
		"lastName": "lastName",
		"email": "email",
		"federationLink": "federationLink",
		"attributes": {
			"LDAP_ENTRY_DN": [
				"LDAP_ENTRY_DN"
			],
			"createTimestamp": [
				"createTimestamp"
			],
			"modifyTimestamp": [
				"modifyTimestamp"
			],
			"LDAP_ID": [
				"LDAP_ID"
			]
		},
		"disableableCredentialTypes": [],
		"requiredActions": [],
		"notBefore": 0,
		"access": {
			"manageGroupMembership": true,
			"view": true,
			"mapRoles": true,
			"impersonate": true,
			"manage": true
		}
	},
	{
		"id": "id",
		"createdTimestamp": 1703277986,
		"username": "username",
		"enabled": true,
		"totp": false,
		"ema{"error":"unknown_error"}
```

Moreover, in admin UI, the following message appears when listing all users : 
> No users found, could be due to wrongly configured federated provider unknown_error

If we search for the culprit user in UI (that I finally found), Keycloak returns nothing.

### Version

Tested on 23.0.0 and 23.0.3

### Expected behavior

Returning an appropriate list of users (as because of one user, all the list can't be accessible), or a more specific error (in API and UI)

### Actual behavior

In API, GET /users returns only :  
```json
{
	"error": "unknown_error"
}
```

In UI, following error is shown : 
 > No users found, could be due to wrongly configured federated provider unknown_error

### How to Reproduce?

Set username as email in realm, then add a local user with an email that exists in your LDAP database.
Then add the LDAP user federation (READ_ONLY, with option importing users).
Finally try to list all users, or request them via API

### Anything else?

I saw a very similar issue #23396 but was closed as the behavior was similar but the origin not (and it hasn't reproduced in 23.0.3)

**Comment by rmartinc** [comment]
Looking into this, as you say, this is very similar to of https://github.com/keycloak/keycloak/issues/23396 but triggered by a different cause. For what I see there is a `ModelDuplicateException` in the [importUserFromLDAP](https://github.com/keycloak/keycloak/blob/23.0.4/federation/ldap/src/main/java/org/keycloak/storage/ldap/LDAPStorageProvider.java#L528) because of the conflicting email when the user is imported into the internal db for the first time. After reading https://github.com/quarkusio/quarkus/issues/34419, the incorrect JSON can be returned depending the buffer size quarkus is using to construct the response. It happens when the output buffer was already filled and sent to the client and later the conflicting user is added to the response. There is no way of resetting the response.

In my tests I can avoid the incorrect json incrementing the `quarkus.resteasy-reactive.output-buffer-size` from default 8KB to 8MB (I used the `conf/quarkus.properties` file to set the new value). I think we won't want to change this general behavior.

But I think you just want to avoid the import of the conflicting user and return all the rest of users or, at least, show a proper error with the invalid user (right now it requires to set `org.keycloak.services.error` to DEBUG devel). I think we can do the first option and log an error for the conflicting user. A different search can import them if the user with the duplicated email is not returned by the search. I'll prepare a PR but probably I need to wait to https://github.com/keycloak/keycloak/pull/25775 to be merged.

**Comment by pedroigor** [comment]
@rmartinc I see you have referenced a commit to fix this problem. Are you planning to send a PR? Otherwise, please let me know so we can take it from where you started.

**Comment by rmartinc** [comment]
@pedroigor The fix is ready, but I needed to wait to another PR to be merged. I need to rebase and send the PR. I will continue with it if you don't mind.

**Comment by nikita-kuznetsov** [comment]
I have the same issue, but it behave a little bit different.

When I'm requesting all users via API, server have correct response, but when I making request WITH PAGINATION (max and first query params) I got an error ONLY ON THE LAST PAGE:
 `  },
    {
        "id": "222aa110-3ce8-4337-880b-950d5057431b",
        "username": "zyabko",
        "firstName": "Алексей",
        "lastName": "Зябко",
        "email": "zyabko@capitalgroupcorp.com",
        "emailVerified": false,
        "attributes": {
            "LDAP_ENTRY_DN": [
                "CN=Zyabko\\, Alexsey,OU=CapitalCity,OU=Users,OU=Corporate,DC=cgcorp,DC=com"
            ],
            "department": [
                "Департамент безопасности"
            ],
            "full_name_ru": [
                "Зябко Алексей Валентинович"
            ],
            "branch": [
                "Управление режима и охраны"
            ],
            "LDAP_ID": [
                "e2afeeb6-2f5c-4711-965e-ce816960ab96"
            ],
            "modifyTimestamp": [
                "20240228115740.0Z"
            ],
            "createTimestamp": [
                "20200715114222.0{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}`

I'm also have several user federation with different username mappings (to resolve duplicates), I found which one caused this issue, but have no clue why. Also there is nothing in application log (info), and when I switch to DEBUG level, it produces over 100k entries at once
`
Mar 05 15:29:33 keycloack01 systemd-journald[701606]: [🡕] Suppressed 111245 messages from keycloak.service
`
