### ISSUE TITLE
Infinispan Cache(embedded) data is not being updated during mergeView event

### ISSUE THREAD

**Issue by sujaykulkarn** [keycloak/keycloak#25837]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

We have a Quarkus keycloak(version) statefulset with 2 replicas. We intentionally set the num_discovery_runs=1 to simulate network partitions. By setting num_discovery_runs to such a low value for kubernetes based Jgroups Discovery protocol, we can simulate both the replicas initially considered themself as master. Later due to merge protocol of Jgroups these instances able to view eachother and the view reconciles. 
 
We update the master realm header only in one of the replica, before the view reconciled. We are updating the realm header via following rest call 

`curl -g -X PUT "https://${POD1_IP}:${KC_HTTPS_PORT}${KEYCLOAK_PATH}/admin/realms/master/" -H "Authorization: Bearer ${TKN}" -H "Content-Type: application/json" -d '{"displayName":"My Custom Realm displayName", "displayNameHtml": "<div class=\"kc-logo-text\"><span>My Custom Realm displayName</span></div>"}'`

We are observing that only one instance of keycloak is getting updated with this change and other instance is not getting updated ever in the lifetime of that keycloak cluster. 
We check the change in the displayName with below rest call. 

`curl -vk https://${POD2_IP}:${KC_HTTPS_PORT}${KEYCLOAK_PATH}/admin/realms/master/ -H "Authorization: Bearer $TKN" | jq -r '.displayName'`

We think Realm caches are not getting synced after the rebalance of membership. Although we have simulated this for the realm cache but we think the same issue is applicable for any other local or distributed cache if keycloak server does not explicitly handle the network partitions scenario. Refer - http://www.jgroups.org/manual5/index.html#HandlingNetworkPartitions 

We are using the default Infinispan cache configuration for kubernetes. 

### Version

22.0.5

### Expected behavior

Once the views are merged after network partitions. Data in the caches should refresh there content from database where applicable or merge there contents(e.g. Authorization tokens)

### Actual behavior

Data in the caches are becoming divergent after network partitions, even though the views were merged at the Infinispan level. 

### How to Reproduce?

Please refer the description.

**Comment by sschu** [comment]
The `realm` cache is not a distributed cache but just a local cache. So the fact it is not being synchronized automatically by Infinispan is expected. It might be possible to just invalidate the complete realm cache when recovering from a network partition, though.

**Comment by ShaswataJash** [comment]
@sschu Hello Sebastian, keycloak server should subscribe to 'ViewChangedEvent' notification from infinispan. If that is done, then keycloak server itself can send message in the 'WORK' cache to invalidate all the local caches, isn't it? 
Also, can you please help us to understand how this issue is automatically taken care for distributed caches? May be reference to the actual source code snippet which is taking care of network-partition handling for distributed cache will greatly help.

**Comment by sschu** [comment]
@ShaswataJash Yup, something in the direction you proposed. For distributed caches, updating cache data after a split would be up to Infinispan, so you would have to look there for code references.

**Comment by ahus1** [comment]
There is already some code which listens to view change events for the WORK cache. At the moment, it is removing stale locks from the work cache. 

https://github.com/keycloak/keycloak/blob/5b1b3ca11be8526482c1cfc3a441c747b107a991/model/infinispan/src/main/java/org/keycloak/cluster/infinispan/InfinispanClusterProviderFactory.java#L197-L210

If this is a merge view, one could also clear all local caches. 

I'd be happy to see a community contribution for this.

**Comment by pruivo** [comment]
I would not use the `work` cache for this since it would invalidate the remote sites in multi-site deployments. 

Since the event is triggered in all the Keycloak server nodes, I would just clear the local cache directly (assuming it would invoke only `cache.clear()` and no other operation is required).

**Comment by ryanemerson** [comment]
It should also be possible to use a [MergeEvent](https://github.com/infinispan/infinispan/blob/313b19301055c6267c6f2ea9065a7ab1b68099fe/core/src/main/java/org/infinispan/notifications/cachemanagerlistener/event/MergeEvent.java) instead of a `ViewChangedEvent ` for this use-case so there are no unnecessary invalidations.

**Comment by belaban** [comment]
BTW: there are better ways to inject a split into a network than setting {{num_discovery_runs}}, e.g. by injecting a new view directly into nodes, or by using DISCARD [1].
[1] https://github.com/belaban/JGroups/blob/master/src/org/jgroups/protocols/DISCARD.java
