### ISSUE TITLE
This condition is always true, so that no role can be created as expect.

### ISSUE THREAD

**Issue by miguoliang** [keycloak/keycloak#25926]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

testsuite

### Describe the bug

In a integration test, developer could create a user and assign a role to the user, for convinence, the method `assignRoleWithUser` is designed to create the specified role if it does not exist. However, after my review on its code, I found the condition used to check the existence of the role is always true, and on the next step, an not found exception will be raised from this exception because of the missing of the role.

### Version

23.0.3

### Expected behavior

Create a role if it does not exist.

### Actual behavior

This condition is always true, and the missing role is not created as expect.

### How to Reproduce?

```
    fluentTestsHelper.createTestUser(username, password)
        .assignRoleWithUser(username, "user");
```

### Anything else?

Considering use `try-catch` to check the existence of a role.

**Comment by sguilhen** [comment]
I think the condition will always be false because the `get("roleName")` is resolved to a proxy even when the server-side endpoint thrown an exception. In this case, it would probably be better to change the condition to something like

 ```
         if (keycloak.realms().realm(testRealm).roles().list().stream().noneMatch(rep -> rep.getName().equals(roleName))) {
```

I'll accept this one as a low priority bug - any PR from the community would be appreciated in case people are using this class in their environments to test the integration with Keycloak. Our own testsuite is not using it.
