### ISSUE TITLE
When the Realm is created, the "User's default Roles" and the "Roles assigned to the client scope mapping in the account-console" are different.

### ISSUE THREAD

**Issue by megumish** [keycloak/keycloak#25928]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

When the Realm is created, the "User's default Roles" and the "Roles assigned to the client scope mapping in the account-console" are different.

For example, this prevents a user from seeing the group when he or she logs in to the Account Console client.

### Version

23.0.3

### Expected behavior

When a Realm is created, the "User's default Roles" is same from the "Role assigned to the account-console Client Scope Mapping."

### Actual behavior

When the Realm is created, the "User's default Roles" and the "Roles assigned to the client scope mapping in the account-console" are different.

### How to Reproduce?

If DefaultRole and ClientScopeMapping are imported without writing them to the realm configuration file

**Comment by megumish** [comment]
https://github.com/keycloak/keycloak/blob/60f80ce0c8fe3e72489422bb177992998021c40b/services/src/main/java/org/keycloak/services/managers/RealmManager.java#L430-L434

Although the implementation here references the DEFAULT of the AccountRole,

https://github.com/keycloak/keycloak/blob/60f80ce0c8fe3e72489422bb177992998021c40b/services/src/main/java/org/keycloak/services/managers/RealmManager.java#L467-L468

it specifies a different one here.

Unless this is an intentional implementation, I would create a PR to fix this.

**Comment by martin-kanis** [comment]
@megumish Sorry but from the description and steps to reproduce I don't really know how to reproduce the issue. Can you please add more details and the file you are trying to import? Thanks

**Comment by megumish** [comment]
@martin-kanis 
Thanks for the reply!

A simple example would be creating a Realm from the UI without importing anything.

In this case, the client scope set in the Account Console client is different from the one set in the User's default role in the  Realm.

This seemed like an unnatural setting to me.

**Comment by martin-kanis** [comment]
@keycloak/core-clients Do you have any opinion about this?

**Comment by stianst** [comment]
Super confused about the description and understanding what the issue is.

The default roles added to a user doesn't include `view-groups` and it is expected that you would add that to individual users, or to the realm default roles to make it available to all users. The `account-console` does have scope on the `view-groups`, so you wouldn't need to update that, but I noticed that `account-console` doesn't have scope on all `account` client roles which it probably should have by default.

**Comment by megumish** [comment]
It pains me that I cannot communicate my intentions well.

Personally, as far as the difference between the default assigned Role and Client Scope Mapping, I can accept it as such. I can also override those defaults and change them to the behavior I want.

I just want to know the intent of `AccountRoles.DEFAULT` being used on the one hand and not being used on the other and being specified directly in the source code.

**Comment by sschu** [comment]
@megumish I think there are two different questions here:
a) What are the default scopes for the account-console client.
b) What are the default account roles for a user.
The answer to a) is pretty clear: the account console needs to have all account roles available as scopes in order to do its job.
The answer to b) is not that clear. You could argue that the user should per default be able to do everything with his account. You could also argue that per default, you want a setup that is more in line with least privileges principles e.g. you could say the user should not be able do modify his account per default.
We could definitely discuss which set of default roles make sense for a user. However, any change to the default roles is potentially dangerous it could either break existing deployments if roles are removed or harm their security if new roles are added.

**Comment by megumish** [comment]
@sschu Certainly, we can consider other ideas regarding question b), and it is a difficult question. And I understand the dangers of changing it carelessly.

I don't see any benefit in changing it, so I'll close this issue. Thanks for your time discussing this. I like keycloak a lot, and if I can contribute anything, I will. Thank you very much!

**Comment by sschu** [comment]
@megumish I think there is definitely still an issue here because a) is not in place. The account console currently only works if the user has `manage-account` (which is the default). At the same time, the account REST API typically allows access to all endpoints if `manage-account` is available. I will reopen this for now and try to discuss if there is anything we can do here.

**Comment by sschu** [comment]
@megumish I have seen there is already an open enhancement request to sort this out (https://github.com/keycloak/keycloak/issues/23606). I would handle the scopes topic as part of that issue.
