### ISSUE TITLE
Failing to import client's authorisation settings through UI

### ISSUE THREAD

**Issue by yujietan** [keycloak/keycloak#25975]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Unable to import client authorisation settings.

### Version

20.0.1

### Expected behavior

importing another client's authorisation settings into client should create the respective resource, policies, scopes and permissions

### Actual behavior

importing another client's authorisation settings into client does not create the respective resource, policies, scopes and permissions 

### How to Reproduce?

1. create client "test" with client authn and authz turned on
2. head over to "test" client Authorization tab
3. delete the default policy and resource
4. create new resource "A-resource"
5. create client policy "A-policy" with account client
6. create resource permission (A-permission) with A-resource tagged to A-policy
7. export the client's authz settings
8. create client "test2" with client authn and authz turned on
9. import the exported "test" client authz settings to test2
10. head over to test2 Authorization tab.
11. It will be still the same state when it was created. A-resource, A-policy and A-permission are not exported

### Anything else?

Hihi just to update. I tried with keycloak 23.0.3. The import still doesnt work. HOWEVER it only works if its imported into the same client that it exported out from. Is this suppose to be the behavior?

_No response_

**Comment by mhajas** [comment]
Thank you for the report. This is indeed a bug. I was able to reproduce this.

This has been an issue for a long time, I tested randomly with Keycloak 12.0.1 and it is present there too.

The reason for this issue is that current authz storage does not check ResourceServer id when searching for [Resources](https://github.com/keycloak/keycloak/blob/acd9def8aa7f7f782edc8d59fca2551f1e04bb86/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAResourceStore.java#L91-L99)/[Policies](https://github.com/keycloak/keycloak/blob/c4b1fd092a14f99961c88013cf051bf2089c00bb/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAPolicyStore.java#L94-L106)/[Scopes](https://github.com/keycloak/keycloak/blob/acd9def8aa7f7f782edc8d59fca2551f1e04bb86/model/jpa/src/main/java/org/keycloak/authorization/jpa/store/JPAScopeStore.java#L89-L99) by id.

The question is whether we want to introduce a query that includes both `id` and `resourceServerId` or if it is faster to search by id and then check in Java whether the resource server id is correct. I would vote for the first option but didn't do a perf comparison. The fix should consist from fixing this for all authz entities (links above^) and a test testing this.

It seems it was introduced here: https://issues.redhat.com/browse/KEYCLOAK-4929

I would say this is not the highest priority at the moment therefore I am marking this issue as `help-wanted`.

##### Workaround

I was able to import the setting when I removed all "id:" from the imported JSON. For example:
```json
    {
      "id": "ade5be55-6dc3-4b60-bb76-0a3d8c4d0d36",
      "name": "Permission A",
      "description": "",
      "type": "resource",
      "logic": "POSITIVE",
      "decisionStrategy": "UNANIMOUS",
      "config": {
        "resources": "[\"Resource A\"]"
      }
    }
```
to 
```json
    {
      "name": "Permission A",
      "description": "",
      "type": "resource",
      "logic": "POSITIVE",
      "decisionStrategy": "UNANIMOUS",
      "config": {
        "resources": "[\"Resource A\"]"
      }
    }
```

**Comment by udayrachati** [comment]
i have tesed with version 23.0.0.6 version ,i am not able to import with authorizationSettings

**Comment by jonkoops** [comment]
> i have tesed with version 23.0.0.6 version ,i am not able to import with authorizationSettings 👍

Just FYI, that version is no longer supported. Please ensure this is reproducible in the latest version of Keycloak.

**Comment by millwheel** [comment]
It is reproducible in Keycloak 24.0.1

**Comment by millwheel** [comment]
I solved this problem by creating new named query for each entity and set each id as null when importing the client's authorization setting. I will prepare PR if you are still interested in this issue.

**Comment by millwheel** [comment]
I created PR for this issue.
https://github.com/keycloak/keycloak/pull/28317
