### ISSUE TITLE
Enable verify-profile required action by default

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#25985]
### Description

This is to enable verify-profile required action by default for new realms, which can be done once user-profile is enabled by default.

This was planned as part of the task https://github.com/keycloak/keycloak/issues/25151, but I am creating separate task to handle verify-profile action as it is quite a lot of test failures in the testsuite and hence handling this in separate task might be better as #25151 is already quite big.

Tests are failing as we have lots of the tests, which just create user with username/password and then login, but this breaks the test assumption (as the test now display verify-profile page instead of directly login user). We might need to update tests in the manner like:
- Disable verify-profile just in the testsuite for the affected tests
- Create user entirely in the particular tests (including firstname, lastname, email etc)
- Rewrite some tests to display user-profile page and fill the remaining attributes

Maybe some combination of all approaches above might work.

We might also consider whether verify-profile page should be really enabled by default? IMO it can be nice, but not 100% sure it is strictly needed.

**Comment by mposolda** [comment]
Discussed with @pedroigor . We agreed on potentially closing this issue and add `verify-profile` required action just on demand (so not having it as enabled by default in the new realms).

**Comment by mposolda** [comment]
Discussed this with @stianst . He mentioned that it can be nice to have verify-profile action enabled by default in new realms. But not a blocker for Keycloak 24.

**Comment by rmartinc** [comment]
@mposolda @pedroigor Yesterday I was doing a first try with this. There are tons of tests that fail but, if we disable the verify profile action in the imported tests, it reduces the failures a lot. So I have followed that route and then enabled it for some of them. Nevertheless some users should also be created fully filled (when the master realm is managed for the test instead of the imported one). My branch is https://github.com/rmartinc/keycloak/tree/issue-25985 and test passed OK for keycloak-ci (https://github.com/rmartinc/keycloak/actions/runs/7508488765). I see that javascript-ci fails (https://github.com/rmartinc/keycloak/actions/runs/7508488764) so probably some modification is needed for it (not checked at all yet). So let me know what you think, I'll maintain the branch if we decided to delay this to have the current changes there.

**Comment by mposolda** [comment]
@rmartinc Thanks! IMO your testsuite changes are fine.

But it raises some questions how exactly to handle admin user. I wonder about some options like: 
1) auto-fill firstname, lastname, email (pretty much like you did)
2) Skip this required action for master realm
3) Let the admin fill his profile (email, firstname, lastname) during first login (maybe not that ideal due it complicates various automation stuff, which assume admin user fully set)
4) Something else?

**Comment by rmartinc** [comment]
@mposolda Yes, exactly, initially all tests failed because the `admin` user could not login. I just did the easiest approach which was creating the `admin` user with all the values (firstName and lastName as the username, hardcoded/invalid email). A possible 4 point would be that the required action skips the admin user in master (so similar to 2 but just for the super admin user, not for all the maser realm).

For the moment I'm not working on this, if it's required for 24 let me know to polish it and send a PR.

**Comment by mposolda** [comment]
Added to Keycloak 24 for now, but started discussion on core ML for whether to enable it by default or not in Keycloak 24

**Comment by rmartinc** [comment]
Re-opening issue as the PR was reverted because it was affecting other CIs.

**Comment by marc-weber1** [comment]
This is really disruptive to automatic workflows - I was just trying to set up a user that is only logged into by an API with no email, username, or password, and had to spend an hour finding this issue before I figured out how to just get a token with postman.

A stack overflow answer slowly getting upvotes, from people that had to figure out the same thing: https://stackoverflow.com/a/78212422

Would really recommend reversing this PR, a lot of APIs using keycloak already implement their own verification for profile information before calling keycloak and this commit is actively making it harder for devs to use.

@mposolda

**Comment by SailReal** [comment]
@HerrDerb we aren't exactly in the same situation as we tried to disable it during Realm import but I created https://github.com/keycloak/keycloak/issues/29220 for it.
