### ISSUE TITLE
Permanently lock users out after X temporary lockouts during a brute force attack

### ISSUE THREAD

**Issue by douglaspalmer** [keycloak/keycloak#26172]
### Description

Instead of forcing administrators to choose between temporary and permanent lockouts during brute force attacks we should allow them to use both. The administrator should be able to specify a number of temporary lockouts permitted before permanent lockout. Setting 0 would go straight to permanent lockout and setting -1 would never permanently lockout.

**Comment by mposolda** [comment]
My vote is to use `-1` for both new and existing realms (By existing realms I meant the realms migrated from previous versions) due the fact that permanent lockout has some other price to pay (especially it allows potential attacker to permanently lockout the accounts of valid users just by knowing their usernames).

**Comment by ad-zsolt-imre** [comment]
> My vote is to use `-1` for both new and existing realms (By existing realms I meant the realms migrated from previous versions) due the fact that permanent lockout has some other price to pay (especially it allows potential attacker to permanently lockout the accounts of valid users just by knowing their usernames).

God bless you @mposolda .

I was looking to see how this feat worked as I wanted to make sure neither the permanent nor the temporary lockouts were default behaviour or enabled by default. I'd hate to have a "security feature" that opens up a security vulnerability by allowing an attacker to locking out users and, thus, perform a denial of service attack.

(Now I'm even thinking if there was a way to completely hide/remove this "enable DoS" feature from our Keycloak admins?)

**Comment by hpopov** [comment]
Hey, @douglaspalmer !
After migration from Keycloak 20 (with `permanentLockout` set to `false`) to Keycloak 24 I had `maxTemporaryLockouts` **set to zero by default**, even though, according to the ticket / implementation description it should have been set to `-1`.

Isn't this a migration bug?

How it used to be: new realm is created with kcadm.sh (`./kcadm.sh create realms --file "$tmpFile`) with the following config properties:

```json
...
  "bruteForceProtected": true,
  "permanentLockout": false,
...
```

Now, after creating a new realm with the same configuration, and then exporting that configuration back, I receive
```json
...
  "bruteForceProtected": true,
  "permanentLockout": false,
  "maxTemporaryLockouts": 0,
...
```

I would expect `maxTemporaryLockouts` to be set to **-1**, otherwise it contradicts `permanentLockout: false` property. It seems to be an issue with configuration properties: on Keycloak Console BruteForce mode is "Lockout temporarily":
![image](https://github.com/keycloak/keycloak/assets/41228916/c2968fa0-6a70-42ec-8d28-8b4358741a6a)

**Comment by douglaspalmer** [comment]
> Hey, @douglaspalmer ! After migration from Keycloak 20 (with `permanentLockout` set to `false`) to Keycloak 24 I had `maxTemporaryLockouts` **set to zero by default**, even though, according to the ticket / implementation description it should have been set to `-1`.
> 
> Isn't this a migration bug?
> 
> How it used to be: new realm is created with kcadm.sh (`./kcadm.sh create realms --file "$tmpFile`) with the following config properties:
> 
> ```json
> ...
>   "bruteForceProtected": true,
>   "permanentLockout": false,
> ...
> ```
> 
> Now, after creating a new realm with the same configuration, and then exporting that configuration back, I receive
> 
> ```json
> ...
>   "bruteForceProtected": true,
>   "permanentLockout": false,
>   "maxTemporaryLockouts": 0,
> ...
> ```
> 
> I would expect `maxTemporaryLockouts` to be set to **-1**, otherwise it contradicts `permanentLockout: false` property. It seems to be an issue with configuration properties: on Keycloak Console BruteForce mode is "Lockout temporarily": 

We changed the way the implementation worked as we developed things. Instead of using a three way switch on a numeric value (-1, 0, >0) we went with 2 separate variables permanent lockout (true or false) and maxTemporaryLockouts (0 or more). 

Permanent lockout == false is old school temporary lockouts
Permanent lockout == true && maxTemporaryLockouts == 0 is old school permanent lockout
Permanent lockout == true && maxTemporaryLockouts > 0 is the new mixed mode
