### ISSUE TITLE
`GroupRepresentation.getSubGroups` no longer returns subgroups

### ISSUE THREAD

**Issue by transducer** [keycloak/keycloak#26227]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client/java

### Describe the bug

When calling [`getSubGroups`](https://www.keycloak.org/docs-api/23.0.4/javadocs/org/keycloak/representations/idm/GroupRepresentation.html#getSubGroups()) on a group that has subgroups, an empty list is returned.

As described in [this comment](https://github.com/keycloak/keycloak/issues/25053#issuecomment-1893563713) and [the upgrading guide](https://www.keycloak.org/docs/latest/upgrading/index.html#groupprovider-changes), the subgroups field is no longer available in the API because of performance reasons. I expected the call to `getSubGroups` is impacted by this change.

### Version

23.0.4

### Expected behavior

When calling `getSubGroups` on a group resource the list of subgroups is returned.

### Actual behavior

When calling `getSubGroups` on a group resource an empty list is returned.

### How to Reproduce?

Create a group with subgroups.

```java
GroupRepresentation group = realm.groups.group(id).toRepresentation();
group.getSubGroups(); // empty list
```

**Comment by transducer** [comment]
Also [`getSubGroupCount`](https://www.keycloak.org/docs-api/23.0.4/javadocs/org/keycloak/representations/idm/GroupRepresentation.html#getSubGroupCount()) returns null.

**Comment by transducer** [comment]
Via [`realm.groups.query()`](https://www.keycloak.org/docs-api/23.0.4/javadocs/org/keycloak/admin/client/resource/GroupsResource.html#query(java.lang.String)) the whole hierarchy is still recursively returned with working `getSubGroups`, so that is a workaround for now.

**Comment by alice-wondered** [comment]
That's interesting. The underlying method for the linked `realm.group.groups()` functionality is setup to always populate the subgroup count. Not sure why it would get excluded outside of lacking view permissions (but then the groups shouldn't get returned either). 

The hierarchy workaround also interests me because the hierarchy population was previously happening in conjunction with the DB query and was removed from there. AFAIK there isn't anywhere where we climb to the root of the hierarchy and then initiate a full population of the tree but I could have missed something. 

Haven't confirmed/reproduced yet as my attention is elsewhere but wanted to share my initial thoughts

**Comment by jruhe-adesso** [comment]
I can confirm the issue. getSubGroups() always returns an empty list now (using 23.0.6).

**Comment by martin-kanis** [comment]
OK, only `GroupRepresentation#getSubGroups()` doesn't return any subgroups. `GroupResource#getSubGroups()` is working fine. 

```
assertEquals(1, realm.groups().group(topGroup.getId()).getSubGroups(0, null, false).size());
GroupRepresentation representation = realm.groups().group(topGroup.getId()).toRepresentation();
assertEquals(1, representation.getSubGroups().size()); // this fails
```

`GroupRepresentations` states following comment:
```
// For navigating a hierarchy of groups, we can also include a minimum representation of subGroups
// These aren't populated by default and are only included as-needed
protected List<GroupRepresentation> subGroups;
```

@pedroigor @sguilhen @alice-wondered We need a consensus what is an expected behavior and make sure it is consistent across Keycloak codebase. Also documentation and REST API docs need to be checked.

**Comment by jruhe-adesso** [comment]
Leider ist `GroupResource#getSubGroups()` eine recht neue Methode, die in älteren Versionen von Keycloaks Admin-Client keine Entsprechung hat. Wenn man wie wir den Client noch nicht upgraden kann (neuere Versionen des Clients benötigen Java 17), sitzt man in der Falle, wenn der Keycloak-Server upgegradet wird.

**Comment by pedroigor** [comment]
@jruhe-adesso We can't do much but recommend using the Java version used by Keycloak.

@transducer Please, look at https://www.keycloak.org/docs/23.0.7/upgrading/#fix-handling-of-groups-getsubgroups-briefrepresentation-parameter. As mentioned in other comments, sub-groups are now handled differently for performance reasons.
