### ISSUE TITLE
OIDC logout when not logged in redirects to wrong url without scheme and authority

### ISSUE THREAD

**Issue by bocca** [keycloak/keycloak#26245]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When invoking protocol/openid-connect/logout, if KEYCLOAK_IDENTITY cookie is missing, invalid or expired, Keycloak should redirect to the full post_logout_redirect_uri URL. Instead, it redirects to the path & query part of that URL, without origin (scheme, domain and port), If post_logout_redirect_uri and Keycloak have different origins, the browser redirects to the wrong URL. For example, the use could land to the Keycloak 404 page.

Note that, if the KEYCLOAK_IDENTITY cookie is valid, the logout continues normally, and the final redirecto to the full post_logout_redirect_uri works fine.

### Version

23.0.4

### Expected behavior

When invoking protocol/openid-connect/logout with a valid full post_logout_redirect_uri, and WITHOUT a valid KEYCLOAK_IDENTITY cookie, Keycloak should redirect to the full post_logout_redirect_uri.

### Actual behavior

When invoking protocol/openid-connect/logout with a valid full post_logout_redirect_uri, and WITHOUT a valid KEYCLOAK_IDENTITY cookie, Keycloak redirects to the path & query part of post_logout_redirect_uri.

### How to Reproduce?

Initiate a logout to protocol/openid-connect/logout, but WITHOUT a valid KEYCLOAK_IDENTITY cookie. For example, capture a valid logout in 'Fiddler' debug proxy, and repeat the request to protocol/openid-connect/logout in the 'Composer' tab, removing the 'Cookie' header. The response contains a Location header with the path & query part of post_logout_redirect_uri.

**Comment by bocca** [comment]
FYI, in my case, Keycloak is behind an IIS ARR reverse proxy. So, waiting for this issue to be resolved, I can make a workaround with a URL rewrite outbound rule to fix the problem:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        [...]
      </rules>
      <outboundRules>
        [...]
        <rule name="Keycloak-Issue-26245">
          <match serverVariable="RESPONSE_LOCATION" pattern="^/.*$" />
          <conditions logicalGrouping="MatchAll">
            <add input="{PATH_INFO}" pattern="/protocol/openid-connect/logout$" />
            <add input="{QUERY_STRING}" pattern="post_logout_redirect_uri=(http?s%3A%2F%2F.+?(%3A\d+)?)%2F" ignoreCase="true" />
          </conditions>
          <action type="Rewrite" value="{UrlDecode:{C:1}}{R:0}" />
        </rule>
      </outboundRules>
    </rewrite>
  </system.webServer>
</configuration>
```

**Comment by rmartinc** [comment]
Hi @bocca!

I cannot reproduce this. In my case I'm always redirected to the passed `post_logout_redirect_uri` passed to the endpoint (using last 23.0.6). I tried passing the `id_token_hint` and not passing it to the endpoint. I have deleted the identity cookie in the browser to simulate that I don't have the cookie and  I also accessed the URL twice. My client is using Front-channel logout URL. There are a lot of things that can be involved here (for example how you are calling the logout endpoint, how the client is configured to do the logout, frontend/backchannel,...).

Can you please add clear reproducer steps? It would be nice if you start from a fresh realm in a dev box and give us the (more or less) complete steps to reproduce the issue, because probably we are missing something.

**Comment by bocca** [comment]
Sorry so much! Another outbound rule in my HTTP proxy was mdifying the redirect. Keycloak has no bug in this regard. Again, sorry. And thank so much you for your attention.
