### ISSUE TITLE
Operator support for setting default value of `http-pool-max-threads`

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#26466]
### Description

This is a follow-up from #26455.

Operator should set some reasonable default for `http-pool-max-threads` if not specified by user. The value might be affected by CPU limits set on Pod and/or number of Keycloak instances.

We should also consider HPAs where we might want to avoid unnecessary deployments restarts caused by tweaking the `http-pool-max-threads` value when scaling is performed.

**Comment by vmuzikar** [comment]
CC @ahus1

**Comment by ahus1** [comment]
With #33939 in place, there is now no more a big reason to tune the workers for Keycloak for stability, but rather for fine tuning. Keycloak already sets good-enough values based on the CPUs. It is no longer dependent on the number of instances you are running.

Due to this, this is IMO less of a priority, and therefore should be closed.
