### ISSUE TITLE
Infinite loop during X509 authentication

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#26588]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

It seems that with some corner cases, it can happen that the code in:

- `BCUserIdentityExtractorProvider.unwrap`
- `BCFIPSUserIdentityExtractorProvider.unwrap`

can cause the infinite loop. It is not easily reproducible and can probably happen just with some certificates and it can depen on the  environment. It is also not confirmed if this is in latest Keycloak main. Creating this GH issue to investigate this further. More details are in related support ticket.

### Version

nightly

### Expected behavior

No infinite loop. Ideally also being able to authenticate (if the corresponding certificate meets all the other requirements like correct certificate chain found etc).

### Actual behavior

Infinite loop in some cases

### How to Reproduce?

See above and more details in the support ticket

**Comment by mposolda** [comment]
Adding to Keycloak 24 for now. It is not strictly a blocker, but will be nice to look at this soon.

**Comment by rmartinc** [comment]
Not an issue. The problem was internal because of the BC upgrade. In main it was correctly done here: https://github.com/keycloak/keycloak/commit/37acb2fd09c10219848c421d12581282748089bb#diff-8ee6f6d636e1a3be295e63f525a29a760ce46d11d9b328e2c9c1d8ac4e40d6daR201.

And in 23.0.6 it was not needed because it was using the old BC version. So everything is OK in keycloak and this issue cannot be reproduced (and we are really testing it in the BCUserIdentityExtractorProvider).
