### ISSUE TITLE
Log in into the admin console with a `/#/realms` suffix breaks the UI 

### ISSUE THREAD

**Issue by hashworks** [keycloak/keycloak#26700]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Previous Keycloak versions (<23) sometimes used the `/#/realms` suffix for admin console paths:

`https://auth.example.net/admin/foo/console/#/realms`

A lot of users still have links with the `/#/realms` suffix in their history, so they re-use it to open the admin console. Since newer versions use a different syntax it breaks the UI without any error, while still allowing them to log in:

![image](https://github.com/keycloak/keycloak/assets/2362091/63ce6314-7ec3-4f43-9f0f-1d7a4248174f)

Clicking on "realms" then calls `https://auth.example.net/admin/realms/realms/ui-ext/realms?` which returns `{error: "Realm not found."}`.

### Version

23.0.5

### Expected behavior

Either the user receives a descriptive error message or he is redirected to `https://auth.example.net/admin/foo/console/`.

### Actual behavior

No error is shown, so the user thinks Keycloak itself is broken.

### How to Reproduce?

Open a realm admin console with a legacy `/#/realms` suffix, like `https://auth.example.net/admin/foo/console/#/realms`. Replace the domain and the `foo` realm accordingly.

**Comment by jonkoops** [comment]
I think we should be doing a better job here at error handing, in this case an error should be shown and the user prompted to refresh the page (like with other errors) and return to the root.

**Comment by praguru14** [comment]
Hi , I am looking to contribute in Open source projects , I find that I can fix this issue.
Can I get it assigned?

**Comment by jonkoops** [comment]
Sure, go right ahead @praguru14

**Comment by jonkoops** [comment]
I am removing the assignee from this issue so that someone else can pick this up.

**Comment by etiksouma** [comment]
Hi,
as a first step towards contributing to the project, I started analyzing this issue. 

I built and deployed the latest changes from the main branch (commit ID: 967ceddfbb0cd67).

I tried to reproduce the issue locally:

1. GET http://localhost:8080/admin/master/console/#/realms
2. Redirected to login page: http://localhost:8080/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fadmin%2Fmaster%2Fconsole%2F%23%2Frealms&state=f6edad50-2004-40e0-82bf-173a8179440c&response_mode=fragment&response_type=code&scope=openid&nonce=60ad144c-8451-4d29-b82b-01436c815dc3&code_challenge=iIyhRmNV6eqTq2MswNUQz-zgwYTrkJIyliirF1vfdtw&code_challenge_method=S256
3. After posting login credentials, an error is displayed:

<img width="1377" alt="after-login" src="https://github.com/keycloak/keycloak/assets/155627547/eebde72b-b358-408f-9019-ec77e55c335e">

The loading of the realms in the dropdown stops working 
I could see the following errors in the console:

GET http://localhost:8080/admin/master/console/whoami?currentRealm=realms  
Response:
500 
{"error":"unknown_error","error_description":"For more on this error consult the server log at the debug level."}


 GET http://localhost:8080/admin/realms/realms/ui-ext/realms/names
Response:
404
{"error":"Realm not found.","error_description":"For more on this error consult the server log at the debug level."}

The issue as far as I could see is related to the fact that "realms" is stored as the current realm in the frontend.

4. An error page with a refresh link is shown. Clicking on the refresh link redirects me to the "home" page 

<img width="1377" alt="after-refresh-2" src="https://github.com/keycloak/keycloak/assets/155627547/34a0867c-67b1-40f4-a8c9-d5e036c8887e">

My first try calling the refresh link showed however some network error. But I would rather suspect a local network issue to the docker pod here.
<img width="1377" alt="after-refresh" src="https://github.com/keycloak/keycloak/assets/155627547/5b163135-684b-481f-a7ca-ea46bafada1d">


@jonkoops 

It seems to me that this issue is already resolved.
You said: "in this case an error should be shown and the user prompted to refresh the page (like with other errors)". 
Does this correspond to the page shown at step 4 in my tests?

**Comment by jonkoops** [comment]
I still think that we should try to get this resolved properly, there is something weird going on. But it's good to see our error handling has improved.

**Comment by etiksouma** [comment]
Then I am afraid I will give up on this issue as  I cannot reproduce it using the latest changes. Maybe the next one who works on it would be "luckier".

**Comment by jonkoops** [comment]
Thanks for the feedback and detailed research @etiksouma. I'll remove the 'good first issue' label, but keep it 'help wanted'. For good issues I'd filter our backlog based on those labels, feel free to pick up anything you see. Let me know if you want to pick an issue that has already been assigned, but has not been acted on for a while.
