### ISSUE TITLE
User Profile Applies Validation To Service Account Users

### ISSUE THREAD

**Issue by patrickjennings** [keycloak/keycloak#26716]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

When adding user profile validation, such as requiring a particular field to be provided, this applies the validation to service accounts users as well.

### Version

nightly

### Expected behavior

We should be able to update attributes to service accounts independently of user profiling or be able to specify whether the validation happens for service account users.

### Actual behavior

Can no longer update service account users if the user profile validation fails.

### How to Reproduce?

Make sure user profile is enabled.
Set a field as required, such as first name or last name.
Create a service account.
Go to the service accounts user details page.
Notice you may no longer save the service account.

**Comment by rmartinc** [comment]
@patrickjennings I have submitted a PR that makes any non-builtin for service accounts optional. With it the service accounts do not require any attribute (except username) but enforces the other validators if a value is provided (for example if the email is updated, the check for duplication and format is executed, the same for any other custom attribute). I have implemented this way because I think that service accounts should not enforce any attribute (except username) but, if attributes are provided, should control the passed values. WDYT? Is this OK for you?
