### ISSUE TITLE
Login via brokerage to identity provider fails with clients having UUID with uppercase letter 

### ISSUE THREAD

**Issue by g10f** [keycloak/keycloak#26868]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

identity-brokering

### Describe the bug

When using a client with an id in the layout of a UUID but with an upper case letter in it (e.g 34445442-1942-40a9-816f-d73d6c20a74A where the last letter is uppercase)
{
  "id": "34445442-1942-40a9-816f-d73d6c20a74A",
  "clientId": "oidc-demo",
  "name": "oidc-demo",
 ....
}
then logging in via a configured Identity Provider via brokerage fails with IDENTITY_PROVIDER_LOGIN_ERROR and error="invalid_code"
Using exactly the same client json representation, but  "id": "34445442-1942-40a9-816f-d73d6c20a74a" works.
If the id is not a uuid it also works with uppercase letters.

### Version

23.0.6 and 22.0.8 (rhbk 22.0.8)

### Expected behavior

Functionality should be case independent. 

### Actual behavior

Brokered login works not with client having an id in the format of a uuid but with uppercase letters.

### How to Reproduce?

1. Create an Identity Provider with oidc in keycloak
2. Create a client with an uppercase letter in the id and an uuid format by uploading the client json file.
3. Create a login flow using the Identity Provider Redirector to the Identity Provoder from step 1

**Comment by pedroigor** [comment]
@g10f Can you please check the latest version to see if the issue persists? I tried to reproduce this by importing a [client](https://github.com/keycloak/keycloak/files/14671580/test.json) with an ID with uppercase letters.

**Comment by g10f** [comment]
At least in 24.0.1 the issue is still there.

**Comment by pedroigor** [comment]
@g10f Thanks. I was able to reproduce the issue too. I was setting the uppercase ID in the client used by the broker rather than the client starting the authorization request and that is why I did not manage to reproduce before.

Considering that this issue is a corner case where an unexpected format is being forced on the ID of our domain objects, I would suggest either removing the ID from their clients or changing their values to lowercase.

Based on https://www.ietf.org/rfc/rfc4122.txt, when creating an ID with a given input, the input is case insensitive but the output and the resulting UUID is lower case. That said, the server is working as expected and any change we make will add more complexity to solve a problem that is not aligned with how we are using/implementing the specs.

However, I see we can improve our documentation to make this situation very clear and highlight the usage of lowercase values in our domain object IDs, such as the client.
