### ISSUE TITLE
CVE-2023-35116 - jackson-databind - 2.15.2

### ISSUE THREAD

**Issue by natasa-radenovic** [keycloak/keycloak#26923]
### Description

Our security tool Sysdig found a vulnerability in **jackson-databind - 2.15.2** used by **quay.io/keycloak/keycloak:23.0.6**. It's in several places:

- /opt/keycloak/lib/lib/main/com.fasterxml.jackson.core.jackson-databind-2.15.2.jar:jackson-databind
- /opt/keycloak/bin/client/keycloak-client-registration-cli-23.0.6.jar:jackson-databind
- /opt/keycloak/bin/client/keycloak-admin-cli-23.0.6.jar:jackson-databind

The CVE ID is [CVE-2023-35116](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2023-35116)

The resolution would be to switch to **jackson-databind - 2.16.0** or **jackson-databind - 2.16.0-rc1**

**Comment by abstractj** [comment]
@natasa-radenovic thank you for submitting your report. The issue is indeed present in our dependency tree on the latest release. However, it has already been addressed in the `main` branch. Therefore, it should be resolved in the upcoming releases. If you wish to verify this, please follow these steps:

1. Clone the repo
2. Run  mvn dependency:tree | grep -A 0 -B 1 "jackson-databind"

**Comment by abstractj** [comment]
@keycloak/core there's no action required here. As soon as we release 24, the issue should be automatically fixed.

**Comment by natasa-radenovic** [comment]
@abstractj Thank you for addressing this so quickly. I see that the main branch no longer has the vulnerable jackson-databind version. 🙌
