### ISSUE TITLE
SSSD user federation doesn't sync users automatically

### ISSUE THREAD

**Issue by gabrielpadilh4** [keycloak/keycloak#27069]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

After configuring a SSSD federation, only after the user login it becomes available in Keycloak.
Only groups are being imported, no users.

### Version

23.0.0

### Regression

- [ ] The issue is a regressions

### Expected behavior

When the process of user storage sync runs, it should import the users into Keycloak.

### Actual behavior

When the user sync process runs, no user is imported.

### How to Reproduce?

Configure a SSSD user federation, select the federation, go to Option and click on Sync All Users. There is no effect with changed users also.

**Comment by rmartinc** [comment]
Hi @gabrielpadilh4!

This is a limitation of the SSSD user storage provider. The current implementation does not implement the `UserQueryMethodsProvider` interface and it cannot search users. Its factory doesn't implement the ImportSynchronization neither, so if you try to "Sync al users" you should receive that import is ignored. It can only ask for a single user and that's the reason they are just imported when they are used (login or any other operation over the user).

If you need for some reason force the import of a user because you need it to configure something in the user, try to login with that user (no matter if the password is not OK). Probably we should give some operation to search a user just by username and allow importing them in a simpler way (in general for any storage that cannot implement the `UserQueryMethodsProvider` or `ImportSynchronization` methods). But, sadly, this is working as expected right now.

FYI there is some initial activity on using SSSD via ipa-tuura instead of ifp (REST endpoints). But this is just an idea we are exploring right now and I personally don't know what is going to be the scope of the new provider.

Regards!

**Comment by pedroigor** [comment]
Thanks a lot, @rmartinc. I'm closing because the behavior is expected for the reasons you mentioned.
