### ISSUE TITLE
Custom claims are missing in Access token generated using refresh token

### ISSUE THREAD

**Issue by atul-epam** [keycloak/keycloak#27083]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

In my application, I am adding custom claims in the access token by extending AbstractOIDCProtocolMapper and implementing OIDCAccessTokenMapper as shown below:

`public class CustomTokenMapper extends AbstractOIDCProtocolMapper implements OIDCAccessTokenMapper {`

In CustomTokenMapper class, I am overriding following method to add custom claims in access token:

```
@Override
    public AccessToken transformAccessToken(AccessToken accessToken, ProtocolMapperModel protocolMapperModel,
                                            KeycloakSession keycloakSession, UserSessionModel userSessionModel, ClientSessionContext clientSessionContext) {
```
But once the access token is expired and I generate a new access token using the refresh token (grant_type = refresh_token) that I received in my previous request, I am getting new access token without any custom claims.

I checked the KeycloakSession object in which I set the custom claims as attributes previously to get them in CustomTokenMapper. But the KeycloakSession object does contain any attribute.

I also tried to set the custom claims in realm object (RealmModel realmModel), but it is storing them in cache and keep them till cache is cleaned. This is not secure and not reliable when multiple users are logged in together.

### Version

23.0.4

### Regression

- [ ] The issue is a regressions

### Expected behavior

All the custom claim available in access token in initial login request should also be available in all subsequent access tokens generated using refresh token.

### Actual behavior

There is no custom claim present in new access token generated using refresh token.

### How to Reproduce?

Generate the access token using refresh token generated from previous login request (/protocol/openid-connect/token)

**Comment by rmartinc** [comment]
Hi @atul-epam!

The refresh token also calls the `transformAccessToken` when creating the access token via `refresh_token`. The sequence is the following:

1. The token manager in `refreshAccessToken` calls `validateToken` ([line](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L390)).
2. The `validateToken` method validates the refresh token and creates the new access token in `createClientAccessToken` ([line](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L239)).
3. Finally the `createClientAccessToken` initializes the new access token and execute all the mappers ([line](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L557)).
4. The `transformAccessToken` is the method that executes the method in the mappers ([line](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/TokenManager.java#L768)).

So in theory the method is also executed in the refresh token and it should execute your mapper. Check if your method is called because it should be. Note that out common mappers (like [UserAttributeMapper](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/mappers/UserAttributeMapper.java)) are using the same interface and they are executed on refresh.

**Comment by kanchantambe** [comment]
Hi @rmartinc 
In our case, **transformAccessToken** method is getting called but keycloak session is getting **NULL** hence no values are getting extracted. We are setting up these custom claims in the keycloak session in **isValid()** method overridden from **CredentialInputValidator** class during initial authentication. Are we missing anything at the initial login?

**Comment by rmartinc** [comment]
Do you mean the first argument `session`? That session is generated for each request and it will be different, any attribute saved there it's lost in the subsequent calls (you can use the userSession or clientSession but don't know if they are available in the part you are setting the value).

**Comment by kanchantambe** [comment]
ok, thank you @rmartinc We will try to check if other approach is possible.

**Comment by rmartinc** [comment]
A mapper example using the user session is for example the [UserSessionNoteMapper](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/mappers/UserSessionNoteMapper.java#L85-L86). For the client session is more or less the same but using `clientSessionCtx.getClientSession().getNote(noteName)`. The idea is the note is previously set in the session using the corresponding set method in each object. For example for the user session the token manager sets a lot of notes (for example [here](https://github.com/keycloak/keycloak/blob/23.0.6/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L628)).

**Comment by rmartinc** [comment]
@atul-epam I'm closing the issue now. If you have more issues please re-open or better file a new one. Regards!
