### ISSUE TITLE
CVE-2024-21742: CWE-20 Improper Input Validation apache-mime4j-core@0.8.9

### ISSUE THREAD

**Issue by souravs17031999** [keycloak/keycloak#27372]
### Description

Hi, 

Owasp vulnerability scan in our CI pipelines are reporting following vulnerability coming with keycloak-admin-client package 

![image](https://github.com/keycloak/keycloak/assets/33771969/64c2912b-f715-4d17-a347-c047c1ea58b7)

![image](https://github.com/keycloak/keycloak/assets/33771969/afb30023-2aaf-4382-adad-ed60c5b6ef34) 

[CVE-2024-21742](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2024-21742)

**Comment by rmartinc** [comment]
Just a note, the mime4j is just used for the admin-client (not present in the server). So you can always exclude the version provided 0.8.9 and include the fixed one 0.8.10+. To change the default version provided by keycloak the resteasy version [here](https://github.com/keycloak/keycloak/blob/25.0.1/pom.xml#L111) needs to be upgrade to 6.2.7.Final (which transitively depends on mime4j 0.8.11).

**Comment by rmartinc** [comment]
The upgrade to quarkus 3.13.x upgraded resteasy to version 6.2.9 in #31676. Besides the new keycloak-client project was also aligned to this version in https://github.com/keycloak/keycloak-client/issues/39. So this will be fixed in the next version 26.0. Closing this as done because of the commented issues.
