### ISSUE TITLE
Log warning when not using scope `openid`

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#27391]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When doing a non-OpenID request (not including `openid` scope) there is a warning in the logs.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

No warning for pure OAuth2 request

### Actual behavior

Outputs the following warning:
```
2024-02-29 13:48:36,927 WARN  [org.keycloak.services] (executor-thread-11) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request.
```

### How to Reproduce?

Do an token request without `scope=openid`

**Comment by rmartinc** [comment]
@stianst I remember this warning (or similar) since I started in keycloak :smile:. It's just a warning that was added initially [here](https://github.com/keycloak/keycloak/commit/dcc4ea3aea63ad32bf94625fde1897bd38bca14e#diff-e9608ca25f93f2aded87719eb11ff9855e7f2a0a1cd4fd984f918d1592beb386). We can lower the message to debug or even remove it completely if we all agree. @mposolda FYI.

**Comment by mposolda** [comment]
Adding to important as it should be easy to do.
@rmartinc +1 for lowering to `debug` or `trace` .
