### ISSUE TITLE
Missing Maven dependencies for keycloak-model-jpa and keycloak-services

### ISSUE THREAD

**Issue by synth3** [keycloak/keycloak#27567]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

- `keycloak-model-jpa` is missing the dependency `io.smallrye:jandex`
  - a dependency of `org.hibernate.orm:hibernate-core`
- `keycloak-services` is missing the dependency `org.yaml:snakeyaml`
  - a dependency of `com.github.ua-parser:uap-java`

May there be more?
 
The causal change must have been made with version >23.0.3 and <=24.0.0.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The Maven modules have their dependencies set as needed.

### Actual behavior

Missing dependencies in Maven modules.

### How to Reproduce?

Use the mentioned Modules by adding them as Maven dependencies.

**Comment by mposolda** [comment]
@synth3 Is it any concrete scenario, which doesn't work because of those dependencies changes? Are you seeing any Keycloak server functionality not working or are you seeing issues just because you are using those modules in your own project?

For the 2nd case, note that modules `keycloak-services` and `keycloak-model-jpa` are Keycloak internal modules. Keycloak can remove (or update) 3rd party dependencies from them anytime. If you are using those in your own java project and you're implementing some Keycloak internal SPI, then it is your responsibility to adjust dependencies in your project as needed. The ideal is to avoid using those in your java project and just rely on the dependencies like `keycloak-server-spi` if possible as this is the only one where backwards compatibility is guaranteed (But I know that most SPI are not available and it is not so ideal, but still not considering this as Keycloak bug for this case).

**Comment by synth3** [comment]
@mposolda Thanks for taking the time looking into this! It's more or less the 2nd case.

I had the expectation that in a Maven multi-module project, aiming for self-contained effective dependencies within each module is beneficial: It promotes loose coupling and reusability, and enables in-depth dependency analyses and testing on a per-module basis. Now the affected modules only work in a context where these ("invisible") dependencies are provided (because someone manually kept track of that), and Maven is no longer of any help for that.
This is essentially why I reported this.

In the meantime I also figured out what caused that:
- In keycloak-parent there is an exclude to `org.yaml:snakeyaml`: [pom.xml](https://github.com/keycloak/keycloak/commit/ee5593a88f8e7814d8d8855d28fd0cf9560c1286)
  - If it's because the the version of `snakeyaml` should be under control, why not re-add the dependency next to `uap-java`?
- In the quarkus-bom there is an exclude for `io.smallrye:jandex` that used to be an exclude for `org.jboss:jandex`: [generated-platform-project/quarkus/bom/pom.xml](https://github.com/quarkusio/quarkus-platform/commit/cc6ff5eb1585892e80d2f73543c37fcf28c8c734)
  - I honestly don't know how to deal with that transparently

I find it at least unfortunate that the dependencies are no longer self-contained, but it's not a big deal of course.
