### ISSUE TITLE
Check if auth_time can be removed from lightweight access token by default

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#27623]
The claim `auth_time` is not needed in lightweight access token. We can probably include it by protocol mapper on demand. See https://github.com/keycloak/keycloak/issues/23727 description for the details.

We may possibly try to implement "client note protocol mapper" .

**Comment by graziang** [comment]
`auth_time` claim according with the specification is required for id token when a `max_age` request is made or when `auth_time` is requested as an Essential Claim:

https://openid.net/specs/openid-connect-core-1_0.html#:~:text=the%20date/time.-,auth_time,-Time%20when%20the

In Keycloak the `auth_time` is stored in the user session notes and never read from the access token, for instance in the `CookieAuthenticator` when you need to check if re-authentication is required the `auth_time` value is read from user session. 

So IMO we have different options:
1. Continue hardcoding the claim only for id token and introduce a mapper for `auth_time` (removing `auth_time` by default from access token)
2. Continue hardcoding the claim for id token and normal access token, and introduce a mapper for `auth_time`
3. option 1 + adding a "`default`" scope with mapper for `auth_time`, as described in #23727

I think that option 3 is the final goal for almost all those claims in this situation.

Since `auth_time` is a user session note, `UserSessionNoteMapper` can also be used
