### ISSUE TITLE
Used encrypted JGroups connection by default in Operator deployments

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#27736]
### Description

#25703 added support for easy configuration of TLS in JGroups. As this is used for internal purposes of Keycloak and certificates of the issuing CA are granted access to the internal Keycloak communication, a self-signed certificate MUST be used.
* The Operator should obtain a certificate and configure Keycloak to use TLS in Infinispan by default.
* This behavior should be possible to disable via a config option in Keycloak CR.
* [Needs discussion] The certificate and key could be obtained either via [cert-manager Operator](https://cert-manager.io/) (which would require detecting its presence and integrating with it), or Keycloak Operator could generate it itself (which would require also handling renewals).

**Comment by ahus1** [comment]
Thank you for opening the issue. I changed "As this is used for internal purposes of Keycloak, even a self-signed certificate can be used." to "As this is used for internal purposes of Keycloak and certificates of the issuing CA are granted access to the internal Keycloak communication, a self-signed certificate MUST be used."

Only trusted parties (the nodes in the Keycloak cluster) should be handed certificates signed by this CA.

**Comment by ahus1** [comment]
My opinion on this: Either the user provides the keys/certificates, or the Keycloak Operator uses the cert-manager Operator to generate it. Such security logic shouldn't duplicated. 

The relevant docs are here to create self signed certificate https://cert-manager.io/docs/configuration/selfsigned/ and either use that directly, or to set up a CA afterwards https://cert-manager.io/docs/configuration/ca/

Setting up a CA based on a self-signed certificate would allow a durable root certificate which all Keycloak nodes trust and then keys and and short-lived certificates for the different Keycloak nodes to communicate with each other. Note that as of today any change in a key/certificate for the service would require a Keycloak restart. The root certificate though must not change to ensure a rolling restart, otherwise the restarted node would not be able to communicate with the other nodes which use the old root certificate.

**Comment by vmuzikar** [comment]
Related to: #9781

**Comment by ahus1** [comment]
Closing this one as obsolete due to the plans for #35577 in KC 26.2+
