### ISSUE TITLE
User profile fields cannot be set empty once they have a non-empty value (in Login Theme)

### ISSUE THREAD

**Issue by danielFesenmeyer** [keycloak/keycloak#27797]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

I have observed that it's currently not possible to set a non-empty field to empty by means of the "Update profile" action (and I guess the same applies to the other Login Theme actions).
To be more precise, the UI allows to set an empty value (when the field is not required), but the empty value is not stored at server side. In both Admin and Account UI the old (non-empty) value is still displayed.

### Version

23.0.7 AND current main branch (commit 1c0c56e8055ef227d3aa72102a2acb10eb306d16)

### Regression

- [ ] The issue is a regression

### Expected behavior

- When a field is not required, it should be possible to set the field to empty, and the empty value SHOULD BE persisted.

### Actual behavior

When a field is not required, it is possible to set the field to empty, but the empty value is NOT persisted.

### How to Reproduce?

- In the Admin UI (or via Admin API): 
  - Add a simple optional attribute to a realm's user profile - let's call it `test`.
  - Create a user at the realm, set the required action "Update Profile" for the user, and initialize the `test` attribute value with "anything".
- In the Login Theme / Account UI:
  - Login at the Account UI with the user.
  - The "Update Profile" screen should be displayed with `test` attribute value "anything".
  - Clear the `test` attribute field and submit the form.
  - The Account UI should now be displayed. The `test` attribute value displayed there is still "anything". The same applies when displaying the user in the Admin UI. 

### Anything else?

Note that I've tested this with version 23.0.7 and current main branch. Probably this also occurs with version 24.x.

**UPDATE**: Clearing values with the Account UI and Admin UI works fine. The issue seems to be restricted to the Login Theme.

**Comment by danielFesenmeyer** [comment]
@keycloak-bot Are you serious? I've mentioned the issue is on the main branch from today, so that should be even more relevant than the nightly build.

**Comment by jonkoops** [comment]
@danielFesenmeyer sorry, that was my fault, I mislabeled this issue.

**Comment by sguilhen** [comment]
I was able to reproduce the issue - as described, the issue seems to be happening only when updating the profile during login - any non empty value is properly persisted, but if we clear the value the issue is visible and the empty value is not persisted.

When clearing the value both in account console and in the user page in admin console, the empty value is properly persisted.

**Comment by pedroigor** [comment]
I see the inconsistency between the different UIs, but why do we want to persist empty values?

**Comment by danielFesenmeyer** [comment]
It's about deleting optional data.
Example: If a user specified her employer in the profile, she might want to delete it, when she is now working as a freelancer.

**Comment by pedroigor** [comment]
Now I see. The consistency should be about removing the attribute when the value is empty whenever the attribute is not required.

I'm changing to important. Sorry, @sguilhen :)

**Comment by pedroigor** [comment]
@danielFesenmeyer Sent https://github.com/keycloak/keycloak/pull/27831. The attribute is now removed whenever they have empty values. In this case, we assume there is an explicit intention to remove the attribute because it is was sent to the server but with empty values.

If the attribute is not sent at all, the attribute won't be removed. This behavior can change in the future and we can assume that any attribute not sent (or sent with empty values) should be removed. The reason for not changing that now is backward compatibility with existing deployments customizing themes and expecting "partial updates" to attributes.
