### ISSUE TITLE
Get Groups in admin/cli returns all groups and not the groups that meets the condition specified in -q option

### ISSUE THREAD

**Issue by Amrooo161** [keycloak/keycloak#27877]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

Using get groups with a condition set in the -q option returns all groups in the specified realm, this option should return only the groups that meets the condition specified, example "get groups -r admin -q name=admin" should return only the groups the have the string "admin" in its name

### Version

faced the issue in both Keycloak 21.1.1 and 23.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

get groups with a specified condition (-q option) should return only the groups that meets the condition

### Actual behavior

get groups with a specified condition (-q option) returns all the groups present in the realm

### How to Reproduce?

use the admin cli to get groups available in a specific realm that meets a condition and it will return all the groups in that realm instead

Example Command: get groups -r admin -q name=admin

**Comment by Amrooo161** [comment]
Just wanted to clarify that this happens with kcadm commands in the admin/cli

**Comment by shawkins** [comment]
This looks like a bug with the kcadm client. When you specify a -q option, those values get sent to the server as general url parameters: ?name=admin - rather than as the q parameter.

It looks like there are five endpoints that support q parameter. I'm not sure what other endpoints may be expecting the raw parameters. cc @vmuzikar @Pepo48

**Comment by jonkoops** [comment]
@shawkins could you assign this a priority?

**Comment by shawkins** [comment]
@jonkoops my guess would be normal priority, but this does affect several endpoints so feel free to change it.

~priority-normal

**Comment by vmuzikar** [comment]
@shawkins Isn't this rather a REST API issue that it doesn't accept the q parameter?

**Comment by shawkins** [comment]
> @shawkins Isn't this rather a REST API issue that it doesn't accept the q parameter?

No, see https://github.com/keycloak/keycloak/issues/27877#issuecomment-2007261845 - kcadm does not send a q parameter.

**Comment by shawkins** [comment]
@vmuzikar @mabartos could we consider #27458 before tackling this one?

**Comment by vmuzikar** [comment]
> could we consider #27458 before tackling this one?

Works for me. 👍

**Comment by shawkins** [comment]
@vmuzikar @Amrooo161 finally got back to looking that this again. This is mostly a documentation issue. You have to know the -q or --query don't mean the same thing as the q parameter. Realizing this you would use:

get groups -r admin -q q=name:admin

That will get converted into the http query ?q=name:admin - where name:admin will properly url encoded.

I'll update the docs via this issue.

~priority-low

**Comment by Amrooo161** [comment]
@shawkins Just to clarify, is this supposed to be working properly in the current keycloak with the mentioned example ? if not, with the last commit should this be working with that example in the next keycloak release then ?

I tried that on my system and it returned empty brackets although I have a group called admin.

**Comment by shawkins** [comment]
> Just to clarify, is this supposed to be working properly in the current keycloak with the mentioned example ? if not, with the last commit should this be working with that example in the next keycloak release then ?

@Amrooo161 The pr is correct with what it is documenting - I did have to change the examples used there to not reference name:admin. It appearently comes down to what is considered an attribute. For a group name is not an attribute. In the UI if you navigate to a group, see the attribute tab.

Based upon the GroupsResource https://github.com/keycloak/keycloak/blob/879fe082dd1f9fe6612f05dba8b8ff4a718040eb/services/src/main/java/org/keycloak/services/resources/admin/GroupsResource.java#L101 you would to specify the search query parameter instead:

```
get groups -r admin -q search=admin
```

Unfortunately the docs on https://www.keycloak.org/docs-api/latest/rest-api/index.html#_groups aren't sufficient to glean this functionality, nor does the admin cli make this easy either, you have to read the source. I think another issue is in order to improve the rest docs.

**Comment by shawkins** [comment]
> I think another issue is in order to improve the rest docs.

Captured as #29222
