### ISSUE TITLE
Significant Performance Degradation from Keycloak Version 23 to 24

### ISSUE THREAD

**Issue by freddidierRTE** [keycloak/keycloak#28010]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I've noticed a significant performance degradation when upgrading from Keycloak version 23 to version 24. This issue is particularly noticeable in terms of memory usage and request handling time.

Here are the details of my tests, which were conducted on my local machine using Docker:

**Test 1: Keycloak Version 23.0.7-0**

Memory usage after startup: 412.8 MB
Memory usage after 200 token requests: 437.2 MB
Time taken for 200 token requests: 11 seconds

**Test 2: Keycloak Version 24.0.1-0**

Memory usage after startup: 1.468 GB
Memory usage after 200 token requests: 1.608 GB
Time taken for 200 token requests: 63 seconds
In addition to the increased memory usage and request handling time, I've also noticed that the memory used grows with each token request and is never released.

Memory usage was measured using docker stats.

This issue has also been tested on other computers, with similar behavior observed.

You can find all the elements used for the test in this GitHub repository: https://github.com/opfab/keycloak-perf

### Version

24.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

No memory leak and reasonable memory consumption 

### Actual behavior

Memory leak and high memory consumption

### How to Reproduce?

See  https://github.com/opfab/keycloak-perf

**Comment by stianst** [comment]
As you can see in https://www.keycloak.org/2024/03/keycloak-2400-released.html the password hashing intervals changed significantly in Keycloak, and this explains the time it takes to do token requests, since you are doing client credential grants in your testing.

In terms of the memory you are not looking at used memory but rather claimed memory. The increase here will be explained by the fact that the default initial and maximum heap sizes for the container changed in 24 to make it easier to configure memory available to the container. 

~invalid
