### ISSUE TITLE
Paging issue in groups via user view

### ISSUE THREAD

**Issue by MartaGolabek** [keycloak/keycloak#28080]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Paging doesn't work for groups in user view.

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Paging works, going back and forth between pages is possible

### Actual behavior

Paging doesn't work. It is only possible to go to the second page.

### How to Reproduce?

1. Go to Users
2. Select a user
3. Go to Groups Tab
4. Click 'Join Group'
5. Go to the next page
6. Following is displayed instead of correct pages:
![image](https://github.com/keycloak/keycloak/assets/15276644/7b202d6f-704c-40c1-84a0-dd47de2005f9)
7. It is impossible to go back to previous page

**Comment by bodograumann** [comment]
We see the same issue. Still present in 24.0.1.

**Comment by MartaGolabek** [comment]
@bodograumann Is this issue: https://github.com/keycloak/keycloak/issues/28079 also still present in 24.0.1?

**Comment by bodograumann** [comment]
Source is here: https://github.com/keycloak/keycloak/blob/main/js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx

Is there any documentation for the react components, e.g. a storybook?

**Comment by bodograumann** [comment]
I guess I have to mention that we are having a lot of subgroups and seeing the bug there.

When a group is selected, and we are thus seeing subgroups, a slice from first to first+max is done:
https://github.com/keycloak/keycloak/blob/619775b8dbb66300385b70c64a79645e5691960e/js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx#L226
But the fetch will only fetch a list of max+1 subgroups:
https://github.com/keycloak/keycloak/blob/619775b8dbb66300385b70c64a79645e5691960e/js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx#L96-L103
so I don't think that can work as-is.

I don't think that is the main problem though, because when looking at subgroups and changing the number of displayed groups or going to the next page, the view breaks, but the fetch for the new number or range of subgroups is not sent.
On the other hand, when staying on the list of main groups, changing the number of shown items per page there and then selecting a group to inspect its subgroups, everything seeems to work fine.

**Comment by bodograumann** [comment]
Seems this code as well assumes, that all subgroups are loaded, once you select the parent group:
https://github.com/keycloak/keycloak/blob/619775b8dbb66300385b70c64a79645e5691960e/js/apps/admin-ui/src/components/group/GroupPickerDialog.tsx#L90-L103

That is actually the case. So when switching the page, no new data is fetched, while still only the first `max+1` (e.g.) subgroups exist in `groups`. The `slice` mentioned above than leads to only the `max+1`th subgroup being displayed.

So I guess we could either fetch all subgroups initially, or refetch when the `first` or `max` parameters change.
