### ISSUE TITLE
Admin API: User PUT operation clears firstname, lastname email fields

### ISSUE THREAD

**Issue by DimiF4W** [keycloak/keycloak#28220]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When updating user attributes, you need to send firstName, lastName, email (OPTIONAL fields).
In the version < 24 we used the admin API to update attributes, when doing the same with version 24.0.2 the API clears the firstname, lastname, email field.

### Version

24.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

When updating a user and you dont send OPTIONAL fields, the API should keep the field content of those fields.

### Actual behavior

The API clears the fields.

### How to Reproduce?

Send a PUT request to any user api endpoint:
PUT /admin/realms/{realm}/users/{id}
`{
     "attributes": {
        "test": "1"
     }
}`
Check the Keycloak user again, firstname, lastname, email are gone

**Comment by czqrny** [comment]
in my case, a temporary workaround is to remove the rights to edit these attributes for administrators in the user profile settings

however, this prevents the creation of users via the administration API

**Comment by DimiF4W** [comment]
The only workaround we see is to add the 4 fields in the PUT request as well, but thats not expected compared with the <24 version of Keycloak.

**Comment by cesarcoruna** [comment]
It happens to me too in 24.0.2. There wan't this problem in 23.0.x relases

**Comment by shawkins** [comment]
@abstractj confirmed this is a regression. The prior behavior was to allow PUT to act like a PATH verb with a JSON Merge Patch. The new behavior is that https://github.com/keycloak/keycloak/blob/440f05e5933abedeb970440e09a1265dde897bc2/server-spi-private/src/main/java/org/keycloak/userprofile/DefaultAttributes.java#L395 will return false for isIncludeAttributeIfNotProvided calls so the existing values are no longer populated. It looks like changes for the declarative user profile are introducing write predicates that weren't there before. 

The admin cli supports a merge option so that a single cli call will overlay / patch the existing. I don't know if that's the new expectation here, or if the previous behavior was desirable, or if a PATCH endpoint should be supported.

**Comment by shawkins** [comment]
~priority-important

**Comment by DaBonse** [comment]
Same situation here, we use this method to update user attributes only and it worked like a charme till Keycloak 24.

Excactly same behaviour like #28252, now we got the API error: `error-user-attribute-required`

**Comment by abstractj** [comment]
@shawkins it might be worth to speak to someone (if you didn't already) from the Core IAM team to clarify expectations about it.

**Comment by shawkins** [comment]
@abstractj I hadn't reached out specifically on this, so the JIRA messages may have been missed. I've bumped the priority to a regression pending further analisys from @keycloak/core-iam

**Comment by sguilhen** [comment]
@pedroigor looks like we need to look into this

**Comment by pedroigor** [comment]
The previous behavior was not desirable because we have never supported PATCH operations from any endpoint. But I see the expectations from previous versions now broken because we are forcing a full representation to be sent.

I did not find any release notes for this.

@DimiF4W and others affected. Is it so bad to pass those attributes along with the attribute map in your case? I know it is a breaking change but I want to have some consistency here with other endpoints like the Account API and also to the semantics of PUT operations.

**Comment by Pilario** [comment]
It feels like a workaround to me. I totally agree with this change, but I would expect an extra PATCH operation instead where we can send one or more attributes/fields to update.

**Comment by DimiF4W** [comment]
It feels like a workaround to me. I totally agree with this change, but I would expect an extra PATCH operation instead where we can send one or more attributes/fields to update.

**Comment by DaBonse** [comment]
@pedroigor to clarify the actual behaviour, can you please have a look at this question:
https://github.com/keycloak/keycloak/discussions/28943

**Comment by czqrny** [comment]
From my point of view the documentation is very misleading on this, lets see how this endpoint is documented at [documentation](https://www.keycloak.org/docs-api/latest/rest-api/index.html#_users:~:text=List%5BUserSessionRepresentation%5D-,PUT%20/admin/realms/%7Brealm%7D/users/%7Buser%2Did%7D,-Update%20the%20user)

It is described with text "Update the user" and the information that UserRepresentation can be sent as body. Now lets look at [UserRepresentation structure documentation](https://www.keycloak.org/docs-api/latest/rest-api/index.html#UserRepresentation)

All fields are optional and there is no information about default values or something similar. If something is optional then I would expect it not to change if it is not defined in the query.

Now I have a question how you define "full representation" of user because now firstName, lastName, email are getting overwritten but for example "groups" field is not?

**Comment by pedroigor** [comment]
> It feels like a workaround to me (sending all attributes, its possible ofc, see my [previous message](https://github.com/keycloak/keycloak/issues/28220#issuecomment-2022112006)) . I totally agree with this change, but I would expect an extra PATCH operation instead where we can send one or more attributes/fields to update.

I have no objection to keeping the old behavior if you guys think it is the best way to go, from a project perspective.

I don't think we are going to enable PATCH any time soon as per https://github.com/keycloak/keycloak-community/blob/main/design/rest-api-guideline.md#patch.

**Comment by pedroigor** [comment]
> Now I have a question how you define "full representation" of user because now firstName, lastName, email are getting overwritten but for example "groups" field is not?

@czqrny Yeah, the documentation is misleading. Mainly if you consider that the constraints for those attributes (firstName, lastName, email, usernae) re not set in stone as they depend on the realm and user profile settings. For instance, you can opt for making the firstName required or optional or enable `Email as username` in your realm so that `email` becomes mandatory.

The `groups` field is not a user attribute and that is why it works differently. The same for required actions, credentials, etc.

**Comment by pedroigor** [comment]
@DimiF4W I'll send an update to our migration and upgrade guide about this change and keep the current behavior. Sorry for the confusion and not being clear about this change.

If you think otherwise, please react and we'll revisit if the fix is more appropriate. The reasons why I think we should keep the behavior are stated here https://github.com/keycloak/keycloak/issues/28220#issuecomment-2065313631.

**Comment by pedroigor** [comment]
Thanks for your comprehension. Sent https://github.com/keycloak/keycloak/pull/29214.

**Comment by gms1** [comment]
updating root attributes, e.g `{'enabled': True}` or `{'email': 'mytest@smaststream.ai', 'emailVerified': True}`
retains the other root attributes

trying to update a non-root attribute, e.g `{'attributes': {'phoneNumber': '+87654321'}` fails:
> 400: {"field":"email","errorMessage":"error-user-attribute-required","params":["email"]}

and when adding the email  as workaround, e.g `{'email': 'mytest@smaststream.ai', 'attributes': {'phoneNumber': '+87654321'}}` the other root attributes are cleared.

The same is true, when just updating `{'email': 'mytest@smaststream.ai', 'attributes': {}}`


> @DimiF4W I'll send an update to our migration and upgrade guide about this change and keep the current behavior. 

So as long as we only update root attributes, it is a partial update. However, once we update non-root attributes, we need to add all root attributes, so that they are not cleared. Is this the expected behavior?

**Comment by pedroigor** [comment]
The root attributes are actually the `email`, `firstname`, `lastname`, and `username`. The `enabled` is not a root attribute in the sense they are not related to user profile info. Think about these attributes as those the user can manage.

That said, the behavior is expected because you always need to send all `attributes` when updating the user. Those root attributes are, for historic reasons, also available as a property/field but they are regular attributes, managed through the `attributes` map. But for those, you don't necessarily need to include them in the `attributes` map because you can set their values directly to their respective fields/properties.

If you think we should make this more clear here https://github.com/keycloak/keycloak/pull/29214, please let me know.

**Comment by J-Dany** [comment]
> The previous behavior was not desirable because we have never supported PATCH operations from any endpoint. But I see the expectations from previous versions now broken because we are forcing a full representation to be sent.
> 
> I did not find any release notes for this.
> 
> @DimiF4W and others affected. Is it so bad to pass those attributes along with the attribute map in your case? I know it is a breaking change but I want to have some consistency here with other endpoints like the Account API and also to the semantics of PUT operations.
> 
> Also, those "root" attributes are now regular user attributes from a user profile point of view.

In my case, I am forced to make 2 calls, one for get the user profile, update it locally with some logic, and then make a PUT call to update the user profile. I quote @DimiF4W. I understand that PATCH is not implemented in any endpoint, but to update _just one attribute_ I need to do every steps defined before (get user profile, update the json, sent via PUT).
