### ISSUE TITLE
single signout is not working in keycloak spring security adpter 18.0.2

### ISSUE THREAD

**Issue by Prashanth-chinnla** [keycloak/keycloak#28297]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/spring

### Describe the bug

I have mutliple applications configured under same realm and using keycloak security adapter 18.0.2 library, when I login to one app, it automatically logs me to all other application, that part is good, but when I logout from one app it did not log out from other apps, I see that keycloak sessions were cleared for all the connected clients, all other applications are using old keycloak security context as it did not know about the logout from the opther app where logged out. I did even try backchannel logout feature, it did not help though, please help with this issue.  

### Version

18.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

It should log all other application sessions when I logout from one app.

### Actual behavior

I have mutliple applications configured under same realm and using keycloak security adapter 18.0.2 library, when I login to one app, it automatically logs me to all other application, that part is good, but when I logout from one app it did not log out from other apps, I see that keycloak sessions were cleared for all the connected clients, all other applications are using old keycloak security context as it did not know about the logout from the opther app where logged out. I did even try backchannel logout feature, it did not help though, please help with this issue.  

### How to Reproduce?

I have mutliple applications configured under same realm and using keycloak security adapter 18.0.2 library, when I login to one app, it automatically logs me to all other application, that part is good, but when I logout from one app it did not log out from other apps, I see that keycloak sessions were cleared for all the connected clients, all other applications are using old keycloak security context as it did not know about the logout from the opther app where logged out. I did even try backchannel logout feature, it did not help though, please help with this issue.

**Comment by rmartinc** [comment]
Hi @Prashanth-chinnla!

The spring adapter and all the rest of java adapters are deprecated now and they are going to be removed in the next major version 25 (see [release notes](https://www.keycloak.org/docs/24.0.1/release_notes/#java-adapter-deprecation-and-removal)). So we are not going to work in adapter issues anymore.

From now on the idea is every technology will use their own resources to connect to keycloak (in your case default spring security oauth2/openid-connect implementation). So better start using keycloak-security and not the deprecated keycloak adapter.

Nevertheless I think there was an old blog post to implement the single logout with the keycloak adapter [here](https://developers.redhat.com/articles/2022/12/07/how-implement-single-sign-out-keycloak-spring-boot).

Closing this because of deprecation/removal of adapters.

Regards!
