### ISSUE TITLE
Rolling upgrade to version 24.0.2 not possible [`java.io.IOException: Unknown type: 28`]

### ISSUE THREAD

**Issue by jganczorz-revolve** [keycloak/keycloak#28617]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

I have a Keycloak 22.0.4 instance deployed on AWS ECS with [jgroups S3 ping](http://www.github.com/jgroups-extras/native-s3-ping) as a protocol for distributed cache.

When I'm trying to deploy a new instance with Keycloak 24.0.2, it fails with an error
```
ERROR [org.infinispan.CLUSTER] (jgroups-6,ip-xx-xx-xx-xx-xxxx) ISPN000475: Error processing response for request 2 from ip-xx-xx-xx-xx-xxxx: java.io.IOException: Unknown type: 28
```

Keycloak 24 changed the Infinispan version from `14.0.21.Final` to `14.0.27.Final`, so it seems to be connected to [an Infinispan issue](https://issues.redhat.com/browse/ISPN-15887).

Until the issue is resolved, maybe Keycloak should consider downgrading Infinispan to version `14.0.24.Final`?

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Version 24 should be able to rollout to an existing AWS ECS production environment without an error.

### Actual behavior

When starting a new instance on an environment with Keycloak pre-24 already running, the new instance fails when trying to rebalance members.

### How to Reproduce?

1. Create a production environment with an earlier version of Keycloak and distributed cache configured.
2. Try to deploy a Keycloak 24.0.2 instance to this environment.

**Comment by shawkins** [comment]
An outline for this style of upgrade was captured here: https://github.com/keycloak/keycloak/discussions/21067#discussioncomment-8855429

basically the new / old members need to be segregated from one another via separate discovery services.

**Comment by jganczorz-revolve** [comment]
> if you’re okay with losing old sessions
In other words, if you are okay with a degraded experience for all active users of the application?

**Comment by shawkins** [comment]
> In other words, if you are okay with a degraded experience for all active users of the application?

Unfortunately that does not seem to be easily avoidable currently.

One approach to avoiding this would be to allow both versions of keycloak to operator side by side, but route new session creation only to the new instance. Then only scale down the old instance when no more sessions were active.

There's also the coming persistent session feature #28265 that should handle eventually be able to handle the upgrade  scenario as well - cc @ahus1

**Comment by ahus1** [comment]
@jganczorz-revolve - sorry to say that there is no supported way to keep your sessions. Some people are connecting a remote Infinispan to Keycloak to keep the sessions. Although this seems to work for several members of the community, this was never officially supported. Only since KC24, this is supported for Cross-DC setups only. 

@shawkins mentioned the right issue, see  #28265 on how we plan to improve in KC25 and onwards. Once that is implemented, you might still need to shut down all instances of Keycloak first, but when you restart them the sessions will be loaded again from the database. 

Another area where we want to improve is to allow patch upgrades without shutting down Keycloak first (24.0.1 -> 24.0.2). Major upgrades will take longer.
