### ISSUE TITLE
Upgrade quarkus to 3.9.2

### ISSUE THREAD

**Issue by ssho0508** [keycloak/keycloak#28615]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Related vulnerability analysis:
[CVE-2024-2700](https://scout.docker.com/vulnerabilities/id/CVE-2024-2700?s=github&n=quarkus-core&ns=io.quarkus&t=maven&vr=%3C%3D3.9.1&utm_source=desktop&utm_medium=ExternalLink)
[quarkus-core leaks local environment variables from Quarkus namespace during application's build](https://github.com/advisories/GHSA-f8h5-v2vg-46rr)

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Run docker container successfully

### Actual behavior

 ✘ Container keycloak  Error                                                                            
dependency failed to start: container keycloak is unhealthy

### How to Reproduce?

docker compose up

**Comment by shawkins** [comment]
We will upgrade as soon as possible to address any CVEs. The one that you reference does not have a significant impact on Keycloak. We only persist keycloak options, and the usage of quarkus properties is otherwise considered unsupported.

Marking this as resolved for now - please do check back for a keycloak release that formally addresses this CVE.

cc @vmuzikar @abstractj

**Comment by codespearhead** [comment]
Quarkus 3.8.4, [which fixes that CVE](https://github.com/quarkusio/quarkus/issues/39927), has been in use since PR #28884 was merged on Apr 18, 2024.

The latest release of Keycloak, version 24.0.3, [was released on Apr 16, 2024](https://github.com/keycloak/keycloak/releases/tag/24.0.3).

So your scanning system will stop flagging issues once the new minor version is released.

**Comment by mamccorm** [comment]
Hey @codespearhead, be great if we could cut a new release soon to avail of the quarkus v3.8.4 bump - any rough ETA? and very much appreciated
