### ISSUE TITLE
Inconsistent values of profile metadata endpoints

### ISSUE THREAD

**Issue by Aldisti** [keycloak/keycloak#28620]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

When calling the `/admin/realms/master/profile/metadata` endpoint, in the username info, I get **"readOnly": false**.

But when I call the `/admin/realms/master/users/{admin-id}?userProfileMetadata=true` endpoint, in the username metadata info, I get **"readOnly": true**.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The `/admin/realms/master/profile/metadata` endpoint should return the same values as the `/admin/realms/master/users/{admin-id}?userProfileMetadata=true` endpoint.

### Actual behavior

The metadata endpoint returns a different value than the users endpoint.

### How to Reproduce?

I'm running keycloak in a container and I'm using this image: `quay.io/keycloak/keycloak:24.0.2`.

I'm on Ubuntu 23.10, but I don't think information like this could help.

**Comment by pedroigor** [comment]
I can see the inconsistency but that is expected because the endpoint `/admin/realms/master/users/profile/metadata` is mainly used to build the page to create users in the Admin API and when at that page, the username is writable if `Email as username` not enabled.

The endpoint you should consider when updating users is the other one.
