### ISSUE TITLE
Emphasize the need for setting container limit

### ISSUE THREAD

**Issue by mabartos** [keycloak/keycloak#28729]
### Description

After providing changes[1] to memory settings for the container deployments in Keycloak 24, we've faced some issues related to increased memory utilization. The JVM Heap setting has changed and uses relative values, instead of static ones specified via `-Xms`, and `-Xmx` JVM options. 

At this moment, the heap is defined via the `-XX:InitialRAMPercentage`, and `-XX:MaxRAMPercentage` JVM options with values `-XX:InitialRAMPercentage=50`, and `-XX:MaxRAMPercentage=70`. It states, that the initial heap size should be 50%(it's usually less - more comprehensive topic) of the total container memory, and the maximum heap as 70% of the total container memory.

When the limit for the containerized env is not set, it computes these values from the available memory for the container, which might be the total memory of the machine/node. 

Even when we already have information in docs around the limit, it seems that users are not so aware of them. We should emphasize more that the limit setting for running Keycloak in the container is very recommended. 

[1] https://github.com/keycloak/keycloak/pull/26661

For instance, issue: 
https://github.com/keycloak/keycloak/issues/28671

**Comment by vmuzikar** [comment]
Just my two cents. Since we don't explicitly support tweaking GC settings, it's perfectly fine from my perspective to document that the JVM frees memory very reluctantly. It's true for our only supported setup. We could be a bit more explicit with the wording though and make it clear that this is concerning Keycloak specific configuration.

> Ok, we can mention it as a brief paragraph that it's possible to use the old behavior, but rather recommending setting the limit.

-1 for this. Unless we want to support it, I would not document it. It's fine to make breaking changes in major releases.
