### ISSUE TITLE
Add missing german translations for user federation in admin UI

### ISSUE THREAD

**Issue by thomasdarimont** [keycloak/keycloak#28814]
### Description

The user federation configuration for LDAP and Kerberos is lacking a lot of german translations.

**Comment by ch-lepp** [comment]
I added a PR to add the missing German translations: https://github.com/keycloak/keycloak/pull/28962

**Comment by codespearhead** [comment]
PR #28962 was closed a few hours ago, but since it wasn't [linked to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), this issue wasn't closed automatically.

 @thomasdarimont , can you close this issue?
