### ISSUE TITLE
Issue with adding Attributes for account Management Console to custum user  profile

### ISSUE THREAD

**Issue by smiririhem** [keycloak/keycloak#28852]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/api

### Describe the bug

When attempting to modify a user's profile in Keycloak version 23.0.6, I encountered an error related to adding new attributes . Despite efforts to change the account theme and modify the accountpage.js file, an error occurred: "Bad Request: Unrecognized field 'phoneNumber' (class org.keycloak.representations.account.UserRepresentation)."

### Version

23.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

I expected to be able to add and modify user profile attributes, including custom ones like "phoneNumber," without encountering errors and to have a clear documentation about how to custimuze atributes in account with react 

### Actual behavior

Encountered a "Bad Request" error stating: "Unrecognized field 'phoneNumber' (class org.keycloak.representations.account.UserRepresentation)."

### How to Reproduce?

Navigate to the user profile modification page.
Attempt to add and modify custom attributes like "phoneNumber."
Observe the "Bad Request" error.

### Anything else?

The issue arises due to the transition of the account theme to React, leading to difficulties in incorporating new attributes. Assistance in resolving this issue would be appreciated.

**Comment by pedroigor** [comment]
If you are getting an `Unrecognized field` error is because you are adding that attribute as a top-level field in the user representation but there is no field with this name. For instance, you have the `firstName`, `lastName`, but not that one.

If you want to set that custom attribute, try adding it to the `attributes` field so that you can set key/value pairs for any custom attribute you want.

Also, make sure to properly configure this attribute in the user profile configuration for your realm. See https://www.keycloak.org/docs/latest/server_admin/#user-profile.
