### ISSUE TITLE
some GUI validation check missing 

### ISSUE THREAD

**Issue by katariakhyati** [keycloak/keycloak#28978]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

while testing we have found below issues with GUI

Click to Clients -> click to choose a client -> click Authorization tab -> choose Policies tab -> choose a policy -> click Add role button.
Expected behavior : Roles cannot be duplicated
Actual behavior : Roles can duplicate{}

2. Clients -> a client -> Authorization -> Policy -> create a policy -> choose policy type =time
   Expected behavior : Start time should not be greater than Expire time.
   Actual behavior : Accepting the start time greater than expire time

In previous version it was providing proper error message.

### Version

Keycloak 21.1.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Click to Clients -> click to choose a client -> click Authorization tab -> choose Policies tab -> choose a policy -> click Add role button.
Expected behavior : Roles cannot be duplicated

2. Clients -> a client -> Authorization -> Policy -> create a policy -> choose policy type =time
   Expected behavior : Start time should not be greater than Expire time.
  

### Actual behavior

Actual behavior : Roles can duplicate{}
Actual behavior : Accepting the start time greater than expire time

### How to Reproduce?

1.Click to Clients -> click to choose a client -> click Authorization tab -> choose Policies tab -> choose a policy -> click Add role button.

2. Clients -> a client -> Authorization -> Policy -> create a policy -> choose policy type =time
   
In previous version it was providing proper error message.

### Anything else?

![properValidation](https://github.com/keycloak/keycloak/assets/97315402/04b14211-b5fa-4586-9a99-796e301e3dfb)
![issue2](https://github.com/keycloak/keycloak/assets/97315402/9f003bf8-cbf9-4713-ba81-382246844dfc)
![Issue1 (1)](https://github.com/keycloak/keycloak/assets/97315402/0571b4dc-514e-450f-b7cc-479121b355e9)

**Comment by ssilvert** [comment]
I have verified both of these.  Both are actually a problem with the API though.  The admin API should do the validation.

**Comment by sguilhen** [comment]
We certainly should add some validations for these. In the roles case, instead of an error, we could simply remove the duplicates when saving the changes, so the policy would end up with only one role.

What I would really like to see though, is a behavior consistent with other places in the admin console when assigning roles. For example, when assigning roles to a group, when you click on the "Assign role" button, the page displays all roles available to be assigned and it filters out any roles already assigned. So the user can't even select a duplicate role because it won't be available.

Of course, the backend must still validate/remove duplicates because policies can be created using the API instead of the UI, but I feel like the UI experience should be consistent.
