### ISSUE TITLE
Docs: securing_apps/topics/oidc/java/installed-adapter.adoc

### ISSUE THREAD

**Issue by ctrworthin** [keycloak/keycloak#29063]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

File: securing_apps/topics/oidc/java/installed-adapter.adoc

The documentation for CLI / Desktop applications mention both `desktop` and `manual`  variants in the second paragraph, however the `manual` variant has no further elaboration beyond the subsequent sentence, which states that difference between the two:

> The KeycloakInstalled adapter supports a desktop and a manual variant. The desktop variant uses the system browser to gather the user credentials. The manual variant reads the user credentials from STDIN.

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Proportional documentation of the `manual` variant.

### Actual behavior

Only a brief mention of the `manual` variant, with no further explanation beyond it's primary distinction from the `desktop` variant. Other than the second paragraph in which it is mentioned, it reads as there is no alternative to authenticating through a browser.

**Comment by rmartinc** [comment]
In the manual option the user should do the operation in the browser manually. Then copy the code and pass it to the java using a Reader. I suppose it was not documented because it's not very useful. Check the code [here](https://github.com/keycloak/keycloak/blob/24.0.3/adapters/oidc/installed/src/main/java/org/keycloak/adapters/installed/KeycloakInstalled.java#L293-L310).

Nevertheless the [adapters are going to be removed](https://www.keycloak.org/docs/24.0.1/release_notes/#java-adapter-deprecation-and-removal) in teh next version of keycloak. The `KeycloakInstalled` was indeed removed just a few days ago from main (see #28790). So no updates in documentation will be done as the `KeycloakInstalled` code and documentation are already not present in the project.

Closing this as not planned.
