### ISSUE TITLE
Docs: upgrading/topics/migrate_themes.adoc

### ISSUE THREAD

**Issue by espinal1976** [keycloak/keycloak#29180]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

File: upgrading/topics/migrate_themes.adoc

after downloading keycloak-24.0.3 migrating a theme and doing a minor customization to add a privacy policy requested by Facebook in the login screen. The UI Login got Ugly.  Checking I have found that my theme seems to look for base.css and app.css which ARE NOT included in keycloak-24.0.3.  

Instead of getting these two file I am getting a 404.

Looking to keycloak-22.0.1 where the theme is coming from I have found this files: 

112	./common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css.gz
8	./common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css.gz
124	./common/keycloak/web_modules/@patternfly/react-core/dist/styles
128	./common/keycloak/web_modules/@patternfly/react-core/dist
132	./common/keycloak/web_modules/@patternfly/react-core
136	./common/keycloak/web_modules/@patternfly
140	./common/keycloak/web_modules 

But in keycloak-24.0.3 they are not present. 

Video with a better explanation:  https://vimeo.com/941201529/3b5d78202b?share=copy 

Also, could you please identify where should I download keycloak theme. Also If I do not want to upgrade where can I find the login.ftl and templated.ftl for keycloak-22.0.2. I have tested the actual ones and get the server broken.

### Version

24.0.0

### Regression

- [ ] The issue is a regression

**Comment by mposolda** [comment]
@espinal1976 This looks more like an ask for help with your custom theme, rather than Keycloak bug. Please use the user forum for asking questions. 

Few tips:

- Does UI look normal when you NOT use your custom theme at all? Is the default Keycloak login screen shown, which looks normally? If yes, then you know that the issue is isolated in your custom theme.
 
- Does UI look normal when you deploy your theme, but NOT override base templates like `login.ftl` or `template.ftl` ? If UI looks normal, then it is probably isolated to your custom `login.ftl` or `template.ftl` files. In that case, I suggest to look at latest `login.ftl` and `template.ftl` from latest Keycloak and check the changes from last version. If they work, then apply your customizations to those files. Those files in particular change quite often, so every release, you need to check what were the changes done between the releases (like between Keycloak 22 and 24 releases) and adjust your theme to use the new versions, just with your customizations added on top.

If it is not in `login.ftl` or `template.ftl`, it could be perhaps some other place like some CSS file.


Some more tips here: https://www.keycloak.org/docs/latest/upgrading/index.html#_migrate_themes
