### ISSUE TITLE
Receiving an unknown error in Keycloak when either the first name or last name is missing.

### ISSUE THREAD

**Issue by rinnuagna** [keycloak/keycloak#29296]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

In our application, when creating a new user, all fields are required (first name, last name, username, email, password). We are currently using version 24.0.2. When we attempt to create a user with only the first name entered and click submit, an error message is displayed. This error message says 'Please specify this field,' whereas it previously stated 'Enter the last name.' The same issue also occurs if only the last name is provided for rest of the field the message specifies the reason.

![image](https://github.com/keycloak/keycloak/assets/43952574/3710d5eb-20c3-4139-ba27-3b8aa84e2228)
 This started happening after version upgrade. This was how it looked in the previous version.
 
![image](https://github.com/keycloak/keycloak/assets/43952574/02ae5330-0c02-4440-99a1-c3f574f95ff8)

### Version

24.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

Error message should specify which field is missing

### Actual behavior

For first and last name , the error message is vague telling Please specify the field

### How to Reproduce?

In user creation, enter firstname and click submit (keep all the fields mandatory)

**Comment by mposolda** [comment]
Just a note that this is probably related to the fact, that you are using custom theme. With the default theme, the UX is much better because messages are displayed right above the fields (See screenshot below).

![Screenshot from 2024-05-17 09-10-18](https://github.com/keycloak/keycloak/assets/1223965/2fb72b09-ad9f-4f41-b852-287e6c79ab69)


@rinnuagna @pedroigor At the same time, I think that we can probably improve usability by displaying some message specifying also the name of the field. So something like: `Please specify this field: First Name` . So it will have better usability even for custom themes. WDYT?

I am changing component to `user profile` and let the core-iam to triage this.

**Comment by pedroigor** [comment]
Yeah, the messages are based on how we handle the built-in templates.

The thing about  changing to `Please specify this field: First Name` is that the message is close to the field already in our built-in templates. 

You can also customize the message by changing the `error-user-attribute-required` message property. For instance, using a value like `Please specify attribute {0}.` where `{0}` will be the attribute name.

@rinnuagna Does it work for you?
