### ISSUE TITLE
Add mobile_number and mobile_number_verified built for in similar to email 

### ISSUE THREAD

**Issue by smandlavdiya** [keycloak/keycloak#29436]
### Description

Mobile Number is very common to signup now a days we can include it by default and achieve below functionality built in:

we can have dummy provider for SMS implementation included and actual implementation can be added by SPI as required by us. 

Phone support like e-mail
Check ownership of a phone number (Forms and Rest API)
Use SMS as second factor in 2FA method (Browser flow)
Login by phone (Browser flow)
Reset Password by phone
Authentication by phone (Rest API)
Authenticate everybody by phone, auto create user on Grant (Rest API)
Register with phone
Register only phone (username is phone number)
Register add user attribute with redirect_uri params

a similar project can be found here: https://github.com/cooperlyt/keycloak-phone-provider/tree/master

**Comment by jonkoops** [comment]
Please refrain from mentioning team members, we will triage your issue and it will be prioritized as per Keycloak policy.

**Comment by codespearhead** [comment]
In my opinion, this should be closed as not planned because, [as Okta states](https://sec.okta.com/articles/2020/05/sms-two-factor-authentication-worse-just-good-password):

> [SMS-based two-factor authentication](https://www.okta.com/blog/2020/10/sms-authentication/) shows up as an option on many websites, but in some cases, it’s worse than not having a second factor at all!

Many companies, such as [Evernote](https://discussion.evernote.com/forums/topic/147112-we-are-removing-sms-as-a-two-factor-authentication-method/), [Twitter](https://blog.x.com/en_us/topics/product/2023/an-update-on-two-factor-authentication-using-sms-on-twitter) and [Microsoft](https://www.reddit.com/r/sysadmin/comments/16irazw/microsoft_removing_sms_mfa_auth_entirely_starting/) are on the path to discontinuing SMS-based 2FA. They recognize that the cost sending SMS messages and the increased risk of user attacks are not worth the convenience it provides.

The same concerns apply to email-based 2FA, which although it is less vulnerable and cheaper than the previous method, it still has the disastrous side effect of enabling a hacker to lock the user out of their account permanently since the hacker holds the literal 2FA seed, a hacked email account (personal email, not business email) or a cloned SIM card, which are far easier to get their hands on remotely than if the user only used a username and a password and weren't exposed to what Okta listed (considering those credentials weren't leaked, which is why MFA was created in the first place).

Once the do so, they are free to carry out scams on behalf of the user for months, which is particularly common on [Instagram](https://www.reddit.com/r/InstagramMarketing/comments/15jzcru/instagram_account_hacked_and_phone_number_and/).

**Comment by codespearhead** [comment]
@smandlavdiya Could you please close this issue [1] in favor of [2][3]?

Make sure to upvote it by adding a 👍 to the description to help it gain visibility.

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
[2] https://github.com/keycloak/keycloak/discussions/27152
[3] https://github.com/keycloak/keycloak/discussions/27152#discussioncomment-10923758

**Comment by codespearhead** [comment]
Can you please close this issue/discussion [1][2]?

This question has been asked several times before. You can find previous discussions by searching for “sms” or “email” in the GitHub search bar of the Keycloak repository [3][4].

Currently, there is no official support for using email or phone numbers for authentication in Keycloak. Therefore, any issues you encounter with third-party solutions should be reported in their respective repositories, not here.

If you're interested in this feature, feel free to share your use case here [5], and upvote it by adding a ⬆️ to the discussion’s description after reading this answer carefully [6].

***

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
[2] https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#closing-a-discussion
[3] https://github.com/search?q=repo%3Akeycloak%2Fkeycloak+%22SMS%22&type=issues
[4] https://github.com/search?q=repo%3Akeycloak%2Fkeycloak+%22SMS%22&type=discussions
[5] [https://github.com/keycloak/keycloak/issues/29436](https://github.com/keycloak/keycloak/issues/29436#issuecomment-2168836968)
[6] https://github.com/keycloak/keycloak/issues/29436#issuecomment-2168836968

**Comment by codespearhead** [comment]
Can you please close this issue/discussion [1][2]?

This question has been asked several times before. You can find previous discussions by searching for “sms” or “email” in the GitHub search bar of the Keycloak repository [3][4].

Currently, there is no official support for using email or phone numbers for authentication in Keycloak. Therefore, any issues you encounter with third-party solutions should be reported in their respective repositories, not here.

If you're interested in this feature, feel free to share your use case here [5], and upvote it by adding a ⬆️ to the discussion’s description after reading this answer carefully [6].

***

[1] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue
[2] https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#closing-a-discussion
[3] https://github.com/search?q=repo%3Akeycloak%2Fkeycloak+%22SMS%22&type=issues
[4] https://github.com/search?q=repo%3Akeycloak%2Fkeycloak+%22SMS%22&type=discussions
[5] https://github.com/keycloak/keycloak/discussions/27152
[6] https://github.com/keycloak/keycloak/discussions/27152#discussioncomment-10923758
