### ISSUE TITLE
Custom Authenticators: action(context) is never called

### ISSUE THREAD

**Issue by agbaroni** [keycloak/keycloak#29449]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When a custom Authenticator challenge a form the its submit button doesn't call the action() method but it returns to call authenticate(), showing the same form.

### Version

24.0

### Regression

- [ ] The issue is a regression

### Expected behavior

After a click on submit button the expected behaviour is the action() method is called.

### Actual behavior

The authenticate() method is called again.

Please note: the authenticate() method receives the form data.

### How to Reproduce?

[custom.zip](https://github.com/keycloak/keycloak/files/15275422/custom.zip)

### Anything else?

Official Keycloak 24 documentation: https://www.keycloak.org/docs/latest/server_development/index.html#implementing-an-authenticator

**Comment by rmartinc** [comment]
@agbaroni I'm attaching more or less your sample but in a maven project (please when you report a extension issue send an easy project and not separated files, we are bus people in general). I have done more or less the same you are doing except that I'm using the `terms.ftl` template instead of adding a new one. The project is for current 24.0.4. Just compile unzip and compile it (`mvn clean pakcage`). Deploy the resulting jar into the providers folder and start.

[keycloak-custom-authenticator.zip](https://github.com/keycloak/keycloak/files/15277623/keycloak-custom-authenticator.zip)

You need to configure a flow. I cloned default browser flow and I added the custom step after the username/password step (I have removed some not needed things like kerberos, otp,...). My final flow is like this:

![Screenshot from 2024-05-10 18-44-50](https://github.com/keycloak/keycloak/assets/26901232/1e17bfb8-fc59-4ae2-9e6a-82965a08c951)

With this everything is working. The custom authenticator just successes if terms accepted and fails if declined, but it shows the data is received ok.

If you find something that can be improved in teh doc don't hesitate to send yourself a PR for it. I will close this issue if you don't say enything different because this is working as expected. Note that default forms uses the same interfaces.

**Comment by agbaroni** [comment]
Thank you Ricardo, I'm sorry for the inconvenience.

terms.ftl works for me also, so why with a custom .ftl is not working? I'm not able to see any logical difference between custom.ftl and terms.ftl.

Here [1] there is the entire Maven project with instructions; please note that custom.ftl is really sms.ftl.

[1] https://github.com/agbaroni/rest-otp-authenticator

**Comment by rmartinc** [comment]
Your `form` tag in the `sms.ftl` has attribute `url` instead of `action`, just change that. Therefore there is no action, and the browser is sending the post against the same URL currently in the page. @agbaroni You should have guessed it yourself after seeing that `terms.ftl` was working. Just changing things one by one would have been enough to see what was wrong. I'm closing this issue now.
