### ISSUE TITLE
A bad request can cause a client application to no longer be able to log a user out.

### ISSUE THREAD

**Issue by arifd** [keycloak/keycloak#29527]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

I’ve noticed that if I can produce this error (by attempting to exchange the same code twice)

```
2024-02-21 17:07:05,002 WARN  [org.keycloak.protocol.oidc.utils.OAuth2CodeParser] (executor-thread-75) Code 'c3d11805-9069-4670-b7ff-86b35d689408' already used for userSession '103571cd-8bd8-4926-9d49-d1296c2
85462' and client '427c56e7-2696-4312-bd84-79dbce933456'.
2024-02-21 17:07:05,002 WARN  [org.keycloak.events] (executor-thread-75) type=CODE_TO_TOKEN_ERROR, realmId=146101a1-221e-4e35-859d-1ae0a6e5ee81, clientId=cabinetdev, userId=null, ipAddress=172.31.0.1, error=i
nvalid_code, grant_type=authorization_code, code_id=103571cd-8bd8-4926-9d49-d1296c285462, client_auth_method=client-secret
```

Then the refresh token I have stored on the successful attempt, now can no longer be used in the revocation endpoint. resulting in this error

```
2024-02-21 17:32:02,613 WARN  [org.keycloak.events] (executor-thread-124) type=REVOKE_GRANT_ERROR, realmId=146101a1-221e-4e35-859d-1ae0a6e5ee81, clientId=cabinetdev, userId=null, ipAddress=172.31.0.1, error=u
ser_session_not_found, client_auth_method=client-secret
```

I.e. a bad (or malicious) request can cause a session to no longer be revoked.

### Version

bitnami/keycloak:24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Failed token exchange attempts should not change/discard any existing refresh-token.

### Actual behavior

The refresh token that I have can not be used to revoke the session of the user. The user remains logged in.

### How to Reproduce?

Hit the exchange route with the same code twice, it being successful on the first attempt, and later failing on the second attempt. Now from the client application, attempt to revoke the refresh token that you have from the successful exchange... You can not.

### Anything else?

cross-posted: https://keycloak.discourse.group/t/bug-or-my-misunderstanding/24689

**Comment by mposolda** [comment]
@arifd It is on purpose that when you attempt to exchange same `code` twice, the client session is removed. This is from security reasons as when someone tries to exchange code twice, it means that something strange happens and it is not clear if it was "honest user" or the "possible attacker" who manage to successfully exchange the `code` . As it is possible that attacker was able to read the OIDC authentication response (with the `code` parameter) and then managed to exchange `code` for the token earlier than the honest user.

So I am closing as this is expected behaviour. Please update your client application to avoid exchanging same code twice.
