### ISSUE TITLE
Can we cleanup SAML adapters more?

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#29922]
### Description

We need to keep SAML adapter to be available for Wildfly galleon feature pack.

But few more things we can maybe consider for cleanup. It should be doublechecked if those can be safely cleaned or not.
- Do we need SAML galleon feature pack to be available for JEE at all? If not, we can maybe keep only "jakarta" modules and remove the "jee" modules? This possibly applies to:
  - `adapters/saml/core` (VS `core-jakarta`)
  - `adapters/saml/wildfly-elytron` (VS `wildfly-elytron-jakarta`)
  - `adapters/saml/wildfly/wildfly-subsystem` (VS `wildfly-jakarta-subsystem`) . But actually not sure if we need `wildfly-subsystem` at all when adapters are handled by galleon feature pack?

- Can we cleanup something more inside directory `distribution` ? Maybe `distribution/feature-packs` and also maybe something for SAML, but again should be doublechecked...

### Child tasks

- [x] #30555 
- [x] #30556

**Comment by mposolda** [comment]
Related issue: https://github.com/keycloak/keycloak/issues/30324

**Comment by rmartinc** [comment]
Working in #30324 I think we can clean the saml adapter code even more after tha tissue is finished (CI tests wildfly 28/29 using layers). I think that there are three things we can clean up:

1. Remove undertow provider (javax and jakarta) and just maintain elytron. Layers should be updated because some jars will disappear.
2. Remove any saml adapter project based on javax (I see three of them: core-jakarta, wildfly-elytron-jakarta and wildfly-jakarta-subsystem).
3. Remove the saml adapter distribution via zip (just layers remain).

We can talk about this in tomorrow's weekly meeting.

**Comment by mposolda** [comment]
@rmartinc @pskopek Added #30555 and #30556 as subtasks of this one. There is separate issue #30554 for removing undertow adapter in the testsuite.

**Comment by mposolda** [comment]
Closing as all the subtasks were addressed.
