### ISSUE TITLE
LDAP dynamic groups memberships can't be synced into Keycloak

### ISSUE THREAD

**Issue by kc548** [keycloak/keycloak#30046]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

I configured dynamic groups in OpenLDAP with groupOfURLs objectClass using dynlist overlay. Here's an example of a group entry : 
```
dn: cn=group,ou=services,dc=example,dc=com
cn: group
objectClass: groupOfURLs
objectClass: top
memberURL: ldap:///ou=people,dc=example,dc=com??one?(service=group)
member: uid=user2,ou=people,dc=example,dc=com
member: uid=user3,ou=people,dc=example,dc=com
```
Now I want to sync these groups into Keycloak. I configured a User Federation and it works fine for importing users. For the groups sync, I configured a mapper : 
```
Name => services-into-groups
Mapper type => group-ldap-mapper
LDAP Groups DN => ou=services,dc=example,dc=com
Group Name LDAP Attribute => cn
Group Object Classes => groupOfURLs
Preserve Group Inheritance => Off
Ignore Missing Groups => Off
Membership LDAP Attribute => member
Membership Attribute Type => DN
Mode => READ_ONLY
User Groups Retrieve Strategy => LOAD_GROUPS_BY_MEMBER_ATTRIBUTE
```
The problem is when I click on "Sync LDAP groups to Keycloak" on my mapper's tab, it retrieves the groups but they don't have any members in it. But Keycloak does not detect any issue, it says the sync is successful. Even the logs don't say much : 
`2024-05-31 13:23:39,829 INFO  [org.keycloak.services] (executor-thread-1) KC-SERVICES0087: Syncing data for mapper 'services-into-groups' of type 'group-ldap-mapper'. Direction: fedToKeycloak` (I tried debug log level as well).

In order to see what was happening, I installed tshark to check if I could get any clue from the packets sent to LDAP as to why it was not working as expected.
`tshark -i any -f "dst port 389" -O ldap -V`

In the output, I noticed this : 
```
Control
    controlType: 2.16.840.1.113730.3.4.2 (Manage DSA IT LDAPv3 control)
```

The ldapsearch equivalent of this controlType is the flag -M. So I tried doing ldapsearch requests with this flag :

```
ldapsearch -x -M -H ldap://localhost -D cn=admin -w secret -b "ou=services,dc=example,dc=com" member
# extended LDIF
#
# LDAPv3
# base <ou=services,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: member 
# with manageDSAit control
#
dn: ou=services,dc=example,dc=com
```

The same request without this flag gives : 

```
ldapsearch -x -H ldap://localhost -D cn=admin -w secret -b "ou=services,dc=example,dc=com" member
# extended LDIF
#
# LDAPv3
# base <ou=services,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: member 
#
dn: ou=services,dc=example,dc=com
member: uid=user2,ou=people,dc=example,dc=com
member: uid=user3,ou=people,dc=example,dc=com
```

The thing is the member attributes are not returned when using this controlType. And it's the same thing for memberOf so Keycloak's LOAD_STRATEGY won't change anything. So why Keycloak uses this to request LDAP ? It would be convenient to have an option to disable it.

I tried to sync static groups with Keycloak (using memberUid) and it works but in my case, working only with static groups is a huge constraint.

I hope I helped anyone who had the same issue figure out what was causing this. Unfortunately, I did not find any solution satisfying enough for a production environment. If you're in this situation, please upvote this issue so it can be prioritised. 

### Version

24.0.4 (latest)

### Regression

- [ ] The issue is a regression

### Expected behavior

LDAP groups and their members should be synced into Keycloak.

### Actual behavior

When using LDAP dynamic groups, Keycloak is not able to sync memberships. (the groups are retrieved but stay empty)

### How to Reproduce?

Configure OpenLDAP with dynlist overlay, create a dynamic group with memberURL, configure a Keycloak User Federation and a group-ldap-mapper (working on member attribute and DN membership attribute type).

### Anything else?

Many people before us have had this problem and the issue persists as of today. Some examples include : 
https://github.com/keycloak/keycloak/issues/10294
https://keycloak.discourse.group/t/opendlap-group-ldap-mapper-with-groupofurls/7458

**Comment by sguilhen** [comment]
Setting this as important as this has been affecting several users

**Comment by wzrdtales** [comment]
this used to work in earlier keycloak, not sure when this was broken... . currently regretting having updated keycloak

**Comment by kc548** [comment]
Hi, do you have any update on this issue ? We have tried updating our Keycloak instance to the latest version (v. 25.0.4) and we are still experiencing the same issue.

**Comment by sguilhen** [comment]
@kc548 I was reading a related issue (see[ this comment](https://github.com/keycloak/keycloak/issues/26317#issuecomment-1940511333)), and I was wondering if setting the `Referral` option to `follow` doesn't fix this behavior. In particular, this part:

"PR https://github.com/keycloak/keycloak/pull/24852 fixes this because the "referral" option removes ManageReferralControl/manageDSAit from the LDAP context, which makes JNDI behave more like basically every other existing LDAP client does by default." is strongly suggesting that it is needed in order to disable the DSA IT LDAPv3 control that Java enables by default for all searches.

**Comment by rmartinc** [comment]
AFAIK keycloak has never managed dynamic groups (objectclass `groupOfURLs`). What keycloak manages is static groups with members (DN or uid) and it also manages groups defined in a user attribute (typical `memberOf` attribute from AD for example). The dynamic groups are not standard (they were created by old Sun -maybe Netscape- Directory Server) and are not included in RFC 4519 or any spec (check [reference](https://ldap.com/ldap-oid-reference-guide/)).

Besides dynamic groups are very dangerous in terms of performance because how do you know all the dynamic groups of a user? You have to get all the dynamic groups and execute the search (attribute `memberURL`) to see if the user entry is returned for each one. That has an important performance impact that I don't know if we want to take. What I have also seen is that ldap servers sometimes expand the dynamic groups using attributes automatically (for example AD [here](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-rule-member-of) or oracle OUD). If the expansion is done automatically by the server inside an attribute that can be configured in keycloak. They always comment about the performance risk.

But for sure this is not a bug. This is an enhancement. And we need to carefully think if we want to follow this route. Probably a new mapper will be needed and maybe we should just copy the information to the database instead of querying all the time the ldap. Changing this to enhancement.

**Comment by kc548** [comment]
> @kc548 I was reading a related issue (see[ this comment](https://github.com/keycloak/keycloak/issues/26317#issuecomment-1940511333)), and I was wondering if setting the `Referral` option to `follow` in the LDAP settings doesn't fix this behavior. In particular, this part:
> 
> "PR #24852 fixes this because the "referral" option removes ManageReferralControl/manageDSAit from the LDAP context, which makes JNDI behave more like basically every other existing LDAP client does by default."
> 
> is strongly suggesting that it is needed in order to disable the DSA IT LDAPv3 control that Java enables by default for all searches.

Thanks for the reply. It works and the Manage DSA IT LDAPv3 control doesn't appear in the packets sent to LDAP anymore. We have looked into it for quite a long time now and we haven't really checked that option. It didn't seem as if it could have an effect on this. Anyway, thanks for your help.
