### ISSUE TITLE
Option `cache-remote-tls-enabled` is missing the default

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#30120]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

Seems some defaults for config options don't work as expected. This requires further investigation.
See: https://github.com/keycloak/keycloak-benchmark/issues/840

### Version

main

### Regression

- [X] The issue is a regression

### Expected behavior

Defaults work.

### Actual behavior

Defaults don't work.

### How to Reproduce?

See https://github.com/keycloak/keycloak-benchmark/issues/840

**Comment by ahus1** [comment]
Workaround in preparation: #30130

**Comment by ahus1** [comment]
Root cause identified: When JMX is enabled with JDK21, it will initialize Java's ForkJoinPool before Quarkus can set the property `java.util.concurrent.ForkJoinPool.common.threadFactory`. Due to that, all threads in the pool will not have the correct classloader set, and due to that those threads won't pick up the correct configuration from SmallRye.

I'll prepare a PR.
