### ISSUE TITLE
Keycloak Organizations as a supported feature

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#30229]
### Description

The `organization` feature will be a supported feature in Keycloak 26.

There is no plan to add additional capabilities other than those already available from Keycloak 25:

- https://github.com/keycloak/keycloak/issues/28609

The goal is to make the feature ready for production deployments considering the following requirements:

* Stability of the database schema
* Scalability
* Documentation
* Any blocker or important issue fixed if related to the current scope of the capabilities as per #28609.

We might eventually add additional capabilities depending on the feedback from the community until Keycloak 26 is released. However, any issue we accept should take into account the roadmap of the feature without any delay in our schedule to make it fully-supported.

### Discussion

N/A

### Issues

- #30084
- #31730
- #32209
- #31301
- #31944
- #31643
- #31642
- #29080
- #30085
- #30088
- #30087
- #30305
- #30312
- #30313
- #31438

### Motivation

Make the `organization` feature fully supported.

**Comment by pedroigor** [comment]
I would like to propose including https://github.com/keycloak/keycloak/pull/29613 even though not originally planned. Please, let me know your thoughts.

**Comment by paultempleman** [comment]
@pedroigor including #29613 i.e. support for joining multiple organizations, would greatly assist some of the more complex use case scenarios in government and healthcare. It would also help some of the work being OpenID for Verifiable Credentials being done by the Keycloak OAuth SIG. Is there any chance it could be any earlier than 26?

**Comment by smandlavdiya** [comment]
> I would like to propose including #29613 even though not originally planned. Please, let me know your thoughts.

It will be definitely a great addition to the feature

**Comment by shkmaaz11** [comment]
> [youssefbennour](/youssefbennour)

Did you plan anything for this or still waiting for it to be supported in 26?

**Comment by youssefbennour** [comment]
I started integrating it already.
I'll try to convince my managers to wait for the other features (the most important is cross-user organizations).

**Comment by youssefbennour** [comment]
@shkmaaz11 
Sorry, I meant Keycloak 25

**Comment by pedroigor** [comment]
@youssefbennour @shkmaaz11 Can I ask you to give your thoughts and help with what you expect from the support of users joining multiple organizations?

Please, add any comments here https://github.com/keycloak/keycloak/issues/30747.

**Comment by santosmken** [comment]
Hi there! I just want ask if it is possible to have a support later about different session by organization? Or even more granular like clients related to an organization?

**Comment by Lord-KalEl** [comment]
At first, thanks for this required feature … I wanted to leave KeyClok because of the lack of this future (the extension was an option, but this, I thought, has to be core in such a software.)

But now, the organizations are there, the first step is done. It makes less sense, to have only the organizations, without orga-roles or orga rules. This step is very important, because otherwise, the orgas are similar to the groups.
Next thing is the nested organizations … if you have many of them, you should be able to struct them. 
One of your features will be orga-groups.
Definition of a group in KeyCloak is, to group some users.
Definition of a orgas in KeyCloak is, to group some users, but to isolate the rules and polices (and theming and other features)

So the idea is, we need both, nested groups AND nested orgas.

By the way, themes should be changable without a restart of KeyCloak … and it would be nice, if every orga can have their own theme. (500 to 1000 organizations, the downtime will be very high ;) )

Greetings
Kal

**Comment by gfl-akovalchuk** [comment]
Is it already "supported feature" or it's still "experimental one"? 
26.3.2 - I still need to enable this feature as "--features organization"

**Comment by cvivieca** [comment]
@gfl-akovalchuk  It is a supported feature, but I'll call it myself as an experimental one. It is lacking of many important features to be useful, such as organization roles, organization groups, organization clients, etc. It might be a usable feature on KC 27. There are many PRs trying to achieve these enhancements but not one from the KC team take a look of them, such as simple PR as https://github.com/keycloak/keycloak/pull/40508.

**Comment by gfl-akovalchuk** [comment]
> [@gfl-akovalchuk](https://github.com/gfl-akovalchuk) It is a supported feature, but I'll call it myself as an experimental one. It is lacking of many important features to be useful, such as organization roles, organization groups, organization clients, etc. It might be a usable feature on KC 27. There are many PRs trying to achieve these enhancements but not one from the KC team take a look of them, such as simple PR as [#40508](https://github.com/keycloak/keycloak/pull/40508).

thanks for the reply! Let's see.
