### ISSUE TITLE
Executor consent-required does not work for client-roles condition

### ISSUE THREAD

**Issue by yuichi-nakamura** [keycloak/keycloak#30284]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

It seems that client-roles condition is not working for consent-required executor.

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

When client-role condition is set for a client role, consent-required executor sets "Consent required" field of  matched clients  as "ON" in updating configuration of clients. 

### Actual behavior

"Consent required" field of of a client is not set "ON" in updating configuration of the client, where client role matches the role in "client-role".

### How to Reproduce?

1) In realm settings -> Client policies, create a profile containing "consent-required" executor
2) Create a policy, condition is set as "client-roles (client roles is "testrole"), profile is set as the profile created in 1)
3) Create a OIDC client "testclient"
4) In Roles tab of  "testclient", create role "testrole"
5) For "testclient" set consent required "ON" and save
6) For "testclient" set consent required "OFF" and save
7) See "testclient" again, I can see consent required is still "OFF", but "ON" is expected, because "consent-required" executor was set in 1)-4).

### Anything else?

When I set other executors like "secure-session" with "client-roles" condition, it was applied to "testclient".

**Comment by rmartinc** [comment]
Hi @yuichi-nakamura!

Probably it's because the UPDATE event is not managed by the `ClientRolesCondition` [here](https://github.com/keycloak/keycloak/blob/25.0.0/services/src/main/java/org/keycloak/services/clientpolicy/condition/ClientRolesCondition.java#L70-L101). Note that the REGISTER event is never executed on `ClientRolesCondition` because the client to be created has no roles yet.

I suppose that adding the event is enough and a little test in the CI would also be needed. If someone wants to work on this please let me know. If not I'll try to submit a fix in the next weeks.
