### ISSUE TITLE
CVE-2024-30171 - org.bouncycastle:bctls-fips

### ISSUE THREAD

**Issue by vsun757** [keycloak/keycloak#30340]
### Description

CVE-2024-30171 - org.bouncycastle:bctls-fips affects Keycloak version 25.0.0

**Comment by codespearhead** [comment]
To follow-up on [this comment](https://github.com/keycloak/keycloak/issues/29608#issuecomment-2151643133) by @ahus1 in https://github.com/keycloak/keycloak/issues/29608 :

Similar to what happened with `org.bouncycastle:bc-fips` in https://github.com/keycloak/keycloak/issues/30341 , more specifically what was described in [this comment](https://github.com/keycloak/keycloak/issues/30341#issuecomment-2166829373), [CVE-2024-30171](https://github.com/advisories/GHSA-v435-xc8x-wvr9) might not have been patched by https://github.com/keycloak/keycloak/pull/30174 . However, this time I couldn't pinpoint where `org.bouncycastle.bctls-fips` was hardcoded in the codebase, but it's used without a version here:

https://github.com/keycloak/keycloak/blob/2f11605a5b6a283e2949a97a157280ebb85a0aaf/crypto/fips1402/pom.xml#L72-L75

What I did find was `org.bouncycastle.bcpkix-fips:1.0.7`, which [is currently the latest version and doesn't have any publicly reported vulnerabilities](https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-fips). Hence, it might not have anything to do with the problem at hand:

https://github.com/keycloak/keycloak/blob/2f11605a5b6a283e2949a97a157280ebb85a0aaf/pom.xml#L83-L84

I wonder if since `org.bouncycastle.bcpkix-fips` depends on `org.bouncycastle.bc-fips` as per [Maven Central](https://central.sonatype.com/artifact/org.bouncycastle/bcpkix-fips/dependencies), this issue will be resolved once https://github.com/keycloak/keycloak/issues/30341 is closed, in which case this issue [should be linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to https://github.com/keycloak/keycloak/pull/29670 (I currently don't have permissions to do that).

**Comment by abstractj** [comment]
@rmartinc is this issue similar to https://github.com/keycloak/keycloak/issues/30341 ?

**Comment by rmartinc** [comment]
Yep, this was solved as soon as https://github.com/keycloak/keycloak/issues/26568. is fixed. Closing this one.

Duplicate of https://github.com/keycloak/keycloak/issues/26568.
