### ISSUE TITLE
Documentation missing for Identity provider mapper field : "Regex Attribute Values"

### ISSUE THREAD

**Issue by omasseau** [keycloak/keycloak#30405]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

I wanted to know how I could map a SAML attribute to a group using a regex to only keep a part of the attribute value.
Exemple: 
If I have CN=test,OU=A,DC=com  -> I only want to keep the value 'test'.

I see there is a "Regex Attribute Values" field for identity provider mappers that can be enabled.
But there is no documentation in Keycloak documentation about this field and about how to format the regex so that Keycloak can know which part of the regex should be used to extract the desired value.

The field tooltip just says : "If enabled attribute values are interpreted as regular expressions." which is not really helpful ;)

![image](https://github.com/keycloak/keycloak/assets/11772429/e61aae67-3676-428b-bb55-a7686bd26f9f)

### Version

22.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The documentation should : 
- Document the usage of the "Regex Attribute Values" field of identity provider mappers.
- Document how the regex should be formatted (examples whould be useful)

### Actual behavior

There is no documentation

### How to Reproduce?

Try to figure out how to extract only a given part of an attribute value returned by the identify provider.

**Comment by rmartinc** [comment]
@omasseau It's java regex format, keycloak is developed in Java and all regex are [Java format](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html). But I don't understand your question, the mapper you are commenting is a `Advanced Attribute to Group` and that mapper just assigns a keycloak group to a user if the attribute is present in the SAML response (equals or regex comparison). So you cannot get partial value, it just assigns a already present group if the attribute is present in the response.

**Comment by rmartinc** [comment]
And please, github issues are for clear bugs in the keycloak code. Not to get advise or ask questions. For those goals please use the the [keycloak user google group](https://groups.google.com/g/keycloak-user).

**Comment by omasseau** [comment]
@rmartinc 

Hello,

So why is this available ? : 
![image](https://github.com/keycloak/keycloak/assets/11772429/71821aff-26c8-4700-bf0b-e5fbe5138b40)

Teling something is not documented is not asking for an advise or asking a question.

**Comment by omasseau** [comment]
> @omasseau It's java regex format, keycloak is developed in Java and all regex are [Java format](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html). But I don't understand your question, the mapper you are commenting is a `Advanced Attribute to Group` and that mapper just assigns a keycloak group to a user if the attribute is present in the SAML response (equals or regex comparison). So you cannot get partial value, it just assigns a already present group if the attribute is present in the response.

Thanks, that is exactly what should be documented ;)

**Comment by rmartinc** [comment]
@omasseau If you file a documentation bug that means you want to modify/improve the documentation files. The idea is you explain what section is wrong and the new paragraph that you suggest to add or modify. You can even send a PR because a documentation PR is easier and it does not require any development skills or knowing about the keycloak code base.

In this particular case, the only documentation for the IdP mappers are in the [server admin](https://www.keycloak.org/docs/latest/server_admin/#_mappers). And the doc is general and does not describe mapper by mapper. The only improvement I see for this issue is changing the tooltips for the mapper which are [here](https://github.com/keycloak/keycloak/blob/25.0.0/services/src/main/java/org/keycloak/broker/saml/mappers/AdvancedAttributeToGroupMapper.java#L59-L78). Feel free to send a PR improving them if you think that it is necessary, but please do the same for the other Advanced attribute group/role mappers to be consistent.

**Comment by rmartinc** [comment]
Closing this. If you want to improve tooltips please send a PR with the new ones to review them.
