### ISSUE TITLE
Upgrade BCFIPS to 2.0 to make sure it can be used on OpenJDK 21

### ISSUE THREAD

**Issue by mritunjaysharma394** [keycloak/keycloak#30415]
According to [1], the 2.0 stream is working with Java 21, when previous 1.0 stream just with Java 17. Also there is recent FIPS 140-3 certification [2], which applies to 2.0 stream (maybe for 1.0 stream as well, but this is not very clear to me).

I don't know exactly, but I estimate that upgrade won't be so huge effort considering that all our BCFIPS integration is in the module "crypto/fips1402" in the codebase. Moreover, we don't provide support for BCFIPS bits and hence we're not dependent on using same versions as Quarkus uses.

[1] https://www.bouncycastle.org/download/bouncy-castle-java-fips/
[2] https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4743

### Original description

It seems like Keycloak has released its v25 and now supports JDK21 and will deprecate JDK 17. That brings me to the question that as of now it seems BouncyCastle FIPS support up to JDK17 so it can affect the Keycloak-FIPS compliance here https://www.keycloak.org/server/fips

What are our plans for that and should we wait for bumping to JDK21 till we have BCFIPS available for it? 
https://github.com/bcgit/bc-java/issues/1558#issuecomment-1882382781

**Comment by codespearhead** [comment]
I might be misinterpreting the paragraph below, but isn't FIPS compliance already offered by Keycloak and certified by the [RHBK](https://access.redhat.com/products/red-hat-build-of-keycloak) without the need for the BouncyCastle-FIPS bits?

https://github.com/keycloak/keycloak/blob/18a6c790113998bf039f46d6c71ffb668e961036/docs/guides/server/fips.adoc?plain=1#L31-L36

The [RHBK Documentation](https://access.redhat.com/documentation/en-us/red_hat_build_of_keycloak/22.0/html/server_guide/fips-) says the very same thing, and they even go as far as to say that neither officially support the commercial version of the BouncyCastle-FIPS bits.

In that case, this issue is invalid. However https://github.com/keycloak/keycloak/issues/30275 isn't not closed yet, so there might be still room for debate in case that affirmation is incorrect, as per [this comment](https://github.com/keycloak/keycloak/pull/28518#issuecomment-2139236264) from @mposolda :

"I am not sure if we want to officially deprecate Java 17 in release notes considering FIPS? Not 100% sure if we need to use "RHEL ELS" image for the FIPS 140 support, which might be based on RHEL 8.6. But RHEL 8 seems to support Java 21 from 8.9 based on: https://access.redhat.com/articles/1299013 . Or do we still deprecate Java 17 and then re-evaluate in Keycloak 26?"

**Comment by mamccorm** [comment]
That's correct - there isn't a FIPS image provided by default, but Keycloak does [support FIPS](https://www.keycloak.org/server/fips) and lays out the info to configure, as well as bringing your own bcfips JRE.

By adding a dependency on JDK21 before a bcfips version is validated, this will essentially means a breaking change for keycloaks FIPS capabilities. We might want to delay this change, or maintain compatibility with JDK17 in parallel until such times it can be dropped as supported. Thoughts?

**Comment by mamccorm** [comment]
Also separate, but related issue to FIPS support
https://github.com/keycloak/keycloak/issues/30964
