### ISSUE TITLE
All user attributes readonly in admin ui and admin API after setting edit mode of one user federation to READ_ONLY

### ISSUE THREAD

**Issue by bk-js** [keycloak/keycloak#30476]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have two ldap user federations connected to different ADs. In only one of those user federations "fed_a" the edit mode is set to READ_ONLY. In another user federation "fed_b" the edit_mode is set to WRITABLE.

Now if we go to the edit view of a user which was imported from "fed_a" in the admin ui the mapped attributes username, email, first name, last name... are all readonly (which is expected).
However, when we then go to the user details of a user from "fed_b" all the mapped attributes are also readonly, which is not expected.
Also, when we then try to add a new user via the admin ui, the mapped attributes are not even displayed and can not be added.
So no user can be added in this state as the username and email fields are also missing.
![image](https://github.com/keycloak/keycloak/assets/91532004/cd649030-5112-4cc9-b7f1-89642568782c)

Additionally, when we try to add a user via the admin API, the mapped attributes such as email are not set on the user.
These issues only seem to appear if we first go to the edit view of a user from "fed_a".

All these issues do not appear if we change  the edit mode in "fed_a" to WRITABLE or UNSYNCED.

### Version

24.0.5, 25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The user attributes of users that are not imported from the user federation "fed_a" should all be editable at all times.
The add user view in the admin ui should not be affected by the edit mode setting in "fed_a".
The create user request in the admin API should not be affected by the edit mode setting in "fed_a".

### Actual behavior

If we go to the edit view of a user which was imported from "fed_a" in the admin ui the mapped attributes username, email, first name, last name... are all readonly (which is expected).
However, when we then go to the user details of a user from "fed_b" all the mapped attributes are also readonly, which is not expected.
Also, when we then try to add a new user via the admin ui, the mapped attributes are not even displayed and can not be added.
So no user can be added in this state as the username and email fields are also missing.
Additionally, when we try to add a user via the admin API, the mapped attributes such as email are not set on the user.
These issues only seem to appear if we first go to the edit view of a user from "fed_a".

### How to Reproduce?

1. Configure two user federations and set one of them to edit mode: READ_ONLY "fed_a"
2. Go to user list and then to user details of a user which was imported from "fed_a"
3. Go to the user details of a user which was not imported from "fed_a"
4. Go to add user in admin UI.
5. Try to add a new keycloak user via admin API

**Comment by bahag-kotarlicb** [comment]
We have this exact issue with 24.0.5 and were able to reproduce it with the new version 25.0.0.
In addidtion to steps described above we also tried a slight variation of it to meet our use case.

We have two active directories (Edit mode: read only) and one custom provider module.
When we open user details of one of the users from an read-only active directory then all user attributes from all users switch to read only.

**Our workaround**
We switched the two active directories to "Edit mode: unsynced"

**Comment by wornr** [comment]
I can only confirm that in 25.0.1 issue is still there. I have connected Keycloak to only one Active Directory with read-only mode. Whenever I open details screen of the federated user, I can no longer create non-federated users nor modify them.
Workaround proposed by @bahag-kotarlicb helps to overcome this issue.

**Comment by jonkoops** [comment]
Thanks for confirming the issue is still present in the latest release @wornr

**Comment by edewit** [comment]
Do you have any errors in the console of the browser, or in the server log?

**Comment by wornr** [comment]
Unfortunately, no errors in the browser or server are logged.

**Comment by agagancarczyk** [comment]
@bk-js @wornr I'm not able to reproduce it. I used this ldap_federation.json config, first with LDAP's edit mode set to READ_ONLY and then set to WRITABLE. Everything is working as expected.

Could you modify the attached .json with your configurations so that I can simply import it during new realm creation and reproduce the issues reported? Otherwise, it's simply not possible to reproduce.

[ldap_federation.json](https://github.com/user-attachments/files/16085129/ldap_federation.json)

**Comment by wornr** [comment]
I tried to reproduce the issue with the configuration you have provided with no luck either. @bk-js @bahag-kotarlicb and myself are using Active Directory, so I bet it has something to do with it. Unfortunately, I cannot provide you with configuration to reproduce the issue.

**Comment by jpeek-egbc** [comment]
I can also reproduce this when there is an Active Directory connected in User Federation. The way we can reproduce it 100% is merely viewing an Active Directory user in Keycloak, where it'll show the attributes as read-only, and then all other users, regardless of where they come from (i.e. non-AD users) attributes are read-only and the API calls can no longer be made to update them.

**Comment by wornr** [comment]
I'm pretty sure it's not really a UI problem, because I'm not even able to edit custom user attribute of the non-federated user through an API when AD is in READ_ONLY mode.

Here are the steps:
1. Create custom attribute in Realm settings -> User profile -> Attributes.
2. Create user in Keycloak (let's call him j.doe).
3. Configure AD connection in READ_ONLY mode with enabled import -> users are imported to Keycloak.
4. Enter edit screen j.doe and put some value to custom attribute -> **possible** (also possible through `PUT /admin/realms/{realm}/users/{user-id}`)
5. Enter edit screen of user imported from AD -> **not possible** to edit any attribue (also not possible through `PUT /admin/realms/{realm}/users/{user-id}`); btw, here I would assume the custom attribute to be editable, but it's not.
6. Repeat step 4 -> **no longer possible to edit attribute even through API**
7. Switch AD READ_ONLY mode to UNSYNCED and repeat step 4. -> **possible again also through API**

**Comment by exaV** [comment]
We have exactly the same issue here. When Keycloak starts everything is fine until you look at a federated user for the first time and from that point on all users are in read-only mode. The problem temporarily goes away when Keycloak is restarted or when another replica is used.
