### ISSUE TITLE
Missing Id in (Resource|Policy|Scope)Representation of authorization is causing problems in keycloak-config-cli

### ISSUE THREAD

**Issue by bohmber** [keycloak/keycloak#30519]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/api

### Describe the bug

Since the Respresentation no longer contains the id, the keycloak-config-cli tool can not process authorizations of clients

### Version

25.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

Resources should have an Id

### Actual behavior

There is no id in the Resources

### How to Reproduce?

https://github.com/adorsys/keycloak-config-cli/pull/1052

### Anything else?

https://github.com/adorsys/keycloak-config-cli/pull/1052

**Comment by jonasvoelcker** [comment]
Hi @ahus1, @sguilhen & @pedroigor,

we've found out that the changes in this PR (https://github.com/keycloak/keycloak/pull/28317) lead to a problem in our config tool. In my opinion the problem is not that the IDs are no longer available but in combination with the missing accessor for the ResourceResource we can't operate on those entries any longer.

Are there other ways to get the ResourceResource at hand without using the ID?

This topic is quite urgent as it hinders everybody using the keycloak-config-cli from upgrading to Keycloak 25 😉

Best Regards
Jonas

**Comment by bohmber** [comment]
Might be caused by keycloak-config-cli is calling exportSettings instead of calling getSettings on AuthorizationResource. For an export the ids are not important. Will ask this question in keycloak-config-cli

**Comment by jonasvoelcker** [comment]
Hi @bohmber, I've checked different things and the getSettings does not even contain the resources, policies and scopes, we need to work upon.

**Comment by bohmber** [comment]
Oh, I can see. Thanks

**Comment by jonasvoelcker** [comment]
@bohmber I've found a way to search the desired resources by name: https://github.com/adorsys/keycloak-config-cli/pull/1052

In my opinion this issue can be closed due to that solution.

**Comment by bohmber** [comment]
I had a similar idea. Thanks
