### ISSUE TITLE
Infinite loader on the admin console for non-admin users

### ISSUE THREAD

**Issue by graziang** [keycloak/keycloak#30683]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When a non-admin user tries to access the admin console, after logging in, they end up on a page with an infinite loader.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

The admin console should display an error message after login.

### Actual behavior

The admin console shows an infinite loader after login.

### How to Reproduce?

Create a user without roles on the real `master` and log in to the admin console.

**Comment by hmlnarik** [comment]
Caused by #27783 (specifically [this condition](https://github.com/keycloak/keycloak/pull/27783/files#diff-446b1858b1873dc49e5b94a3ea5b9ed603569a469c7418c5ed58ca7ccff65de0R24-R26))

The issue #27840 that fix is for also shows that if the initial state of the serverinfo is set to `{}`, there is a race condition.

**Comment by graziang** [comment]
@hmlnarik, Could we create a backport for this one? it's requested by support
