### ISSUE TITLE
Version 22.0.4 of the component_config table contains insecure private keys, secrets, certificates, and other information

### ISSUE THREAD

**Issue by yuhong-zhang** [keycloak/keycloak#30846]
### Description

Dear developer:
         Hello! In the database table, component_config found private keys, secrets, certificates, and other information that were not encrypted, which may pose a security risk. What should be done to address such security issues?

### Discussion

Enhanced login password security

### Motivation

There are safety hazards present

### Details

Hello! In the database table, component_config found private keys, secrets, certificates, and other information that were not encrypted, which may pose a security risk. What should be done to address such security issues?
![image](https://github.com/keycloak/keycloak/assets/71396064/be61dbc5-1983-4a8f-9518-3d358504d2d0)

**Comment by rmartinc** [comment]
Hi @yuhong-zhang ,

Just a kind remind that issues like this one, which can be security related, should be reported in a different way not in a public github issue. Please check the [security policy](https://github.com/keycloak/keycloak/security/policy#reporting-a-suspected-vulnerability). But no problem, because this is a known limitation in keycloak.

Those fields are mainly the realm keys defined for the different realms of the server. The default key providers (`<type>-generated`) store the keys inside the database and that's why people use the [java keystore](https://www.keycloak.org/docs/24.0.0/server_admin/#loading-keys-from-a-java-keystore) to externalize it. But I have just realized that the java-keystore key provider does not support a vault for the passwords. It also needs to support all types of keys (hmac, aes,...). So I'm going to close this issue and file an enhancement to extend the JavaKeystoreKeyProvider with other keys and vault support.

**Comment by rmartinc** [comment]
Related issues to achieve all ralm keys not in database:

* https://github.com/keycloak/keycloak/issues/29755
* https://github.com/keycloak/keycloak/issues/30880

Closing this one as it's a known limitation now in keycloak.
