### ISSUE TITLE
admin Login denied after upgrade to keycloak 25.0.1

### ISSUE THREAD

**Issue by sw506** [keycloak/keycloak#31035]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

Login as "admin" user not successful after upgrade.

`Jul 03 18:18:55 keycloak-a kc.sh[700]: 2024-07-03 18:18:55,430 WARN  [org.keycloak.events] (executor-thread-11) type="LOGIN_ERROR", realmId="master", clientId="security-admin-console", userId="<redacted>", ipAddress="172.x.x.x", error="invalid_user_credentials", auth_method="openid-connect", redirect_uri="https://signon.example.org/admin/master/console/", code_id="c45213ed-ecfb-41bb-b57a-3fb2ab12f407", username="admin"`

One can observe that in the database the pbkdf2-sha256 hash has changed to argon2 one after the first try, so the password seems to be correct

Password is only alphanumeric and has a length of 12 characters

### Version

25.0.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Login successfull to admin console

### Actual behavior

Login not successfull

### How to Reproduce?

upgrade from 24-25

### Anything else?

can give user / credential row if neccessary

**Comment by Tushar-kalsi** [comment]
only credential keycloak is accepting is : 

username: admin
password : admin

**Comment by sw506** [comment]
for me not unfortenately :(

**Comment by sw506** [comment]
> only credential keycloak is accepting is :
> 
> username: admin password : admin

for me that doesn't work

**Comment by kioskOG** [comment]
i'm using keycloak (quay.io/keycloak/keycloak:25.0.1) for apicurio-registry-sql auth/authz. once i provide the creds for apicurio ui/artifacts path, it starts loading in a loop & throw 502.

<img width="1507" alt="image" src="https://github.com/keycloak/keycloak/assets/31181135/9363fc83-082a-4ee0-aa20-46fbd6a74709">

**Comment by rmartinc** [comment]
Hi!

We test the upgrade in the CI. So we need more details of what it's happening here because there should be something more in your installation. If this issue was just for the upgrade we would have tons of complaints right now. I have done a simple upgrade with a realm with two admin users and they can login without issues after the upgrade from 24.0.5 to 25.0.1. I see the password changes OK from pbkdf2-sha512 to argon2 after the administrator login.

So we need more information. Is there anything meaningful in the log if you setup trace level? Can you make a fresh 24 install fail after the upgrade in such a way we can reproduce the issue?

**Comment by sw506** [comment]
@rmartinc After trying to reproduce the bug and upgrading keycloak again it works
