### ISSUE TITLE
Can't update the user where  userName contains uppercase letters

### ISSUE THREAD

**Issue by shankaryadavy9** [keycloak/keycloak#31240]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

My user federation was working without no issue till KC 23.  As soon as I updated to KC 24 , not able to update attributes . I noticed it happens only where username are in uppercase like NYM105276.  I can see If i click on record ,usernames are converting in small case like nym105276 and if I add any attributes , it fails . 
![image](https://github.com/user-attachments/assets/91504b6a-09e2-49d7-bc09-5afd6709f21e)

 This is happens with api and admin console both. 

### Version

24, 25,25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Should be able to add attributes.

### Actual behavior

Fails with error .

### How to Reproduce?

Use any   user federation example and try to update user(which has userName in uppercase )  attributes.

**Comment by vramik** [comment]
@shankaryadavy9 thank you for the report, I believe your issue might be caused by the fact that the user profile feature was switched on by default. I might want to learn about Managed and Unmanaged attributed and the user profile: https://www.keycloak.org/docs/latest/server_admin/index.html#user-profile and update the setting to allow editing username.

**Comment by shankaryadavy9** [comment]
Thanks @vramik  for quick reply.  I understand profile feature and I have enabled it as I required to update some attributes.  But the problem is username  going to wrong format(from uppercase to lowercase) while updating attributes.  I see no problem with users who have completely small case or numeric usernames.   See below picture. 
![image](https://github.com/user-attachments/assets/6c845784-d066-4e86-bbf6-2fe7b185c925)

![image](https://github.com/user-attachments/assets/c1914546-0642-4766-b791-a43b6ad044ac)
![image](https://github.com/user-attachments/assets/70b2f9e9-d870-43c9-aea1-45f9759f561a)
![image](https://github.com/user-attachments/assets/d9eb3bdc-ef22-4c4b-88b2-26dd48f267c3)

Request you to reopen the issue please .  I guess its not honoring userName format coming for **User Federation**.  I remember same case happened while migrating user from IDP and    @pedroigor    made the code .  Let me know if more details has to sent.

**Comment by pedroigor** [comment]
@shankaryadavy9 The issue is a bit different than the IDP because there we store the "original" username. For Keycloak, usernames are always in lowercase.

From a technical perspective, isn't better to keep your usernames in lowercase?

**Comment by shankaryadavy9** [comment]
@pedroigor  thanks for the response.  Please see my  table `federated_user` I am running KC 23.0.7 currently

![image](https://github.com/user-attachments/assets/d33d7b9d-c410-441e-ae6c-89a89575766e)

- My federation service store in that format only and KC has been storing in that format only since beginning.
- All downstream services that calls KC for user details, also storing in that format only.

So I am sure KC did not store in lower case.  Please suggest what is best way.

**Comment by pedroigor** [comment]
@shankaryadavy9 That is the `ID` which have the username in it. I'm more curious if it is not better for you to use lowercase usernames as they won't suffer from things like different users with the same chars/digits but with different casing.

As per the problem, I think what is happening is that user profile will always format the username to lower-case. That is because the `username` of users in KC (not IDs) is always in lower case.

But here we are talking about federated users and we did not have this specific behavior, to respect the username format from external identity stores, covered or explicit in our code. I'm also curious why others have not complained about it yet, if I'm not missing any other similar issue in our backlog.

I'll take a look and come back with more details.

**Comment by pedroigor** [comment]
@shankaryadavy9 Can you please try out https://github.com/keycloak/keycloak/pull/31631?

**Comment by shankaryadavy9** [comment]
Hi @pedroigor , took me some time to run your changes.  Sadly you changes does solve my problem!  

If my usernames are coming in uppercase from federation i am not able to edit attributes or update the user. It throws the same  error like `{
    "field": "username",
    "errorMessage": "error-user-attribute-read-only",
    "params": [
        "username"
    ]
}`

As I said earlier if  usernames are coming in lower case from federation all are working fine.
Note:-
Admin UI still converting userName in lowercase while updating , but I tried intercepting the request and convert userName to Uppercase as per my federated username but still no luck.

**Comment by pedroigor** [comment]
@shankaryadavy9 Are you able to provide then with a reproducer? I don't know what I'm missing because the changes are basically trying to replicate a scenario where you have a user storage other than the local database (e.g.: LDAP) where users there have their usernames mapped to an attribute where the value is in upper-case.

**Comment by pedroigor** [comment]
@shankaryadavy9 I found the problem. I'm not considering the ID format for federated users.

**Comment by pedroigor** [comment]
@shankaryadavy9 I've updated the PR it should work now when using a external storage other the built-in ones like LDAP.

**Comment by shankaryadavy9** [comment]
You are too fast @pedroigor!   I was just working on your ask and you figured out :)
Damn its working like a charm , thank you for saving me!  

Last question will it be backported to KC24 ?

**Comment by pedroigor** [comment]
I'm considering backporting it (even though did not set the labels) to 24 and 25.

**Comment by amelie1842** [comment]
Hello, 
Thank you so much for the fix!
We have indeed the exact same issue on Keycloak 24 (impossible to update attributes when LDAP username has uppercase), which is very blocking for our production usage. Will the fix be available in a new version 24.0.6?
