### ISSUE TITLE
Token remains active even after session is timed out

### ISSUE THREAD

**Issue by pyaracetamol-650mg** [keycloak/keycloak#31374]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

when a token is set for 2hrs. it should expire if the session is terminated, but the access token keeps on active for 2hrs.
which can be accessed by other applications like Postman

### Version

25

### Regression

- [ ] The issue is a regression

### Expected behavior

the token should expire

### Actual behavior

the token is not expiring

### How to Reproduce?

set a time for access token, login into the application, copy the user token and terminate the session.
go to postman and make a call using the same token.

**Comment by rmartinc** [comment]
Hi @pyaracetamol-650mg!

When you say `go to postman and make a call using the same token`. Where are you sending the token with postman? What application is receiving it? How the application is validating the token?

The idea is the access token is short-lived (5 minutes by default) and knowing if it's still valid depends how the applications manage the token. If the application calls the server for introspection or user-info or any other endpoint the token will be detected as invalid (because there is no session attached to it). But if the application just validates signatures, expiration, issuer and other local things, but does not perform a call to the keycloak server, the token is valid for the app.

**Comment by pyaracetamol-650mg** [comment]
HI, we're using refresh token, but while validating the the refresh token in our AWS Lambda logs, getting this error:

2024-08-05T13:40:30.732+05:30
[ERROR]	2024-08-05T08:10:30.732Z	<request_id>	Error when trying to decode the received token
Exception: bad_signature: 

[ERROR] 2024-08-05T08:10:30.732Z <request_id> Error when trying to decode the received token Exception: bad_signature:
2024-08-05T13:40:31.296+05:30
RequestId: <request_id> Error: Runtime exited with error: exit status 1
Runtime.ExitError

RequestId: <request_id> Error: Runtime exited with error: exit status 1 Runtime.ExitError

**Comment by pyaracetamol-650mg** [comment]
please refer this ticket for reposnse - https://github.com/keycloak/keycloak/issues/31895
