### ISSUE TITLE
RESTART_AUTHENTICATION_ERROR when login in on an ios device

### ISSUE THREAD

**Issue by xdubx** [keycloak/keycloak#31457]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

User cannot log in on an ios phone
![image](https://github.com/user-attachments/assets/aa7fce9e-3e7b-4e73-82eb-cf43a20e1ffa)
![image](https://github.com/user-attachments/assets/b792ca2a-5f3c-45f8-b537-0413a56d5c5f)
![image](https://github.com/user-attachments/assets/7cbfc8d0-4a30-473f-b3a9-26757c3a0680)

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should be logged in.

i pached up from v16 to v25.

### Actual behavior

User get an error message

### How to Reproduce?

Use an IPhone with the current OS. Try to login 

### Anything else?

maybe as hint but its fixed now. https://github.com/keycloak/keycloak/issues/30334

**Comment by xdubx** [comment]
I testet to replicate the problem on v24. And it's not there. 
Mentioned in the patch notes the SameSite tag can be problematic. But i don't have the posibiliy to change the settings? I only found the legacy flag that disables the samesite thing. 

Downgrade currently don't work as expected. Import/export throws errors. After some editing in the exported realm file the import works. But the user passwords doesn't. 

Now at this point i does not know how to deal with the problem. I will try again to import the user with the working passwords. But i hope that someone can help me sap.

**Comment by xdubx** [comment]
thx for the feedback. i think its an problem on the plugin provider side from nextcloud. It seems to be an cookie detection problem or an implementation fault. I can only reproduce this in this environment ( keycloak with nextcloud social-login plugin) all other apps seems to be working.

**Comment by iquiw** [comment]
@jonkoops 
Safari on iOS seems not to support `beforeunload` event.
Ref. [Handling Events](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW5), [javascript - window.onbeforeunload not working on the iPad? - Stack Overflow](https://stackoverflow.com/questions/3239834/window-onbeforeunload-not-working-on-the-ipad)

So the #30334 fix is likely not to work with Safari on iOS.

Since the interval of the timer in `authChecker.js` is 2 seconds, the problem does not always happen, but only in some timing.
I have faced this issue on some (not open) application on iPadOS 17.6.
I will check your https://github.com/jonkoops/kjs-playground and open new issue if the problem is reproducible.

**Comment by jonkoops** [comment]
Sound good, timing issues like these are notoriously had to reproduce, so feel free to mess with the timing to trigger it more aggressively. It's weird that support is limited, as Can I Use reports it as [fully supported](https://caniuse.com/mdn-api_beforeunloadevent). We might follow the recommendation outlined in the docs instead:

> The `load` and `unload` events may not work as expected for back and forward optimization. Use the `pageshow` and `pagehide` events instead

**Comment by iquiw** [comment]
Thank you for the feedback!
I will follow your suggestion about timing.

As for the possible fix, I suppose `pagehide` is an alternative to `beforeunload` on iOS. But I am not perfectly sure as I am not an expert in this area...

**Comment by jonkoops** [comment]
Seems like `pagehide` is [not flawless](https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event#usage_notes) here either.

**Comment by tiago-bortoluzzi** [comment]
Any news on this? I have been facing the same issue... I am using Keycloak 25.0.2 as MindSphere/InsightsHub IdP. Login flow is perfect on Desktop and Android, but fails with this error on iPhone (Safari, Chrome). I have tried changing beforeunload to pagehide on theme authChecker.js without success.

**Comment by iquiw** [comment]
No news from me. I was slow to setup the reproducible envirnoment.
But since others have the same problem (#33071), I think the above is not so important.

I have no idea how to fix this if `pagehide` does not work, though...

**Comment by JoaoTeixeira20** [comment]
Hi, the way i used to workaround this issue on **google** SSO provider on iOS was setting **prompt** as "select_account" on identity providers -> google identity provider -> prompt.

What this does is instead of immediately redirect back to the callback url provided of your app (if you already logged in on the app previously), it will prompt you to select an account, this will avoid the race condition of the event handlers occuring that is not friendly with iOS.

This solution relies on each provider to ask for an additional step before redirecting back to your app, while it's not ideal and not the solution, it works well and avoids tinkering on keycloak implementation.
