### ISSUE TITLE
Support lightweight access tokens for Admin REST API

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#31513]
### Description

With many realms access tokens for the master realm becomes very large. In addition when creating a new realm, the new realms roles will not be in the token, requiring getting a new token after the realm is created.

For `admin-cli` and `security-admin-console` there is a work-around for the above, where instead of checking roles in the token for these clients the [user and client scope is checked directly](https://github.com/keycloak/keycloak/blob/21d00704ae2190bb4fac03fdd2a25a99bcd850cd/services/src/main/java/org/keycloak/services/resources/admin/permissions/MgmtPermissions.java#L102). However, this solution only applies to those clients, and is not available to other applications.

A proper solution to this issue would be to support lightweight access tokens (where the roles are not added to the token) when invoking the Admin REST APIs. This should be done by introspecting the token, to get the effective roles for a given token (including considering any scopes).

It would also be important to check the audience when using lightweight access tokens, to make sure the token is indeed intended to be used to invoke the Admin REST APIs.

An additional nice to do as part of this would be to remove the current work-around for `admin-cli` and `security-admin-console`, and instead use lightweight access tokens.

**Comment by graziang** [comment]
Roles are not added to tokens for the `admin-cli` and `security-admin-console` clients because *Full Scope Allowed* is disabled by default, and no roles are assigned to the dedicated scope.

For these two clients, there is a workaround that directly checks if the user in the token has a role assigned without looking at the roles in the token (since there are none) and without evaluating scopes.

To introduce support for lightweight access tokens for the admin REST API, one possible solution could be to check for the presence of the `sub` claim in the token. If the claim is missing, perform a token introspection, check the audience, and continue the evaluation by constructing the `KeycloakIdentity` based on the introspection result.

This is the general approach, but what should we do to eliminate the workaround for the `admin-cli` and `security-admin-console` clients?

To use lightweight access tokens on the admin API, you need to enable lightweight access token for the client via "Always use lightweight access token" or via client policy and also enable *Full Scope Allowed* (otherwise, roles would not be resolved through introspection) on the `admin-cli` and `security-admin-console` clients, with some migration effort.

Could there be issues if there are thousands of realms? Should we maintain the workaround for these two clients?

One idea could be to optimize role resolution for lightweight access tokens by restricting role resolution to only the realm being invoked by the API. For example, when calling `/admin/realms/test/clients`, only the roles of the `test-realm` client would be evaluated. @mposolda @stianst

**Comment by mposolda** [comment]
@graziang IMO it will be good to figure some approach, which will allow to use lightweight access tokens and:

- Everything works from the functionality perspective

- Performance is acceptable when there are huge number of realms (hundreds of realms) for lightweight access tokens

- Removing workaround for the `admin-cli` and `security-admin-console` will be good bonus point, but not a blocker IMO

I think the approach you mentioned in your last paragrap (restricting role resolution to only the realm being invoked by the API) may be a way to go. Maybe we don't need to perform full introspection, but make sure that same logic is used for evaluating "effective roles" to be used.

Just a note that there are some endpoints, which are not specific to any concrete realm - like "Create realm" endpoint, which requires role `create-realm` of the `master` realm. Or AFAIK server info endpoint. So something may need to be figured for those endpoints as well.

IMO it is fine if we update the `security-admin-console` and `admin-cli` clients to use `Always use lightweight access tokens` and enable `Full scope allowed`. This can make sure that their tokens look same as before and functionality will be also OK. In that case, the workaround for those clients may not be needed if I understand correctly, but maybe I am missing some corner cases?

As we discussed, you can use [keycloak benchmark](https://github.com/keycloak/keycloak-benchmark) to add many realms to the DB and then compare the performance before/after your changes. Ideal is, if the performance is better after your changes :-) Or at least similar, but not significantly worse... You can probably test the performance manually by invoking admin console before/after your changes (which will effectively test the `security-admin-console` client with `lightweight access token`).
