### ISSUE TITLE
The console takes a very long time to display group members with LDAP provider

### ISSUE THREAD

**Issue by hokuda** [keycloak/keycloak#31786]
### Description

IHAC who has a lot of users and groups in LDAP and wants to sync Keycloak users/groups with LDAP federation provider.
A group has hundreds of members, and the LDAP federation provider has tens of user-attribute-ldap-mappers.
In this case, the Keycloak console takes so long time to display group members in Manager>Groups>group>Members tab.
I observed that thousands of deletes and inserts to the DB tables are performed (uncecessarily?) then, and they might be the casue.
This has a large impact on the usability of the solution for the customer.
Are there any workarounds?
If no workaround, is it feasible to change the behavior not to perform deletes and inserts?

**Comment by hokuda** [comment]
how to reproduce

1. download and untar reproducer.tar.gz
2. cd reproducer
3. ./start-example-ds.sh
4. ./reset_entries.sh
5. start keycloak24
6. import testrealm1.json
7. Sync all users in the ldap provider
8. Sync LDAP groups to Keycloak in the group-ldap-mapper-1
9. go to Groups>group0000
10. go to Members tab
[reproducer.tar.gz](https://github.com/user-attachments/files/16437422/reproducer.tar.gz)

**Comment by rmartinc** [comment]
The listing of group members is never going to be super fast in LDAP. This is only used for the admin console. I think that no final user use-case needs to list members of a group. Nevertheless probably we can do something to make it more performant. At first look I see the following ideas:

1. The console is not passing the `briefRepresentation=true` to the members endpoint. This means the user is returning in full when the listing just needs the common attributes. This is an easy point to implement.
2. As @hokuda commented the users are imported in the database because they are read again. Everything is updated, mappers included. Maybe we can avoid this and re-use the user if it's already in the database (not updating the user). We can pass another parameter to the import method to specify re-import is not needed. Don't know how easy or complicated this point could be.
3. The console is showing for each user all the groups the user belongs to (column membership). This makes the console call the `members` group endpoint and then iterate the results to call the `groups`user endpoint for each row. Is the second call really necessary? The admin can click the user to get all the user details (groups tab among them). This is a change in behavior in the console.

This is a enhancement and it's properly assigned.

**Comment by Anderen2** [comment]
> The listing of group members is never going to be super fast in LDAP. 

Why is this? A similar search done directly to the LDAP returns the data fast. 

> This is only used for the admin console. I think that no final user use-case needs to list members of a group.

I disagree. Both listing members of a group, and groups of a member are common usecases when administrating users in a IAM platform. 
This is also already a supported use-case by Keycloak. As users of the Admin UI have no way of knowing that going to `/admin/master/console/#/<realm>/groups/<groupid>` is slow while `/admin/master/console/#/<realm>/users/<userid>/groups` is fast, we keep getting complaints about that the interface is unbearably slow, without any way for us to fix it. 

We've provided ample resources to both the LDAP hosts, the Postgresql servers and the Keycloak app servers, with no effect. The overall load on the systems are borderline idle, which indicates to me that this likely is a issue with a single-threaded code-path used within Keycloak.

**Comment by rmartinc** [comment]
bq. Why is this? A similar search done directly to the LDAP returns the data fast.

Because you need to search the group in the ldap. Get the merbers (which are DN). Search each DN to check if it's a user and it's managed by the provider. Return the list. So it's not one search is N+1 search (being N the number of users in the group).

Regarding the second paragraph you are answering yourself. This use-case is only for administrators, not for final users, which is what I'm saying.

Anyway, we will try to improve the performance. If anyone is interested they can try the points I have commented before.

**Comment by Anderen2** [comment]
> Because you need to search the group in the ldap. Get the merbers (which are DN). Search each DN to check if it's a user and it's managed by the provider. Return the list. So it's not one search is N+1 search (being N the number of users in the group).

Then a fourth improvement suggestion (if possible, I'm not too familiar with the codebase here) could be to first gather the list of DN's from LDAP and fetch them from the SQL in bulk. Eg.
- First perform a ldap-search for the group with member attributes. This returns a list of DN's which are members of the group. 
- Then construct a database query for retrieving all the users via the DN's using the same federation link.

However, the three potential solutions you highlighted earlier are likely a better way forward to start. 

> Regarding the second paragraph you are answering yourself. This use-case is only for administrators, not for final users, which is what I'm saying.

I believe discussing this is nonconstructive, as this depends on whom you consider the final user. For us the final users of Keycloak are the ones using the administrative UI. All access evaluation for endusers are done via LDAP only, without going through Keycloak. 

In addition, regardless of whom the final user is within the solution, the administrative interface is a crucial feature of Keycloak, and should be responsive.

**Comment by rmartinc** [comment]
I have quickly implemented the three commented points in this branch: https://github.com/rmartinc/keycloak/tree/issue-31786. I create two commits just in case UI guys don't want to remove the `membership` column. But I would do it as it makes no sense to do what it's doing now.

@Anderen2 Can you please test in your environment? I tested with a local apacheds with a group with 500 members. I see an improvement but it was not so bad even with default version 25.0.4. So better if you test it.

I cannot work on this in the next days so I'm not taking the issue just in case anyone want to jump in. If not, I will continue when I'm available again.

@pedroigor FYI, if it works just take my branch and send a PR. If you need to perform change feel free to do it.

**Comment by rmartinc** [comment]
@Anderen2 Have you tested my branch? Do you see any improvement?

**Comment by sguilhen** [comment]
@rmartinc I've tested your fixes with the reproducer attached here and the members are loaded considerably faster with your changes. I'm opening a PR so we can get the reviews, specially from the UI team given that we're changing the member of thing (which makes total sense to me to be doing)
