### ISSUE TITLE
Hi @rmartinc

### ISSUE THREAD

**Issue by pyaracetamol-650mg** [keycloak/keycloak#31895]
When you say `go to postman and make a call using the same token`. Where are you sending the token with postman? What application is receiving it? How the application is validating the token?

The idea is the access token is short-lived (5 minutes by default) and knowing if it's still valid depends how the applications manage the token. If the application calls the server for introspection or user-info or any other endpoint the token will be detected as invalid (because there is no session attached to it). But if the application just validates signatures, expiration, issuer and other local things, but does not perform a call to the keycloak server, the token is valid for the app.

_Originally posted by @rmartinc in https://github.com/keycloak/keycloak/issues/31374#issuecomment-2236385035_

please find the response
            Where are you sending the token with postman? - we're just trying to validate the same exact token for which the session is terminated.
             What application is receiving it? - AWS Lambda running in python which is using JWt to decode and validate the token, which is still in use after the session is terminated.

 How the application is validating the token? - 
![image](https://user-images.githubusercontent.com/175820056/355040533-69dd29e5-f14e-4376-80e0-921de12469b3.png)

**Comment by codespearhead** [comment]
> when a token is set for 2hrs. it should expire if the session is terminated, but the access token keeps on active for 2hrs

Unless you're adding extra layers to your authentication flow, there shouldn't be any sessions at all because OAuth 2.1 is sessionless. This suggests that you might be using the [wrong OAuth flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/which-oauth-2-0-flow-should-i-use) for your use case, which could lead to security breaches.

However, if it's a third-party software which security is not of your concern, then tou can resort to Keycloak's OIDC backchannel logout at [/realms/{realm-name}/protocol/openid-connect/logout](https://www.keycloak.org/docs/latest/server_admin/#backchannel-logout).

**Comment by jonkoops** [comment]
Closing this as it did not go through the regular issue template, if this problem persists please use our regular issue reporting worklow.
