### ISSUE TITLE
Remember Me with External Infinispan is not works properly

### ISSUE THREAD

**Issue by necipakca** [keycloak/keycloak#32100]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

We are using v23.0.7 with external infinispan v14.0.21

**SSO Session Idle Remember Me**  value does not respect set value from UI.

When I check the core I found [this](https://github.com/keycloak/keycloak/blob/e13c9bf46297303b1457ef07bbcab378e502f3c7/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java#L86) line of code.

Because of that  it sets session cache **maxidletimeseconds** value to **SSO Session Max + 30 min**

**UI Values :**

```
SSO Session Idle : 5 min
SSO Session Max : -29 min (minus)
SSO Session Idle Remember Me : 30 min
SSO Session Max Remember Me : 60 min
```

and the related session cache entry is :

```
{
  "cache-control" : [ "max-age=59" ],
  "cluster-backup-owners" : [ "infinispan-central-keycloak-1-26300" ],
  "cluster-node-name" : [ "infinispan-central-keycloak-0-47692" ],
  "cluster-primary-owner" : [ "infinispan-central-keycloak-2-32175" ],
  "cluster-server-address" : [ "[10.233.88.151:7800]" ],
  "content-length" : [ "0" ],
  "content-type" : [ "application/x-jboss-marshalling" ],
  "created" : [ "1723563920995" ],
  "etag" : [ "1512539968" ],
  "expires" : [ "Tue, 13 Aug 2024 15:47:35 GMT" ],
  "last-modified" : [ "Tue, 13 Aug 2024 15:45:20 GMT" ],
  "lastused" : [ "1723563995737" ],
  "maxidletimeseconds" : [ "60" ],
  "timetoliveseconds" : [ "35999" ]
}
```

Because of hard coded value of :

This line `context.maxIdleTimeLoader.getMaxIdleTimeMs(realm)` somehow returns the **SSO Session Max** not idle time.

`final long maxIdleTimeMs = loadedMaxIdleTimeMs + 1800000;`

maxidletimeseconds is 60 sec. And that is understandable.

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

maxidletimeseconds should get its value from **SSO Session Idle Remember Me** when I set it

### Actual behavior

It gets from hard coded value

### How to Reproduce?

Explained

**Comment by mhajas** [comment]
Thanks for the report @necipakca. 

I think I understand the report and I identified two issues on this line: https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/InfinispanUserSessionProviderFactory.java#L322
1. We are returning `getSsoSessionMaxLifespan` instead of `getSsoSessionIdleTimeout` even though we later use the method for [setting maxIdle](https://github.com/keycloak/keycloak/blob/main/model/infinispan/src/main/java/org/keycloak/models/sessions/infinispan/remotestore/RemoteCacheInvoker.java#L83) 
2. The method does not take into account the remember me flag. We would need to add another parameter to the method and based on this we should decide whether to call `...RememeberMe` method or regular.

Note 1. is relevant for user and client session caches and 2. is relevant for all four user/client+online/offline session caches.

One thing that caught my attention was the negative `SSO Session Max` set to -29. Is it just for the purposes of this report or you are using it in your deployment?


Since remote stores as used in this report are soon to be deprecated https://github.com/keycloak/keycloak/issues/32577 (in Keycloak 26) I tend to close this issue as not planned or mark it low-priority/help-wanted. Please let me know whether I understand your report correctly or if I missed something.

**Comment by ahus1** [comment]
I agree the persistent user sessions should be preferred here. Still for older release this might be worth a fix as the change might be rather small. I'm creating a PR.

**Comment by necipakca** [comment]
> caught

@mhajas I believe your findings are correct. I set a negative value to ensure it retrieves the value from 'SSO Session Max.' It was only for testing purposes.

**Comment by necipakca** [comment]
> One thing that caught my attention was the negative `SSO Session Max` set to -29. Is it just for the purposes of this report or you are using it in your deployment?
> 
> Since remote stores as used in this report are soon to be deprecated #32577 (in favor of [Persistent user sessions](https://github.com/keycloak/keycloak/discussions/28271)) I tend to close this issue as not planned or mark it low-priority/help-wanted. Please let me know whether I understand your report correctly or if I missed something.

I believe your findings are correct. I set a negative value to ensure it retrieves the value from 'SSO Session Max.' It was only for testing purposes.
