### ISSUE TITLE
Key not found error during bearer token validation in master realm

### ISSUE THREAD

**Issue by Anarktos** [keycloak/keycloak#32145]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

When attempting to authenticate a bearer token using AppAuthManager.BearerTokenAuthenticator(session).authenticate(), a "Failed to verify identity token: Key not found" error occurs specifically within the master realm.

Debugging revealed that the root cause is an incomplete key set returned by session.keys().getKeysStream(session.getContext().getRealm()). This results in the absence of the necessary key with the correct kid for bearer token validation.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The expected behavior is that the bearer token validation should be performed using AppAuthManager.BearerTokenAuthenticator, even when the session is started from the master realm. Additionally, the method session.keys().getKeysStream(realm) is expected to return all keys belonging to the master realm.

### Actual behavior

The bearer token validation is not working when the session's realm is the master realm because the method session.keys().getKeysStream(session.getContext().getRealm()) is not returning all the keys belonging to that realm.

### How to Reproduce?

1. Create a session from the master realm using the admin-cli client (this problem occurs with every client of the master realm).
2. Make a request to trigger a method that uses AppAuthManager.BearerTokenAuthenticator(session) with that session.
3. Validate the keys returned by the session.keys().getKeysStream(session.getContext().getRealm()) method.
4. Validate the kid contained in the bearer token.
5. Enter the master realm, go to realm settings, and then keys. The list shows all the keys, including the key that contains the kid in the JWT token, but this key is not returned by the getKeysStream method in step 3.

**Comment by rmartinc** [comment]
@Anarktos The `keys` endpoint that the console is using is internally calling `session.keys().getKeysStream(realm)`, you can see the source code [here](https://github.com/keycloak/keycloak/blob/25.0.2/services/src/main/java/org/keycloak/services/resources/admin/KeyResource.java#L69). So that method is for sure returning the same keys you see in the admin console (realm settings -> Keys tab) for the same realm.

Besides the `AppAuthManager.BearerTokenAuthenticator` is using the method `verifyIdentityToken` which does not use that method exactly. To retrieve the key it calls `verifier(kid)` [here](https://github.com/keycloak/keycloak/blob/25.0.2/services/src/main/java/org/keycloak/services/managers/AuthenticationManager.java#L1474). And, for example, the asymmetric implementation uses the `getKey` version with realm, usage, alg and kid [here](https://github.com/keycloak/keycloak/blob/25.0.2/services/src/main/java/org/keycloak/crypto/ServerAsymmetricSignatureVerifierContext.java#L33), and not the one that returns all keys for the realm.

So we don't understand your issue. I suppose you are doing an extension or similar, can you please attach a little project or something that we can use to reproduce your issue. Just a playground maven project with the minimal set to show your problem.
