### ISSUE TITLE
Keycloak 25.x admin client breaks compatibility

### ISSUE THREAD

**Issue by andrejpetras** [keycloak/keycloak#32337]
## Description

This is not strictly a bug as until Keycloak 25, we did not support connecting with new admin-client to older Keycloak servers. This is explicitly mentioned in the docs https://www.keycloak.org/docs/latest/upgrading/index.html#upgrading-the-keycloak-admin-client . So changing this to "task" instead of "bug" .

On the other hand, we are improving on backwards compatibility support for admin-client from Keycloak 26, so adding this to milestone 26. It is possible that this issue is already fixed due this commit https://github.com/keycloak/keycloak/commit/e7d9a717c9cf4d3b0089af3618f78efce15b38db , but not 100% sure. We will doublecheck when working on the client tests, which will test creating client with the admin-client against Keycloak 24 (Related issue for adding tests is https://github.com/keycloak/keycloak-client/issues/44 )

### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/client-java

### Describe the bug

New version of the admin client library breaks compatibility with older version of Keycloak Admin Rest API ( 24, 23, .. )

```json
    {"error":"Unrecognized field \"type\" (class org.keycloak.representations.idm.ClientRepresentation), not marked as
```    
    
   Source code change: 
   https://github.com/keycloak/keycloak/commit/3fffc5182ebf93225b3da40fce5d945e04155cdf

### Version

23, 24

### Regression

- [X] The issue is a regression

### Expected behavior

Create a compatible API where optional attributes are possible.

### Actual behavior

Admin client get a response 400 and body

```json
    {"error":"Unrecognized field \"type\" (class
    org.keycloak.representations.idm.ClientRepresentation), not marked as
    ignorable (43 known properties: \"enabled\", \"clientAuthenticatorType\",
    \"redirectUris\", \"clientId\", \"authenticationFlowBindingOverrides\",
    \"authorizationServicesEnabled\", \"name\", \"implicitFlowEnabled\",
    \"registeredNodes\", \"nodeReRegistrationTimeout\", \"publicClient\",
    \"attributes\", \"protocol\", \"webOrigins\", \"protocolMappers\", \"id\",
    \"baseUrl\", \"surrogateAuthRequired\", \"adminUrl\", \"fullScopeAllowed\",
    \"frontchannelLogout\", \"clientTemplate\", \"origin\",
    \"defaultClientScopes\", \"directGrantsOnly\", \"rootUrl\", \"secret\",
    \"useTemplateMappers\", \"notBefore\", \"useTemplateScope\",
    \"standardFlowEnabled\", \"description\", \"directAccessGrantsEnabled\",
    \"alwaysDisplayInConsole\", \"useTemplateConfig\",
    \"serviceAccountsEnabled\", \"optionalClientScopes\", \"consentRequired\",
    \"access\", \"bearerOnly\", \"registrationAccessToken\", \"defaultRoles\",
    \"authorizationSettings\"])\n at [Source:
    (org.jboss.resteasy.reactive.server.vertx.VertxInputStream); line: 1,
    column: 100] (through reference chain:
    org.keycloak.representations.idm.ClientRepresentation[\"type\"])"}
```    

### How to Reproduce?

Use keycloak-admin-client version 25.x and connect to Keycloak 24.x or 23.x

```java
           ClientRepresentation client = new ClientRepresentation();
           .....
            try (var resp = keycloak.realm("test").clients().create(client)) {
                return "OK;
            }
```

**Comment by mposolda** [comment]
@andrejpetras This is not strictly a bug as until Keycloak 25, we did not support connecting with new admin-client to older Keycloak servers. This is explicitly mentioned in the docs https://www.keycloak.org/docs/latest/upgrading/index.html#upgrading-the-keycloak-admin-client .

On the other hand, we are improving on backwards compatibility support for admin-client from Keycloak 26, so adding this to milestone 26. It is possible that this issue is already fixed due this commit https://github.com/keycloak/keycloak/commit/e7d9a717c9cf4d3b0089af3618f78efce15b38db , but not 100% sure. We will doublecheck when working on the client tests, which will test creating client with the admin-client against Keycloak 24 (Related issue for adding tests is https://github.com/keycloak/keycloak-client/issues/44 )

**Comment by buianhtai** [comment]
I think we can fix this by modifying the Keycloak Client and customizing the ObjectMapper to only send non-null values. This way, the new properties from the latest version won't be sent

```java


  public static Keycloak buildKeycloak() {
        Client client = createCustomClient();
        
        return KeycloakBuilder.builder()
                .serverUrl("https://your-keycloak-server.com/auth")
                .realm("your-realm")
                .clientId("your-client-id")
                .clientSecret("your-client-secret")
                .grantType("client_credentials")
                .resteasyClient(client)
                .build();
    }

    private Client createCustomClient() {
        // Create a custom ObjectMapper
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL); // Send only non-null values

        // Build a custom client using the ObjectMapper
        return ClientBuilder.newBuilder()
                .register(new CustomJacksonProvider(objectMapper))
                .build();
    }

    @Provider
    public static class CustomJacksonProvider implements ContextResolver<ObjectMapper> {
        private final ObjectMapper objectMapper;

        public CustomJacksonProvider(ObjectMapper objectMapper) {
            this.objectMapper = objectMapper;
        }

        @Override
        public ObjectMapper getContext(Class<?> type) {
            return objectMapper;
        }
    }
                                ```

**Comment by mposolda** [comment]
@buianhtai It is already done in latest main: https://github.com/keycloak/keycloak/blob/main/integration/admin-client/src/main/java/org/keycloak/admin/client/JacksonProvider.java#L16 .

I think this issue is already fixed, but will close it once we have automated test for backwards compatibility in the Keycloak client repository.

@andrejpetras @buianhtai BTW. Maybe you can already try to test with latest keycloak-admin-client from the latest nightly build? This can be done by declaring dependency on `org.keycloak:keycloak-admin-client:999.0.0-SNAPSHOT` and allowing snapshot dependencies for your project (temporarily)

**Comment by mposolda** [comment]
Closing as this is already done and tested in keycloak-client repository: https://github.com/keycloak/keycloak-client/blob/main/testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite/ClientTest.java#L120

**Comment by minthaka** [comment]
Hi to everyone!
I am struggling to even import Keycloak and UsersResource classes from keycloak-admin-client v. 26.0.2
How can I find them? I intend to create KC users via SpringBoot, but it seems it is totally broken. I use the same version of KC server.
