### ISSUE TITLE
"Duplicate" methods user storage federation interfaces

### ISSUE THREAD

**Issue by tahvane1** [keycloak/keycloak#32340]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

I'm trying to implement user Storage Federation with interface UserRoleMappingsFederatedStorage and UserQueryMethodsProvider.

Problem is that UserRoleMappingsFederatedStorage has
Stream<String> getRoleMembersStream(RealmModel realm, RoleModel role, Integer firstResult, Integer max)
and UserQueryMethodsProvider has 
Stream<UserModel> getRoleMembersStream(RealmModel realm, RoleModel role, Integer firstResult, Integer maxResults)

Thus both interfaces can't be implemented at the same time.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

It should be  possible to implement both

### Actual behavior

Not possible due to different return  type (by mistake?)

### How to Reproduce?

Try to implement

**Comment by sschu** [comment]
What exactly is stopping you from implementing both methods in your provider? The methods have different parameter lists, so they are different methods even if they have the same name.

**Comment by tahvane1** [comment]
I copied from version of the method. But problem is exactly that that they contain same name and same parameter type list.

**Comment by sschu** [comment]
So your problem is that one returns a `Stream<String>`and the other a `Stream<UserModel>`? I don't know the background of this but I assume it is intentional. Looking at where the method returning a `String` is called, it is probably sufficient to implement one of the two interfaces, see: https://github.com/keycloak/keycloak/blob/708a6898db8e6a96838e6ac19ccd43012c8263fd/model/storage-private/src/main/java/org/keycloak/storage/UserStorageManager.java#L478-L490

**Comment by tahvane1** [comment]
It seems that I have to implement another provider for roles. Thank you for your help.
