### ISSUE TITLE
"Cookie not found" in multi-step auth flows / mobile browsers

### ISSUE THREAD

**Issue by dominikschlosser** [keycloak/keycloak#32462]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

We have a multi-step auth flow which results in Keycloak using internal URLs for each step / execution. If a user without KC_RESTART and AUTH_SESSION_ID cookies opens this URL directly (for example because he closed his browser and re-opens it later with the browser remembering the last URL - a common issue on mobile devices), Keycloak displays a "Cookie not found" error.
This error basically means that the user has to start from scratch but we see from feedback of our users, that they dont understand that / think that our site is broken.

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

The user should be redirected to the client where he can start the flow from scratch (or do other things). This would be the same behavior as "already_logged_in" or "temporarily_unavailable".

### Actual behavior

Keycloak returns a "Cookie not found" error page.

### How to Reproduce?

Make sure to get to a subpage of the login flow by either configuring a multi-step flow or entering a wrong user/password once in the default flow. Then delete the KC_RESTART and AUTH_SESSION_ID cookies and reload the page.

Alternatively do it like our users in a browser which remembers the last opened URL (like most mobile browsers do) and close+reopen the browser after you are on the flow-sub-page.

### Anything else?

I propose to handle this error like "already_logged_in" here: https://github.com/keycloak/keycloak/blob/4d621e5dfd814586aaa2166886f6f15052fbd972/services/src/main/java/org/keycloak/services/resources/SessionCodeChecks.java#L199-L207

-> Use the client_data, validate it against the client-configuration in Keycloak and redirect to to given redirect-uri with error=temporarily_unavailable

**Comment by mposolda** [comment]
@dominikschlosser Just to doublecheck, do you have "Base URL" configured for your clients? If yes, I suppose there is also link like "Back to the application" which user can click and then restart their login from scratch?

Maybe we can support to automatically redirect to clients in more scenarios instead of just "You are already logged-in" . But I wonder that for backwards compatibility, we should control this with some switch on the client side like `Redirect to client in case of errors` or something like that. In such case, we should also specify what errors exactly should be shown to the clients and those errors should be then documented on places like this as this is not OIDC or SAML standards:
https://www.keycloak.org/securing-apps/oidc-layers#_oidc-errors
https://www.keycloak.org/securing-apps/saml-galleon-layers#_saml-errors

I am considering this issue as a "Feature" or Epic rather than a bug as it looks that amount of work for this could be relatively big. Also I don't think that this is "Important" bug, so I would rather vote for changing the priority to "Normal" and help wanted as I don't see this as big priority TBH (There is not just error page, but also the link "Back to application" displayed to the users where they can continue login in case that client is appropriately configured).

**Comment by dominikschlosser** [comment]
@mposolda The "Back to the application" link is present on our themed error page but this doesnt help because the user still sees an error and doesn't know why. I see this as a bug, because just re-opening your (mobile) browser resulting in an error just doesn't seem like intended behavior, with or without "Back to application" link.

**Comment by mposolda** [comment]
Fixed by making the message a bit clearer instead of slightly confusing `Cookie not found` . 

Automatic redirect to the client will be much more work, so we ommit it for now. Feel free to create another issue if you want this, but note that Keycloak team probably won't have time to look into that anytime soon, so it will need to be a community contribution. And might be bigger effort as the redirect to the client will need to be done in a way that is backwards compatible (so not enabled by default) and should be reviewed what are all the various error cases, which would require redirect to the client.
