### ISSUE TITLE
Issues with Keycloak and LDAP Federation Link during User Import via JSON

### ISSUE THREAD

**Issue by malikceesay** [keycloak/keycloak#32742]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

Hello everyone,

I'm facing the following issue:

I’m using Keycloak with LDAP set up as a Federation.
The goal is to import users into Keycloak via a JSON file so that they are automatically created in LDAP.
When I include the Federation Link in the JSON for the users, the users are neither created in Keycloak nor in LDAP.
If I remove the Federation Link from the JSON, the users are created in Keycloak, but there is no link to LDAP.
My configuration seems correct, but the Federation Link doesn’t seem to work as expected.

Questions:

- What configurations or settings are required for imported users to be automatically linked with LDAP?
- Do I need to manually configure anything in the JSON file or Keycloak admin to ensure the Federation Link is applied correctly?
- What logs or Keycloak settings should I check to identify any issues with the Federation Link?

Thank you in advance for your help!

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

When importing users via a JSON file in Keycloak, the users should automatically be linked to LDAP using the specified Federation Link. Users should be created both in Keycloak and LDAP, and their profiles should reflect the Federation Link with all related LDAP attributes. This process should occur without requiring manual intervention.

### Actual behavior

When importing users via a JSON file in Keycloak with a Federation Link, the users are not created in either Keycloak or LDAP. However, when the Federation Link is removed from the JSON, the users are created in Keycloak but are not linked to LDAP, and no Federation Link is set.

### How to Reproduce?

1. Set up Keycloak with an LDAP Federation.
2. Prepare a JSON file to import users with the following attributes: username, firstName, lastName, email, enabled, and federationLink.
3. Include a valid federationLink that corresponds to the LDAP Federation in Keycloak.
4. Import the JSON file into Keycloak via the User Import feature.
5. Observe that no users are created in Keycloak or LDAP when the federationLink is included.
6. Remove the federationLink from the JSON and re-import the users.
7. Observe that users are created in Keycloak but without a Federation Link or LDAP synchronization.

**Comment by raff897** [comment]
Hi,
are you planning to import users into another Keycloak instance using a different user federation?
I apologize, but I am struggling to understand the purpose of importing users into Keycloak to have them also imported into the user federation.
The user federation is responsible for managing the users; it should be the one handling import/export operations. Keycloak manages the users who are not part of the user federation and who need to be managed exclusively by it.
In any case, the federation link is an ID that Keycloak generates, so even if you use the same provider, a different Keycloak instance will generate a different ID.

**Comment by malikceesay** [comment]
Hi,

Thank you for your response.

To clarify, I am using Keycloak integrated with an LDAP Federation. The goal is to import users into Keycloak via a JSON file, and I would like those users to automatically be synced with the LDAP Federation. Currently, when I include the federationLink in the JSON file, users are not created at all, either in Keycloak or LDAP. Without the federationLink, users are created in Keycloak, but they do not sync with LDAP.

The idea is to have Keycloak as the interface for user management while the LDAP Federation handles the actual storage and access control. I understand that the federationLink is an ID generated by Keycloak, but I am looking for a way to ensure that users imported into Keycloak also get linked and synced with LDAP.

Could you provide any guidance or suggestions on how to achieve this?

Thanks again for your help!

**Comment by raff897** [comment]
Personally, I believe that this issue is more appropriately considered a feature rather than a bug.
Keycloak cannot create users in LDAP; it can only modify the data of an existing user, provided that the edit mode policy is set to "writable". In this context, there is no mechanism for Keycloak to create users in LDAP, as the management and creation of users should remain under the purview of the system that holds these entities, in this case, the LDAP server.
If I may suggest, it would be advisable to handle user creation directly on the LDAP server. You could import users from the old LDAP system and then connect Keycloak to the new server. This way, you would regain access to all users.

**Comment by sguilhen** [comment]
This is not something that Keycloak supports - partially importing a JSON to import users will work as long as those users already exist in the LDAP server. Simply setting the federation link won't suffice because the imported users are imported locally only - i.e. their creation is not propagated to LDAP even if it has the WRITABLE mode set. 

In fact, right after the import you will see the users in the `user_entity` table in the DB, but as soon as you try to login as one of those users, or perform a search, the LDAPStorageProvider will try to find that user in LDAP and when it fails to do so it removes the user from the DB because it detects an inconsistency.

The right way to do it would be to either import those users directly in LDAP and sync back into Keycloak, or use the proper user REST API to create the users sending a POST with the user representation. Users created this way will be propagated to LDAP if the sync mode is WRITABLE.
