### ISSUE TITLE
Requested `grant_types` inconsistent with created `grant_types` for OpenID Connect Dynamic Client Registration

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#32801]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When specifying `grant_types` in a OpenID Connect Dynamic Client Registration the requested and returned `grant_types` do not match. 

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Requested and returned `grant_types` are the same

### Actual behavior

Requested `grant_types` results in different created `grant-types`:

* `authorization_code` --> `authorization_code` [OK]
* `client_credentials` --> `[authorization_code, client_credentials]` [NOT OK]
* `password` --> `authorization_code` [NOT OK]
* `urn:ietf:params:oauth:grant-type:device_code` --> `authorization_code` [NOT OK]

### How to Reproduce?

Use `kct` to dynamically create clients for different flows, using the following command replacing flows with browser, client, password, and device, to try the different grant types:

```
kct config context create --iss myissuer -c mycontext --create-client --flow <FLOW> -X
```

Before running the above you need to create an issuer in `kct`, and context with a flow that uses boostrap admin user or client, and register that context with the issuer as the `client-registration-context`.

Using `-X` option you will see the request sent to Keycloak, and the responses.

**Comment by mposolda** [comment]
I am marking it as important as we may not implement the specification 100% correctly. But ATM I am not sure if this can be easily fixed without changing the configuration formats of the Keycloak OIDC clients.

Few points, which comes to my mind:

- There are some small differences between OIDC and OAuth2 specifications. It can be nice if we can somehow support both in a sensible way. Specifications:
  - OIDC: https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
  - OAuth2: https://datatracker.ietf.org/doc/html/rfc7591#section-2

- When we are at this, we should probably review and test `response_types` as well as those are slightly related to `grant_types` . 

- Also we can possibly add some validations at client registration/update as some combinations don't make sense. For example when using combination of `grant_types: { "client_credentials" }, response_types: { "code" }` , we should probably throw an error as this combination does not makes sense. (That's because if client allows only `client_credentials` grant, then it does not use authorization-endpoint at all and hence `response_types` with any value does not makes sense at all) Also we should make sure that default values makes sense (For example when `response_types` is omitted, but grant types are set to only `client_credentials`, then the default value of `response_types` should be empty and not the `code` (which is mentioned as the default if omitted in the OIDC specification, probably because OIDC specification does not consider OAuth2 grant types)

- We should doublecheck if `response_type=none` works as expected

- Keycloak has it's own options like `Standard flow enabled`, `Implicit flow enabled`, `Direct grant enabled` etc, which may not allow the flexibility provided by the options `grant_types` and `response_types` of OIDC/OAuth2 specs. Not sure if we can keep using those options or if we need some additional options for more flexibility...
