### ISSUE TITLE
Lightweight access token is not working for bootstrap admin client

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#32802]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I tested out https://github.com/keycloak/keycloak/pull/32347 with the bootstrap admin client, and ran into some issues: 

* Bootstrap admin client doesn't use lightweight tokens, which it should by default
* When enabling `Always use lightweight access token` for the client I get a 403

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Bootstrap admin client uses lightweight access token by default, and works out of the box

### Actual behavior

Uses regular tokens by default, and results in a 403 if `Always use lightweight access token` is enabled for the client. I suspect this is down to the fact that in `https://github.com/keycloak/keycloak/pull/32347` it states it uses the presence of the `sub` claim to determine if it's a lightweight access token or not, but the token I get with `Always use lightweight access token` includes the sub claim:

```
$ kct token -c admin -d
{
  "exp" : 1726053554,
  "iat" : 1726053494,
  "jti" : "286867a7-e822-4a2c-b3e8-4355d917117a",
  "iss" : "http://localhost:8080/realms/master",
  "sub" : "eb7bfd3a-bb09-477f-94d9-e0fa2ff0ee05",
  "typ" : "Bearer",
  "azp" : "temp-admin",
  "scope" : "profile email"
}
```

### How to Reproduce?

Start Keycloak with `--bootstrap-admin-client-secret=mysecret` and grab a token for that client, decode it and see that it contains all claims. Enable `Always use lightweight access token` for the client, and try to invoke the Admin REST APIs with it, and you'll get a 403.

Another thing is that it seems the `sub` claim should not be present in a lightweight access token by default, but it still is:
![image](https://github.com/user-attachments/assets/df7be101-0d21-4563-b209-fe0b6ab6b444)

**Comment by graziang** [comment]
The issue seems to be caused by the combination of lightweight access tokens and transient sessions.

The `sub` claim is always added to the token in the case of a transient session. Otherwise, both `sid` and `sub` would be missing, making it impossible to get the user from the token, and also the introspection wouldn't work.

A token should be considered lightweight if it does not contain Personal Identifiable Information (PII). 
The question is: how should we check if the access token is lightweight for the admin API?

- Checking if the `sub` claim is missing.
- Checking if the `preferred_username` is missing.
- Checking if the switch "Always Use Lightweight Access Tokens" or if the `UseLightweightAccessTokenExecutor` can be triggered on the client related to the `azp` claim of the token.
- Checking if there are no client roles or realm roles in the token.


A hybrid option to cover the case of a transient session for the admin REST API could be to check in addition to the `sub` claim, if the `sid` is null and there are no realm roles or client roles in the token.

Something like:
```java
(accessToken.sub == null || (accessToken.sid == null && accessToken.realmAccess == null && accessToken.resourceAccess == null))
```

**Comment by mposolda** [comment]
> A hybrid option to cover the case of a transient session for the admin REST API could be to check in addition to the sub claim, if the sid is null and there are no realm roles or client roles in the token.

> Something like:

> (accessToken.sub == null || (accessToken.sid == null && accessToken.realmAccess == null && accessToken.resourceAccess == null))

@graziang +1 for this suggestion
