### ISSUE TITLE
Deprecation of https-trust-store-* weakens X509 browser authentication

### ISSUE THREAD

**Issue by Dahu-Taquin** [keycloak/keycloak#33172]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Deprecation of https-trust-store-file-* options prevents specifying a dedicated trust store for X509 authentication.
So, any client cert emitted by extra CAs (such as Digicert) are trusted for client auth, which disables most of control on client certification validation.

### Version

25.0.6

### Regression

- [X] The issue is a regression

### Expected behavior

Trusted CAs for X509 browser authentication should be ONLY the ones specified in a dedicated trust store.

### Actual behavior

Trusted CAs are merged with the default Java trust store ([Configuring the System Truststore](https://www.keycloak.org/server/keycloak-truststore)). So, for X509 browser authentication, all certificates emitted by the CAs in the default Java trust store are trusted !

#### Generate a TLS certificate for the server
```
mkdir ssl
keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=localhost" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore ssl/server.keystore
```

#### Start the server, enabling X509 client auth
`docker run --rm -p 8443:8443 -v $PWD/ssl:/opt/keycloak/conf/ssl -e KC_LOG_LEVEL=info quay.io/keycloak/keycloak:25.0.6 --verbose start --https-key-store-file=/opt/keycloak/conf/ssl/server.keystore --https-client-auth=request --hostname=localhost`
#### View trusted CAs
`openssl s_client -connect localhost:8443 -prexit`

...
Acceptable client certificate CA names
C = US, ST = Illinois, L = Chicago, O = "Trustwave Holdings, Inc.", CN = Trustwave Global ECC P256 Certification Authority
C = US, O = Certainly, CN = Certainly Root E1
C = US, O = SecureTrust Corporation, CN = SecureTrust CA
C = US, O = "Entrust, Inc.", OU = See www.entrust.net/legal-terms, OU = "(c) 2012 Entrust, Inc. - for authorized use only", CN = Entrust Root Certification Authority - EC1
C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
...

### Anything else?

Related issue : [ Truststore consolidation broke keycloak fips mode #28526 ](https://github.com/keycloak/keycloak/issues/28526)

**Comment by shawkins** [comment]
This is an expected behavioral change - do you want it highlighted more in the migration docs? 

If you do not trust certs in the system truststore, you are free to override it.

**Comment by Dahu-Taquin** [comment]
Here is the use case : 
Keycloak has to trust certificates emitted by my Company-CA for X509 browser authentication. The certificate revocation list of my Company-CA are hosted on a website with a TLS certificate provided by a public well-known CA.
So, if "https-trust-store-*" parameters are NOT used, the System Trust store must contain the certificate of my Company-CA, AS WELL AS the certificate of the well-known CA (to validate the website hosting the CRLs).
This implies that all the client certificates emitted by the well-known CA are also trusted for X509 browser authentication. 
More generally, the system trust store has to contain the Company-CA certificate AND the certificate chain of the website hosting the CRL.
https-trust-store-* parameters allow to put ONLY Company-CA certificate for X509 authentication.

**Comment by shawkins** [comment]
I believe in this case you would configure revocation or specialized identity extraction on the "X509/Validate Username config" step if you wanted to narrow the trust. However I agree that this is not ideal - it would be more straight-forward to have a specific check of the issuer. cc @vmuzikar @ahus1 

The rationale for deprecating the https-trust-store was that it is still just a single truststore configuration - if you want to have different trust per realm for example it doesn't allow for that. So to keep the proliforation of truststores to a minimum and promote using standard non-JKS files, we settled on a single one to start with. Remote cache access however uses a separate truststore for a similar reason as this issue.

**Comment by shawkins** [comment]
> As the TLS handshake happens after the server name is sent (SNI), but before the URL is sent, this can never be realm specific.

The set of CAs must be shared across realms - but each realm can have a different configuration for the "X509/Validate Username config" authentication. If I only want to accept certs from issuer X in Realm X and certs from issuer Y in Realm Y - having only a single http truststore doesn't account for that.

> Looking at "X509/Validate Username config" in the Keycloak UI, it seems to lack functionality to check the CA that has been used, so the only place to do this today is the https trust store.

It looks like some platforms have more expressive ways of determining client cert validity: https://learn.microsoft.com/en-us/azure/api-management/validate-client-certificate-policy

**Comment by ahus1** [comment]
> The set of CAs must be shared across realms - but each realm can have a different configuration for the "X509/Validate Username config" authentication. If I only want to accept certs from issuer X in Realm X and certs from issuer Y in Realm Y - having only a single http truststore doesn't account for that.

Agreed. 

> It looks like some platforms have more expressive ways of determining client cert validity

I see that there are some issuer based fields there, and Keycloak also supports the IsserDN in two places, but that would IMHO not cover all the cases where there is a certificate chain with an root CA at the root, an issuer CA In the middle, and the subject's certificate at the leaf. 

The items "Full Certificate in PEM forma" and "SHA-256 Thumbprint" might be good to pin the certificate, but wouldn't allow to leverage the subject's CN in any way. Whenever the certificate is then rotated, the user needs to be updated.

**Comment by ahus1** [comment]
> The more I think about it the more I believe we should treat it as an enhancement to allow different truststores for X.509 for different realms, in other words make this a realm config option instead of server config option.

As all realms share the same hostname on Keycloak, you would still need to prepare the HTTP server to present all certificates to the caller, as when it establishes the TLS connection, the realm context is not known (the URL hasn't been sent yet). 

If you make it a realm config option, you'll need to be prepared to iterate over all realms at startup to pick up the trusted certificates, or you come up with a variant to encode the realm into the hostname.

**Comment by ahus1** [comment]
>  Other option would be not to send the Certificate Request message with the list of accepted CAs. AFAIK it's optional and IMHO not sending it would be more secure in any case – not to expose which CAs Keycloak trusts for auth.

Sending the list of CAs is technical optional, at the same time it enables the UX that the browser suggests the right certificate to the user in the browser. So I'd say it is strongly suggested from an UX point of view to send the CA list.

**Comment by shawkins** [comment]
> Realms can override their frontend URLs.

This would allow for a differentiation of server keys, but I don't think it would affect what is trusted. [X509TrustManager.getAcceptedIssuers](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/X509TrustManager.html#getAcceptedIssuers--) does not consider the URL being accessed.

 > So I'd say it is strongly suggested from an UX point of view to send the CA list.

It sounds like at a minimum we're (re)introducing a mechanism to differentiate trusted clients from trusted servers. Trusted servers remain covered by truststore-paths. 

Presumably this will be done on a per interface basis - so the cache will remain a separate truststore. 

The simplest thing to do is undeprecate https-trust-store-* with the only drawback being the continued support of jks files - although we could specifically deprecate that.

> If you make it a realm config option, you'll need to be prepared to iterate over all realms at startup to pick up the trusted certificates

An alternative is to introduce a tls registry like mechanism, so that the user can create named truststores:

--truststore-[name]-paths=... 

We already have logic to revalidate the cert in the step configuration, but it will work against the singular, and also deprecated, file truststore provider. The step configuration could instead reference a named truststore it wishes to revalidate against. 

Inferring the full https truststore based upon the configuration of the "X509/Validate Username config" settings seems possible by collecting these named truststores, but I think that would require deeper ties into the quarkus tls registry logic for it to reload when a setting changes - otherwise it would be subject to the default reload interval.

You could envision using these named truststores anywhere we can use a truststore, including ldap, mail, etc., but since all of those are currently just tls, not mtsl it seems fine that they are covered by the default truststore-paths.

> plus expressive validation in the authentication flow

I believe the revalidation logic could easily be adapted to check the chain against a list of accepted issuers or other aspects of the identity similar to https://learn.microsoft.com/en-us/azure/api-management/validate-client-certificate-policy.

**Comment by vmuzikar** [comment]
I had a chat with @stianst and based on the discussion here we agreed to undeprecate the `https-trust-store-*` options.
