### ISSUE TITLE
Migrating to a FIPS environment disallows all users from logging in

### ISSUE THREAD

**Issue by jonny-mccoubrey** [keycloak/keycloak#33296]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I have been following the guidance set out in https://www.keycloak.org/server/fips to move my non-FIPS Keycloak environment to a FIPS-enabled environment.
I am currently testing in a development environment where I have an existing database of users.

Although the documentation has got me as far as getting my FIPS-enabled instance up and running, I can not log in with any existing users (with passwords less than and greater than 14 characters). I have tried in both strict and non-strict mode.
My version of Keycloak is 25.0.5

I suspect that the passwords are hashing differently and so when I turn on FIPS, the hashes do not match and a user password is deemed as incorrect.

I am able to workaround the issue by first deploying KC in non-fips mode and setting `--spi-password-hashing-provider-default` to pbkdf2-sha512. I then log in with my test users (should mean their password is re-hashed into the algorithm that FIPS uses) and I can then re-deploy the KC service with FIPS enabled and log into users successfully.
I should also say that when strict mode is on, although I pass `--spi-password-hashing-pbkdf2-sha512-max-padding-length=14`, I can still only log in with users whose passwords are longer than 14 chars.

### Version

25.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect that when I turn on FIPS and re-deploy my KC service, that users should be able to log in before their passwords are re-hashed.

### Actual behavior

When I turn on FIPS mode and try to log in with existing users (with passwords of less than and greater than 14 characters), I receive the error that the username or password is incorrect

### How to Reproduce?

Run a Keycloak environment with version 25.0.5 and create users with passwords of varying lengths.
Re-deploy Keycloak environment with FIPS now turned on.
Try to log in with existing users.

**Comment by mposolda** [comment]
@jonny-mccoubrey  Thanks for the report! As you mentioned, the issue is caused by the fact that there is different hashing algorithm used in FIPS and non-FIPS mode.

Since Keycloak 25, the default algorithm for password hashing is `argon2` . See https://www.keycloak.org/docs/latest/release_notes/index.html#argon2-password-hashing for the details. However this algorithm is not FIPS compliant and hence in FIPS mode, the default algorithm is still `pbkdf2` . The thing is, that when migrating from non-FIPS to FIPS, the user passwords were already hashed with `argon2` and this algorithm does not work in FIPS environment at all.

We need to document this and hence I am adding this issue for Keycloak 26. As a workaround, you need to change your hashing algorithm to `pbkdf2` before migrating to FIPS. If your production environment is already set with `argon2` passwords, you may need some way to ask all your users to reset their passwords (either by "Forget password" functionality or by sending them emails from admin console or some other way).
