### ISSUE TITLE
Admin UI e is undefined if required action recreated with own alias

### ISSUE THREAD

**Issue by TuningYourCode** [keycloak/keycloak#33309]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

If you delete an required action element and recreate it with an `alias` not matching the `providerId` the Admin UI will show ann error.

As i couldn't find an limitation that `alias` has to be `providerId` and the presens of `alias` attribute i guess this behaviour is not intended -> bug.

### Version

25.0.6

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin UI works and shows all (setup) required actions for the realm.

### Actual behavior

The Admin UI will show an error `e is undefined`.

![grafik](https://github.com/user-attachments/assets/6507b892-8dfa-4ab1-a1a1-c2d47bf1f78f)

### How to Reproduce?

```
docker run --name keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.6 start-dev

docker exec -it keycloak /opt/keycloak/bin/kcadm.sh delete authentication/required-actions/webauthn-register --server http://localhost:8080/ --realm master --user admin --password admin --no-config

docker exec -it keycloak /opt/keycloak/bin/kcadm.sh create authentication/register-required-action -s alias=webauthn-register-master -s providerId=webauthn-register --server http://localhost:8080/ --realm master --user admin --password admin --no-config

Open Admin UI:
http://localhost:8080/admin/master/console/#/master/authentication/required-actions -> will show error message
```

**Comment by senyahnoj** [comment]
Added my upvote to this issue. 

In the meantime, this bug left my Keycloak fatally broken so I found that the only way to recover the damage was to look in the database. Posting here in case it helps anyone recover their installation before this bug is fixed.

```sql
SELECT * FROM REQUIRED_ACTION_PROVIDER WHERE ALIAS IS NULL;
```
(I'm using a MySQL back end but I presume the same problem will exist in other databases)

![image](https://github.com/user-attachments/assets/07bf0e86-e4b8-485b-8208-2269083fabea)

I then had to run an update statement to set the ALIAS back to its original value. I found that the NAME field was also NULL and the PRIORITY was set to 0. I also had to restart my keycloak docker container afterwards.

In my case, the problem was caused when I sent a request via the REST API to 

PUT /admin/realms/{realm}/authentication/required-actions/{alias}

and my RequiredActionProviderRepresentation payload only contained boolean "enabled" and "defaultActions" fields.

The problem is that the documentation https://www.keycloak.org/docs-api/latest/rest-api/index.html#RequiredActionProviderRepresentation says that all fields are optional. This is dangerous as when some fields (like alias) are omitted, it will put the database into an inconsistent state which breaks the UI.

![image](https://github.com/user-attachments/assets/397b498d-cf95-4784-9aca-e0b7195df349)

**Comment by edewit** [comment]
It's not an error on the alias, but on the name. How would you know what actions to use when it doesn't have a name? I can remove the error, but then the screen will look like this:
![image](https://github.com/user-attachments/assets/0a2427fc-fb08-4ecf-992d-052ad89eb54a)

**Comment by senyahnoj** [comment]
I agree. The issue is not the UI. The issue is that the API should not let you save this incomplete configuration in the first place.
