### ISSUE TITLE
Missing organization claim in access token when user is assign to more than one organization

### ISSUE THREAD

**Issue by osajdapawel** [keycloak/keycloak#33556]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

I was about to test organizationId in claim and noticed that there is missing **organization** claim in JWT token when user is added to more than one organization. For one organization everything works correctly.

One organization assigned:
![image](https://github.com/user-attachments/assets/b47d202f-12f1-432b-a618-342480821c6b)

Claim exists:
![image](https://github.com/user-attachments/assets/838a320e-4d3f-4107-83f9-da72d6dfb60b)

More than one organization assigned to the user:
![image](https://github.com/user-attachments/assets/93dd0cfc-aea6-4d12-9499-98e7a7f77dc1)

No organization claim:
![image](https://github.com/user-attachments/assets/c1c4256e-4070-43e4-9fab-8aaba9256d23)

### Version

26.0.0

### Regression

- [X] The issue is a regression

### Expected behavior

There should be an array of organization assigned to the user.

### Actual behavior

When more than one organization assigned organization token claim not exists.

### How to Reproduce?

1. Create realm with organizations
2. Create two organizations.
3. Create client
4. Make organization client scope default (easier to test - no scope selecting required then)
5. Create user
6. Assign user to one organization
7. Evaluate claim for user (tab evaluate in client scopes of client)
8. Assign user to second organization
9. Evaluate claim for user
10. Claim is missing

**Comment by pedroigor** [comment]
@osajdapawel I think is because you are not requesting all the organizations. Can you please check https://www.keycloak.org/docs/latest/server_admin/#mapping-organization-claims_server_administration_guide?

Basically, the authorization requests should have the `scope` parameter set with `organization:*`. Using just `organization` will map a single organization after the user selects one during the login.

I think the problem here is that the client scope evaluation tool does not fully support the different formats of the `organization` scope.

**Comment by vaish0117** [comment]
@pedroigor 
I have the same issue.
If an user is a member of 2 organizations, and if client scope includes Organization scope, then the ID/access token does not contain organization details of the user, while it works for an user who is a member of only 1 organization.

**Basically, the authorization requests should have the scope parameter set with organization:***
Regarding this, can you please elaborate?
Where do I provide 'organization:*' in admin console while creating scope?

**Comment by CarlosRodrigues** [comment]
> @pedroigor I have the same issue. If an user is a member of 2 organizations, and if client scope includes Organization scope, then the ID/access token does not contain organization details of the user, while it works for an user who is a member of only 1 organization.
> 
> **Basically, the authorization requests should have the scope parameter set with organization:*** Regarding this, can you please elaborate? Where do I provide 'organization:*' in admin console while creating scope?

Hi @vaish0117, I believe this is when you are requesting the access token. You need to provide a scope (usually openid for most applications). You'll need to pass organizations:* in your token request.

How are you obtaining the token now?

**Comment by nicolashery** [comment]
I was having this issue as well, but what made it tricky is that the `organization` **client scope** was set as "Default" for my client. So even if I added `organization:*` to my request's `scope` when getting a token, it seems it was taking into account the default `organization` client scope and the "organization" claim was missing from the response.

Not sure if this is the expected way to do things, but what I did was to _create a new client scope_ with the name `organization:*`, and set that one as "Default" on my client. And that seems to work, I get all of the user's organization when requesting a token (without having to specify anything in the request's `scope` regarding organizations).

<img width="1356" alt="Screenshot 2024-10-21 at 2 40 21 PM" src="https://github.com/user-attachments/assets/6601521c-fb20-4dff-a718-4a47677b5638">

<img width="1347" alt="Screenshot 2024-10-21 at 2 41 16 PM" src="https://github.com/user-attachments/assets/2451f768-60ff-44d2-a87b-0d6532378f3f">

```json
    "scope": "organization:* profile email",
    "organization": {
        "org1": {
            "id": "afaf3e66-606c-41e2-8a42-6924ceb10030"
        },
        "org2": {
            "id": "c5339391-84d1-423d-ba1f-3fe6b80f84fa"
        }
    },
```

**Comment by osajdapawel** [comment]
@nicolashery Yeah it works, thank you very much. 
@pedroigor yes it seems that this was more issue with evaluate tool. Thx guys

**Comment by nicolashery** [comment]
@pedroigor Not sure if this is a bug (in which case happy to open another issue) or something wrong with my Keycloak setup, but:

When I set my custom **Client scope** `organization:*` to "Default" for my Client, and when asking for a an access token with `grant_type=refresh_token`, then the `organization` claim _comes back as a list with one map entry, instead of a map_.

Notes:
- The first access token using `grant_type=authorization_code` has a well-formed `organization` claim (i.e. a map). This only happens on subsequent access token requets using the refresh token.
- The `scope` in the response contains the `organization:*` claim twice (ex: `"scope": "openid organization:* organization:* profile email"`)
- This does not happen with the built-in Client Scope `organization` set as "Default" on the client, only with a copy of it renaming the client scope to `organization:*` (see my [comment](https://github.com/keycloak/keycloak/issues/33556#issuecomment-2427470489) above on why I'm doing that).

Screenshots:

`grant_type: authorization_code`

<img width="1287" alt="Screenshot 2024-10-31 at 3 12 17 PM" src="https://github.com/user-attachments/assets/f45cb684-9462-46d3-bb72-f95cc4e1088c">

`grant_type: refresh_token`

<img width="1232" alt="Screenshot 2024-10-31 at 3 14 26 PM" src="https://github.com/user-attachments/assets/ae14f869-bed9-42ea-9854-c7517daf6fc5">

**Comment by ognjen-it** [comment]
Hi all,

It worked on Keycloak 26.0.8, but it doesn't work on the fresh latest version (26.1.3) of Keycloak,. I tested twice before posting here.

**Comment by therecluse26** [comment]
@ognjen-it same, it doesn't work for me. on 26.1.4

**Comment by ccoder1233** [comment]
does not work on 26.1.3

**Comment by DHill-bsl** [comment]
I managed to make this work on Keycloak 26.1.4 by adding a mapper to the organization:* client scope.

Create a client scope:

![Image](https://github.com/user-attachments/assets/00461da1-35c1-4baa-898e-847fb0db81f0)

Configure a new mapper for organization:* and select Organization Membership:

![Image](https://github.com/user-attachments/assets/fc154fac-be5d-4c4a-893e-b767318825c1).

My client then has organization client scope as an optional type, and organization:* as a default type.

**Comment by ognjen-it** [comment]
Hi @DHill-bsl , thank you for suggestion.

As far as I remmaber, I tried to add mapper in claim organization:* just as it exist in claim organization, but it didn't work. But I don't see why mapper would be requred?
I will let you know as soon as I check 26.1.4 version (tomorrow).

**Comment by ognjen-it** [comment]
Ok, I just upgraded from 26.0.8 to 26.2.3 and claim organization is not present when I have multiple organizations.
My client has organization:* claim:

![Image](https://github.com/user-attachments/assets/9b54eb43-0dca-436f-aeef-432d2e02a2ba)

Client scope:

![Image](https://github.com/user-attachments/assets/94a1ac6f-7fc4-4a4e-b10f-d427f9a7602c)

Mapper:

![Image](https://github.com/user-attachments/assets/6084af64-6a75-4496-bb23-7894ed32d7f7)

Get token from client_id saas:

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/68749664-f9db-444b-bb54-285b703c1636" />

And claim doesn't exist:

![Image](https://github.com/user-attachments/assets/3b2623c6-85a3-4ab5-b4f1-51a9f4dc5834)

**Comment by zant23** [comment]
Just tested this on 26.2.4 and it works if you do not forget to add the mapper to the custom "organization:*" scope.


> I managed to make this work on Keycloak 26.1.4 by adding a mapper to the organization:* client scope.
> 
> Create a client scope:
> 
> ![Image](https://github.com/user-attachments/assets/00461da1-35c1-4baa-898e-847fb0db81f0)
> 
> Configure a new mapper for organization:* and select Organization Membership:
> 
> ![Image](https://github.com/user-attachments/assets/fc154fac-be5d-4c4a-893e-b767318825c1).
> 
> My client then has organization client scope as an optional type, and organization:* as a default type.
> 
> KC version: ![Image](https://github.com/user-attachments/assets/033f4b1b-54d5-46e4-9aad-d419f4dd6ace)
> 
> Access token claim:
> 
> ![Image](https://github.com/user-attachments/assets/54fc2fb3-4779-4b1c-a2b9-2f5070cfd21d)

**Comment by transducer** [comment]
Also have this issue in Keycloak 26.6.2.

For a user that is a member of one organization the attributes do come into the ID token if the organization mapper is added to a client, if the user is member of two organizations they are empty.
