### ISSUE TITLE
Kubernetes Keycloak Getting Started not works

### ISSUE THREAD

**Issue by masalinas** [keycloak/keycloak#33847]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/cli

### Describe the bug

Folling the example Kubernetes Keycloak Getting Started from your link: https://www.keycloak.org/getting-started/getting-started-kube not works

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Access to Keycloak Admin Console without any error

### Actual behavior

I can't access to Admin Console with these error from: `https://keycloak.192.168.49.2.nip.io/admin`

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.

Refused to frame 'http://keycloak.192.168.49.2.nip.io/' because it violates the following Content Security Policy directive: "frame-src 'self'" in keycloak.js:57
```

<img width="1424" alt="Captura de pantalla 2024-10-12 a las 16 03 08" src="https://github.com/user-attachments/assets/299236c2-ef4a-4c29-a89b-049e81d04214">

### How to Reproduce?

Follow your tutorial from [https://www.keycloak.org/getting-started/getting-started-kube](https://www.keycloak.org/getting-started/getting-started-kube)

- Install a fresh Ubuntu 24.04 arm64 LTS version.
- Install a fresh Docker 27.3.1 version
- Install minikube 1.34.0 version.
- Deploy a fresh kubernetes version using the Docker driver.
- Execute the commands from tutotial

Deployment start correctly: the version of keycloak is 26.0.1 using your commands in the tutorial:

`kubectl create -f https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes/keycloak.yaml`

<img width="1425" alt="Captura de pantalla 2024-10-12 a las 16 10 00" src="https://github.com/user-attachments/assets/c636b9da-fab3-4f80-9f58-522888904182">

The keycloak service is created correctly but in orange color because the service is loadbalanced as you purpose:

<img width="1413" alt="Captura de pantalla 2024-10-12 a las 16 10 22" src="https://github.com/user-attachments/assets/281738c9-f380-424e-ba34-88654f331ddf">

Create the ingress executing your command and the ingress rule is created too:

```
wget -q -O - https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes/keycloak-ingress.yaml | \
sed "s/KEYCLOAK_HOST/keycloak.$(minikube ip).nip.io/" | \
kubectl create -f -
```

<img width="1433" alt="Captura de pantalla 2024-10-12 a las 16 12 49" src="https://github.com/user-attachments/assets/ffa46bf0-14f8-4b8d-9df9-7c942e2e1f09">

Execute the comand to discover the uris to access Keycloak:

```
KEYCLOAK_URL=https://keycloak.$(minikube ip).nip.io &&
echo "" &&
echo "Keycloak:                 $KEYCLOAK_URL" &&
echo "Keycloak Admin Console:   $KEYCLOAK_URL/admin" &&
echo "Keycloak Account Console: $KEYCLOAK_URL/realms/myrealm/account" &&
echo ""

Keycloak:                 https://keycloak.192.168.49.2.nip.io
Keycloak Admin Console:   https://keycloak.192.168.49.2.nip.io/admin
Keycloak Account Console: https://keycloak.192.168.49.2.nip.io/realms/myrealm/account
```

Load from Google Chrome: https://keycloak.192.168.49.2.nip.io/admin

<img width="1436" alt="Captura de pantalla 2024-10-12 a las 16 15 44" src="https://github.com/user-attachments/assets/35f83f5e-f1c6-4713-ba7b-bd93c2b638e6">

**Comment by shawkins** [comment]
Tls termination introduces a proxy, which the default deployment is not
configured for. The front end URL is being created as http because because
that is what the incoming request from the proxy is using. I believe the
ingress should at least be setting the Forwarded header, so the deployment
needs proxy-headers=forwarded set.

It also looks like we should also update that deployment to use the new
bootstrap-admin properties

**Comment by codespearhead** [comment]
The workflow for Keycloak 26 in the keycloak-quickstarts repository is broken [01].

This is likely due to the Kubernetes CRD [02][03] using deprecated environment variables.

There's already a PR addressing this [04]. Could you please close this issue [05] and upvote the PR with a 👍 to help increase its visibility? If you're able to test the changes and leave a comment on whether it worked, that would be even better.

[1] https://github.com/keycloak/keycloak-quickstarts/actions/runs/11175544432/job/31067115216
[2] https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/latest/kubernetes/keycloak.yaml
[3] https://github.com/keycloak/keycloak-quickstarts/blob/latest/kubernetes/keycloak.yaml
[4] https://github.com/keycloak/keycloak-quickstarts/pull/612
[5] https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/closing-an-issue

**Comment by masalinas** [comment]
Ok thanks I checked your commit (UPDATE: deprecated env variables) with the new env variables to be used:

        env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"

I changed these variables in your Kubernetes Keycloak Getting Started sample, configure a realm/client, make a simple angular app to connect to keycloak and everything works ok now. Thanks for your help

**Comment by masalinas** [comment]
Closing ticket after updating old env variables
