### ISSUE TITLE
Add More Info to Organization Events

### ISSUE THREAD

**Issue by Degoya-Studio** [keycloak/keycloak#34013]
### Description

Currently, it's not possible to determine which user was removed or added to an organization. Therefore, It would be helpful to further add that info to the payload of an organization event.

### Discussion

https://github.com/keycloak/keycloak/issues/31421
https://github.com/keycloak/keycloak/issues/30180

### Motivation

The information can be published to internal APIs

**Comment by codespearhead** [comment]
Sounds reasonable.

Relevant file: [1].

***

[1] https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java

**Comment by Degoya-Studio** [comment]
Hi @pedroigor I'll try

**Comment by Degoya-Studio** [comment]
@pedroigor I'm not sure if I took the correct branch for the pull request. Please let me know in case I should haven taken another one or something is missing.

**Comment by Lord-KalEl** [comment]
At first, thanks for this required feature … I wanted to leave KeyClok because of the lack of this future (the extension was an option, but this, I thought, has to be core in such a software.)

But now, the organizations are there, the first step is done. It makes less sense, to have only the organizations, without orga-roles or orga rules. This step is very important, because otherwise, the orgas are similar to the groups.
Next thing is the nested organizations … if you have many of them, you should be able to struct them. 
One of your features will be orga-groups.
Definition of a group in KeyCloak is, to group some users.
Definition of a orgas in KeyCloak is, to group some users, but to isolate the rules and polices (and theming and other features)

So the idea is, we need both, nested groups AND nested orgas.

By the way, themes should be changable without a restart of KeyCloak … and it would be nice, if every orga can have their own theme. (500 to 1000 organizations, the downtime will be very high ;) )

Greetings
Kal

**Comment by pedroigor** [comment]
@Lord-KalEl Thanks for the feedback. Both capabilities `Organization Groups` and `Group of Organizations` are on our radar. We are not sure yet about release dates. See https://github.com/keycloak/keycloak/issues/30180.

**Comment by embesozzi** [comment]
Just a minor observation regarding this issue: the username and email were added when a user was removed from or added to an organization.
[OrganizationMemberResource.java#L175](https://github.com/pedroigor/keycloak/blob/41950a0e61eea84e8f691c4cc1834d0b805f3e0f/services/src/main/java/org/keycloak/organization/admin/resource/OrganizationMemberResource.java#L175)

When handling the admin event, I typically use the user identifier, as is done for other events when users are removed from or added to roles. Would it be a good idea to also include the userId in the event details?
