### ISSUE TITLE
Dist Folder Missing From keycloak.js after npm install 26.0.1

### ISSUE THREAD

**Issue by JahlersSoundThinking** [keycloak/keycloak#34060]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

adapter/javascript

### Describe the bug

After updateing my keycloak.js libraries to 26.0.1 using npm install I get this error, "An unhandled exception occurred: Script file node_modules/keycloak-js/dist/keycloak.min.js does not exist". When I opened the package it seems to be missing the dist folder. This worked in 25.0.3

### Version

26.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

The keycloak,js folder should have a dist folder with the keycloak.min.js file

### Actual behavior

The dist folder is missing from the keycloak.js package

### How to Reproduce?

Npm install the newest 26.0.1 keycloak.js npm module and look into the keycloak,js package and there will be no dist folder

**Comment by jonkoops** [comment]
This is working as intended. When version 26 was released the package structure changed. If you take a look at the [contents of the package](https://www.npmjs.com/package/keycloak-js/v/26.0.1?activeTab=code) you'll see files are now in the `lib` directory.

The directory structure of the package is not considered a stable part of the API with guarantees about backwards compatibility. Instead, we use the [`exports`](https://nodejs.org/api/packages.html#exports) field in the `package.json` to [define the entry-points](https://github.com/keycloak/keycloak/blob/7d8ff710c20ebf2b668b1761dbecbe4bf23f6f80/js/libs/keycloak-js/package.json#L6-L15) and which files they resolve to.

**Comment by JahlersSoundThinking** [comment]
I understand that directories have changed but there is no keycloak.min.js file in the lib folder either so does that file no longer exist or was it renamed?

**Comment by jonkoops** [comment]
The minified version has been removed. It is now expected that the consumer of a package that wants to optimize it will do so themselves (e.g. using a bundler such as Vite or WebPack) as they know their environment the best. If you need to include the dependency on a webpage you can host and minify it yourself, or use a CDN that does this for you.

**Comment by JahlersSoundThinking** [comment]
Thank you so much for the clarification!

**Comment by rokf** [comment]
I'm just adding this here in case that anyone else will be looking for a potential quick solution to making the new adapter versions work with `<script>` tags in browsers. We've used [Rollup](https://rollupjs.org/) with the [UMD](https://github.com/umdjs/umd) format:

```sh
rollup keycloak.js --format umd --name "Keycloak" --file keycloak.min.js --plugin terser
```

The `--plugin terser` part can be left out in case that you do not need to minify the output. Otherwise you'll need to install [@rollup/plugin-terser](https://www.npmjs.com/package/@rollup/plugin-terser).

**Comment by jmthomas** [comment]
This also threw me because I was pulling the minified file from jsdelivr. It looks like they are still minifying it for you: https://www.jsdelivr.com/package/npm/keycloak-js?tab=files&version=26.1.2 but it is now in the `lib` directory instead of `dist`. Url is `https://cdn.jsdelivr.net/npm/keycloak-js@26.1.2/lib/keycloak.min.js`

**Comment by jonkoops** [comment]
@jmthomas you should not be appending the file path, like I said before we don't consider the directory structure of the package to be a stable part of the API,  so it can change at any time in new versions. We use the [`exports`](https://nodejs.org/api/packages.html#exports) field to indicate what the entry-points of the package are.

It looks like jsDelivr also supports providing a URL without a path, but this does not seem to work, perhaps because they do not fully support the aforementioned `exports` field, e.g:

```
https://cdn.jsdelivr.net/npm/keycloak-js@26.2.0
```

If you are going to use a CDN I would recommend that you use the [JavaScript module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) version,  which is more aligned with web standards and how our documentation reflects it.

```html
<script type="module">
  import Keycloak from 'https://cdn.jsdelivr.net/npm/keycloak-js@26.2.0/+esm';

  const keycloak = new Keycloak({ ... });
</script>
```


Additionally, you can use an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) to make it possible to import it the package by name.

```html
<script type="importmap">
  {
    "imports": {
      "keycloak-js": "https://cdn.jsdelivr.net/npm/keycloak-js@26.2.0/+esm"
    }
  }
</script>
```

```html
<script type="module">
  import Keycloak from 'keycloak-js';

  const keycloak = new Keycloak({ ... });
</script>
```

**Comment by jmthomas** [comment]
As part of our build process we download the minified version and then directly reference it. I'm not putting a remote location in a script tag like your examples. Once we have a local minified copy we directly reference it like:

```javascript
import Keycloak from '/js/keycloak-js-26.1.0.min.js'
```

**Comment by jonkoops** [comment]
Yes, that is a great solution! I would always recommend that over a CDN, since you can never fully trust a third-party service to stay online or have your best interests at heart.

**Comment by jmthomas** [comment]
@jonkoops I would appreciate it if you ever move the files around you put that in the release notes for people like me who are just adding it to our build. Thanks!
