### ISSUE TITLE
parent-groups are not retuned by group mapper

### ISSUE THREAD

**Issue by cod3monk** [keycloak/keycloak#34166]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Using the Group Membership mapper only direct assigned groups are returned, but not parent groups of assigned groups.

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

As group hierarchies implies that group member of a sub group is also a member of its parent, the parent group should also be retruned.

### Actual behavior

Only assigned sub-groups are returned.

### How to Reproduce?

1. create parent group
2. create sub-group within parent group
3. add user to sub-group members
4. add group membership mapper to client
5. inspect returned group information

### Anything else?

to not break current behavior this could be a configuration of the mapper

**Comment by zeddit** [comment]
@cod3monk hi, I am new to keycloak and face this issue when using version 26.0.1. 
I wonder if the nested groups are returned right in version 25.0.6? great thanks.

**Comment by zeddit** [comment]
I have a workaround to see nested groups in claims, but it needs much effort.

that is, we need to create severals realm roles, which have the same name with groups, and then we assign the corresponding role to the group. 
Finally, we use the built-in group mapper rather than the one before to map groups like
<img width="1085" alt="截屏2024-10-23 20 21 29" src="https://github.com/user-attachments/assets/d22d6c40-91f4-4b55-8e0c-d454bc08a5b2">

**Comment by martin-kanis** [comment]
Yeah this seems more like enhancement request than a bug. Feel free to upvote https://github.com/keycloak/keycloak/issues/33247 so it get more traction.
