### ISSUE TITLE
Non compliant OpenID Client Authentication when `client_secret_jwt` with PAR (Pushed Authorization Requests)

### ISSUE THREAD

**Issue by GPrimola** [keycloak/keycloak#34547]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Endpoint `POST http://keycloak.local/realms/myrealm/protocol/openid-connect/ext/par/request` does not authenticate (returns 401) with `client_secret_jwt` when `client_assertion` and `request` keys are provided.

I.e. not compliant with [OpenID Connect PAR specs](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) and [PAR's RFC-9126](https://datatracker.ietf.org/doc/html/rfc9126)

### Version

26.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

A POST to `http://keycloak.local/realms/myrealm/protocol/openid-connect/ext/par/request` should return 201 with similar (values may vary) body response

```
{
  "request_uri": "urn:ietf:params:oauth:request_uri:2277ae07-1bd1-4d43-84dc-2adb1680a016",
  "expires_in": 60
}
```

when valid `request`, `client_assertion`, `client_assertion_type`, `scope`, `response_type` and `client_id` are provided.

### Actual behavior

Keycloak does not authenticate ANY request to `http://keycloak.local/realms/myrealm/protocol/openid-connect/ext/par/request` when valid `request`, `client_assertion`, `client_assertion_type`, `scope`, `response_type` and `client_id` are provided. Instead it returns:

```
status: 401
resp body:

{
  "error": "invalid_request",
  "error_description": "Authentication failed."
}
``` 

### How to Reproduce?

With any realm and client:

Perform a POST to endpoint `/realms/myrealm/protocol/openid-connect/ext/par/request` with content type as `x-www-form-urlencoded` and form with the following keys (defined in the [Pushed Authorization Requests RFC](https://datatracker.ietf.org/doc/html/rfc9126)) with valid values:

`request`, `client_assertion`, `client_assertion_type`, `scope`, `response_type` and `client_id`

### Anything else?

All the calls were done based on [RFC 9126](https://datatracker.ietf.org/doc/html/rfc9126) which refers to the Pushed Authorization Requests and [OpenID Client Authentication](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) specification.

**Comment by mposolda** [comment]
Not 100% sure if this is a setup issue or the real bug. Anyway, the contributions to fix this is welcome from the community (if it is real bug).

**Comment by thomasdarimont** [comment]
@mposolda @tnorimat I think this is a real issue with client authentiation with SignedJWT and SignedJWT with Client secret.

The current code in [ClientAuthenticationFlow#processFlow](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/ClientAuthenticationFlow.java#L72) calls `authenticator.authenticateClient(context);` for EVERY authenticator listed in the client auth flow for this client (or realm if not set on a client) without checking if the current `AuthenticationExecutionModel` matches `client.getClientAuthenticatorType()`.

If we have the client auth sequence:
1) clientid secret
2) signed jwt
3) signed jwt with client secret
4) x509 certificate

and a client is explicitly configured to use `signed jwt with client secret` `ClientAuthenticationFlow#processFlow` will ALSO execute the `signed jwt` authenticator. This has the consequence that `org.keycloak.authentication.authenticators.client.JWTClientValidator#validateTokenReuse` is called twice, first by `JWTClientAuthenticator#authenticateClient` followed by `org.keycloak.authentication.authenticators.client.JWTClientSecretAuthenticator#authenticateClient`. The first call adds the current marks the current JWT as "used" in the `SingleUseObjectProvider`, and the second one triggers an exception (token reuse detected).

I recommend to change the logic in `ClientAuthenticationFlow#processFlow` to only call `authenticator.authenticateClient(context);` if the client authenticator is configured for the current client.

To confirm that everything works, I disabled the Signed JWT client authenticator in the client auth flow and then I could successfuly execute a PAR request with a Signed JWT (signed via client secret and HS256 (explicitly configured for client credentials)).

I think this should be fixed in Keycloak 24, 25, and 26.

**Comment by thomasdarimont** [comment]
@mposolda I created https://github.com/keycloak/keycloak/pull/34573

**Comment by thomasdarimont** [comment]
@mposolda yes, in my example I configured the test client with "Signed JWT with Client Secret" and `HS256`
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/bc792170-4532-41f2-aa6a-0bfeefe741e0">

I wouldn't consider it a "corner case", as you need to use ths sort of configuration when you want to use "Signed JWT with Client Secret".

With this configuration, I can clearly see that 
`org.keycloak.authentication.authenticators.client.JWTClientAuthenticator#authenticateClient`
and
`org.keycloak.authentication.authenticators.client.JWTClientSecretAuthenticator#authenticateClient`
are both executed.

The JWTClientAuthenticator execution records the JWT as already used, the second JWTClientSecretAuthenticator throws the exception on `validator.validateTokenReuse();` which eventually leads to an 401 response.

Storing some additional status information in the authentication context is an option, but I think it would be better to only call the client authenticator that is configured for a particular client, or if there is only one in the flow execute only that. In my PR iItried exactly that, but this wasn't enough as the ClientSecret authenticator is also used for "public" clients. 
I didn't have time yet to write a proper fix, but I think it's really needed as the current implementation doesn't work correctly when "Signed JWT with Client Secret" is used.

**Comment by mposolda** [comment]
> @mposolda yes, in my example I configured the test client with "Signed JWT with Client Secret" and `HS256` <img alt="image" width="1198" src="https://private-user-images.githubusercontent.com/314690/382923604-bc792170-4532-41f2-aa6a-0bfeefe741e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTQ4MzMsIm5iZiI6MTczMDc5NDUzMywicGF0aCI6Ii8zMTQ2OTAvMzgyOTIzNjA0LWJjNzkyMTcwLTQ1MzItNDFmMi1hYTZhLTBiZmVlZmU3NDFlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwODE1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTgxMmM3YTNjM2RmZjM5MGU2ZmJkN2NiN2UzNDBjMzI1MDY3NWRkNmE2OTI4MjRlZDk0NzBlMzg4OWJlODMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ge6_Erzq7NIgF5lTYs4KC5OXqhbcLYCbizStywtXUhs">
> 
> I wouldn't consider it a "corner case", as you need to use ths sort of configuration when you want to use "Signed JWT with Client Secret".
> 
> With this configuration, I can clearly see that `org.keycloak.authentication.authenticators.client.JWTClientAuthenticator#authenticateClient` and `org.keycloak.authentication.authenticators.client.JWTClientSecretAuthenticator#authenticateClient` are both executed.
> 
> The JWTClientAuthenticator execution records the JWT as already used, the second JWTClientSecretAuthenticator throws the exception on `validator.validateTokenReuse();` which eventually leads to an 401 response.

Yeah, but my point is how is possible that `JWTClientAuthenticator` managed to successfully authenticate the client and verify the signature in such case? I suppose it is possible just if you have realm key of HS256, which is exactly the same as the key corresponding to the client secret of your client `acme-service-client-jwt-auth` . That is what I consider as a corner case, which is also not good practice IMO to re-use the key (using the same realm key as the client-secret of some realm client). Otherwise I don't get how is possible that `JWTClientAuthenticator` managed to authenticate client and go to `validateTokenReuse()`, which is done as very last step... But maybe I am wrong here? Can you please confirm if your client secret is the same as some realm key or if I missed something in my assumption above? It is possible that we have rather bug in `JWTClientAuthenticator` as AFAIK that authenticator should not use client-secret at all for validating JWT signature.

> 
> Storing some additional status information in the authentication context is an option, but I think it would be better to only call the client authenticator that is configured for a particular client, or if there is only one in the flow execute only that. In my PR iItried exactly that, but this wasn't enough as the ClientSecret authenticator is also used for "public" clients. I didn't have time yet to write a proper fix, but I think it's really needed as the current implementation doesn't work correctly when "Signed JWT with Client Secret" is used.

I see your point. However IMO there is flaw in the specification due the fact that `client_id` is optional parameter in the grant requests. So the thing is, that when you are triggering client authentication, you don't know which client you are authenticating and hence you don't know exactly which client authenticator to try. That is why all the available client authenticators are tried.

We can possibly improve this in case that `client_id` is available as in that case, we can set just the client authenticator for the particular client? Also we can improve in case that only 1 client authenticator is configured as `required` as then we don't need to try all authenticators (which is what you did in your PR. +1 for that change).

**Comment by thomasdarimont** [comment]
@mposolda are you available in the CNCF slack? I could show you the issue in a quick call.

**Comment by mposolda** [comment]
@thomasdarimont Thanks Thomas for further clarifications!

> @mposolda are you available in the CNCF slack? I could show you the issue in a quick call.

Sorry for slow answer, as I have some other meetings and errands etc, but hopefully we can have a call next week if needed? Some more answers inline.

> 
> It seems that the JWT Validation in `org.keycloak.authentication.authenticators.client.JWTClientAuthenticator#authenticateClient` internally uses the current client secret as default key when the signature alg is HS256 (judging from `org.keycloak.jose.jws.DefaultTokenManager#verifyJWS` and `org.keycloak.crypto.ClientMacSignatureVerifierContext#getKey`), which makes the `JWTClientAuthenticator#authenticateClient`complete successfully.

Thanks, so this is a bug in `JWTClientAuthenticator` then. I think that `JWTClientAuthenticator` should not ever try to use client-secret. It should rely on the client keys as specified in our documentation https://www.keycloak.org/docs/latest/server_admin/index.html#_client-credentials . If the client needs to rely on client-secret, the client should use `signed jwt with client secret` instead of `signed jwt` authenticator. So if we fix this in `JWTClientAuthenticator`, we will also fix the issue in question as `JWTClientAuthenticator` won't be able to validate the signature and hence it won't call the `validateTokenReuse()` .


> If the client is present in the request, which is IMHO the majority of cases, we should filter the client authenticators to those explicitly configured for the client, while handling the special cases for public clients correctly.

+1 . I agree that if client is present in the request, we can filter in advance to allow just the authenticator, which is suitable for the current client. I believe that this can be done by the presence of `client_id` parameter right? If we know the client from `client_id` parameter, we can use just the authenticator suitable for that particular client.

However we still need to count the cases when the `client_id` is not known as it is not the required parameter really. Some references:
- The OAuth2 specification mentions `client_id` as the required parameter just for public clients: https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3 . But the example below (the POST request) does not even use the `client_id` parameter. So for such request, Keycloak does not know which client it is authenticating (until it parses the `Authorization: Basic` header, which is done by trying `ClientIdAndSecretAuthenticator` )
- The example in the `JWT Client authentication` specification also does not use `client_id` parameter: https://datatracker.ietf.org/doc/html/rfc7523#section-2.2 . So you don't know which client you're authenticating until you try the client authenticator, which would parse the `client_assertion` .
