### ISSUE TITLE
Error on testsuite "group_test" on Cypress

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak#34605]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

There is an error on the test "Duplicate group" on the "group_test" testsuite

https://github.com/keycloak/keycloak/actions/runs/11655914950/job/32451389621
https://github.com/keycloak/keycloak/actions/runs/11638165707/job/32412651345
https://github.com/keycloak/keycloak/actions/runs/11621918237/job/32366664637

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

Pass

### Actual behavior

Fails

### How to Reproduce?

Seems flaky

**Comment by charley04310** [comment]
Hey,  I think I have **identified the source of the issue**:  

the method `assertNotificationCouldNotCreateGroupWithDuplicatedName` has a hardcoded error message. This causes a mismatch because the error message actually changes depending on whether it's for a `childGroup` or a main group. Additionally, the first CSS class used, `#itemRowDrpDwn`, was incorrect. Once updated to `.pf-v5-c-menu-toggle`, everything seems to work as expected (both the fail and pending states).

![duplicatedGroup](https://github.com/user-attachments/assets/f19b8d0d-6fac-4fb6-a9b5-16c4a7ba8434)

Can you assign it to me ? :smile:

**Comment by ssilvert** [comment]
I don't think this needs a backport to 26.0.
