### ISSUE TITLE
Docs: server_admin/topics/assembly-creating-first-admin.adoc

### ISSUE THREAD

**Issue by alshoaili96** [keycloak/keycloak#35069]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

File: server_admin/topics/assembly-creating-first-admin.adoc

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

i should be presented with login page

### Actual behavior

stuck on "local access required"
![Screenshot 2024-11-19 at 10 32 17 AM](https://github.com/user-attachments/assets/06c4bcbf-000a-4c06-ad04-69e882e042a3)

### Anything else?

i followed the instruction however still facing this issue.

**Comment by rmartinc** [comment]
@alshoaili96 Are you using `localhost` as the [documentation says](https://www.keycloak.org/docs/latest/server_admin/index.html#creating-the-account-on-the-local-host)? If you are accessing another server that is not localhost you need to create the admin using the env vars (as teh documentation also comments about [here](https://www.keycloak.org/docs/latest/server_admin/index.html#creating-the-account-remotely)).

**Comment by alshoaili96** [comment]
no, i am not using localhost, i am using the public ip of my OCI instance.

**Comment by rmartinc** [comment]
Then you have to create the env vars as documented: https://www.keycloak.org/docs/latest/server_admin/index.html#creating-the-account-remotely

The admin user creation page is only for localhost as the documentatios says. It's this way because of security issues. Closing the issue as it's working as expected.

**Comment by alshoaili96** [comment]
no i get this issue:
![Screenshot 2024-11-19 at 1 17 54 PM](https://github.com/user-attachments/assets/5e2a7a54-9d62-469b-a5ab-487ea1e7f482)

here is my keycloak service:
[Unit]
Description=Keycloak Server
After=network.target

[Service]
User=keycloak
Group=keycloak
Environment=KEYCLOAK_HOME=/opt/keycloak-26.0.5
Environment=JAVA_OPTS="-Djboss.bind.address=0.0.0.0", KC_BOOTSTRAP_ADMIN_USERNAME=admin, KC_BOOTSTRAP_ADMIN_PASSWORD=admin
ExecStart=/opt/keycloak-26.0.5/bin/kc.sh start-dev --http-port=8443
Restart=always

[Install]
WantedBy=multi-user.target

here is my keycloak.conf:
# The database vendor.
db=postgres

# The username of the database user.
db-username=abdullah

# The password of the database user.
db-password=Br@zil123

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
db-url=jdbc:postgresql://postgresip:5432/keycloak
hostname-strict-backchannel=false
https-enabled=true
https-port=8443
https-certificate-file=/opt/keycloak-26.0.5/conf/server.crt.pem
https-certificate-key-file=/opt/keycloak-26.0.5/conf/server.key.pem
hostname-strict=false
# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
#hostname=myhostname

not sure what i am doing wrong

**Comment by rmartinc** [comment]
This is another error and it's because by default the realm is created with `Require SSL` set to `External requests`. You are starting the server with `start-dev` which is plain http, not https. Try using the common `start` that should be used for any production environment. And please, do not use this issue a placeholder to ask anything that happen to my installation. This is another issue different to the problem you specified at the beginning. Do not use this issue again. File another issue if you think you have found a bug. If you have general questions you have to use the user mailing list: https://groups.google.com/g/keycloak-user.

And please, please, please do not paste your passwords in these issues.
