### ISSUE TITLE
Ability to reject authentication to users without 2FA configured

### ISSUE THREAD

**Issue by mposolda** [keycloak/keycloak#35231]
### Description

The customer has a business requirement to take certain actions if users are not configured for 2FA. They are looking to perform an authentication Flow that uses this condition to detect if a user does not have any 2FA method.

### Possible solution

The easiest approach is to implement the option `Negate output` in the condition `Condition - User configured` . The option `Negate output` is available for example in the `Condition - user role` .

Currently the `Condition - User configured` evaluates to true if at least one of the 2-factor authenticators configured in the related conditional subflow is present. So when added `Negate output` option, it will allow to have subflow, which will evaluate to true just if NONE of the configured 2-factor authenticators from the same subflow is present.

Together with the `Deny Access` authenticator, this can be used to achieve the requirement. As for example it may be possible to configure the authentication flow with the subflows like these:

```
- (All other authenticators like cookie, password etc)
- Subflow1 - 2factor enabled
  - Condition - user configured (Negate output = false)
  - OTP ALTERNATIVE
  - WebAuthn ALTERNATIVE
  - Recovery codes ALTERNATIVE
- Subflow2 - 2factor disabled
  - Condition - user configured (Negate output = true)
  - Deny Access ALTERNATIVE
  - OTP ALTERNATIVE
  - WebAuthn ALTERNATIVE
  - Recovery codes ALTERNATIVE 
```

This will allow to authenticate users with 2-factor configured (subflow1), but reject authentication for users without 2-factor configured (subflow2).

It is possible that some other adjustements may be needed in the implementation of `ConditionalUserConfiguredAuthenticator` to make this happen or configure the `subflow2` in slightly different way. But hopefully some setup like this may work. Will need further investigation...

The disadvantage is the need of duplication of all the 2-factor authenticators in both subflows and the complication of such a setup. The better will be to have authentication policies, which would allow better achieve something like this more easily. But that is for the future though...

**Comment by rmartinc** [comment]
@mposolda I've been thinking about this and doing the negation is complicated because the `deny-access` should be executed and I don't know how to differentiate this authenticator from the others (otp, webauthn,...). But I have thought about another solution that maybe is simpler and works in the same way.

The idea would creating another conditional authenticator to check if a sub-flow was executed successfully in the authentication flow peviously (or negated, not executed). This way the same use-case would be:

```
- Subflow1 - 2factor enabled (Conditional)
  - Condition - user configured (Required)
  - OTP (Alternative)
  - WebAuthn (Alterntive)
  - Recovery codes (Alternative)
- Subflow2 - 2factor disabled (Conditional)
  - Condition - sub-flow executed (flow='Subflow1 - 2factor enabled' check='not-executed') (Required)
  - Deny Access (Required)
```

The subflow1 contains the normal alternative condition with all the 2fa methods. The subflow2 checks if the subflow1 was not executed successfully and in that case deny the access. Instead of `deny-access` we can even enforce the user to configure some 2FA method (OTP required for example to force the user to configure OTP). So the idea allow to do things if previous flows was executed or not executed. WDYT?
