### ISSUE TITLE
Maven clean shouldn't be skipped by default on Windows

### ISSUE THREAD

**Issue by Pepo48** [keycloak/keycloak#35289]
### Description

Currently if `mvn clean` is executed in the project's root, the clean phase is skipped due to the `clean-when-not-on-windows` profile[1]. 

I think this could be improved in one of 3 ways:
* change the default behaviour to to false and skip the clean phase only when the `-Djs.skip.clean` is passed
* define it rather on a submodule level
* document it somewhere to make it more visible.

[1] https://github.com/keycloak/keycloak/blob/837fbf85f42bb32194bb4466774ef0bcdd367651/pom.xml#L1735

**Comment by jonkoops** [comment]
This is done on purpose because Windows is an operating system that doesn't handle symbolic links properly. If this profile is not activated the `node_modules` are removed, but it will follow the symbolic links in there and start pruning much more than it really should, possibly leaving the build in a possibly broken state.

**Comment by Pepo48** [comment]
@jonkoops the thing is that the current setup is also influencing other directories build-related directories, like `target` folders. These are not deleted, nor their content is deleted. I guess we should find another approach. Or at least document it if we don't come up with something better.

**Comment by jonkoops** [comment]
That is certainly not good yeah, let's get that that fixed.
