### ISSUE TITLE
Inconsistency when returning user attributes when executing a seach or fetching users by ID from external user storage providers

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#35637]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

The user attributes are fetched differently when executing searches and fetching users by their identifiers.

When running a search, the external user storage provider is called and eventually returns a `UserModel` that fetches the user attributes from their storage.

However, when querying users by their identifiers where the user is already cached the user attributes will have their values fetched from the cache, which can be different than the value from the external user storage. This is especially true when the user storage provider is updated directly without necessarily going through the server.

This issue is mainly impacting the LDAP user storage provider, for now. But it should apply to any other user storage provider (including custom ones). The LDAP mappers that support the setting `Always read value from LDAP` will not work as expected because values won't be (always) read from LDAP if the user is already cached.

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

The user attribute values are the same when fetching users using a search and when querying by their identifier.

### Actual behavior

The user attribute values are not the same when fetching users using a search and when querying by their identifier.

### How to Reproduce?

* Create an LDAP provider and make sure the mapper corresponding to the `firstName` has the `Always read value from LDAP` enabled
* Import a user from LDAP
* Change the value of the `firstName` attribute in LDAP
* Go to `Users` to list all realm users and see the `firstName` attribute set with the value from LDAP
* Try to edit the user and see the `firstName` attribute with a different value

### Anything else?

See https://github.com/keycloak/keycloak/issues/34954#issuecomment-2515431058.

**Comment by mposolda** [comment]
The `Always read value from LDAP` was meant to be used for reading the particular attribute from LDAP rather than from Keycloak DB. However if the user is cached, the value from cache is still preferred and hence user won't be read from LDAP if there were some direct changes done to the user in LDAP. That is due the fact that if user is cached, Keycloak doesn't even try to call userStorage, but just use the `UserModel` from the cache.
 
AFAIR the caching support was added later to userStorage providers than LDAP mappers, so that is why this is maybe a bit confusing... If people prefer to really enforce reading always the value from LDAP after doing changes directly in LDAP server, it is also needed to set `Cache policy` of LDAP provider to `NEVER` .

For improve this, maybe the options are:
1) Just slightly update the description and tooltip for `Always read value from LDAP` . Maybe update description to something like `Read attribute from LDAP instead of Keycloak DB` ? And in the tooltip make it more clear, that cache has preference, so if people want to enforce reading from LDAP, the `Cache Policy` should be `never` (with a note about performance impact of this...)

2) Allow `Always read value from LDAP` just if `Cache policy` is set to `NEVER` . But this will be backwards incompatible and may have impact on performance if people are forced to never use cache...

3) Do something smart, like that if some data are directly changed in LDAP, Keycloak will have some "LDAP listener", which would allow to react to it and evict the user from the cache. Something like [debezium](https://debezium.io/) , but for LDAP servers (debezium itself unfortunately doesn't support LDAP AFAIK and I don't have clue if something like this exists in LDAP. I can imagine something can exists for MSAD, however probably not LDAP standard, but just guessing...)

4) Something else?

My preference is (1) as it is easiest, backwards compatible and just make it more clear what the switch is supposed to do. The (3) is also feasible IMO, but will require some searching if something exists for LDAP.

Maybe we can also mention debezium in the docs for custom userStorage providers as it can be used if people have their users in the DB, which has debezium support?

**Comment by pedroigor** [comment]
I would not do (3) because this sounds more like a use case for SCIM. I'm also not sure how much LDAP vendors support such mechanisms, but it makes more sense to use SCIM as the main mechanism to sync identities from external user storage in the future . If we can avoid vendor lock-in (and - more - proprietary mechanisms) and favor standard-based solutions that span different vendors, it will be better.

The option (1) sounds good to me. It should make the design/behavior of the LDAP provider more clear as I did not find anything related in our documentation.

> Maybe we can also mention debezium in the docs for custom userStorage providers as it can be used if people have their users in the DB, which has debezium support?

I'm not sure because it means we need to evaluate Debezium, document, and support the integration. I would say it deserves a specific epic/issue and discussion. I think Debezium not only can help with user storage but perhaps also help with upgrades.

**Comment by rmartinc** [comment]
Taking a deeper look to the issue, I think that it is more in the model (infinispan/storage-private) side than in the ldap side. The root cause is the infinispan is returning the cached entry directly in some methods (getUserByUserame or getUserById) but calling the delegate (UserStorageManager) in searchForUserstream. The latter always validates the entry calling ldap via guuid. So the issue is some methods are validating the entry and other methods are not validating it.

We can change to always validate or to not validate cached entries.

If we decide to not validate cached entries the problem is that we are changing the current behavior.  Although it can make sense because (you can remove the cache with NO_CACHE or set the cache to some value MAX_LIFESPAN), people can complain that ldap is not detecting changes as before. Note that doing this we are improving searching users in ldap providers when importing a lot (the guuid search is avoided while cached).

We can also try to do the other way around. Try to call the validate when returning from cache in the infinispan methods (getUserById/getUserByUsername for example). Although in this case the cache setting is a bit meaningless.
