### ISSUE TITLE
Login stuck when using 26.0.7 version with old browser(palemoon) or desktop office application(px ms teams, or outlook) to office365

### ISSUE THREAD

**Issue by akops76** [keycloak/keycloak#35896]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

We have a production keycloak installation running 26.0.6. The keycloak is used to login to our office 365 tenant using saml authentication.
After upgrading to 26.0.7, our users who use palemoon browser and the ones who use MS desktop applications (ms outlook or ms team app) cannot login to office365.
Specifically the authentication at the keycloak login page is successfully, but the page is stuck at redirecting.

During the problem, no error is logged at the logfile.

When using a modern browser (chrome, brave) the login to office365 is successfully.
The problem was solved after reverting to 26.0.6

![keycloak_stuck](https://github.com/user-attachments/assets/6225f549-f171-4572-997e-3ffe7c7450ac)

### Version

26.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

Ours users should login to office365 when using the ms desktop apps and older browsers as such palemoon.

### Actual behavior

When a user is trying to login to www.office.com, with saml authentication with keycloak he pass successfully the authentication part of keycloak login, but the page is stuck for ever with the message "Redirecting, please wait.".

### How to Reproduce?

Try to login to a office365 tenant with saml authentication and keycloak 26.0.7

### Anything else?

We have also tried to login to another office365 tenant with a second installation of keycloak 26.0.7. The same problem occured.

**Comment by rmartinc** [comment]
This is probably because of https://github.com/keycloak/keycloak/issues/33071 and the `requestSubmit` change. This was reverted for SAML in https://github.com/keycloak/keycloak/issues/35488 because some of our old tests for the old adapters failed. So it will be fixed in 26.0.8. You can try with the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly) to be sure.

But, nevertheless, `requestSubmit` is quite old, it's supported by all [major browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) and it will be used sooner or later in keycloak (as soon as we can get rid of all our old adapters). You can always modify the theme to use your own ftl version.

**Comment by jonkoops** [comment]
Closing this issue as it will be addressed by #35488 in the next patch release. These user agents are not in our official support target though, so I would recommend upgrading nonetheless.

**Comment by jonkoops** [comment]
No, it means that we're not actively testing against them, so there is no guarantee that upgrading your Keycloak server won't break in these products. Not that we're going out of our way to be incompatible, it is simply the fact that we cannot reasonably integrate these products in our test suite.

Looking at the error it seems they are using some ancient embedded version of Internet Explorer, so it is really on Microsoft to fix this long term.
