### ISSUE TITLE
Client roles won't create (Forbidden) with Fine Grained Permission (without manage-clients realm-management role)

### ISSUE THREAD

**Issue by mpalavrov** [keycloak/keycloak#35974]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

When Fine Grained permission is used for Client, "Role" inside client can NOT be created without having the realm-management:manage-clients

### Version

26.0.7

### Regression

- [X] The issue is a regression

### Expected behavior

The client is created if the current Fine Grained permission is added

### Actual behavior

Forbidden screen is shown

### How to Reproduce?

Similar to https://github.com/keycloak/keycloak/issues/28633

**Comment by ssilvert** [comment]
@mpalavrov We are making some big improvements to fine-grained auth which may or may not solve your problem.  It will be out relatively soon as it is a top priority for us to make fine-grained into a supported feature.

Since fine-grained is still considered a "Preview" feature in its current form, I'm going to defer this issue for now.  Once we have the new fine-grained auth code complete, I encourage you to try it out in a nightly build and let us know if it fixes your problem.  If not, we will fix it asap.

Thanks for your patience.
