### ISSUE TITLE
Token Exchange setting incorrect clientId

### ISSUE THREAD

**Issue by nickzelei** [keycloak/keycloak#8756]
### Describe the bug

I'm attempting to do an internal-to-internal token exchange. The exchange returns successfully, but it appears that the `issuedFor` or `azp` claim is set to the incorrect client.

This poses a problem in that the exchanged token is not able to be refreshed with its access token because the refresh token is bound to the wrong client.

I'm exchanging the token so that I can get the scopes, etc from the target client. That works great here, but I then need to be able to use the refresh token to exchange it for a new access token that has those same scopes.
In the current state, I instead have to re-initiate the token exchange all over again.

I'm I understanding token exchange correctly here? I took it that you take a token from client A and are able to completely exchange it for a token from client B. The way this is currently set up, the token is exchanged for another client A token, but that has been enriched with scopes from client B.
Also, why is no identity token returned from the exchange?

### Version

15.0.2

### Expected behavior

The Access Token and Refresh token should have the `azp` set to the target client.

### Actual behavior

The Access Token and Refresh token are set to the starting client.

### How to Reproduce?

To reproduce, simply follow the internal-to-internal token exchange [docs](https://www.keycloak.org/docs/latest/securing_apps/#internal-token-to-internal-token-exchange) and inspect the tokens that are returned. The `azp` will be set to the starting client.

Once the tokens have been exchanged, attempt to issue a refresh against the target-client.

```
POST /realms/:realm/protocol/openid-connect/token

grant_type: refresh_token
refresh_token: <token>
client_id: target-client
```

Response:
```
{
    "error": "invalid_grant",
    "error_description": "Invalid refresh token. Token client and authorized client don't match"
}
```

This makes sense given the `azp` is for the starting-client, not the target.

### Anything else?

* [responseBuilder.getAccessToken().issuedfor(client.getClientId());](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java#L342)
* [responseBuilder.getRefreshToken().issuedFor(client.getClientId();](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/protocol/oidc/DefaultTokenExchangeProvider.java#L342)

**Comment by nickzelei** [comment]
I just came across this Keycloak issue and it seems related:
https://issues.redhat.com/browse/KEYCLOAK-19116?jql=project%20%3D%20KEYCLOAK%20AND%20component%20%3D%20%22Token%20Exchange%22

**Comment by moribvndvs** [comment]
Same issue here. I have also noted the `azp` is for the starting client rather than the target-client. If, in the refresh call, I reference the _expected_ target-client as the client_id, I get the same error. If I try to use the starting client instead (to match the `azp`), I get a different error:

```
{
    "error": "invalid_grant",
   "error_description": "Session doesn't have required client"
}

```

**Comment by EmadiGhobad** [comment]
The same issue on Keycloak 18.0.0, the exchanged token cannot be refreshed!

> {
>     "error": "invalid_grant",
>     "error_description": "Invalid refresh token. Token client and authorized client don't match"
> }

**Comment by pedroigor** [comment]
@nickzelei When exchanging the token you are actually issuing the token to the client making the token exchange so that this client and access some protected resource from the target audience.

The token should be issued to the client making the request and the RS to which the token is meant for should be basically validating this token to give access to a protected resource.

The scenario described by @moribvndvs makes sense for me and perhaps we need to update documentation. I sent this change recently https://github.com/keycloak/keycloak-documentation/pull/1581. It tries to clarify the conditions that should be met in order to successfully exchange a token after changing the token exchange due to some vulnerabilities that were found.

I can send more updates to the docs but I'm not sure if I'm following your use case to understand what we need to fix/update in code or in docs.

**Comment by nickzelei** [comment]
Preface: I no longer work at the company where I was utilizing this technology.

But the setup was such that we had two clients that we would authenticate clients through. The first (or starting) client was used to do the initial authentication. 
Then we would perform a token swap to the second client based on the company account the user was operating under. This would swap out the token and give them more specific scopes that was appropriate for the account they were acting as.

I assumed the token exchange was a true exchange such that it was as if the user fully authenticated through the target client, not just swapped.

But it seems to me that the swapped token is still bound in some way to the original authenticated client.
This makes the refresh logic a bit more complex because the original token doesn't become throw away such that we have to continually issue another swap once the swapped token expires.

**Comment by NeoVG** [comment]
Similar problem here. :-/

What I want to do is to use a confidential client to create a new user via POST request to the `/admin/realms/{realm}/users` endpoint, and then use the token exchange feature to acquire an access and refresh token for this newly created user, but bound to another, public client instead (as these tokens are intended to be used in our frontend).

With Keycloak 17 Legacy, I got it to work using the method described by @moribvndvs, namely putting the target client_id into _both_ the `audience` _and_ `client_id` fields and removing the `client_secret` field. This way I received a token that has both the source and target client IDs in its `aud` property and the target client ID in its `azp` property.

After upgrading to Keycloak 18 however, this workaround does not work anymore and the call to the token exchange endpoint results in `access_denied: Client is not the holder of the token`. Without the workaround (with having the source client ID in the `client_id` field and adding the `client_secret` field again, just as described in the documentation for the token exchange), it's back to the original behavior, having both the source and target client IDs in its `aud` property, but the _source_ client ID in `azp`. When I try to use this token with the target client, for example to refresh it on the frontend side, I get the same error @EmadiGhobad described, namely `Invalid refresh token. Token client and authorized client don't match`.

Now I ask myself: Is that, what I want to do, even intended to be possible? 🤔 Means: Is it a bug in Keycloak, or is it just not possible to use a confidential client to acquire a token for another, public client?

**Comment by pattersongp** [comment]
Hi @DGuhr are there any thoughts on this issue? I'm also experiencing the same blocker when upgrading to `19.0.1`. @NeoVG describes it [here](https://github.com/keycloak/keycloak/issues/8756#issuecomment-1177481542) succinctly.

**Comment by NeoVG** [comment]
BTW, we found a workaround, at least kind of:

Instead of initiating the token exchange with an access token belonging to a service account of the confidential client (that was acquired using client id and secret), I'm now using the public client to acquire an access token for an actual user (the "superadmin" ;)), who has the permission to impersonate every other user in the realm (using its username and password to login), and use that one to initiate the token exchange. Since now the source and target clients are the same, it works as intended.

Problems with this solution are 1) that the public client needs to have direct access grants enabled (which might not be an option for everyone) and 2) that this "superadmin" user might be a security issue.

**Comment by pedroigor** [comment]
@NeoVG It does not make sense to exchange a token from a confidential client for a public client.

**Comment by pedroigor** [comment]
Thanks for the discussion. If there is anything else to discuss, feel free to re-open.

**Comment by viltsuhanninen** [comment]
> BTW, we found a workaround, at least kind of:
> 
> Instead of initiating the token exchange with an access token belonging to a service account of the confidential client (that was acquired using client id and secret), I'm now using the public client to acquire an access token for an actual user (the "superadmin" ;)), who has the permission to impersonate every other user in the realm (using its username and password to login), and use that one to initiate the token exchange. Since now the source and target clients are the same, it works as intended.
> 
> Problems with this solution are 1) that the public client needs to have direct access grants enabled (which might not be an option for everyone) and 2) that this "superadmin" user might be a security issue.

did you manage this on 19.01? I've been trying to set up that workaround, but I keep getting 'Client not allowed to exchange' error (when using the internal to internal token exchange examples from the docs).  I get this error only when trying to do token exchange on a public client, seems to work fine when using a confidential client as `starting client`

**Comment by viltsuhanninen** [comment]
> > BTW, we found a workaround, at least kind of:
> > Instead of initiating the token exchange with an access token belonging to a service account of the confidential client (that was acquired using client id and secret), I'm now using the public client to acquire an access token for an actual user (the "superadmin" ;)), who has the permission to impersonate every other user in the realm (using its username and password to login), and use that one to initiate the token exchange. Since now the source and target clients are the same, it works as intended.
> > Problems with this solution are 1) that the public client needs to have direct access grants enabled (which might not be an option for everyone) and 2) that this "superadmin" user might be a security issue.
> 
> did you manage this on 19.01 @NeoVG ? I've been trying to set up that workaround, but I keep getting `Client not allowed to exchange` error (when using the internal to internal token exchange examples from the docs). I get this error only when trying to do token exchange on a public client, seems to work fine when using a confidential client as `starting client`

an update; I forgot to assign the public client to the client impersonators policy I had created, works now

**Comment by keliwath** [comment]
Same issue here. If "it does not make sense to exchange a token from a confidential client for a public client", what should we be doing to achieve this? The direct access grant workaround looks like a potential security issue.

**Comment by pedroigor** [comment]
@keliwath Yeah, the resource-owner password grant should be avoided and it is removed from the latest versions of the OAuth2 spec. Could you elaborate more about your use case and why you want to exchange a token to access a public client?

**Comment by keliwath** [comment]
@pedroigor Sure. I have an Angular SPA with two authentication workflows: the first one is the standard Keycloak login with a public client, this works fine. In the second one I have to authenticate a user against a legacy system and then impersonate them in order to get a Keycloak token that can be used as normal from the SPA. For this I need a token issued to the public client. 

Up until version 15 I was using exactly the same workaround as moribvndvs in this thread: setting "client_id" to the target public client in a token exchange using a token from a confidential client using the client credentials grant. This produced a token with the azp claim set to the public client, and everything worked fine.  

But now we have upgraded to version 18 and as stated by NeoVG this doesn't work anymore, I get the error `Client is not the holder of the token`. If I modify the exchange token call to use the confidential client then the exchanged token can't be used in the Angular SPA because there is no user session associated with the public client (since the azp is different). 

Using the password grant to impersonate the user works, of course, but I would rather avoid it. Maybe I've misunderstood what token exchange actually is, but Is there any way to get a token issued to the public client in this scenario?

**Comment by pedroigor** [comment]
Allowing public clients to exchange tokens opens security holes and that is the reason behind the last updates we did in this area. Conceptually, it is also wrong because a public client is conceptually a client and not a resource server.

You might consider looking at some SPA architectures in this [specification](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#page-6). In particular, the first one is related to both SPA and API living within the same domain.

Another possible approach is to provide your own custom `TokenExchangeProvider` implementation so that you can support your legacy system as an additional subject token type.

**Comment by dazasa** [comment]
Do someone have an example how to overwrite the TokenExchangeProvider?

**Comment by pedroigor** [comment]
But `masterClient` is the requesting party, right? As such the token is issued to that client and not the `audience`.

The token however is built to be used at the `audience`. And the `audience` must know that the client that obtained the token was the client that did the exchange.

**Comment by piabor** [comment]
The problem is still there in version 20.0.2. However, as mentioned previously in the thread, changing the client id and secret from starting client to target client in the token exchange request returns an access token and refresh token that is for the target client.

I believe the token exchange request in the Keycloak documentation should be updated (yes, it is still incorrect, but we never know maybe it is a bug, after all, it is a preview feature).

**Comment by doflo-dfa** [comment]
@pedroigor ... I was curious what's the right way to do this ? ... why is going from a confidential client to a public client generically bad ?

I mean the issue with refresh and id tokens not following audience minting hints certainly seems like a bug and I follow your validation logic but it also seems like a wont-fix-bug because it's not what we should be doing so given a number of people here have use cases that are not possible is there guidance on how these flows should work.

In our scenario we have an SPA which I would assume is a common scenario using a public client and we have multiple server side API's utilizing a confidential client authing with JKWS assertions .. 

we would like to use a TOKEN_EXCHANGE scenario when an existing user attempts to sign up rather than returning that the user is already on our system we would like to send them a OTP to their email to continue the signup (new) or to login them in (existing) to do that we need to TOKEN_EXCHANGE from our API (backend of signup) to our SPA (public client)

I can not use a confidential client in an SPA ... and why would I want to use a public client server to server.

**Comment by pedroigor** [comment]
Based on this [draft](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps) you should use the Backend for Frontend Proxy (BFF). If I understood your use case correctly.

This architectural pattern allows you to use a confidential client to act as a mediator between your public client and proxy.

From the AS perspective, the behavior we had before is plain wrong and risky to support. As I mentioned before, we had CVEs related to this behavior.

**Comment by doflo-dfa** [comment]
So is the thought that eventually the keycloak-JS project would have some type of a BFF proxy project as a companion ?

I only bring it up to make sure I’m not missing something. I’m guessing that the BFF proxy is in fact itself additional code that’s essentially handling that communication hand off between the public and the private clients.

Admin User
(202) 600-9049
***@***.***
doflo.com
________________________________

**Comment by pedroigor** [comment]
Yeah, it is additional code and adds more complexity on the client side: development and deployment-wise.

I don't think we are going to provide a BFF-proxy-like component for the JS adapter.

TBH, I'm almost convinced that we should somehow enable the use case that you are doing as it looks similar to what others are trying to do. As long as we enable it very explicitly through configuration and with the appropriate permissions to allow it, I think we can support it.

Do you mind creating an RFE describing the use case and the requirements? We would then invite others to chime in and give their thoughts.

**Comment by doflo-dfa** [comment]
Understood .. and honestly as long as there are guardrails anything implemented would have to be more secure than some of the other workaround solutions that are being proposed... 

Even if there was a concept of a hybrid client that allowed for a service account attached to a public client ... or essentially allowing limited public mode (secretless) interactions on a confidential client

**Comment by pedroigor** [comment]
> Understood .. and honestly as long as there are guardrails anything implemented would have to be more secure than some of the other workaround solutions that are being proposed...

Exactly. When the token exchange was implemented, it was still a draft in IET. As a result, we ended up not implementing some parts of the spec like:

* The standard makes a clear distinction between the `delegation` and `impersonation` semantics and we mix them both. For us, impersonation is what the specs define as delegation. And our "impersonation" (which is a delegation accordingly to the specs) is not based on standards and does not support key params related to the actor (the entity actually impersonating another subject)
* The specs do not define how to support token exchanges for public clients. The focus there is service chaining and securing RS-RS communication. The specs is open to how public clients should be supported and we ended up with some behaviors (like the use case you are proposing) that are at the very minimum contradictory and wrong if you take into account how sensitive it is to allow token exchanges.
* We do not properly implement RT support. For instance, by default, we should not issue RTs at all because the spec is focused on the RS-RS use case. We need to be more strict about issuing RTs and probably introduce permission to explicitly allow it for a particular client/token exchange context.

The use case you are proposing is an example of how contradictory it is to issue a token, through token exchange, from a confidential client (or even from another public client) to a public client. It does not make sense given that access tokens are meant to access protected resources at an RS.

**Comment by doflo-dfa** [comment]
I think the most common use case is simply one of conferring identity ... I mean moving from confidential to public that is all I would assume ... for that scenario you are only protecting what you are comfortable protecting via a very public contract and so simply being able to steer the audience correctly while providing a access refresh and id token ... that probably solves a majority of the use cases at least from what I can glean from the comments here.

Even if it requires a second token exchange using the public client via  the access token that spans from the confidential to public client that would probably be acceptable to most.

Private Client -> [public client azp access_token] -> public client -> [properly based access refresh and (id) ]

? I mean the two problems that were blockers were the azp not including the destination client when setting the audience and then the fact that the refresh token pointed to the original client ... so the above scenario ... while it invokes an extra non requested subject exchange ... still keeps things sane ?

**Comment by Ketec** [comment]
User Z can impersonate B,C
D can impersonate only E,F.

Or even each group having "group admins" who can only manage and impersonate users within their group. The KC impersonation role does not allow that. It's just a generic superadmin feature that grants access to impersonate everyone.

This is why the confidential -> public is important - you can control who and if gets to impersonate who through your own secure API layer. Or even set up User granted access to impersonate them with a time limit.

**Comment by franzmoca** [comment]
I am trying to use the external to internal token exchange to import an user from an external idp and then use the generated token in a web application using the JS adapter.

When I try to init the javascript adapter with the generated token I encounter the same issue with the refresh token.

What would be the correct way to implement my use case?

For now as a workaround I am considering implementing a custom TokenExchangeProvider SPI that sets the azp to the targetClient, but I would prefer a more robust and maintenable solution.

**Comment by Ketec** [comment]
There isn't.  That's the conclusion I reached after two days of trialing potential alternatives.

So today I had to set up a maven project, extend default spi (hard since you can't access lots of private properties). Build and deploy jar - with default as I'd (git build spi override refused to swap to custom id).

It now needs rebuild and testing after every kc update.

There is also a third line that needs a fix - for refresh token it looks at source client if it's allowed, not target.

**Comment by EmDee** [comment]
> There is also a third line that needs a fix - for refresh token it looks at source client if it's allowed, not target.

This is what confuses me _a lot_. What is the sense in being able to request a refresh token (via `requested_token_type`: `urn:ietf:params:oauth:token-type:refresh_token`), but _not_ being able to refresh the token?

**Comment by gassan** [comment]
Use keycloak 17 with  target id and target secret.
They do not even want to introduce a config variable to disable the access_token.auz == client_id check introduced in kk18.

**Comment by nschipperbrainsmith** [comment]
> ncept of a hybrid client that allowed for a service account attached to a public client ... or essentially allowing limited public mode (secretless) intera

After putting in quite some effort into setting up the token exchange logic, so an admin user could impersonate another user. And working through the hurdles of the fact it is also still semi in preview, I also hit upon this issue. The flow from within Keycloak sadly was and is too difficult for the support staff of the project. And this seemed like a nice, sensible way to go about it. First, I request the API server to exchange the token for the user and then refresh the client with the newly received tokens using the `Keycloak.init()` method. This sadly always results in: 

`<<keycloak url>>/realms/<<realm>>/protocol/openid-connect/token` 400 bad request
`Invalid refresh token. Token client and authorized client don't match`

Meaning, like most others here, I would have to build a BFF-proxy just for one piece of functionality that I would be more than comfortable configuring through a setting. Allowing the confidential client to exchange the token to the public client with which the users on the frontend login. With the correct `AUZ`

**Comment by garronej** [comment]
If you're trying to use Token Exchange for impersonation and are stuck with the `azp` claim issue, I might have an alternative approach based on a custom Admin theme:

https://github.com/user-attachments/assets/e8f3ee2b-cb32-49d3-bfe9-f81968a45339

It's detailed here: https://github.com/keycloakify/keycloakify-starter/tree/direct_impersonation?tab=readme-ov-file
