### ISSUE TITLE
Keycloak return redirect url with wrong port

### ISSUE THREAD

**Issue by alimzhanovamir** [keycloak/keycloak#8876]
### Describe the bug

When developing a frontend for a localhost, I connect to the backend and go through authorization through the keycloak. Keycloak always after redirection substitutes the port on which the backend is running (8080), if you launch the frontend on localhost:8080, then everything will be fine, but if on a different port, then the redirect url will be with port 8080 and authorization does not work.

How to make it return the redirect url with the correct port?

### Version

12.0.4

### Expected behavior

Keycloak returns the correct redirect url and authorization passes

**Comment by stianst** [comment]
Pretty sure this one isn't valid, as you're configuring the full front-end url including the ports, but there's not enough information to understand what you're doing or what's not working. Please provide a better description, including steps to reproduce the issue.

**Comment by KOVCHENKO** [comment]
@stianst 
The situation is the following. 
There are two services that are running locally:
1. Front-End (FE) -> localhost:8083
2. Back-End (BE) -> localhost:8080

FE makes a request to BE and BE is authorized using keycloak.
First, I tried to override the following redirect method (_org/keycloak/adapters/OAuthRequestAuthenticator.java -> String getRedirectUri(String state)_)
To get the necessary redirect uri with the replaced port when authenticating, i.e.
_https://auth.env6.nonprod.atyponrex.com/auth/realms/MASTER/protocol/openid-connect/auth?response_type=code&client_id=master-backend&redirect_uri=http%3A%2F%2Flocalhost%3A8083%2Fsso%2Flogin?forwardIdp%3Dalm%26target_url%3D%252Fdashboard&state=2fb05ca7-3466-4b87-9d9e-9479c77e2c62&login=true&scope=openid&forwardIdp=alm&addChannel=true_

In this case, it seems that now I have a port not from BE, but from FE.
It has been overridden to test as follows:
```
@Override
  protected String getRedirectUri(String state) {
    StringBuilder sb = new StringBuilder(super.getRedirectUri(state));
    Optional.ofNullable(facade.getRequest().getQueryParamValue(FORWARD_IDP))
        .ifPresent(forwardIdp -> sb.append(String.format("&%s=%s", FORWARD_IDP, forwardIdp)));
    sb.append("&addChannel=true");

    String rtrnUrl = sb.toString();
    String referer = facade.getRequest().getHeader("referer");
    try {
      URL refererURL = new URL(referer);
      int portFromReferer = refererURL.getPort();
      return rtrnUrl.replace("8080", Integer.toString(portFromReferer));
    } catch (MalformedURLException e) {
      e.printStackTrace();
    }

    return null;
  }
```

Second, there is a place where I found the changing of redirect uri:
_org/keycloak/adapters/OAuthRequestAuthenticator.java -> AuthChallenge resolveCode(String code)_
`strippedOauthParametersRequestUri = rewrittenRedirectUri(stripOauthParametersFromRedirect());
`
The place has been also overridden otherwise I will get the 400 error with _'Invalid redirect url'_ message

Third,
The last place where changing of redirect uri has been found is the HttpServletResponse interface. It is located in the redirectURLCC field. I tried to use the following possibility to change it:  
`rs.encodeRedirectURL("http://localhost:8083/dashboard");
`
But in this case, I get null in redirectURLCC.

Could you please clarify if there is an easier way to change redirect uri?

**Comment by stianst** [comment]
I'm not really following to be honest. Can you update the description a bit, and please fill in the actual/expected behaviour and steps to reproduce?

**Comment by abstractj** [comment]
@stianst considering that it has been a while since we got an update on it. This GH issue should be closed due to the lack of details. Do you disagree?
