### ISSUE TITLE
Subdomain wildcard in client valid redirect uri

### ISSUE THREAD

**Issue by oliverabclabs** [keycloak/keycloak#8929]
### Description

One should be able to specify a wildcard for subdomains in the valid redirect uri field in Keycloak clients.

E.g

https://\*.foo.com/\*

should allow:

https://bar.foo.com

but not 

https://evil.com/evil.foo.com

### Motivation

Without this, any dynamically generate urls (like auto-generated preview deploys of websites with dynamic urls) dont work with Keycloak. This is very unfortunate.

Any criticism pertaining to security regard this is to my knowledge invalid, seeing as how we currently allow a user to input https://\* into valid redirect uris. And that is much more insecure.

**Comment by stianst** [comment]
This has been discussed quite a few times already. In the OAuth 2.1 specification (and also general best practices) the redirect uri should be a strict match, and not support wildcards in general. Using a wildcard even in the subdomain is not considered a good idea, and can easily lead into issues, so it's definitively not a recommended thing to do in production use-cases.

For dynamically deployed applications I would suggest looking towards dynamic client registration as a solution rather than using wildcards.

Now, with regards to generally supporting wildcards I'm okay with that, but not as a default option. For a while back we introduce client policies, which allows defining policies for a realm. The plan is that we will not support wildcards at all out of the box, except for development scenarios (with Keycloak.X we will have a specific dev-mode and prod-mode, which enables this). 

Wildcards in subdomains is not something we will implement ourselves, but I would be happy to accept a contribution to this if it is not enabled by default, and controlled with client policies.

**Comment by navrocky** [comment]
For now you can just use "\*" to ignore any restriction of redirect uri. It works for me.
![image](https://user-images.githubusercontent.com/6428186/144866655-f60dd616-43cf-419f-8c2f-fce032b5b3b8.png)

**Comment by stianst** [comment]
> For now you can just use "*" to ignore any restriction of redirect uri. It works for me. ![image](https://user-images.githubusercontent.com/6428186/144866655-f60dd616-43cf-419f-8c2f-fce032b5b3b8.png)

That is very bad advice. Please do NOT do this in production.

**Comment by stianst** [comment]
I'm closing this for now, and have opened up a discussion on how we can proceed here:
https://github.com/keycloak/keycloak/discussions/9278
