### ISSUE TITLE
OIDC dynamic client registration does not respect application_type property

### ISSUE THREAD

**Issue by raman-nbg** [keycloak/keycloak#9000]
### Describe the bug

I want to use Keycloak's [OpenID Connect Dynamic Client Registration](https://www.keycloak.org/docs/latest/securing_apps/#openid-connect-dynamic-client-registration) as described in the docs. The docs mention that the [OpenID Connect Standard for Dynamic Client Registration](https://openid.net/specs/openid-connect-registration-1_0.html) is implemented.

It seems like that the Keycloak implementation does not respect the property `application_type` that is part of the request body in the [Client Registration Endpoint](https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest).

Even when I set `application_type = native` Keycloak creates a client that has the access type `confidential`.
![image](https://user-images.githubusercontent.com/20013423/144614483-cf1ecdfc-8956-40e3-afe9-4ba1e5a62d22.png)

For me this seems to be a bug - at least the Keycloak implementation of OIDC DCR does not follow the specs.

### Version

15.0.2

### Expected behavior

It should be possible to create a client with the access type `public` using the OIDC DCR endpoint.

### Actual behavior

A client with the access type `public` can not be created by using the OIDC DCR endpoint.

### How to Reproduce?

The following POST request should create a client with the access type `public`.

```http
POST https://<keycloak-server>/auth/realms/<realm>/clients-registrations/openid-connect
Authorization: Bearer <token>
Content-Type: application/json

  {
   "application_type": "native",
   "redirect_uris": [
       "https://client.example.org/callback",
       "https://client.example.org/callback2"
    ],
   "client_name": "my-client",
   "subject_type": "public",
   "token_endpoint_auth_method": "client_secret_post"
  }
```

**Comment by mposolda** [comment]
@raman-nbg As you pointed, Keycloak does not have any support for the `application_type` property of the OIDC dynamic client registration. We don't plan to add support for it, so it will need to be community contribution if this is going to be added.

It will be needed to discuss first how exactly it can work. 

BTV. The OIDC field `application_type` and Keycloak field `access_type` are completely different things unrelated to each other.

If you want create public client, then you can use "token_endpoint_auth_method" with the value "none" instead of "client_secret_post" .
