### ISSUE TITLE
Import realm at startup

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak#9261]
### Description

Similar to the Wildfly distribution, we should also allow importing a realm at startup like when using `keycloak.import` in Wildfly distribution.

IMO, we should not allow this in production but only when running the `start-dev` command and for development/testing purposes.

That said, perhaps we could have a `--import-realm` option.

### Motivation

Improve developer experience by allowing importing realms at startup. Especially when running in a container.

**Comment by stianst** [comment]
Would have to be only for start-dev as you say, and not for start. However, I'm not sure I'm too keen on it regardless, especially since we're going to add the file-based map provider for the new store, with the ability to load realms/etc directly from files.

**Comment by overheadhunter** [comment]
As concluded in duplicate discussion #10216, this is vital for production environments (i.e. for `start`) in order to deploy preconfigured realms as end-users can not be expected to set up a realm matching the application's needs. Using deployment descriptors for k8s/compose/openshift/... is basically the norm today and are expected to set up everything without needing admins to log into each service individually in order to integrate them. See also https://github.com/keycloak/keycloak/issues/10216#issuecomment-1042937867.

**Comment by MikeShiner** [comment]
Really disappointed to see this wasn't included in 17.0.1. It's a requirement of our business, especially coming from older versions. Pre-baking realm into the images will have to do for now.

**Comment by shane-js** [comment]
> Really disappointed to see this wasn't included in 17.0.1. It's a requirement of our business, especially coming from older versions. Pre-baking realm into the images will have to do for now.

@MikeShiner I agree this is necessary for a standard sort of dev ops promotion process - can you please share for me and others how you baked it into your 17.0.1 image?

**Comment by omasseau** [comment]
Can we have an update of the docker container documentation with instructions to import realm at startup ?
https://www.keycloak.org/server/containers

The new documentation is really lacking compared to the old one : 
https://hub.docker.com/r/jboss/keycloak/

At least it should have the complete list of supported environement variables.
