### ISSUE TITLE
Issue using User Federation/LDAP provider in keycloak 16.1.0 with Java 8

### ISSUE THREAD

**Issue by sbappoo** [keycloak/keycloak#9320]
### Describe the bug

I have an LDAP configuration with Active Directory which works well with keycloak 14 and Java 8.

I tested the same LDAP configuration with keycloak 16.1.0 and I had the following error when I made a request to **test the authentication** of the LDAP configuration. 
![ldap](https://user-images.githubusercontent.com/39064501/147194073-95cfec0e-94ee-4409-aa22-520ceeaed229.png)
![ldap-keycloak](https://user-images.githubusercontent.com/39064501/147194084-8ac27a5c-84ac-4318-9ba5-b08847e5972f.png)

**Upon upgrading to Java 11, the issue was resolved.**

### Version

16.1.0

### Expected behavior

Based on the installation prerequisites: [https://www.keycloak.org/docs/latest/server_installation/#:~:text=Java%208%20JRE%20or%20Java%2011%20JRE](https://www.keycloak.org/docs/latest/server_installation/#:~:text=Java%208%20JRE%20or%20Java%2011%20JRE), keycloak 16.1.0 was supposed to support Java 8.

### Actual behavior

The 'Test authentication' fails in keycloak 16.1.0 when Java 8 is used and produces the  error: 'No such method error'.
![ldap-keycloak](https://user-images.githubusercontent.com/39064501/147195021-6e37d0f9-c235-4809-a66b-78796086dfd8.png)

### How to Reproduce?

Requirements:
1. Java 8
2. Keycloak 16.1.0

Steps:
1. Create an LDAP configuration in User Federation.
2. The 'Test connection' shall work fine.
3. 'The 'Test authentication' fails and produces the error 'No such method error'.

**Comment by darius-m** [comment]
I have encountered the same issue and reported it [here](https://issues.redhat.com/browse/KEYCLOAK-19911). Unfortunately, it may not have been explained properly in the Jira issue. It seems that the issue started in 15.1.0, according to issue #9180.

It may also be caused by an issue with the operating system or java package version:
 - OS: Centos Stream 8
 - Java: java-1.8.0-openjdk-1.8.0.312

UPgrading to java 11 fixes the issue (from what I could find, the `clear` method was added in JDK 9, and was unavailable in 8), but may not be the intended use case. This issue is somewhat important since 15.1.1 provides a security fix for versions before it.

**Comment by sighanse** [comment]
I had an identical issue on Windows 2019, latest OpenJDK8, while upgrading from 15.0.2 to 15.1.1.
Upgrading to OpenJDK11 solved the issue.

**Comment by shubhamarora97** [comment]
I have seen an identical issue with "Test Authentication" on keycloak 15.1.1 console. I am currently using Java 8 and want to know if there is any solution available with Java 8.

**Comment by crazyhaida** [comment]
We have the same issue of openldap integration with keycloak 16.1 on jdk 1.8. Is there any plan to fix this issue ? 

I donot see this issue being assigned to anybody ? Upgrading to jdk11 is not possible in existing deployments. Any workarounds for this issue ?
