### ISSUE TITLE
Error getting page when using KeycloakInstalled adapter

### ISSUE THREAD

**Issue by HannahBrown** [keycloak/keycloak#9401]
### Describe the bug

I use the keycloak installed adapter in a desktop java application. Previously, I would go through the login process, then the browser would show a screen that said 'Login Successful. You can close this page' while the application comes up in the background. Now, after logging in, the screen says 'Error: Page not found', though the application still opens successfully.

### Version

16.1.0

### Expected behavior

The browser should show that the login was successful.

### Actual behavior

The browser says redirects to a page that returns a 404.

### How to Reproduce?

The url I am redirected to (that previously said success and now says not found) is https://cerberus.mometrix.com/auth/realms/mometrix-internal/protocol/openid-connect/delegated
Navigating directly to this page without going through KeycloakInstalled gives the same result as going through KeycloakInstalled.

**Comment by NorbertSandor** [comment]
The same error occurs with 17.0.0 :(

**Comment by paoven** [comment]
Hi, I'm having the same issue! [This commit ](https://github.com/keycloak/keycloak/commit/85240c960601731d836d4e2e807075018aba0378) removed kcinit support as well as the endpoint /delegated.
The latest docs are still referencing KeycloakInstalled Java adapter which relies on the existance of that endpoint. 

@stianst  I would really appreciate understand if KeycloakInstalled adapter will be deprecated too and which are the alternatives to obtain cli/destkop oic authentication in keycloak.

Many many thanks, kind regards

**Comment by paoven** [comment]
As it looks that Java Adapters will be deprecated I managed to fix this with a CustomKeycloakIntaller and with a Realm REST API extension as reported in https://stackoverflow.com/questions/69001263/keycloak-desktop-java-adapter-deletes-keycloak-identity-cookies?rq=1

**Comment by ocafebabe** [comment]
This is really a shame and the latest documentation doesn't mention that this adapter had been deprecated at all!

@paoven could you please share your custom implementation of the KeycloakInstalled class?

**Comment by ocafebabe** [comment]
I've tried to recreate the missing endpoint by using a custom realm rest resource provider:

```java
public class CustomResourceProviderFactory implements RealmResourceProviderFactory {
    public static final String ID = "protocol";
    ...
}

public class CustomResourceProvider implements RealmResourceProvider {
    @GET
    @Path("/openid-connect/delegated")    
    public Response get(@QueryParam("error") boolean error) {
        ...
    }
}
```

But unfortunately I'm still getting a "**page not found**" error as it seems that I can't map the URL under "protocol" and there is no way to configure this URL to something else as it's hardcoded in KeycloakInstalled...

Is there a way to overcome this?

**Comment by bekwam** [comment]
You can look over a PR I submitted that's still pending a merge.

[Pull 12796](https://github.com/keycloak/keycloak/pull/12796)

I ended up restoring the methods to the Keycloak class rather than creating my own custom endpoints.

**Comment by ocafebabe** [comment]
Yes, I did see your PR but unfortunately I don't think it's going to be approved since this module is getting deprecated.

**Comment by adame11** [comment]
Hi. I am submitting a [Pull Request 15180](https://github.com/keycloak/keycloak/pull/15180) that proposes fixing this problem the way @stianst suggested that it be fixed in his comments in [PR 12796](https://github.com/keycloak/keycloak/pull/12796). This is my first time contributing so I hope I've addressed all the concerns involved. Basically, instead of redirecting back to the server, show a simple: "Authentication successful. You may close your browser" or "You are logged out. You may close your browser." Although it would be nice to have, I did not try to address adding customizable formatting (or wording), but those could reasonably be added later I'm sure. I do not think the KeycloakInstalled adapter is deprecated, as @stianst suggested at the time that if the fix was made, it could be incorporated into the upcoming release. I hope it's not too late! Thanks for your time.

**Comment by adame11** [comment]
For what it's worth, I've added support in https://github.com/keycloak/keycloak/pull/15180 for customized html and customized text for login and logout when using the Keycloak installed adapter. You can either customize the plain text messages or HTML. For HTML, it works by setting a Path to an optional static single HTML page to serve. Can only serve single page HTML (css and images are not served separately because webserver shuts down immediately after serving the single page). 

All of this is based on the assumption that the KeycloakInstalled adapter for Java swing, is NOT on the list of deprecated adapters: https://www.keycloak.org/2022/02/adapter-deprecation.html? 

We are using this customized adapter successfully, with nicely formatted HTML that matches our login page for login and logout success. It is a relief to not have the "We are Sorry, page not found" error and now users don't have to look at plain text messages either.

**Comment by bekwam** [comment]
Great job!  They are deprecated according to this post `https://www.keycloak.org/2022/02/adapter-deprecation`.

But this ticket was important because they were broken prior to the deprecation decision.  Your fix will buy one of my customers some time and they can stay current while they look for alternatives.

**Comment by jptned** [comment]
An [update](https://www.keycloak.org/2023/03/adapter-deprecation-update) about the deprecation of the Java adapters:

> The Keycloak Java adapters will remain for a while though, at least towards the end of the year, but likely not be removed until early 2024. At the same time don’t expect the adapters to be updated in terms of adding new features, enhancements, or supporting newer versions of Tomcat, Jetty, WildFly, or Spring.

I hope #15180 can be merged in the near feature, since `KeycloakInstalled` is practially unusable with the current version.

**Comment by jsorah** [comment]
Moving to backlog since adapters are deprecated. I do see there is a related PR present and will see if we can get someone to review that.

**Comment by mposolda** [comment]
Closing this issue as the plan is to remove KeycloakInstalled adapter in Keycloak 25 (together with other Keycloak OIDC and SAML adapters) as stated in https://www.keycloak.org/2024/03/keycloak-2400-released (the section "Java adapter deprecation and removal", which is about the removal of all java OIDC adapters).

If anyone is still interested in KeycloakInstalled, the option might be either to rely on older Keycloak release (not ideal) or move it to separate extension and maintain it yourself. The extension could then be possibly added to be listed in Keycloak extensions - https://www.keycloak.org/extensions.html
