### ISSUE TITLE
Map storage factories are processing events even when they are not configured

### ISSUE THREAD

**Issue by sguilhen** [keycloak/keycloak#9483]
### Describe the bug

When `MAP_STORAGE` feature is enabled, the map storage provider factories end up processing events even when they are not configured as the default provider factory for a component. So, when a `realm` is removed, for example, the roles associated with the realm are also removed, triggering a `RoleRemovedEvent`. Users associated with the realm are also removed, triggering a `UserRemovedEvent`. All factories that register themselves with the `KeycloakSessionFactory`  as event listeners receive the events, including the map storage factories.

The problem is that the map storage factories are attempting to handle the event even when they are not the default providers for the components. This results in a variety of errors, ranging from the `ClassCastException` thrown by the `MapClientProviderFactory` when it tries to cast the provider obtained from the session to `MapClientProvider`, to `NullPointerException` thrown by the `MapUserLoginFailureProviderFactory` when trying to obtain the storage provider as part of its `onEvent` logic.

### Version

16.1.0

### Expected behavior

The map storage factories should not attempt to process events when they are not configured as the default providers for the components, and removal of realms should work fine when using legacy JPA providers with the `MAP_STORAGE` feature enabled.

### Actual behavior

The map storage factories are erroneously attempting to handle events that are not meant for them, resulting in a range of different errors when, for example, a realm is removed.

### How to Reproduce?

Easiest way to reproduce is to enable the `MAP_STORAGE` feature but not configure any default provider for the components and then try to run any test (for example, DeclarativeUserTest) that adds and removes realms/users/roles.

Note that running the tests on Undertow will configure server with the either the jpa or map (when using the `-Pmap-storage` profile) providers for all components (see `keycloak-server.json`), and the errors do not happen because the presence of a default provider (either jpa or map) avoids the situation where we have more than one factory initialized and registered as a listener.

**Comment by hmlnarik** [comment]
The proposed **expected behaviour** is incorrect. Map storage should process the events regardless, it has to process it in the context of that configured storage though. For example, should a role be deleted in JPA storage, an event is generated, and the map storage that makes use of this role should be able to remove all references to that role from its storage.

**Comment by sguilhen** [comment]
Design discussion for the event processing by map storage factories has been started at https://github.com/keycloak/keycloak/discussions/9764

**Comment by hmlnarik** [comment]
This is not a bug but expected behaviour. Map storage should (and now also does) process the events from other storages as well.
The #11076 improved the state and cleared `ClassCastException`s. Further work like pushing the [predefined invalidations](https://github.com/keycloak/keycloak/blob/c05898365528d19bf62677b97925b21b954365d9/model/map/src/main/java/org/keycloak/models/map/common/AbstractMapProviderFactory.java#L61-L76) to a separate package so that other objects can hook in those events can be done later
