### ISSUE TITLE
Newline in localization messages causes uncaught syntax error in account console v2

### ISSUE THREAD

**Issue by Lukas0907** [keycloak/keycloak#9503]
### Describe the bug

A properties file with the property `test=foo\nbar` leads to the following JavaScript code that is embedded in the HTML code of the account console v2 (`http://<keycloak>/auth/realms/<realm>/account/`):

```javascript
var l18nMsg = JSON.parse('{..., "test":"foo\nbar", ...}');
```

The string `foo\nbar` cannot be parsed by JavaScript and therefore a SyntaxError is raised which is shown in the developer console.

### Version

16.1.0

### Expected behavior

Backslashes in the properties file must be escaped, e.g., `foo\nbar` must be serialized as `foo\\nbar`.

### Actual behavior

Backslashes in the properties file are not escaped which leads to a SyntaxError exception:

```javascript
> JSON.parse('{"foo": "\n"}')
VM536:1 Uncaught SyntaxError: Unexpected token 
 in JSON at position 9
    at JSON.parse (<anonymous>)
    at <anonymous>:1:6
```

### How to Reproduce?

1. Create a properties file `messages_en.properties` with the content `text=foo\nbar` in the directory `resources` and deploy the JAR file.
2. Open the account console v2.
3. Observe the exception in the developer console.

**Comment by Lukas0907** [comment]
Note that this means that the account console is unusable after login (`failed to initialize keycloak`):

![image](https://user-images.githubusercontent.com/591792/148933577-cfcfbe97-7e6e-422d-adff-b02bc3a114a7.png)

**Comment by ahus1** [comment]
Thanks for reporting this. I can reproduce this issue. 

Could you please provide some details about the scenario when you want to add "\n" and other characters that would need escaping in the messages? So far the messages didn't contain such a character. This scenario could help me to understand the impact. 

Thanks!

**Comment by Lukas0907** [comment]
Thanks for taking a look. We have a custom theme with localization messages that can span multiple lines. These messages are not related to the account console but unfortunately all localization messages are printed in its HTML code.

**Comment by ahus1** [comment]
In that case, I suggest the following workaround, assuming that the `index.ftl` is part of your custom theme:

In the original theme, there is the following line: 

```
var l18nMsg = JSON.parse('${msgJSON?no_esc}');
``` 

The freemarker snippet `${msgJSON?no_esc}` will print it unescaped, leading to the issue you reported. 

When you change this to 

```
<#outputformat "JavaScript">
var l18nMsg = JSON.parse('${msgJSON?js_string}');
</#outputformat>
``` 

Freemarker will print it as an escaped JavaScript string. 

Please note that at the moment msgJSON will still contain single quotes escaped as `%27` as implemented in `AccountClient.java`, and you'll need to call `unescape` on the string like `Msg.tsx` does that in the original theme. Maybe a fix for this issue would change that as well, as this kind of escaping might no longer be necessary in the future. 

Please let me know if this workaround works for you, and if you see that it could break something else. 

Still, keep this issue open so that this escaping issue you reported and maybe also the escaping of quotes can be worked on.
