### ISSUE TITLE
Keycloak UI does not show the UMA authorization policies

### ISSUE THREAD

**Issue by aaltenbernd** [keycloak/keycloak#9545]
### Describe the bug

Hello. We are facing the same problem as described here:

https://keycloak.discourse.group/t/why-does-the-keycloak-ui-not-show-the-uma-authorization-policies/10069

Are there alternative ways around this or will this be fixed? Also we ask ourselves the same questions:

"Is there a way I can see the set of UMA policies from the Keycloak UI?

Alternatively, can I add standard (non-UMA) policies from the REST API? I cannot find the documentation for it, and don’t want to reverse engineer in case it gets deprecated somehow…"

### Version

10.0.2

**Comment by ichantzaras** [comment]
Hi all, 
Linking also a duplicate question
https://keycloak.discourse.group/t/view-uma-created-policies-through-admin-console/1731

**Comment by pedroigor** [comment]
Sorry for the late reply. We are not showing UMA permissions and their policies in the UI by design.

The main reasons for that:

* Impact on UX when you have a huge number of permissions/policies created by clients
* Policies associated with UMA permissions are hard to manage because they are created using UIDs as their names, without any description, hence providing a bad UX
* Clients can always manage these permissions from the Policy Endpoint

It should be quite trivial to enable them on the UI the hard path is how to do it without make the UI worse.

I'm not sure if we are going to be able to work on it due to other priorities but any contribution is welcome.
