### ISSUE TITLE
Clustering support in operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9730]
Make sure Keycloak can properly (manually) horizontally scale.

**Comment by vmuzikar** [comment]
* Leverage clustering functionality in Keycloak.
* Create ClusterIP Service for Keycloak.
* Investigate if we need StatefulSet or stick with Deployment.
* Make sure Infinispan instances in Keycloak can talk to each other.
   * Discovery of other Infinispan nodes, (probably DNS ping)

**Comment by jonathanvila** [comment]
Investigation : 
* in the Go lang operator the health checks are not considering the Infinispan cluster
* Infinispan needs a scaling process that allows the rebalancing process . This means , specially on down scaling, that only 1 pod is killed at a time. In order to not kill main and backup nodes at the same time. 
* In the old operator this was done using a Statefulset, that scales 1 by 1 pods.
* So the "ideal" process would be, when scaling from 10 to 5 : 
  * a pod kill request is sent
  * jgroups in that pod sends the unsubscribe message
  * all pods transition to ready=false , because the healthcheck is considering the infinispan cluster status
  * pod is killed
  * infinispan rebalances
  * all pods become ready=true
  * k8s starts again the process ( until it reaches the desired number)
* For this process there are 2 importants points : 
  * a k8s resource that allows scaling 1 by 1
  * health check of a pod includes a infinispan cluster health check
*  In the current PR : 
  *  it is using a Deployment instead of a Statefulset
  * to have the 1 by 1 scaling we will specify : 
     ```
       strategy:
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
            type: RollingUpdate```
  * there's no check on the infinispan cluster therefore it could happen that pods get killed so fast that main and backup can be deleted without giving time to infinispan to rebalance.

**Comment by jonathanvila** [comment]
In order to adapt the health check to include infinispan : 
* file : https://github.com/keycloak/keycloak/blob/b4c837f14810d09f016ebf37d346339957dffaa3/quarkus/runtime/src/main/java/org/keycloak/quarkus/runtime/services/health/KeycloakReadyHealthCheck.java#L42
* But, in theory Quarkus is adding the infinispan health check in the global health check so it should be already done.

**Comment by andreaTP** [comment]
@jonathanvila where can I read about:

> But, in theory Quarkus is adding the infinispan health check in the global health check so it should be already done.
?

**Comment by andreaTP** [comment]
As discussed I'm taking over this issue.

**Comment by jonathanvila** [comment]
> 

Well, in theory all the extensions are adding their health checkd .... as mentioned here https://quarkus.io/guides/smallrye-health#extension-health-checks  , but I haven't info about that specific to Infinispan.....

**Comment by lanmarti** [comment]
Hi, I checked the operator guides currently available on https://www.keycloak.org/guides but couldn't find anything related to clustering/scaling. Is clustering supported for the Keycloak v2alpha1 CRD, and if yes, is there a guide available on how to set it up?
