### ISSUE TITLE
Make sure attributes with null or empty value are not persistent for all objects

### ISSUE THREAD

**Issue by vramik** [keycloak/keycloak#9741]
### Description

I should not be possible to store attribute with empty or `null` value across all objects. 

It has been done for clients within https://issues.redhat.com/browse/KEYCLOAK-16676.

This issue is about to make it consistent. Maybe also migration step which would remove all current empty and `null` attributes from legacy jpa could be introduced.

**Comment by mhajas** [comment]
This issue is still relevant for JPA Map storage. In CHM and HotRod we have a test to check that undefined values are refused for `MapRealmEntity` entity implementation and `JPARealmEntity` failed that test. I created a commit that enables the test for JPA here: https://github.com/mhajas/keycloak/commit/24dfbdebcf00e2fb16c2975ecb5bcc7328b046fd. I believe it should be added as part of this issue.

**Comment by ahus1** [comment]
As announced to the community in [this blog post](https://www.keycloak.org/2023/10/map-store-removal), we are no longer developing the Map Store, and it will be removed from Keycloak's code base. Follow #24111 for the removal steps.
