### ISSUE TITLE
Enable Cross DC support for quarkus based keycloak distribution

### ISSUE THREAD

**Issue by DGuhr** [keycloak/keycloak#9831]
### Description

... and make sure tests also run for Dist.X.

From: https://issues.redhat.com/browse/KEYCLOAK-19367

**Comment by pedroigor** [comment]
Related to https://github.com/keycloak/keycloak/issues/10046.

**Comment by pedroigor** [comment]
This should be addressed once we integrate the new store and its support for CD.

**Comment by vmuzikar** [comment]
CC: @keycloak/storage-x

**Comment by hmlnarik** [comment]
> Reopening this as we should make sure cross-dc support works with Quarkus incl. both legacy and the new store.

Cross DC should only be available via native storage support in the new store in Quarkus, e.g. by using properly set multisite deployment of CockroachDB.

Cross site in legacy store is not going to be maintained in the future. Even if it would be possible to set up Quarkus legacy store configuration in the way that mimics existing cross site capabilities, it will not be continued because of its known limitations.

**Comment by pedroigor** [comment]
@hmlnarik Shall we close this issue and ignore cross-dc tests then? Or we should keep it until the legacy store is still there and supported?

**Comment by hmlnarik** [comment]
@pedroigor I have changed the title to indicate that this task is for legacy store, and closed it as not planned.

The relevant task for new store is #14069.

**Comment by mhajas** [comment]
@hmlnarik does this mean we are removing current cross DC tests and not running them at all for the legacy store?
