### ISSUE TITLE
Setting custom attributes for user does not work (with user profile enabled)

### ISSUE THREAD

**Issue by arnzel** [keycloak/keycloak#9889]
### Describe the bug

1. go to keycloak admin ui user attribute page
2. add any attribute with a value like "blub" with "1"
3. Saving the attributes
4. New added attribute disappears
5. Message "Success! Your changes have been saved to the user." appears
6. When reloading the page the attribute is still missing

### Version

15.0.2

### Expected behavior

The attribute is saved with the given value

### Actual behavior

The attribute is not saved but you get a message that saving the attribute is successful. If attribute cannot be save it would be good to know the reason

**Comment by arnzel** [comment]
I found out its because of the user profile feature. When i add property to user profile it works. But the behaviour of the gui ist still confusing. A hint why you don't see the added attribute would be good

**Comment by ssilvert** [comment]
I reproduced it.  You have to enable user profile.  The same problem happens on the new admin UI as well.  So I assume this is a problem with the REST API and not the user interface.

**Comment by quetzalcoatl** [comment]
I believe this is not a bug, but rather, a poorly-documented feature.

The 'attributes' tab seems to be meant to behave differently, depending on whever the `legacy provider` or `the new provider` for user-profiles system is used. I think the keyword name for that feature is `declarative user profiles`, and I'm pretty sure this is what it is turned on by that `enable user profile` switch you mentioned.

When you turn this feature on, many things change in the way user profiles are handled, and one of them is  
... how, where, and which attributes are displayed.

Here you can find some info on that: https://github.com/keycloak/keycloak-documentation/blob/main/server_admin/topics/users/user-profile.adoc

And here's an excerpt dealing with hiding attributes on `attributes` tab:

> By enabling the user profile for a realm, {project_name} is going to impose additional constraints on how attributes are managed based on the user profile configuration. In summary, here is the list of what you should expect when the feature is enabled:
> - From an administration point of view, the Attributes tab at the user details page will only show the attributes defined in the user profile configuration.(...)

So.. seems design.

_NB: I've discovered this myself when researching a totally different issue (updating just some (like in: not all) user account data by REST Admin API, which turns out sadly, impossible right now). I think this feature was introduced because someone somewhere noticed that when attributes are used extensively, it's a problem for the users and also administrators to navigate through possibly large number of 'uninteresting' attributes, and it'd be nice to be able to show them only some of the attributes that are relevant for users' profile pages. But I might had gotten it wrong, I haven't really paid much attention to `declarative user profiles` when I stumbles on these discussions._

**Comment by mposolda** [comment]
This looks like a valid issue, but not a blocker for Keycloak 22. Adding to backlog for now. We may revisit once we want to make "user profile" supported feature.

**Comment by raffaeler** [comment]
This is literally diabolic.
I lost half a day and a piece of life trying to understand why the UI (with F12 enabled) was returning success but the user attributes never got saved.

**Comment by transducer** [comment]
Visualization:

![Attributes disappear](https://user-images.githubusercontent.com/5002921/250932253-a033f5f9-3381-4c27-a690-f08d7806c635.gif)

Note that if a user is confused and adds the attributes again manually on that screen, all previous attributes are gone or overwritten.

**Comment by pedroigor** [comment]
I think we have space for improvements, including how we can keep aligned with the design where you must define your attributes beforehand while still making it easier to migrate to the new declarative user profile.

**Comment by jonkoops** [comment]
@hypery2k see #24937

**Comment by KarlDegen** [comment]
With Version 24.0.1 there is a switch on page "Realm settings" and tab "General" named "Unmanaged Attributes"
When you enable this setting, the user details page also shows the "Attributes" tab to add 'unexpected' attributes to the user.

**Comment by hypery2k** [comment]
thx for the hint. I already noticed this
