### ISSUE TITLE
Upgrading Keycloak14.0.0 on itself is failing with NullPointerException in infinispan

### ISSUE THREAD

**Issue by pravsjv** [keycloak/keycloak#9949]
### Describe the bug

Hi Team,

We are trying to upgrade same version of keycloak on itself for a requirement and we have faced the following issue in infinispan.
ESC[0mESC[31m2021-09-28 10:06:35,922 FATAL [org.keycloak.services] (ServerService Thread Pool -- 64) Error during startup: java.lang.NullPointerException
        at org.keycloak.keycloak-model-infinispan@14.0.0//org.keycloak.models.cache.infinispan.entities.CachedRealm.<init>(CachedRealm.java:263)
        at org.keycloak.keycloak-model-infinispan@14.0.0//org.keycloak.models.cache.infinispan.RealmCacheSession.getRealm(RealmCacheSession.java:414)

Can anyone throw some light on how we can avoid this.

Thanks!

### Version

keycloak 14.0.0

### Expected behavior

The upgrade should be successful without any issues.

**Comment by ahus1** [comment]
Looking at the code of CachedRealm.java, the following line throws a NPE: 

```
defaultRoleId = model.getDefaultRole().getId();
``` 

For some reason no default role seems to be available. I suggest you debug the code. 

As the current version of Keycloak is 16 compared to version 14 where you reported this issue, there is not much more I can do. If you experience this issue with the current version of Keycloak, please add a comment stating this. Otherwise I'll close this issue in a few days.

**Comment by ahus1** [comment]
Closed due to lack of additional information from creator.
