### ISSUE TITLE
required action terms_and_conditions is not imported

### ISSUE THREAD

**Issue by an-ant0ni0** [keycloak/keycloak#9991]
### Describe the bug

When importing a user via the gui including the required action `terms_and_contions` this required action is not imported into keycloak. All other required actions are properly imported (including a custom one provided by plugin).

`users.json`:
```json
{
    "users": [
        {
            "username": "chris",
            "firstName": "Chris",
            "email": "chris@example.com",
            "enabled": true,
            "requiredActions": [
                "VERIFY_EMAIL",
                "terms_and_conditions",
                "custom_one",
            ],
            "groups": [],
            "attributes": {}
        }
      ]
}
```

### Version

16.1.1

### Expected behavior

Required action `terms_and_conditions` is imported and shown on first login.

### Actual behavior

Required action `terms_and_conditions` is missing after import.

### How to Reproduce?

Delete existing user. Import `users.json`

### Anything else?

There was already an issue: https://issues.redhat.com/browse/KEYCLOAK-3560
We tried upper (TERMS_AND_CONDITIONS) and lower case (terms_and_conditions) without success.

**Comment by mhajas** [comment]
Hello, thank you for reporting the bug and providing the fix. Your fix would solve the issue you have, but it can introduce some backward compatibility issues, like for example if someone has a realm with the `verify_email` required action, it would stop working because it was relying on the `uppercase()` call you removed. I am not sure what is the correct solution here as required actions usage is a little messy. I will start some discussion around this within the team and let you know.
